### ISSUE TITLE
Offline Site after Joomla 4.1 is looking bad

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#102]
After update to Joomla 4.1 the Offline Page from Joomla looking strange.
The Offline Page from the Theme is working!

**Comment by Chacapamac** [comment]
This is more a Joomla problem, I think?

**This is what I see on Joomla 4.1**

**My Settings:**
![settings](https://user-images.githubusercontent.com/1907276/154509402-9a06f621-5642-43fe-b7bc-fd2487ce1e90.jpg)

**Result:**
![Joomla-offline](https://user-images.githubusercontent.com/1907276/154509597-d766680b-c1de-4502-8ef6-b3fefc404504.jpg)

Need a bit of css to fix. Image is gone to the fifth dimension????

**Comment by Chacapamac** [comment]
@Joomlaplates , Yep, the Astroid coming soon is looking great and work perfectly.

**Comment by biobill** [comment]
No problem on my end
![Screenshot 2022-02-17 at 17-46-48 Home](https://user-images.githubusercontent.com/16140656/154517924-85888a4d-a620-416b-bc13-a33a7baef243.png)
.

**Comment by biobill** [comment]
I confirm that Astroid coming soon is working fine, but Joomla offline is broken.
If I change to Cassiopeia template, offline works fine.

**Comment by Master-and-Desaster** [comment]
Hi!
Found this fault after update from Joomla 4.0.6 to 4.1.0.
If you rename the offline.php in the root of the jp-template,
the offline-page looking good.

**Comment by Chacapamac** [comment]
Confirm @Master-and-Desaster 

**Templare Zero**
- If you rename the “offline.php” in template Zero, Joomla Offline look Ok — Still no image even if set in Joomla 4 config...

![offline-4](https://user-images.githubusercontent.com/1907276/154533757-9bc2f9fe-cb1c-49da-b282-d7dce1c2f926.jpg)

**Comment by Master-and-Desaster** [comment]
'Still no image even if set in Joomla 4 config'

That is correct. It is maybe also a fault.

Our member 'ReLater' in the German Joomla Forum found a solution to fix this problem:

https://github.com/GHSVS-de/plg_system_offlineghsvs

Maybe it will be helpful

**Comment by Chacapamac** [comment]
> Sure you can delete or rename the offline.php from Theme folder, but then the Astroid offline page settings is not working anymore.

Ok thats a problem, they need to be compatible to both choices.

**Comment by sonvnn** [comment]
Hi @Joomlaplates 
May you help me update offline.php in Zero and One template? I am infected with Covid-19. I will be back soon.

Kind Regards,
Sonny

**Comment by biobill** [comment]
Hi @sonvnn,
I hope you'll get better soon...

**Comment by Joomlaplates** [comment]
Get well soon Sony.. BTW I had this virus 3 weeks ago. It wasnt that bad but very annoying, coz I felt weak for 10 days

The problem is, that Joomla since 4.1 has no more css folder in 
**templates/system/css/**
Therefore the css files are not loading
...
Solutions:
We add the css files to the template css folder and load them form there. If you have another idea, let me know

**Comment by Joomlaplates** [comment]
Ok, I have fixed the offline.php in One and Zero Theme.
Please check the new themes 2.5.14 and feedback.
Regards Peter

**Comment by Master-and-Desaster** [comment]
Jipp!
Just tested.
Works fine! :-)

**Comment by Chacapamac** [comment]
Work Perfectly  with the image and all. Great Job!
