### ISSUE TITLE
ToolTip is not working

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#104]
The BS 4.5 and BS 5 Toioltip function is not working anymore.
https://getbootstrap.com/docs/5.1/components/tooltips/
```
initTooltip http://localhost/astroid/j4/industry/media/astroid/assets/vendor/astroid/js/script.js?v=2.5.14:144
    docReady http://localhost/astroid/j4/industry/media/astroid/assets/vendor/astroid/js/script.js?v=2.5.14:244
    jQuery 13
```

**Comment by sonvnn** [comment]
Hi @Joomlaplates 

I fixed it in https://github.com/templaza/astroid-framework/commit/b60471074225954654f437c5c2587e726de83a3a
Please help me check it.

Kind Regards,
Sonny

**Comment by Joomlaplates** [comment]
Hi Sonny,
yes its working now thank.
I close this issue.
regards, peter
