### ISSUE TITLE
Alert can't be dismissed on login page (bootstrap.min.js not loaded) 

### ISSUE THREAD

**Issue by T0mFi** [templaza/astroid-framework#105]
Hello,
The popup message (e.g. wrong password) can't be closed on the **login page**. The bootstrap.min.js is not getting loaded compared to other pages. In the profile edit page for example alerts can be dismissed perfectly normal.
I am using the one-tamplate. I don't know if this only a problem on my side or if there is a bug in the template.
site: https://esport-darmstadt.de

Just wanted to check if it's a bug, before i go for a workaround.

best,

Tom

**Comment by T0mFi** [comment]
I copied the bootstrap.min.js script tag from the working pages and added it manualy in with the "custom code" option, for the page to work propperly.

**Comment by sonvnn** [comment]
Hi @T0mFi 

Thank you for report issue. I added feature allow load Bootstrap JS from Astroid Core at https://github.com/templaza/astroid-framework/commit/6c5a21b86224bfae351e0722a23fdb43dccf9794

You can use it instead of Custom Code.

Kind Regards,
Sonny
