### ISSUE TITLE
Error  when installing 2.5.15

### ISSUE THREAD

**Issue by Chacapamac** [templaza/astroid-framework#108]
![Screen Shot 2022-03-02 at 4 34 05 PM](https://user-images.githubusercontent.com/1907276/156453373-d66036df-7888-4c2e-a796-c5ea8d6828ec.jpg)

When dropping — > astroid-package-v2.5.15.Framework-Template.zip on the Joomla install window

**over this**
![Screen Shot 2022-03-02 at 4 37 20 PM](https://user-images.githubusercontent.com/1907276/156453377-8add9e17-693e-497a-b23e-24a0e64b8756.jpg)

the picture above is also what I see after installing ?

**Comment by Joomlaplates** [comment]
Hello, and with this file:
https://github.com/templaza/astroid-framework/archive/refs/heads/master.zip

**Comment by Chacapamac** [comment]
No more error
But no changes

![Screen Shot 2022-03-03 at 2 47 38 PM](https://user-images.githubusercontent.com/1907276/156641054-c40f0aac-6407-470d-ab96-0b0d8309b535.jpg)

**Comment by 888Jay** [comment]
> Hello, and with this file: https://github.com/templaza/astroid-framework/archive/refs/heads/master.zip

That file does not include the templates.

![Screenshot 2022-03-17 180545](https://user-images.githubusercontent.com/45702513/158908355-4ce281c0-fac7-45d8-913c-d566f7db1f0a.png)

**Comment by Chacapamac** [comment]
@888Jay 
— No error on installatiun
— Framework Updated from 2.5.14
— Gradient appear with help text
![Screen Shot 2022-03-19 at 8 52 20 AM](https://user-images.githubusercontent.com/1907276/159121760-fb671f54-f0ca-4a6a-8a90-28a27018ae42.jpg)

**Suggestions for the Gradient tools:**
I think the gradient tool should appear with a basic default gradient to be firs nicer and help the user to understand how it work
![Screen Shot 2022-03-19 at 8 57 50 AM](https://user-images.githubusercontent.com/1907276/159121922-ef081d13-5bde-411b-b068-e4634ce5b64f.jpg)

SOLVED FOR ME!

**Comment by Chacapamac** [comment]
I mark it as SOLVED — Thanks Jay!
