### ISSUE TITLE
Documentations / examples for new features?

### ISSUE THREAD

**Issue by FrankReisenhofer** [templaza/astroid-framework#109]
With a new version several new features are added.

Would it be possible to add more info in the release notes how to use it or where to find it.

Currently I see only 

e.g. "Add Gradient Angle feature"

Any ideas how to improve this?

**Comment by Chacapamac** [comment]
I hear you @FrankReisenhofer 
I was going to ask the same thing.

**Sonny** and everybody else are bringing great new features on top of the great Astroid Framework but, for now, no real documentation or at least a fast overview of theses features and how to use them are added to the Changelog.

**Users need to know about theses new features and go, search and try to understand themselves theses features. I think that many Users simply doesn't learn about them until they just stumble on them in the settings.** 

**What I suggest and also help with**
1. Add, at least, a **“Fast overview and How to use”** (or a link to) to each new features in the changelog
2. Create a Changelog page on the new website of Astroid where ALL the new features are listed (by version) in a searchable repertoire with their **“Fast overview and How to use”** document or more infos, if needed.
3. Each of the importants new features are also added to the main tutorial with their **“How to”** infos.


———————————————————————————————————————————————
**Just an example** of **“Fast overview and How to use”** for the New **Gradient Tool**

1. Go to **Templates Styles > Your template style > Button Template Options > Layouts**
2. In any Layout elements edition windows _(click Crayon Button on Section, Columns, Element or Rows)_ — > Choose the “**Design Settings**” Tab
3. For the “**Background Type**” chose “**Gradient**”

**ELEMENTS EDITION**
![section-edit](https://user-images.githubusercontent.com/1907276/156812788-965bfe76-9539-4d88-aa2c-d114359511e2.jpg)

**GRADIENT TOOL**
![gradient-tool](https://user-images.githubusercontent.com/1907276/156812920-98c5b505-19ef-4abd-85fb-2571d5096f7e.jpg)

**Comment by Joomlaplates** [comment]
Hi [Chacapamac](https://github.com/Chacapamac),
I think it would be a good idea to post the new features on the website blog.
https://astroidframe.work/
Ask Sonny for access like an author..
Regards Peter

**Comment by sonvnn** [comment]
I created Blog Menu here https://astroidframe.work/blog @Chacapamac you can login with your account and create blog for it :)

**Comment by Chacapamac** [comment]
**Great.**
**If you want?** _(Tell me if OK?)_
— I will start to create Changelog blog articles with the basics infos on the fixes and new features plus a rapid **“How to”** for each new features.

• Also, I see that you have added a “**Documentation**” section to the website. 
—> https://astroidframe.work/support/documentations
- I see that some of that documentation come from Joomdev documentation here
 —> https://docs.joomdev.com/category/astroid-user-manual/
_**Just for infos...**_
_(I already copy all the documentation/images from the Joomdev Documentation in case it disappear (If needed???)_

- **Just remember that you can insert the same videos that you see in their documentation from  your NEW Astroid  Youtube Channel** —>  https://www.youtube.com/channel/UCUHl1uU0Ofkyo-1ke-K4_xg

• Also I will give some suggestions on the design and architecture of the website

• I have JCE Pro, do you want me to install it?

**Comment by sonvnn** [comment]
Hi @Chacapamac ,

> I will start to create Changelog blog articles with the basics infos on the fixes and new features plus a rapid “How to” for each new features.

Sure, I appreciate your help. Please help me create changelog and tutorial "How to" for each version and new feature. 

> Also, I see that you have added a “Documentation” section to the website.

You are welcome to change Menu structure if you feel it is not good and you can make it better. You are Super User and you can do everything for this site.

Thank you for your cooperation.

Kind Regards,
Sonny

**Comment by Chacapamac** [comment]
Great @sonvnn, I’m really close to put a new website online — After that, I will help a lot more.
Good Day!

**Comment by sonvnn** [comment]
You're welcome @Chacapamac :)

**Comment by FrankReisenhofer** [comment]
@sonvnn : Can you please share the link to the documentation?

https://astroidframe.work/support/documentations is not working for me [1]

[1]

This site can’t be reachedThe connection was reset.
Try:

Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics
ERR_CONNECTION_RESET

**Comment by sonvnn** [comment]
@FrankReisenhofer I can access to this site normally. Please help me check your internet connection or firewall.

**Comment by Chacapamac** [comment]
No problem accessing https://astroidframe.work/support/documentations

**Comment by FrankReisenhofer** [comment]
@Chacapamac , @sonvnn : Looks like a strange issue with my firewall. On my second PC I can access the page without issues. 

Thank you.

But one additional question: Where can I find the release specific documentation on the mentioned page. 

E.g. in the new release you added the new features [1]. Where can I find the docu for these new features?

Would it be possible for you to add a link in the release notes to the feature specific documentation.  

[1]
[Add new Preset system](https://github.com/templaza/astroid-framework/commit/997374c00afc2ad99055e24a8b459803b5a2d9e7)
[Add new Preset options for Colors and Typography](https://github.com/templaza/astroid-framework/commit/c838ad941636adb42db34b6ccc11d9dec339f76f)

**Comment by sonvnn** [comment]
@FrankReisenhofer I just little busy with new project. I will create a video tutorial for new feature in few next days.

**Comment by Chacapamac** [comment]
@FrankReisenhofer  — If you Google —> **err_connection_reset windows** 
You got quit a bit of hit on how to fix it....

I’m really mad, because I want to help the project more and it's alway something to take my time away....
Sorry for that!
