### ISSUE TITLE
Add the Theme Width parameter

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#11]
Maybe add an option to setup the theme width settings in options.xml:
```
.container, .container-sm, .container-md, .container-lg, .container-xl, .astroid-layout.astroid-layout-boxed .astroid-wrapper {
    max-width: <?php echo $theme_width; ?>;
}
```
![105771861-8c956700-5f61-11eb-8319-3754bdc1bde8](https://user-images.githubusercontent.com/71080509/140502274-d4e8a4cd-69d4-4961-b515-e676accf0d44.jpg)

**Comment by sonvnn** [comment]
Thank you I will consider about this in the next versions.

Best Regards,
Sonny

**Comment by sonvnn** [comment]
Hello,
This feature is available at #18 
Let's check it and Enjoy ;)

**Comment by Joomlaplates** [comment]
Hi Sonny the parameter is not working.
```
        $theme_width    =   $params->get('theme_width', '');
        if (!empty($theme_width)) {
            $document->addStyleDeclaration('.container, .container-sm, .container-md, .container-lg, .container-xl, .astroid-layout.astroid-layout-boxed .astroid-wrapper {max-width: '.$theme_width.';}');
        }
    }
```

![size-001](https://user-images.githubusercontent.com/71080509/141685492-e8b8209a-d226-477f-9834-c780c23c7bd2.jpg)
![size-002](https://user-images.githubusercontent.com/71080509/141685500-407c7514-108c-4a3d-a926-f5e59a80db0b.jpg)

**Comment by sonvnn** [comment]
I fixed it at https://github.com/templaza/astroid-framework/commit/9947c835183920da15fad845502f761f86e26304
Please try it and give me your result.

Bests,
Sonny

**Comment by Joomlaplates** [comment]
Yes its working now in Astroid developer version
Thanks for quick response. Youre great!
Reagards Peter
