### ISSUE TITLE
can't find how to customize the colors of Tooltip on Astroid

### ISSUE THREAD

**Issue by woluweb** [templaza/astroid-framework#113]
Hi,

On a dark-mode website I needed to customize the color of the tooltips (like on Registration page for instance).
I had tried the following but it does not work.

What have I missed. Isn't the selector .tooltip-inner?

Txs

```
.tooltip-inner {
  background-color: black !important;
  color: red !important; 
}
```

**Comment by Chacapamac** [comment]
Do you have a exemple online?

**Comment by woluweb** [comment]
Sorry, I should have added a link.
Here is an example: https://www.feteducourt.be/creer-un-compte

It is for front-end of course, so not Isis but Astroid :)

**Comment by Chacapamac** [comment]
The pop hover is triggered by 
```
<label id="jform_password1-lbl" for="jform_password1" class="hasPopover required" title="" data-content="Saisissez un mot de passe" data-original-title="Mot de passe">
	Mot de passe<span class="star" style="display: none;">&nbsp;*</span></label>
```
The div is —> div.pophover.fade.right

![Screen Shot 2022-03-10 at 7 38 48 AM](https://user-images.githubusercontent.com/1907276/157663195-9baa0872-ad4b-4619-b1a7-e231272dc022.jpg)

**Comment by woluweb** [comment]
Excellent !
I was using Chrome and the Inspector would not show that area.
But indeed in Firefox it does.

Txs a lllllot for this tip.
And txs for your good work on Astroid :)

**Comment by Chacapamac** [comment]
No Problem, Happy to help Fellow Astroid Users.
