### ISSUE TITLE
Custom JS for readOnly

### ISSUE THREAD

**Issue by 888Jay** [templaza/astroid-framework#117]
I want the address fields for the User-Profile plugin to be read-only in the edit profile screen. I added the following in Custom JS but it's not working. What did I miss? TIA

`document.getElementById('jform_profile_address1').readOnly=true;
document.getElementById('jform_profile_address2').readOnly=true;`

Edit to add:
Joomla 4.1 / PHP 8.1
Astroid Framework 2.5.15
Astroid Template One 2.5.14

Inspect input box:
![Untitled](https://user-images.githubusercontent.com/45702513/159094466-befacfa6-30a6-43a7-a384-5d0603d28ef6.png)

**Comment by sonvnn** [comment]
You should use Joomla template override feature. template-one/html/com_users/profile

**Comment by 888Jay** [comment]
Yes, of course! Rather embarrassed that hadn't occurred to me. Thanks, @sonvnn!!
