### ISSUE TITLE
Row must have a position:relative

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#12]
Hello, the "row" must have a css parameter **position:relative**, otherwise the parameter **absolute** of a module like shape divider is not working
```
.row > * {
    position: relative;
}

```
![row](https://user-images.githubusercontent.com/71080509/140627553-1a5fb175-d7b6-4247-90c0-dac65c59a542.jpg)

**Comment by sonvnn** [comment]
There are many situations in this case. It looks good for your template but not for others. So I think this style should be set in the scss of the template instead of library.

Best Regards,
Sonny

**Comment by Joomlaplates** [comment]
No problem.
But its not about the shape. Its more about that any module with position:absolute will not work if the row have no position.
But anyway, I take this code in my override css file.
Regards Peter
