### ISSUE TITLE
GTmetrix worst offender in task delaying the loading time is astroid media > jquery-3.5.1.min.js?v=2.5.15 ?

### ISSUE THREAD

**Issue by Chacapamac** [templaza/astroid-framework#120]
![astroid-jquert](https://user-images.githubusercontent.com/1907276/160137796-49642763-b31b-4710-9865-b30064f3cb55.jpg)

**Comment by Chacapamac** [comment]
Also, do you think it will be possible to reduce the main compiled.css file?

![Screen Shot 2022-03-28 at 11 35 37 AM](https://user-images.githubusercontent.com/1907276/160435025-e657cbf5-d469-4b81-a332-6e6c3635e232.jpg)

I will check other ways to load Awesome, see if faster

**Comment by sonvnn** [comment]
You can choose load Font Awesome from local instead of CDN in Astroid Plugin.

**Comment by Chacapamac** [comment]
You Right Sonny the local load of awesome gain a **FULL SECOND** on loading the website
![Screen Shot 2022-04-04 at 8 23 55 AM](https://user-images.githubusercontent.com/1907276/161543427-b6591a27-60a3-4302-8ef9-8afab5363e60.jpg)

_What is the point of using CDN, I was thinking it should make thing faster?_

Also I guess I can answer my own question for the Compiled CSS, The only way is to keep the template & custom css to the minimum.
I guess the big part here is the loading of Bootstrap and I can see now that I have to cleanup my custom.scss to the max

**Comment by Chacapamac** [comment]
next I will check what I can do with the JQuery — I will probably use the Joomla “JQuery easy plugin” on Joomla —> https://extensions.joomla.org/extension/jquery-easy/

**Comment by Chacapamac** [comment]
I’m closing this — The Real measurement are way faster — I was taking this the wrong way....
