### ISSUE TITLE
No SmoothScroll function when Header is > Sidebar Left Layout

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#121]
SmoothScroll, backtotop and some other things are not working in Sidebar Layout
-Astroid 2.5.15
-Theme One
-Joomla 4.1
![Screenshot_1](https://user-images.githubusercontent.com/71080509/160160935-be91baca-4c3d-4272-85bf-00818142223f.jpg)

**Comment by Joomlaplates** [comment]
Hi, I found the issue.
The script >` jquery/jquery.easing.min.js` is not loaded in header sidebar

**Comment by Joomlaplates** [comment]
I´ve added the script manually, but still not working.
I have no more clue, sorry.

**Comment by Chacapamac** [comment]
I just test on my test website here —> http://joom4-astro.graf-test.ca/
Header, Sidebar, backtotop work. For Smooth Scroll, think it does, I put it to the max and yes. its maybe smoother up & down

Joomla 4.0.1
Astroid 2.5.15
Template One 2.5.13

Also no warnings or errors in console

**Comment by Joomlaplates** [comment]
Hi, please setup the header section to >> sidebar, like shown the pic above
Your Url is not showing the sidebar left layout.
http://joom4-astro.graf-test.ca/

**Comment by Chacapamac** [comment]
Yep, No “**Back To Top**” — _It is there but with the “display: none;” css_
![Screen Shot 2022-03-27 at 1 01 22 AM](https://user-images.githubusercontent.com/1907276/160267351-6654a10e-3bd4-4dbc-b76e-eca27dd7409e.jpg)

Its missing the “Overflow” command seen below on other header arrangement where it work correctly.
![Screen Shot 2022-03-27 at 1 13 32 AM](https://user-images.githubusercontent.com/1907276/160267621-42206429-37c1-47a0-8464-a2ad74e18872.jpg)


For “**Smooth Scroll**”, I put it at 10000ms (the max) and off or on I see no difference ?

**Comment by Joomlaplates** [comment]
Hi again,
add a menu item with an anchor and try to smooth scroll to any section.
https://docs.joomdev.com/article/creating-one-page-website-in-astroid/
**Its not working!**
Regards Peter

**Comment by Chacapamac** [comment]
Confirm - Not Working
**You can try here**
http://joom4-astro.graf-test.ca/

**Comment by sonvnn** [comment]
Thank you! I did not find the solution for it yet. I tried re-write a new code. But something is blocking the execution of jQuery's animate function. 

May be Mr Mark can help us invest more about it. @imarklee May you help us in this issue?

Thanks & Kind Regards,
Sonny

**Comment by Joomlaplates** [comment]
Hello, I have found the issua.
Add this to the css and it works
```
.astroid-content.has-sidebar {
  height: inherit;
  overflow-y: inherit;
}
```

**Comment by sonvnn** [comment]
Hi @Joomlaplates 

Thank you for your solution. I updated it in https://github.com/templaza/astroid-framework/commit/23ce51e1dca50f36d0719747af0ffcfa191f19bf

Please help me check it.

Kind Regards,
Sonny
