### ISSUE TITLE
Add an active class to the menu item if the ID is in viewport

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#123]
Hello together,
Bootstrap 5 is supporting the scrollspy function..
https://getbootstrap.com/docs/5.0/components/scrollspy/
Therefore we should add this deafure and add an "active" class to the menu item "li" when you scroll to the section ID ot of its in viewport. Its a very nice detail when you build a onepage design.
Regards Peter

**Comment by Chacapamac** [comment]
Yep that’s a pretty cool navigation system!, Thanks, Peter!

**Comment by Joomlaplates** [comment]
Hello together,
I did it manually, see picture
1.) Open the index.php from the template folder and add this code to the body tag.
`data-bs-spy="scroll" data-bs-target="#astroid-header"`
But at least a config option for `menu active bg color` and `menu active bg color hover` would be a good idea.
Greatings Peter
![bs5](https://user-images.githubusercontent.com/71080509/161763137-ce7735fa-67a5-4d32-893e-c354c32b846c.jpg)

**Comment by Chacapamac** [comment]
@Joomlaplates , do you have a live example ?

**Comment by sonvnn** [comment]
Hi @Joomlaplates 

It will affect to Astroid Header only. When you click to Sticky Menu, it will not work.

Let's try it again with Horizontal Header.

Regards, Sonny

**Comment by Joomlaplates** [comment]
> 

https://demo.joomlaplates.de/onepage/

**Comment by Joomlaplates** [comment]
> Hi @Joomlaplates
> 
> It will affect to Astroid Header only. When you click to Sticky Menu, it will not work.
> 
> Let's try it again with Horizontal Header.
> 
> Regards, Sonny

Yes, I noticed its working only in sidebar layout. In horizontal and stack layout I get a javascript error.

**Comment by Chacapamac** [comment]
Ok, now I see what you mean, it is interesting.
For me, it make not to much sens with the horizontal menu or I miss something. It will only work with the sticky header on.

**Comment by Joomlaplates** [comment]
Hi again,
ofc it makes sense in the horizontal header menu too. Why not? YOu can build a one page design with top menu too.
But currently its working only with sidebar header.
I am still on research why its not working with stacked menu on the top
Regards, Peter
