### ISSUE TITLE
Cannot install framework + template

### ISSUE THREAD

**Issue by deltapapa01** [templaza/astroid-framework#126]
Hello, I have a small problem installing the framework and the template package. When I try to install it on a clean Joomla 4.1.2 and PHP 8.1.4 I get the following error:
![image](https://user-images.githubusercontent.com/19833064/163770283-138a3dc9-9c2d-43f6-bcfa-7ec302d9c0ed.png)
I can install the framework standalone without any problems.
I have now copied the two templates from astroid-package-v2.5.15.Framework-Template.zip, packed them as zips and then installed them individually, which worked without any problems.
Is it possible that a path in the download package is not correct?

WBR,
deltapapa

**Comment by nidzo80** [comment]
It's possible and I don't know why is not corrected.
In installation XML file there is astroid-template-zero and astroid-template-one folder instead astroid-one-template and astroid-zero-template

**Comment by Chacapamac** [comment]
@sonvnn 
Yep, In last package with templates —> **astroid-package-v2.5.15.Framework-Template**

**pkg_astroid.xml** is
<files folder="astroid">
      <folder type="library" id="astroid" client="site">astroid-framework</folder>
      <folder type="template" id="**astroid_template_one**" client="site">**astroid-template-one**</folder>
      <folder type="template" id="**astroid_template_zero**" client="site">**astroid-template-zero**</folder>
   </files>

But **Templates folder names in the package are wrong:**
_astroid-zero-template
astroid-one-template_

**Should be**
_astroid-template-zero
astroid-template-one_

**Comment by sonvnn** [comment]
Opps!!! I am sorry.
I updated package in version 2.5.16. Please help me download version 2.5.16 and re-check again https://github.com/templaza/astroid-framework/releases/tag/v2.5.16

Don't hesitate to let me know if this issue happens again.

Kind Regard,
Sonny

**Comment by deltapapa01** [comment]
Hello, I checked it, now it works exactly as it should.
Great and thank you, the ticket can be closed I think.
deltapapa

**Comment by Chacapamac** [comment]
> Opps!!! I am sorry.
_My father always said to me that only people doing nothing are not making mistakes._

**Thank You Sonny** for the great work you are doing, I can’t wait to be out of my current work to help Astroid more. Great group here!
