### ISSUE TITLE
Margin Top on Search component

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#129]
Hi there,
if you add a menu item > **Smart search** you have a margin-top which is white ( body background)
To fix it, add this css code 
```
.com-finder > * + *, .com-finder__results > * + * {
  margin-top: 0;
}
```
![margin](https://user-images.githubusercontent.com/71080509/164981573-d76a195b-b152-49e8-94b6-25b9c1c11f34.png)

Regards Peter

**Comment by Chacapamac** [comment]
Good to know, Tanks!

**Comment by Joomlaplates** [comment]
`do you talk about Joomla Smart Search?`
yes Joomla Smart search

**Comment by Chacapamac** [comment]
Cool!, Noted!
Thank You Peter!

**Comment by sonvnn** [comment]
Hi @Joomlaplates 

I added this to scss. https://github.com/templaza/astroid-framework/commit/febec97a6e78ab54666fc6a2fc23c6be1630c247

Thanks & Best Regards,
Sonny
