### ISSUE TITLE
Layout Klick in Backend is not working

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#13]
Astroid 2.5.6 > Template ONE Backend > the klick on Layout is not working. ( not scrolling too)
Sorry I couldnt find the issue, see attached video.
https://youtu.be/G-vW8Nrm8tY

**Comment by sonvnn** [comment]
It's strange for me. It works very well on my One template backend. https://www.screencast.com/t/ExXBQOnoKxq
Did you override something in your back-end? Please help me check them again.

Best Regards,
Sonny

**Comment by Joomlaplates** [comment]
I found the issue.
If you have installed Astroid 2.5.4 and update to Astroid 2.5.7 the issue is there.
But if you uninstall the Astroid 2.5.4 first and then install the Astroid 2.5.7 its ok.
That means there is some file left from old Astroid which is not deleted  by updating to Astroid 2.5.7

**Comment by sonvnn** [comment]
I tried to update from 2.5.4 to 2.5.7. It works well. I not sure I assume you have some problem with cache. :)

**Comment by Joomlaplates** [comment]
Yeah maybe. Its strange sometimes it works sometimes not.
I never used any cache on testing.
