### ISSUE TITLE
Accessibility Check is not working

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#130]
Hello, if you click on Accessibility Check from backend the button on the right buttom shows no information.
It brings a script error, something with jooally...
![Screenshot_1](https://user-images.githubusercontent.com/71080509/164776047-b51b0609-9e12-468e-b725-2007b51bcb5f.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/71080509/164776050-891e8811-f177-47d6-9c26-f3739f5398ec.jpg)
Regards, Peter

**Comment by Chacapamac** [comment]
Sorry not to knowledgeable of the Accessibility settings/tools

**• Why, that CASSIOPEIA TEMPLATE, in the middle of the article?**

This is my results on my astroid/Joomla 4 test website
![click](https://user-images.githubusercontent.com/1907276/164781509-7d94dc2b-5aa1-4f65-b961-aba8eaa56656.jpg)

**Comment by Joomlaplates** [comment]
Its not working with ONE Template!
https://youtu.be/GeBXVEivxOI

**Comment by Chacapamac** [comment]
Yep, 
— I confirm the same errors on both one & zero template
— I confirm that I HAVE the left bottom Accessibility Button on both templates
![Screen Shot 2022-04-23 at 9 42 43 AM](https://user-images.githubusercontent.com/1907276/164903557-fcac56d4-6db1-49b5-9ee7-7fc9d1a685d8.jpg)

The top error arrive on clicking the top “Accessibility Check” Button
Bottom error seem to appear when the lightbox right bottom round accessibility icon button is press

**That jooally.min.js is part of Astroid?**

**Comment by sonvnn** [comment]
Hi @Joomlaplates @Chacapamac 

Thank you for report this bug. I fixed this issue in https://github.com/templaza/astroid-framework/commit/989dd4ad7de8bc9878b25799e806ca8202bc738c 

Please help me check it again. 

Best Regards,
Sonny

**Comment by sonvnn** [comment]
@Chacapamac you can download developer branch at https://github.com/templaza/astroid-framework/archive/refs/heads/developer.zip

Best Regards,
Sonny

**Comment by Chacapamac** [comment]
@sonvnn Thanks! — **NOW I know how to download that Dev file, Thanks for the hint.**
**_Code Button > Download Zip_**
_I guess it download the file with changes before they are commits to the final file.... ( Learning Github.....)_

**• I Just test and everything seem to work proper for the “Accessibility Check” functions**

**• Only this 404 error when clicking the Top Accessibility check button and when the floating window appear**
![Screen Shot 2022-05-17 at 7 42 43 AM](https://user-images.githubusercontent.com/1907276/168802683-3f66e671-3cab-47b7-8b10-29fbd60108d5.jpg)

 **404 error ???**
_07:42:57.304 GEThttp://joom4-astro.graf-test.ca/images/footer-bg.png           [HTTP/1.1 404 Not Found 31ms]_

Everything else seem  right..
![Screen Shot 2022-05-17 at 7 47 06 AM](https://user-images.githubusercontent.com/1907276/168803682-03644d03-20bc-491e-96ee-86a6b58290f5.jpg)
.

**Comment by sonvnn** [comment]
@Chacapamac It's look like browser can't load image from your site. Please check if http://joom4-astro.graf-test.ca/images/footer-bg.png image is exist.

Best Regards,
Sonny

**Comment by Chacapamac** [comment]
@sonvnn - I find the problem
This is a clean install of Joomla 4 and Astroid — I didn’t change nothing in the Templates layout

This error is caused by the Footer section Style that point to a nono existing image —> [footer-bg.png](http://joom4-astro.graf-test.ca/images/footer-bg.png)
**If you clear the image or change for another style the error go away...**
![Screen Shot 2022-05-18 at 6 34 42 AM](https://user-images.githubusercontent.com/1907276/169020946-2cc0cfdd-a597-4dda-b08f-83d292b029b9.jpg)

![Screen Shot 2022-05-18 at 6 35 05 AM](https://user-images.githubusercontent.com/1907276/169020970-bba875b2-a02f-4d00-b6b8-396037068bb7.jpg)
