### ISSUE TITLE
Adding Favicon Manifest Link (Template manager basics) as /favicons/site.webmanifest give //favicons/site.webmanifest?

### ISSUE THREAD

**Issue by Chacapamac** [templaza/astroid-framework#131]
Adding a **Favicon Manifest Lnk** _(Template manager basics)_ as **_/favicons/site.webmanifest_**
Become this in the html (remark the double slash) —> **_//favicons/site.webmanifest_**

Seems to work anyway?
![Manifest](https://user-images.githubusercontent.com/1907276/164978314-65eb6c14-09c2-4615-9820-4afc43af04dd.jpg)

**Comment by sonvnn** [comment]
You can remove slash in your template configure. I think it's not a bug :) Can you help me to put captions for users to understand more easily?

**Comment by sonvnn** [comment]
Hi @Chacapamac,
Thank you! Feel free to install JCE PRO to Astroid.

Best Regards,
Sonny

**Comment by Chacapamac** [comment]
@sonvnn  
- I cannot install JCE Pro (Upload limited to 2mb)
- Can you give me the ftp or hosting access, I will fix it and also make the backup system more secure (Akeeba Backup)

**Comment by sonvnn** [comment]
@Chacapamac I updated upload limited to 15mb. Please help me try it again and let me know if this issue still happens.

Thanks,
Sonny

**Comment by Chacapamac** [comment]
I Install JCE Pro and add the Download Key
I install a quick icons Module In the Administration to speed things up

I install Akeeba Backup core (no need of pro) but I need access to the FTP Root to create a backup folder outside the public_html folder. I can take care of cleaning & download security backup to foolproof the website in case of accident without bloating the hosting account — What type of limit you have on this account?

**Comment by Chacapamac** [comment]
I Close this issue - Fix
You just need to use the caption English/French I made, if they are ok for You!

**Comment by Chacapamac** [comment]
Closed

**Comment by sonvnn** [comment]
> I Close this issue - Fix You just need to use the caption English/French I made, if they are ok for You!

Thank you @Chacapamac . I will add this in the next version. Sorry for the late reply. I just back from a Vacation

**Comment by Chacapamac** [comment]
Everybody need that Sonny - Good Day!

**Comment by sonvnn** [comment]
@Chacapamac I updated language file https://github.com/templaza/astroid-framework/commit/4e8fcfb21d1fa0d1a070b21115a25a6b4bb76463 
Please help me update French language file.

Thanks & Best Regards,
Sonny

**Comment by Chacapamac** [comment]
I just update the french and test successfully with your changes.
(2.5.17) —> [fr-FR.astroid.ini.zip](https://github.com/templaza/astroid-framework/files/8799021/fr-FR.astroid.ini.zip)

**2 points:**
**1.** You still have a Broken link image appear in both One & Zero template — You need to Clear it manually — if not you get a 404 in the frontend — Template should be deliver without this broken link.
![favicons-template-one](https://user-images.githubusercontent.com/1907276/171011812-b619323c-deaa-4edf-adbc-1aa07081f47c.jpg)

2. Curiously some language string appear on both language, both Template for the name of the template (in the backend Layout manager) ????
![astroid_template_one](https://user-images.githubusercontent.com/1907276/171012167-8906199b-b644-4e9e-8f7a-b140dfdb9e62.jpg)
