### ISSUE TITLE
Error 500 after clearing the cache

### ISSUE THREAD

**Issue by wagnerthorsten** [templaza/astroid-framework#133]
I updated the framework from 2.5.4 to 2.5.15 / 2.5.16.
After I cleared the (Astroid-) Cache, I've got the following message:
![grafik](https://user-images.githubusercontent.com/72703556/164992670-0000c578-daef-4d98-9551-3a480cd16d02.png)

The administrator side works fine.
If I go back to 2.5.4, the frontend also works again.

**Comment by Joomlaplates** [comment]
Just take a look at template folder
`/scss/style.scs`s and remove the import and try again.
```
// Theme
// @import "one/style";
```

**Comment by wagnerthorsten** [comment]
Fantastic! It works!!!
Thank you very much for the quick reply!
