### ISSUE TITLE
Export Preset with Sass Overrides

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#134]
When I export the preset, I have no custom Sass Overrides inlcuded.
It would be good if the Sass Overrides settings are get exported too.
![Uploading Screenshot_1.png…]()

![Screenshot_1](https://user-images.githubusercontent.com/71080509/164994780-f24e4b34-25fb-465f-ba92-0bc326cd98aa.png)

**Comment by Chacapamac** [comment]
I never use these overrides, I take a look. Yes, they should follow the export/import

**Comment by sonvnn** [comment]
Hi @Joomlaplates 

I am working for a new preset system which can load all system configures. I will be release in v2.5.18.

Kind Regards,
Sonny

**Comment by sonvnn** [comment]
Hi @Joomlaplates 

I update new Preset system in v2.5.18. Now you can use preset with features below:
- Re-load all configures of template
- Load configure from Color, Theming, Sass Override, Layout. I will continue update for more option in the next versions.

To use this feature. You have to create preset in Preset Profiles tab first. After that you can see options in Colors, Layout and Theming tab.

Let's try it and give me your opinion.

Kind Regards,
Sonny

**Comment by Chacapamac** [comment]
Great Job @sonvnn — I will test that.
Don't forget to put the “How to” in the changelog on the website
