### ISSUE TITLE
Please add ability for module editing on frontend as isFrontendEditing()

### ISSUE THREAD

**Issue by yasseribz** [templaza/astroid-framework#136]
Hi there,

Currently, module config at frontend on the frontend is not considered as `isFrontendEditing`. Kindly add this support to the frontend editing. Cause it won't load the frontend-editing-j4.css

`/index.php?option=com_config&view=modules`

![image](https://user-images.githubusercontent.com/25723021/169201978-bc82e339-8125-454e-a8fa-d334c5c0fca0.png)

Reference:

https://github.com/templaza/astroid-framework/blob/8ca3ed3af4d4269c933abc83b0ed603d87829916/framework/library/astroid/Document.php#L127-L149

**Comment by sonvnn** [comment]
![Screen Shot 2022-06-10 at 10 29 18](https://user-images.githubusercontent.com/3204103/172984691-4b10c787-c295-4a17-b275-725fb9a645d9.png)
I tested with Astroid 2.5.17 everything works well.

**Comment by Chacapamac** [comment]
I just test Joomla 4.1.4 with Astroid 2.5.17 and Template One

**Frontend editing of a custom module.**
— _**All the options of the module are there**_ 
— Some) Like “**Options**” & “**Advanced**” are in a tabs/Accordions at the bottom of the open options

**Warning:** your custom CSS can influx the frontend edition module....
