### ISSUE TITLE
Background color and Overlay pattern not working correctly - Framework 2.17 — Template One 2.5.16?

### ISSUE THREAD

**Issue by Chacapamac** [templaza/astroid-framework#138]
I’m trying to recreate a website with Astroid and the **Background Color** and **Overlay pattern** in the layout manager is not working correctly?

** Framework 2.17 — Template One 2.5.16**

**The result should look similar to that:** — _(Original website)_
![Screen Shot 2022-05-31 at 6 40 26 PM](https://user-images.githubusercontent.com/1907276/171295752-66e70552-b8c9-40f5-9770-ec2253347fac.jpg)
 — On the original website the background color & the png pattern (repeat pattern &  Image original size) are applied by CSS

==================================================
**I edit the section** _(with Section Layout “Without Container”)_

![Screen Shot 2022-05-31 at 6 43 09 PM](https://user-images.githubusercontent.com/1907276/171296327-c6367f7e-f81d-48a5-94b2-9781a41c0851.jpg)

**FIRST & SECOND TEST**

![test1](https://user-images.githubusercontent.com/1907276/171297384-0571095d-47cd-4ca2-aca7-2f2ab00f632c.jpg)

**RESULT for BOTH**

![result-1-2](https://user-images.githubusercontent.com/1907276/171297874-46aed374-b8e9-434d-b355-1443ef71d862.jpg)

==================================================

**THIRD & FOURTH TEST**

![test3-4](https://user-images.githubusercontent.com/1907276/171298415-fed89185-b13c-4123-90c1-7e0076be243b.jpg)

**RESULT for BOTH**

![result3-4](https://user-images.githubusercontent.com/1907276/171298635-afd9cb20-380c-4143-85f9-b88ced3f86b6.jpg)

_**NOTE 1:** I even try to see if the pattern image was loaded somewhere in the frontend by searching the name in the html and it wasn't loaded by the frontend at all._

_**NOTE 2:** I don't see any settings (repeat/size) for the overlay pattern, not to practical...._

**Comment by sonvnn** [comment]
@Chacapamac Because it's Image Background option but you did not select image background then it does not work. Please help me check your site again http://www.graf-test.ca/graf2/index.php/graf-blogue

Kind Regards,
Sonny

**Comment by Chacapamac** [comment]
@sonvnn  — Ok, I understand, **got it working**

**On the attached image I explain why this was confusing for me**
![confusing](https://user-images.githubusercontent.com/1907276/171905164-40441671-68ee-4bc7-b766-1bbeecfafc9c.jpg)

For me an “**Overlay**” is **NOT** a “**Background Image**”, an overlay is something that you put OVER a background image or a background color.

Probably hard to fix to get backward compatible, but I personally think that overlay/Pattern should be control in the “Overlay Pattern section — Make sense?

**Comment by Chacapamac** [comment]
You can close this if you want

**Comment by sonvnn** [comment]
@Chacapamac Thank you for your feedback. I will try to improve UI/UX in the next version. Just busy with new Astroid Template in next 5 days. I will update Astroid after that.

Kind Regards,
Sonny

**Comment by Chacapamac** [comment]
No problem Sonny.
