### ISSUE TITLE
Article type options and blog options look and tabs visibility option in plugin.

### ISSUE THREAD

**Issue by Giorgi625** [templaza/astroid-framework#141]
As I know **Article type options** and **Blog options** are part of **Astroid** template, so why they look weird on **Astroid** template in frontend and  look nice in **Cassiopeia**?  Also problem is with input fields in Article submit forms they can't be seen they are white like background. check links below to compare:
https://joomla.ge/images/problem/astroid.png
https://joomla.ge/images/problem/astroid2.png
https://joomla.ge/images/problem/cassiopeia.png
https://joomla.ge/images/problem/cassiopeia2.png

Also how can I  add / remove / edit article types, badge types and so on? I want to have own name on badges, not the ones provided by template and disable custom badge option. also disable some article types.

Another problem is Tabs visibility option in Astroid plugin. I think each tab should have own option to enable or disable in frontend.
Currently I need to show Article type options in frontend but hide Blog options, because settings inside Blog options are ones which should be managed only by admin, while settings in Article type options should be managed by article authors.

**Comment by Chacapamac** [comment]
**You absolutely right, the frontend edition is a bit messed up...????**
— I just test on last **Joomla 4** with the last **Astroid Template one and Zero** and see the same problems.

**The first problem is that when I click the frontend edit button Joomla ask for loading Cassiopea creating 404 errors (not found)?????**
![Screen Shot 2022-06-18 at 2 51 06 PM](https://user-images.githubusercontent.com/1907276/174452600-6c3f3bce-448c-45fa-92e3-ecad21b3d370.jpg)

**This is the first thing to fix...**

————————————————————
**Other question about custom Badges:**
![badgeoption](https://user-images.githubusercontent.com/1907276/174452811-c0018d09-2906-44fc-b16d-1bbfb39b7823.jpg)

One thing I ask Joomdev before. It will be great to being able as an administrator to modify the list of readily available badges. Without that it can become tedious to always have to type a custom badge name if you have lot of articles. 
???? Maybe using the Joomla tag system”

**The rest are enhancements**

**Comment by Chacapamac** [comment]
For the css fix it’s
In compiled css

I find that css fix — The selector is in the compiled css (meaning it belong to an astroid stylesheet)
#adminForm input[type="checkbox"], #adminForm input[type="radio"] {
  margin-right: 5px;
  display: inline-block;
  float: inherit;
}

**Comment by Chacapamac** [comment]
Great!

**Comment by sonvnn** [comment]
I fixed it in One v.2.5.18
