### ISSUE TITLE
Template One - Adding Custom class to custom module on the “right” position it is also applied to the module content div

### ISSUE THREAD

**Issue by Chacapamac** [templaza/astroid-framework#142]
I didn’t try yet a custom module somewhere else than the “right” position.

**Last Astroid/Template one./ last Joomla 3.10 version**

**PROBLEM**
**When you add a custom class to a custom module on the Astroid “right” position it is also applied to the module content div ?**

**This is the setup.**
— _The 2 top & bottom module were newly created with the Astroid template one (I test 2 time to be sure)_
![module](https://user-images.githubusercontent.com/1907276/174491179-6b6547df-e735-4b47-a0fd-bd419c6496dd.jpg)

— _The middle module were created with another framework (Gantry) and the custom class is not repeat to the content

**Top module Astroid**
![1](https://user-images.githubusercontent.com/1907276/174491436-9c4bfdf5-421c-4b50-a750-483d0ace09f9.jpg)

**Middle module Gantry**
![middle](https://user-images.githubusercontent.com/1907276/174491464-51e042b9-460f-4c96-acbc-eb03fbfd57e1.jpg)

**Bottom module Astroid**
![2](https://user-images.githubusercontent.com/1907276/174491482-662d1e2e-7ed7-4c39-ba02-fab7eea1541e.jpg)

**Comment by sonvnn** [comment]
I tried on my local and it doesn't happen. May you give me your link? I will check it.

**Comment by Chacapamac** [comment]
I will check again deeper and upload the website live if I don’t find the problem....
Good Day @sonvnn

**Comment by Chacapamac** [comment]
I just update & upload the website to my testing Server

I email you the infos

Good Day!

**Comment by Chacapamac** [comment]
Thank You @sonvnn 
I came back here because it can be important for many users that will probably wait the last minute to move their Joomla 3 (end of life — August 17, 2023 — to Joomla 4 to be sure that all the kink are iron out.

**You Said**  
> Cause in Joomla 3 includes Module Class Suffix in module code. Joomla 4 removed it. I helped you removed Class suffix in templates/astroid_template_one/html/modules.php

**This is for other people that can have trouble with this on Joomla 3:**
• Make & keep a copy of the original Astroid override of —> templates > astroid_template_one > html > **modules.php**
• Modify—> **modules.php**
—  **Line 32**  —> echo htmlspecialchars($params->get('moduleclass_sfx'), ENT_COMPAT, 'UTF-8') . $moduleClass;
to —> echo $moduleClass;

—  **Line 75**  —> echo htmlspecialchars($params->get('moduleclass_sfx'), ENT_COMPAT, 'UTF-8') . $moduleClass;
to —> echo $moduleClass;

—  **Line 116**  —> echo htmlspecialchars($params->get('moduleclass_sfx'), ENT_COMPAT, 'UTF-8') . $moduleClass;
to —> echo $moduleClass;

—  **Line 144**  —> echo '<' . $moduleTag . ' class="moduletable split-title-module' . htmlspecialchars($params->get('moduleclass_sfx'), ENT_COMPAT, 'UTF-8') . $moduleClass . '">';
to —> echo '<' . $moduleTag . ' class="moduletable split-title-module' .  $moduleClass . '">';

This should be put in the documentation

**Comment by Giorgi625** [comment]
I have noticed this on my websites as well, but I did not knew it was bug.

**Comment by Chacapamac** [comment]
Closing this
