### ISSUE TITLE
New Preset funtion in 2.5.18

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#145]
Hi Sonni,
the new preset funtion in Astroid 2.5.18 is great and its working well.
BUT its not working if you already have preset styles from Astroid 2.5.17. You can select them but not working.
Regards Peter

**Comment by Chacapamac** [comment]
Can you save an actual layout style even if created in 2.5.17 and after updating to 2.5.18 as a new preset and export it to a new Layout Style? — I will try...

**Comment by sonvnn** [comment]
@Joomlaplates Because old preset system store Color data only. You can not use it to restore Layout or Sass Override.
![Screen Shot 2022-06-28 at 08 18 12](https://user-images.githubusercontent.com/3204103/176066337-dc6609b1-a5e9-4569-bbb7-8e96c5837e00.png)

SOLUTION: 
1. Go to Preset Profiles -> Remove all current Preset Profiles. 
2. Re-Create all preset Profiles again.

I update One Template for new Profiles System. You can download and test is here https://github.com/templaza/astroid-framework/archive/refs/heads/one-template.zip

Thanks & Best Regards,
Sonny

**Comment by Chacapamac** [comment]
@sonvnn 
**I Try the Preset on Astroid 2.5.18 — Template Zero 2.5.16 (last) — Joomla 3.10.10**
— I create and Save a Preset Profile of a Custom layout
— Save everything and load that new save Preset  (with the warning  —> Your current configure will be lost and overwritten by new data. Are you sure?.) 
— I see message “setting imported”
— I resave the Layout, empty cache

**All my custom css are gone, my custom layout disappear?????**

— I also try the button { Load preset) beside the layout Style Title
![new-preset](https://user-images.githubusercontent.com/1907276/176710212-8d3348fd-f6f1-4a77-93e1-e159993653ce.jpg)

**What’s left of the custom layout**
![layout](https://user-images.githubusercontent.com/1907276/176710399-427faf2d-e04f-4e91-be95-b956b8f3d61f.jpg)

**Some people will be angry trying that, something is definitely wrong or I don’t understand how it work????**

**Comment by sonvnn** [comment]
@Chacapamac I created video tutorial for this feature https://www.youtube.com/watch?v=UdRbJ86UoSU
Please help me check it again. 

Best Regards,
Sonny

**Comment by Chacapamac** [comment]
Thanks @sonvnn 
**Little problems with template Zero?**
![zero-dropdown](https://user-images.githubusercontent.com/1907276/176944017-26f62892-5a1d-4881-a53b-a55b8d0bab5f.jpg)
**This is an original install — all the Originals styles are in Zero**
also
![Screen Shot 2022-07-01 at 1 34 14 PM](https://user-images.githubusercontent.com/1907276/176944238-47b5688c-6718-4b65-8979-78f475877a2e.jpg)

**Comment by sonvnn** [comment]
> Thanks @sonvnn 
> 
> 
> 
> **Little problems with template Zero?**
> 
> 
> 
> ![zero-dropdown](https://user-images.githubusercontent.com/1907276/176944017-26f62892-5a1d-4881-a53b-a55b8d0bab5f.jpg)
> 
> 
> 
> **This is an original install — all the Originals styles are in Zero**
> 
> also
> 
> 
> 
> ![Screen Shot 2022-07-01 at 1 34 14 PM](https://user-images.githubusercontent.com/1907276/176944238-47b5688c-6718-4b65-8979-78f475877a2e.jpg)
> 
> 
> 
> 
> 
> 

Let's try with One template first. I did not update for Zero.

Thanks & Best regards,
Sonny

**Comment by Chacapamac** [comment]
Do you plan to update Zero?

**Comment by sonvnn** [comment]
@Chacapamac @deltapapa01 I will update Zero in this Fridays.

Best Regards,
Sonny

**Comment by sonvnn** [comment]
@Chacapamac @deltapapa01 I update Zero to v2.5.18. You can download it at https://github.com/templaza/astroid-framework/archive/refs/heads/zero-template.zip

**Comment by Chacapamac** [comment]
Great News, Thank You Sonny, did you update the releases package —> astroid-package-v2.5.18.Framework-Template.zip ?
— Just to be sure people don’t have problem when updating Zero.

**Comment by deltapapa01** [comment]
Hi, thank you very much.
I created a basic template from the zero, like the docs here.
But this is not updated.
What must i do, that my astroid template get the new features too?

**Comment by sonvnn** [comment]
@deltapapa01 Please send me your admin account via sonlv@templaza.com I will help you check it.

**Comment by Chacapamac** [comment]
I’m staying in the conversation
Are the public package — —> astroid-package-v2.5.18.Framework-Template.zip is updated?

**Comment by sonvnn** [comment]
> I’m staying in the conversation
> 
> Are the public package — —> astroid-package-v2.5.18.Framework-Template.zip is updated?

Not yet my friend. I just busy with some meetings today. I will update it asap. You can download Zero in this git and upload to your site for testing.

**Comment by Chacapamac** [comment]
Thanks Sonny, No problems — I will test the update on my test site and come back

**Comment by deltapapa01** [comment]
@sonvnn Hi, i send you an email :-)

**Comment by sonvnn** [comment]
@deltapapa01 I test your website. Zero template is working well. It's v2.5.18. I did not do anything. Just your website still well as before. 

Please check this video https://www.screencast.com/t/JWoZ4wnEhPia

If you want to copy Zero to a new template. You have to copy all file from Zero -> New template. Now, Your new template is still v2.5.16.

Thanks & Best Regards,
Sonny

**Comment by sonvnn** [comment]
@Chacapamac astroid-package-v2.5.18.Framework-Template.zip is updated. Please help me check it again.

Thanks & Best Regards,
Sonny

**Comment by deltapapa01** [comment]
Hi, thank you very much.
That's exactly what the problem is. Why is my new - template not updated? And what exactly do I have to do for this?

**Comment by Chacapamac** [comment]
@sonvnn 
- I just overwrite my v2.5.18 with the github public package and both Templates where updated to 2.5.18.
- System of Save Preset and Load Preset work perfectly for me in Joomla 4 on both Template Zero & One

• I’m trying on Joomla 3.10.10 and come back here

**Comment by Chacapamac** [comment]
@sonvnn  
Work Perfectly on Joomla 3.10 — Bothe Zero & One
— I like the first letter of the template title be in the design — Nice Pro Touch

**Comment by Chacapamac** [comment]
@deltapapa01 

> That's exactly what the problem is. Why is my new - template not updated? And what exactly do I have to do for this?

**If you want to update your template**

**• Go to the releases on this website** (Github)
https://github.com/templaza/astroid-framework/releases

**• Download the last full package (v2.5.18)**
astroid-package-v2.5.18.Framework-Template.zip

**• Install in Joomla installer** 
Warning: Any installation on a website should be done on a copy of your website first or at least be sure to backup (Akeeba Backup) your website before installation

**You're Template Zero will be updated to v2.5.18.** 
— If you don’t need Template One you can uninstall it by Joomla Manage

**Comment by sonvnn** [comment]
> Hi, thank you very much. That's exactly what the problem is. Why is my new - template not updated? And what exactly do I have to do for this?



> Hi, thank you very much. That's exactly what the problem is. Why is my new - template not updated? And what exactly do I have to do for this?

You have to use ftp account. Copy file from Zero template to Your new template to override it. That's all.

Best Regards,
Sonny

**Comment by deltapapa01** [comment]
Okay, excellent, that's exactly what I wasn't sure about. Maybe you could include that in the documentation, I found out in the German Joomla forum that other people are having problems with it. I'll post the solution there as well.

Thank you very much for the great framework / template and your great work :-)
