### ISSUE TITLE
Joomdev links on Astroid install & 404 link in template Style window

### ISSUE THREAD

**Issue by Chacapamac** [templaza/astroid-framework#148]
• When installing 2.5.18 the Astroid welcome screen **show old Joomdev links**

![Install](https://user-images.githubusercontent.com/1907276/178524013-1ce80087-90ba-498b-b046-d29dac5f8bda.jpg)

• On the Template Style main window the “**More Templates**” link give a 404 error because you change the name on the website for “**Partners**”

**Note:** You Should add the word “Templates” in that “main “Partners” menu.
—> ”Partners & Templates” or even better just “Templates”
—> Ordinary People looking for the NEW Astroid Framework NEED to have a direct access to the Templates available for thath framework. They careless if they are partners or not.

![Template Style](https://user-images.githubusercontent.com/1907276/178526134-c21625f1-0b9e-4b2c-a2c5-fe4118043999.jpg)

**Comment by sonvnn** [comment]
@Chacapamac I updated partner link https://github.com/templaza/astroid-framework/commit/f19a2e727bece8727e030e1947945d566d9fb708

Thanks & Best Regards,
Sonny

**Comment by Chacapamac** [comment]
Good Day Sonny
