### ISSUE TITLE
Article version history displays warnings.

### ISSUE THREAD

**Issue by ReLater** [templaza/astroid-framework#149]
- AF 2.5.18, Joomla 4.1.5, PHP 8.0
- Backend.
- Activate version history for com_content in Joomla 4.
- Activate error reporting in Joomla configuration.
- Create an article and save it.
- Click button "Versions".
- Click a date link to see the overview/preview. Scroll down.

![grafik](https://user-images.githubusercontent.com/20780646/178563271-98fdcdee-8b38-49f6-b033-4cb760dddb47.png)

![grafik](https://user-images.githubusercontent.com/20780646/178563349-54fff5ee-f910-46ef-8ac1-bf1422878cd2.png)

**I think it's a Joomla issue** and can be fixed similar to this pr: https://github.com/joomla/joomla-cms/pull/38245/files

```PHP
	<td><?php
if (\is_array($subValue->value)) {
	if (\count($subValue->value) === \count($subValue->value, \COUNT_RECURSIVE)) {
		$subValue->value = \implode(', ', $subValue->value);
	} else {
		// Multidimensional array
		$subValue->value = \json_encode($subValue->value, \JSON_UNESCAPED_UNICODE);
	}
}
	echo $subValue->value; ?></td>
```

**Comment by Chacapamac** [comment]
I confirm the bug — Same here!
(items & Criterias)
Notice: Array to string conversion in /home/mydomain/domains/mywebsite/public_html/administrator/components/com_contenthistory/tmpl/preview/preview.php on line 50
Array

**Comment by sonvnn** [comment]
@ReLater Thanks for feedback. I check this issue. The correct code should be
```
if (\is_object($subValue->value) || \is_array($subValue->value)) {
                            $subValue->value = \json_encode($subValue->value, \JSON_UNESCAPED_UNICODE);
                        }
```

**Comment by sonvnn** [comment]
@ReLater I created a pull request for Joomla CMS https://github.com/joomla/joomla-cms/pull/38273

Thanks & Best Regards,
Sonny
