### ISSUE TITLE
Responsive Typo is not working

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#151]
Hello, 
just notice the responsive settings for typo is not working.
Its always shown the desktop font-size, doesnt matter what size is selected.
![settings](https://user-images.githubusercontent.com/71080509/179088617-bba34eaf-5145-41ae-8e3f-4495597a98b0.jpg)

**Comment by sonvnn** [comment]
@Joomlaplates I test in my local. Everything is seem well. Please check https://www.screencast.com/t/Ylv3zZB2mB
May you detail your issue?

**Comment by Chacapamac** [comment]
I just test on 2 websites, one local, one live on both template zero and one
and it work well.
Maybe a problem with the choice of font family?

**Comment by Joomlaplates** [comment]
Ok, I found the issue.
It was a not missing bracelet in custom css code
