### ISSUE TITLE
Notifications close button does not work

### ISSUE THREAD

**Issue by Giorgi625** [templaza/astroid-framework#152]
When I save something in frontend there is Success notification block which has X as a close button but it does not work
https://i.postimg.cc/MH36BtP5/notification.png

**Comment by Chacapamac** [comment]
**I test with a Joomla article**

• When I click the “Edit” link I get an error **even if I can edit correctly**
```
Uncaught TypeError: Joomla.initialiseModal is not a function
    connectedCallback http://mytestsite/media/system/js/fields/joomla-field-media.min.js?b9214e72c06daafd562e5c4116292b5763a437fe:1
    <anonymous> http://mytestsite/media/system/js/fields/joomla-field-media.min.js?b9214e72c06daafd562e5c4116292b5763a437fe:1
joomla-field-media.min.js:1:3102
```
• When I save, I get the same type of notification that my article where save. I also get that minuscule “X” bouton that doesn't work.

**• Work perfectly in Cassiopea...**

**Comment by sonvnn** [comment]
@Giorgi625 @Chacapamac This issue because out of date of "html/layouts/system/message.php" since 2.5.4. Please follow step below:

1. Please help me remove file "{yourtemplate}/html/layouts/system/message/php"
2. Go to front-end and try it again.

Best Regards,
Sonny

**Comment by sonvnn** [comment]
@Giorgi625 @Chacapamac I fixed this issue in latest commit you can check it https://github.com/templaza/astroid-framework/commit/7296853d343f78d4409fba4c7759c6f3526c144a

Please help me download developer branch https://github.com/templaza/astroid-framework/archive/refs/heads/developer.zip and test it in your local.

Best Regards,
Sonny

**Comment by Chacapamac** [comment]
@sonvnn 
Just Check on template Zero & One — Work perfectly and the design and close button are perfect.
Solved for me!
Good Day to All.
