### ISSUE TITLE
<meta name instead of <meta property

### ISSUE THREAD

**Issue by Giorgi625** [templaza/astroid-framework#155]
So I am using 3rd party extension called Cobalt CCK on one of my websites to display content. I have field in there whih generates open graph tags. It genereates correct tags <meta property ...
but I also have some menu items where I have set open graph data using Astroid tabs. so on a were I am showing full view of article it shows tags from my field and from parent menu item created using Astroid plugin.
This astroid plugin generates tag with <meta name="og:image which facebook debugger says that is wrong and asks to use <meta property.
Because of this image is not shown on my linke when I share it on facebook. I just disabled astrid plugin for menu item so once hope soon facebook debugger will be able to get correct image and show it, but for people who want to use Astroid plugin I think this should be fixed. 
This is generated by Astroid plugin via menu item tabs:
`<meta name="og:image" content="https://infozugdidi.ge/images/opengraph/gancxadebebi.png">
`
should be this
`<meta property="og:image" content="https://infozugdidi.ge/images/opengraph/gancxadebebi.png">`

**Comment by sonvnn** [comment]
Hi @Giorgi625 

I fixed this in commit https://github.com/templaza/astroid-framework/commit/d63a0f28c329c89c37be83687e0a51a80de02753

Please help me check it.

Best Regards,
Sonny

**Comment by Giorgi625** [comment]
Confirm it is fixed.
