### ISSUE TITLE
PHP 8.x Various Deprecation notices

### ISSUE THREAD

**Issue by ghazal** [templaza/astroid-framework#157]
Working with PHP 8.1.7, i get Various Deprecation Notices from your Astroid Template.
NB : I encountered these Notices on previous versions of PHP 8.x
NB2 : I only suggest here my corrections.
Keep up the good work anyhow.

Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /libraries/astroid/framework/library/astroid/Helper.php on line 240
`$str = str_replace(" AND ", " && ", (string) $str);`

Deprecated: str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in /libraries/astroid/framework/library/astroid/Component/Includer.php on line 46
`$body = str_replace($includer['replace'], (string) self::$func() , $body);`

Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /templates/astroid_template_one/html/com_users/login/default_login.php on line 30

Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /templates/astroid_template_one/html/com_users/login/default_login.php on line 42

`<?php if (($this->params->get('logindescription_show') == 1 && str_replace(' ', '', (string) $this->params->get('login_description')) != '') || $this->params->get('login_image') != '') : ?>`

**Comment by Chacapamac** [comment]
**Just test with PHP 8.1...**
— No errors in console
![bug](https://user-images.githubusercontent.com/1907276/182201747-bdc76b7c-8233-4875-9dfc-b40556def40d.png)

**Comment by sonvnn** [comment]
@ghazal Hi, Thanks for report issue. I fixed this issue in https://github.com/templaza/astroid-framework/commit/c7e9ecc5d2d4d2920923113a0173a10abd6c4f1b

Please help me check it again.
Thanks & Best Regards,
Sonny

**Comment by sonvnn** [comment]
@Chacapamac I fixed issue in https://github.com/templaza/astroid-framework/commit/64519b4326647e7b4842f849d26a751c418cc6ff

Please help me download One-Template and Zero-Template in https://astroidframe.work/download and try it again.

Thanks & Best Regards,
Sonny

**Comment by Chacapamac** [comment]
@sonvnn 
No more text warning in both template Zero & One
No Console errors or warning
and lightning fast... :)

**Comment by Chacapamac** [comment]
@sonvnn 
**Not sure what’s happening???** —  I reinstall the Framework  &  templates using your link —> https://astroidframe.work/download

and the deprecated errors are back on my test website —> http://joom4-astro.graf-test.ca/
_**Note:** I can give you the keys for it, it's only a test website_

**Comment by sonvnn** [comment]
Hi @Chacapamac 
I fixed issue in https://github.com/templaza/astroid-framework/commit/532ff656d79d3167c5ca2a9e426e53b1b6492739

Please help me check it.

Thanks & Best Regards,
Sonny

**Comment by ghazal** [comment]
Tested on 4.2.
No more Deprecation notice for now.
Will let you know here if I find more.
Tks.

BTW, tried Astroid on 4.3 (for fun). At the moment, it's a no-go. But this version in still in early stages.

**Comment by ghazal** [comment]
j!4.2
Same as the one found by Chacapamac (1st post) but I couldn't find your correction.

> htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /templates/astroid_template_one/html/layouts/chromes/astroidxhtml.php on line 28

**Comment by Chacapamac** [comment]
Hi @sonvnn  when you said
> I fixed issue in 532ff65
What I need to do to test, where and what I download? the file itself the last framework/template release, the developer release? 
Sorry to ask, but I’m a newbie to Github....

**Comment by sonvnn** [comment]
A> Hi @sonvnn  when you said
> 
> > I fixed issue in 532ff65
> 
> 
> 
> What I need to do to test? where and what I download? —>  the file itself?, the last framework/template release?, the developer release? 
> 
> Not Sure!
> 
> 
> 
> _Sorry to ask, but I’m still a newbie to Github...._

Please help me download One-Template and Zero-Template in https://astroidframe.work/download and try it again.

Thanks,
Sonny

**Comment by sonvnn** [comment]
> j!4.2
> 
> Same as the one found by Chacapamac (1st post) but I couldn't find your correction.
> 
> 
> 
> > htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /templates/astroid_template_one/html/layouts/chromes/astroidxhtml.php on line 28

It's issue of One Template. Please help me download One-Template and Zero-Template in https://astroidframe.work/download upload to your site and try it again.

Best regards,
Sonny

**Comment by Chacapamac** [comment]
Thanks @sonvnn , I Just did.
• I install both templates and installed.

**Result**
Template Zero — No more deprecated warnings
Template One — No more deprecated warnings

**Comment by Chacapamac** [comment]
@sonvnn 
I just remark a same type of deprecated warning on the **blog_item.php**
It make sense that maybe multiple layout files will be affected...

![Screen Shot 2022-08-05 at 11 22 45 AM](https://user-images.githubusercontent.com/1907276/183109882-20b2fdc5-7c69-460c-a9c7-3d0feec160d3.jpg)

**Comment by sonvnn** [comment]
@Chacapamac I fixed this issue in v2.5.19. Please download https://github.com/templaza/astroid-framework/releases/download/v2.5.19/astroid-package-v2.5.19.Framework-Template.zip and re-install to your site.

Best Regards,
Sonny

**Comment by ghazal** [comment]
Looks like we have a winner here. 
Tested on 4.2.1-rc2
@sonvnn 
Tks

Next big job: adapt astroid to new joomla standards for templates, ie move necessary files to media/templates/site/...
Not that simple.

**Comment by Chacapamac** [comment]
@sonvnn - No More “Deprecated” warnings.
