### ISSUE TITLE
Dropdown Typo > Mobile Size is useless

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#158]
Hi, 
the settings of the Typo in Dropdown Menu > Mobile Size is useless, because the the dropdown menu is not available in mobile devices.
In mobile devices is showing only the hamburger menu. Maybe we could add here the mobile Typo size, or just add a new Typo setting for mobile Hamburger Menu
![dropdwon](https://user-images.githubusercontent.com/71080509/181783031-15332a3e-ae03-4df3-9f85-e085ccd81a6f.jpg)
![dropdwon1](https://user-images.githubusercontent.com/71080509/181783035-a817c20b-21ab-467a-9d05-17b7c27e7aac.jpg)
Greatings, and a nice weekend.

**Comment by Chacapamac** [comment]
I see what you mean, it should impact the mobile menu as well. It make sens.

**Comment by sonvnn** [comment]
@Joomlaplates I totally agree with you. I improve typography mobile style in https://github.com/templaza/astroid-framework/commit/10e0592da4c60e4cbe55a1f4faf25fc4b4d11322

Please help me check it again.

Thanks & Best Regards,
Sonny

**Comment by Chacapamac** [comment]
Ok, I check
**My Settings:** _( Remark that the mobile menu supposed to be bigger than the normal menu...)_
_I clear Astroid and browser cache and replace with the following “Utility.php” with the modifications_
![menu-typo](https://user-images.githubusercontent.com/1907276/184495624-aa9274ff-7e97-449c-9bcb-e8f3657b4c34.jpg)
![mobile-menu-typo](https://user-images.githubusercontent.com/1907276/184495625-b75c29e6-fc57-48c8-a690-f3f4d0e9f6ce.jpg)

**Results:**
![menu-typo](https://user-images.githubusercontent.com/1907276/184495749-0256bf1a-c56f-4b87-82ff-1c3fa05dda5e.jpg)
![mobile-menu-typo](https://user-images.githubusercontent.com/1907276/184495750-9cb9d388-c3e1-47e4-933c-3d83d7c95f4e.jpg)

**What I remark,** 
— I see no change in the menu and mobile menu
— You cannot set a different font family on different device
— the choice of size is correctly registered in the administration after saving the Typography or coming back to the admin

**Comment by sonvnn** [comment]
@Chacapamac May you send me your admin via sonlv@templaza.com? I will check it.

Thanks & Best Regards,
Sonny

**Comment by sonvnn** [comment]
@Chacapamac I test your site and system works well without any issue. 
In the desktop layout: font-size is 16px
In the mobile layout: font-size is 42px

Please check my video https://www.screencast.com/t/ECTGX1MVZ79j

Thanks & Best Regards,
Sonny

**Comment by Joomlaplates** [comment]
@Chacapamac.
Youre wrong. I was talking about the DROPDOWN Menu and the font size in mobile.
1.) The MAIN Menu is not visible in the mobile view
2.) The mobile dropdown menu has nothing to do with the main menu dropdown

**Comment by Chacapamac** [comment]
@sonvnn  — Yes, you right, it work, was probably due to some cache.
Fix for me!
Good Day to All!
