### ISSUE TITLE
Read time is not working if there is no "read more"

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#159]
**Joomla 4 Blog View**
If there is a read more in the article the **read time** is working
But if there is no read more in the article, the **read time** is not working
See picture and Url
https://dev.joomlaplates.de/index.php/joomla/joomla-blog-1-spalte
![reading-time](https://user-images.githubusercontent.com/71080509/182619646-5b341d27-8082-47be-ab26-4c3f50bfa78c.jpg)

**Comment by Chacapamac** [comment]
I just test and without “Read More” whatever the length of the article, the “Read Time” stay at 1minute

**Comment by sonvnn** [comment]
@Joomlaplates @Chacapamac @harrypotter06 I fixed this issue in https://github.com/templaza/astroid-framework/commit/96620a360f163b2ccdee74636fbb95df0e219737

Please help me check it.

Thanks & Best Regards,
Sonny

**Comment by harrypotter06** [comment]
Hello Sonny,

i tested and the first results are loocking nice.
Thanks for this fix.

Question: If the picture float in a article a part from your framework or a part by Template?
I saw that all pictures has  “float: none”  but on Joomla 3.X.X the floating from a picture is selectable.

Thanks and best regards
Klaus


Von: Sonny Le ***@***.***>
Gesendet: Freitag, 5. August 2022 10:32
An: templaza/astroid-framework ***@***.***>
Cc: Klaus Krönert ***@***.***>; Mention ***@***.***>
Betreff: Re: [templaza/astroid-framework] Read time is not working if there is no "read more" (Issue #159)


@Joomlaplates<https://github.com/Joomlaplates> @Chacapamac<https://github.com/Chacapamac> @harrypotter06<https://github.com/harrypotter06> I fixed this issue in 96620a3<https://github.com/templaza/astroid-framework/commit/96620a360f163b2ccdee74636fbb95df0e219737>

Please help me check it.

Thanks & Best Regards,
Sonny

**Comment by Chacapamac** [comment]
@sonvnn Just try the change **framework/article.php**
**Result**
Article with no readmore showing now a correct read time...

Good Day to all!
