### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by darekmer** [templaza/astroid-framework#16]
Hi. Clean installation of joomla 4.0.4 Astroid 2.5.7 template One 1.3.4. PHP 7.4 on Xampp Windows 10.
Sorry, there was a problem we could not recover from.
The server returned a "500 - Whoops, looks like something went wrong."
 
ScssPhp\ScssPhp\Exception\ CompilerException

It's not clear which file to import. Found:
libraries\astroid\framework\library\astroid/./../../../../../templates/astroid_template_one/scss\one/_frontend-edit.scss
libraries\astroid\framework\library\astroid/./../../../../../templates/astroid_template_one/scss\one\frontend-edit.scss: libraries\astroid\framework\library\astroid/./../../../../../templates/astroid_template_one/scss\one/style.scss on line 1, at column 0
Call Stack:
#0 import libraries\astroid\framework\library\astroid/./../../../../../templates/astroid_template_one/scss\one/style.scss libraries\astroid\framework\library\astroid/./../../../../../templates/astroid_template_one/scss\style.scss on line 2
#1 import libraries\astroid\framework\library\astroid/./../../../../../templates/astroid_template_one/scss\style.scss (unknown file) on line 1

**in D:\xampp\htdocs\rod-nowy-2\libraries\astroid\framework\library\scssphp\src\Compiler.php (line 6032)

```
            if (! $this->ignoreCallStackMessage) {
                $msg = $this->addLocationToMessage($msg);
            }
            return new CompilerException($msg);
        }
        /**
         * @param string $msg
         ***
```

**Comment by Joomlaplates** [comment]
Hello, quick fix.
Delete the files with underscore from **scss/one** template folder and install the theme again
![delete](https://user-images.githubusercontent.com/71080509/140738097-d12ddaf0-037a-42be-963d-686d4416c5ef.jpg)

**Comment by darekmer** [comment]
Thanks, it helped

**Comment by sonvnn** [comment]
Yes, I removed astroid_template_one/scss\one\frontend-edit.scss but missing add script to remove it when update. I will update it in the next version.

Best Regards,
Sonny

**Comment by darekmer** [comment]
I found. After deleting '_frontend-edit.scss' the website works.

**Comment by Joomlaplates** [comment]
Hello Sonny, yes its a good idea to insert a script into the Templates which is prove during installaltion, if the wrong files are existing or not and delete the files.

**Comment by sonvnn** [comment]
I updated Astroid template package v2.5.8. Please help me download/update https://github.com/templaza/astroid-framework/releases/download/v2.5.8/astroid-package-v2.5.8.Framework-Template.zip
