### ISSUE TITLE
Deprecated: “str_replace()” warnings in both Zero/One template manager - PHP 8.1.8 

### ISSUE THREAD

**Issue by Chacapamac** [templaza/astroid-framework#161]
This warning appear mostly everywhere in the template manager - PHP 8.1.8  (Joomla 4) didn’t test Joomla 3...

`Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /mywebsitehome/public_html/libraries/astroid/framework/library/astroid/Helper.php on line 240`

![deprecated](https://user-images.githubusercontent.com/1907276/183103549-f65130b8-a509-4c23-8425-8ddb3ad896c1.jpg)

**Comment by sonvnn** [comment]
@Chacapamac I fixed it at #157
Please help me download developer branch and test it again.

Thanks, Sonny

**Comment by Chacapamac** [comment]
@sonvnn Just Tested:

**Developer branch fix:**
— Deprecated  in template manager
— Deprecated in frontend article
— Read Time on Article with no readmore

Everything Good!
