### ISSUE TITLE
Missing language string

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#162]
Hello,
missing language string and button style in the file:
`....\html\com_users\registration\default.php`

Language string is:
`TPL_HAVE_AN_ACCOUNT="Cancel"`

I will add the string to the german and english language file.
Please add the english language string and the button style to the template html override
```
<div class="form-check d-flex justify-content-end">
	<a href="<?php echo Route::_('index.php?option=com_users&view=login'); ?>"><?php echo Text::_('TPL_HAVE_AN_ACCOUNT'); ?></a>
</div>
```
Greatings Peter

**Comment by harrypotter06** [comment]
Hello Peter,

the solution is verry simple. You can change on row 61 the code:

`<a class="btn btn-primary validate" href="/" title="Abbrechen"><?php echo Text::_('TPL_HAVE_AN_ACCOUNT'); ?></a>`

After this change, you have a button loke the original form
