### ISSUE TITLE
No Badge

### ISSUE THREAD

**Issue by harrypotter06** [templaza/astroid-framework#163]
Hello,

i enable the Badge-Funktion. So in the Articel Sourcecode, fond the css classes for badge.
But what i not fond if `<div class="article-badge artikel-badge-1 article-badge-custom-6">HOT</div>` in Article

For testing: I add a simle "echo 'Hello World'; on line 15 into badge.php. But this text will not add to the Article (show source code from Article. Into article i enable badge)

**Comment by Chacapamac** [comment]
I just test Joomla 4 Astroid 4.1.5 — Astroid 2.5.18
I get custom badge on both template Zero & One with the following code
`<div class="article-badge article-badge-1 article-badge-custom-2">My Badge</div>`

![zero](https://user-images.githubusercontent.com/1907276/183663311-5c41145c-547a-47ea-b97b-4319ea1e7418.jpg)

![Screen Shot 2022-08-09 at 9 32 36 AM](https://user-images.githubusercontent.com/1907276/183663413-c8fcaa12-84cc-4b38-aa43-0dd2f2a8c6db.jpg)
