### ISSUE TITLE
Error on php 8

### ISSUE THREAD

**Issue by nidzo80** [templaza/astroid-framework#164]
When I switch to PHP 8.1 my Joomla 4 site gets this error (in backend and frontend)

`Astroid\Framework::getDocument(): Return value must be of type Astroid\Document, null returned`

`in /libraries/astroid/framework/library/astroid/Framework.php (line 84)`

J4 version 4.1.5
Astroid Framework 2.5.18
Zero and One template version: 2.5.18
![astroid php8](https://user-images.githubusercontent.com/21330927/183251886-dd8f2dbf-a086-49f0-8d23-edbe13afc885.jpg)

On other 6 sites with same server settings PHP 8 works without problem.

**Comment by Chacapamac** [comment]
I cannot recreated the problem
My Test Joomla 4.1.5 — Astroid Framework 2.5.18 — Zero and One template version: 2.5.18
Work perfectly in PHP 8.1.8

The only thing I can bring is the PHP extensions on my working PHP 8.1.8. 
![php-extensions](https://user-images.githubusercontent.com/1907276/183445034-6a1901b5-42f7-46c0-bbd7-bef41cd1e199.jpg)

**I mark this as a bug**

**Comment by nidzo80** [comment]
I can't reproduce problem on local WAMP server either. Site is on shared hosting so I asked support to share their PHP 8.1.8 settings so I can try to reproduce problem and give more details here.

**Comment by Chacapamac** [comment]
I Just tested on my Mamp PHP 8.0.8 — No problem?

Did you try to re-download a fresh Astroid an templates and reinstall on top?
Maybe a corrupt install files?

**Comment by nidzo80** [comment]
Yes I did. Even full unistall and install again. 
Problem is that I can't reproduce error problem on localhost WAMP server. Only difference is that live server uses LiteSpeed that cannot be installed on Windows WAMP. I will continue investigating ;)

**Comment by Chacapamac** [comment]
@nidzo80 
This is my system info on my live test website, they use Litespeed also and I have no problems.
![Screen Shot 2022-08-10 at 10 19 37 AM](https://user-images.githubusercontent.com/1907276/183925350-75d5991e-9bc3-4a51-ac43-d2a206f21e60.jpg)

Good Day!

**Comment by Joomlaplates** [comment]
Please disable the Joomla cache completely and try again

**Comment by nidzo80** [comment]
@Chacapamac and @Joomlaplates thank you. Disabling Joomla cache helped. Now I don't get error for Astroid but some other revealed. It is not related to Astroid but if you have any idea I would appreciate.

_mysqli_sql_exception_
`Commands out of sync; you can't run this command now`
in /home/xxxxx/public_html/libraries/vendor/joomla/database/src/Mysqli/MysqliStatement.php (line 137)

![mysqli](https://user-images.githubusercontent.com/21330927/184331814-54a8c8dc-d62a-4a41-a32e-f1155e1b0253.jpg)

**Comment by Chacapamac** [comment]
For your error, I think some extension is causing that as its a database related problem or a misconfiguration of the server. I think?

**Comment by nidzo80** [comment]
I think so! I will close this issue as it is not related to Astroid.
Thanks again guys!
