### ISSUE TITLE
Unable to select colours from the theming section

### ISSUE THREAD

**Issue by ramblerswebs** [templaza/astroid-framework#165]
Hi
I have just started to look at Astroid and so far I am very impressed.
I do however have an issue in the if I go into the Theming section and change or add sass colours then I don't seem to be able to select or use them elsewhere
If I go to say the Basic section and try to change the colour of the preloader then I can only see the manual colour option.
Looking at the image https://www.joomdev.com/wp-content/uploads/2021/11/8-18.jpg
under the RGB display there seems to be the theme colours which I assume you can select.
Looking at my site the popup finishes at the RBG item. If I inspect the html then the extra colours appear to be there but are set to display: none
I am using astroid_template_zero version 2.5.18 on Joomla 3.10.10 PHP 8.0
any help gratefully received

**Comment by Chacapamac** [comment]
@ramblerswebs 
This is weird, I just test on both Templates Zero & One 2.5.18 on Joomla 3.10.10 PHP 8.0 and the last Joomla 4 and this is what I have.

![one](https://user-images.githubusercontent.com/1907276/183438965-a3dec74c-d849-42cd-a3d3-eabe0df790e7.jpg)

**These swatches seems to be in relation with the colors in the **Theming** section of the Template manager.**
![Screen Shot 2022-08-08 at 10 20 24 AM](https://user-images.githubusercontent.com/1907276/183439977-02ab787e-42be-4c46-b97b-c432ec73b5d7.jpg)

My feeling is that these swatches should be there (in my case) and functional (in yours) and users should be able to change them in the “**Theming**” section?

**Comment by ramblerswebs** [comment]
@Chacapamac Yes being able to set up a colour scheme/theme for a site and then select those colours is very important.
Is there anything I can do to help find where the problem is?

**Comment by Chacapamac** [comment]
I just ask Sonny here to look at it.

@sonvnn  — Can you look at this?

**Comment by ramblerswebs** [comment]
For what it is worth, the two display: none statements that stop the display of the set colours is in the file
media/astroid/assets/scss/_spectrum.scss
Lines 147 and 152

If I turn these two statements off this is the popup display
<img width="204" alt="palette" src="https://user-images.githubusercontent.com/8155959/184933181-b49e1cc2-7ebf-4b3c-a31b-b89d12c699a4.png">

**Comment by sonvnn** [comment]
@ramblerswebs Theming uses for override Sass variable only, It useful for developer only. You can override a Sass variable or define a new variable use for your template. 

Your admin screen is very strange. It is not look like 2.5.18. May you send me you admin account via sonlv@templaza.com? I will help you check it.

Best Regards,
Sonny

**Comment by ramblerswebs** [comment]
Sonny
I have no idea why this issue is closed. 
You say Your admin screen is very strange. It is not look like 2.5.18 but all I did was install the software I gave you the link for that software, was that wrong?
When I go to the test site I gave you access to the colour selector looks the same to me.

**Comment by sonvnn** [comment]
I closed this issue because you did not provide more information for it. May you give me your admin account? I need to check it in admin. With your screenshot I can not debug the issue

**Comment by ramblerswebs** [comment]
Sonny
I did try and send you the information you asked for.
The email I sent is below, I have done an update that was flagged since then



Sonny

thanks you very much for helping. I just hope I am not doing something stupid.

I have set up a test site for you to look at

the site is https://test.locahaberandlorn-ramblers.org.uk/administrator

please log on with sonny/Astroid1  Please change the password once you have logged on!

As far as Astroid is concerned all I have done is to install

https://github.com/templaza/astroid-framework/releases/download/v2.5.18/astroid-package-v2.5.18.Framework-Template.zip

If I go into the zero template and click on the preloader colour I get the colour selector but without the preset colours


thanks again for your help

**Comment by sonvnn** [comment]
@ramblerswebs I enabled Spectrum Palette feature. Now you can use preset colours in admin.

Thanks & Best Regards,
Sonny
