### ISSUE TITLE
Posts - Hide title (and all options)- is changed unintentionally when saving in the frontend

### ISSUE THREAD

**Issue by WM-Loose** [templaza/astroid-framework#167]
Error only occurs if Astroid Framework 2.5.18 is installed on Joomla 3.10.10 and Joomla 4.1.5.

No matter what was preset for an individual post in the backend, it will be overwritten by the post options set in the global settings in the backend (posts / options) when the post is edited and saved in the frontend.

Thus, the user has to go back to the backend and adjust the option of the edited post again and again.

If I have set options for a post in the backend and open and save the editor in the frontend, all individual options set in the backend are overwritten by the global options. This only happens if the Astroid Framework is installed.

Testing:
Posts Options "Show title set to YES by default"

Open or create a post in the backend and set the title display to "do not show" for this individual post, deviating from the standard.

Open this post in the frontend, edit it and save it.

Now the title is automatically set to "show" again, which I don't think was the case before.

If I change editorial content via the backend in the post, the selection of the title (show or not) is retained without automatically loading the default setting.

So it only happens when editing in the frontend.

This behavior is not editor specific and happens the same way with JCE as it does with Tiny.

**Comment by Chacapamac** [comment]
Yes, I duplicate the problem on both Joomla 4 and 3

**I label it as a bug**

**Comment by WM-Loose** [comment]
Ok thanks

**Comment by sonvnn** [comment]
@WM-Loose Hi! Thanks for report issue. I tested and realized that it is Joomla core issue. I change default template to Default template and this issue happen again and again. I posted this issue on Joomla issue https://github.com/joomla/joomla-cms/issues/38508 
We will invest and fix this issue in the next Joomla update version.

Thank you & Best Regards,
Sonny

**Comment by Chacapamac** [comment]
Great Day to All!

**Comment by sonvnn** [comment]
@WM-Loose @Chacapamac I found issue from `Joomla Form:loadFile()` function. I tested and Helix Framework got same issue, too.

I fixed it in Astroid by trigger event `onContentBeforeSave` https://github.com/templaza/astroid-framework/commit/72fa0cdef58339c983085cd238de867f3d1e3e57

Please help me check it again and give me your comment.

Thanks & Best Regards,
Sonny

**Comment by Chacapamac** [comment]
**I Just change the 3 files in my test website.**
—> The custom article option is still overwritten if the article is re-save/modified in frontend 

**Not sure if I download the file correctly,**
I take the raw version of each files and save it to a unformatted (plain text) document and save them with the proper name and extensions and replace the same files (rename with a .old extension on my test website.

**Tell me if it's the way to do that?**
![hide](https://user-images.githubusercontent.com/1907276/185950092-c752db9b-0e35-4e62-9078-fe6c30b3b1ab.jpg)

![no-title](https://user-images.githubusercontent.com/1907276/185950114-1a700537-9d6f-4076-a95e-164395155721.jpg)

![Screen Shot 2022-08-22 at 10 46 52 AM](https://user-images.githubusercontent.com/1907276/185950136-f73b8a1e-af3e-412e-a65e-ea340fcb231e.jpg)

**Comment by sonvnn** [comment]
Please download developer branch and re-test again. Thank you

**Comment by Chacapamac** [comment]
**Developer Branch work perfectly !**
Backend article options does not revert to default wen frontend editing
SOLVED FOR ME!

**Comment by WM-Loose** [comment]
Sonny you are the best. Everything works fine now. 
Thanks for the quick help and many greatings from germany.
