### ISSUE TITLE
New fr-FR.astroid.ini base on last modification of en-GB.astroid.ini #169 

### ISSUE THREAD

**Issue by Chacapamac** [templaza/astroid-framework#170]
Testing the **en-GB.astroid.ini #169** modification —> https://github.com/templaza/astroid-framework/pull/169#event-7193549601
I revise the **fr-FR.astroid.ini** to reflect the last modifications.

**File was tested successfully.**
[fr-FR.astroid.ini.zip](https://github.com/templaza/astroid-framework/files/9351369/fr-FR.astroid.ini.zip)

**Comment by sonvnn** [comment]
@Joomlaplates please help me update fr-FR.astroid.ini to language branch

**Comment by Chacapamac** [comment]
@sonvnn — I insert the tested french file in this post. See above.
This is my last modification base on your changes to the english language file in the #169 modifications.

**• If you change the english file again, where I can download it?**
—> development branch, last release?

**Comment by sonvnn** [comment]
Yes, developer branch is latest release, my friend

**Comment by Chacapamac** [comment]
Your developer branch miss the #169  modification ?   (TPL_HAVE_AN_ACCOUNT="Cancel")
The french file I upload first has it, plus all other change from the actual dev branch.

• Take this one, I change the date and version in the header (for my record) and it contain the #169 modification
• Tested before ZIP

[fr-FR.astroid.ini.zip](https://github.com/templaza/astroid-framework/files/9397159/fr-FR.astroid.ini.zip)

**Comment by Joomlaplates** [comment]
Thanks so much. New version is online.
Regards Peter
