### ISSUE TITLE
New Issue in Joomla 4.2

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#171]
Hi there, 
in Joomla 4.2 you get an error like this
`count(): Argument #1 ($value) must be of type Countable|array, null given`
The problem is based on the file with the template html folder
`>> mod_login/default.php`
I have just removed the code from Line 52 - 67 and the issue is gone.
**Here is the code which i´ve deleted**
```
   <?php if (count($twofactormethods) > 1) : ?>
      <div id="form-login-secretkey" class="form-group">
         <?php if (!$params->get('usetext', 0)) : ?>
            <label for="modlgn-secretkey">
               <?php echo Text::_('JGLOBAL_SECRETKEY'); ?>
               <i class="fas fa-info-circle hasTooltip" title="<?php echo Text::_('JGLOBAL_SECRETKEY_HELP'); ?>"></i>
            </label>
            <div class="input-group">
               <input id="modlgn-secretkey" autocomplete="off" type="text" name="secretkey" class="form-control" tabindex="0" size="18" />
            </div>
         <?php else : ?>
            <label for="modlgn-secretkey"><?php echo Text::_('JGLOBAL_SECRETKEY'); ?></label>
            <input id="modlgn-secretkey" autocomplete="off" type="text" name="secretkey" class="form-control" tabindex="0" size="18" />
         <?php endif; ?>
      </div>
   <?php endif; ?>
```

**Comment by sonvnn** [comment]
@Joomlaplates I got it. I fixed it in https://github.com/templaza/astroid-framework/pull/172/files
May you help me download "developer" branch and test it?

Best Regards,
Sonny

**Comment by Chacapamac** [comment]
@sonvnn 
Just test Joomla 4.2 + "Developer" branch
_**Note:** I also add a Login module in case it was necessary???_

**NO ERRORS**


=============================================================
The only error was related to an broken image link in the footer (404) of Template One.
Just need to clear it
![Screen Shot 2022-08-17 at 10 07 25 AM](https://user-images.githubusercontent.com/1907276/185157998-cbb2cac9-9612-4861-9940-203e86a58513.jpg)

**Comment by sonvnn** [comment]
@Joomlaplates May you help me confirm this will solve your template problem?
