### ISSUE TITLE
Falang

### ISSUE THREAD

**Issue by eomatica** [templaza/astroid-framework#175]
Joomla version 4.2 When i enable Falang Driver (4.1.0) site brokes and ask for astroid framework activation (2.5.19)

Tried both plugins in diferent orders, one before another, the first or the last one

Magazine tz template

**Comment by Chacapamac** [comment]
I mark it as a bug.

_Just to talk:_
I’m sure, you probably need this specific multilingual component. I remember using Joomfish in the Joomla 1.5 era. Good luck for Joomla this permit international websites. I will not be able to use Joomla without Joomfish, at that time...

Today, I wonder why using third party component when Joomla offer in its core a powerful mature, simple and beautiful multilingual system completely integrated in it’s administration?

**Comment by eomatica** [comment]
Falang right now makes the work except main menu that can't get it translated it

⁣Obtener BlueMail para Android ​


-------- Mensaje Original --------
De: Chacapamac ***@***.***>
Enviado: Tue Aug 30 16:00:30 GMT+02:00 2022
A: templaza/astroid-framework ***@***.***>
Cc: eomatica ***@***.***>, Author ***@***.***>
Asunto: Re: [templaza/astroid-framework] Falang (Issue #175)

I mark it as a bug.

_Just to talk:_
I’m sure, you probably need this specific multilingual component. I remember using Joomfish in the Joomla 1.5 era. Good luck for Joomla this permit international websites. I will not be able to use Joomla without Joomfish, at that time...

Today, I wonder why using third party component when Joomla offer in its core a powerful mature, simple and beautiful multilingual system completely integrated in it’s administration?

**Comment by Chacapamac** [comment]
Cool!

**Comment by Chacapamac** [comment]
@eomatica  I think this is not an Astroid related bug — I change the “bug” label as an “issue”

You said :

> When i enable Falang Driver (4.1.0) site brokes and ask for astroid framework activation (2.5.19)
This is weird because Astroid 2.5.19 is an old JOOMDEV version
https://github.com/joomdev/Astroid-Framework/releases

What is your actual Astroid framework?

**Comment by sbouey** [comment]
Hi, the issue with menu don't exist anymore with android 
Framework Version: 2.6.2
Template Version: 1.3.11

Only a problem with the article param's in backen, i'm looking in a solution for this

Stéphane
Falang team

**Comment by Chacapamac** [comment]
> Only a problem with the article param's in backen, i'm looking in a solution for this

@sbouey Can we close this issue?

**Comment by sbouey** [comment]
yes you can close it, 
if you need the next release of Falang write me directly by mail so i can send it to you. this version fix display for param's (aticle an others)

Stéphane

**Comment by Chacapamac** [comment]
No problem Stephane — Happy New Year!
Good to know that Falang work with Astroid, Thanks!

**Comment by Chacapamac** [comment]
I close the issue

**Comment by sbouey** [comment]
yes it's closed for menu but not yet for extra articles param's translation articletypeoptions

Stéphane

**Comment by Chacapamac** [comment]
@sbouey — I think you should open another Issue or Discussion for your “extra articles param's translation articletypeoptions” and maybe give a bit more details. It’s easier to have one issue by post. I will check your issue.

**Comment by sbouey** [comment]
Hi, i have open a discussion but if you prefer an issue it's possible,
i have published the last falang with fix on param's translation only the article.xml from astroid need to be commented.
https://github.com/templaza/astroid-framework/discussions/270

Stéphane
