### ISSUE TITLE
Downgrade to 2.5.17 via FTP

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#178]
Hello together,
we have many problems with J 4.1.5 and Astroid 2.5.19 with PHP 8.
![Unbenannt](https://user-images.githubusercontent.com/71080509/186872724-e47cb9b6-b364-4637-8c4a-140ceca6c37c.PNG)

Always got an error and have no more access to Joomla backend.
...
Its possible to downgrade Astroid via FTP? Which files need to replaced?

**Comment by Chacapamac** [comment]
I see the error is Class ”Astroid\Framework not found”

Seem like something is missing in your installation? Not Sure — I flag it as a bug

Just updated my Joomla 4.2 + Astroid framework & Templates Zero/One to 2.5.19 on PHP 8.1.9 — No problems - No Errors

**Comment by sonvnn** [comment]
@Joomlaplates It look like Astroid is not install successfully. Let's go to phpmyadmin > #__extensions table disable plugin astroid. Go to extension > Re-install Astroid again.
![Screen Shot 2022-08-27 at 09 59 22](https://user-images.githubusercontent.com/3204103/187011791-8b2b6f4f-c950-4b63-af92-5e308eff7a75.png)
