### ISSUE TITLE
After update to 2.5.19 my edits in html folder were overwriten. 

### ISSUE THREAD

**Issue by Giorgi625** [templaza/astroid-framework#180]
I knew that what you edit in html folder of template should not be overwritten when you update template, but few minutes ago I updated template to 2.5.19 and edits I made to frontend edit form file in html/com_content/form folder was changed so I lost my edits.
I was able to restore backup and get back my edits, but I am curious why it happened.

**Comment by sonvnn** [comment]
Hi @Giorgi625 ,

I apologize for this inconvenience. Some functions in the form are not supported by Joomla 4. I removed it to load from Joomla Core. I removed this code as it is not needed in the next version. So you can update without worry in 2.5.20

Best Regards,
Sonny

**Comment by Giorgi625** [comment]
So can I keep my old file which I edited in 2.5.18 version ? or better to edit again file from latest version ?

**Comment by sonvnn** [comment]
I removed override code at https://github.com/templaza/astroid-framework/commit/2664898e1901213fb304d4bcfb6636bec1974004

Please wait to Monday. I will release Version 2.5.20 on Monday after @Chacapamac confirm some issue resolved.

Best Regards,
Sonny
