### ISSUE TITLE
Change LOGO Size in Header 

### ISSUE THREAD

**Issue by MichaelMGK** [templaza/astroid-framework#182]
Hello, I am looking for a solution how I can resize the Logo in the header. The Logo is very small on my view. Much more smaller than the regular image. Can I define a standard high or width for desktop-view?

**Comment by Chacapamac** [comment]
My way to do that is to use a custom module and position in the Astroid Header. You need to use an absolute positioning to permit to your logo to exceed the size of the parents containers.

You can see an example on a website I’m working on on mt testing server —> http://www.graf-test.ca/

**Comment by nidzo80** [comment]
I use custom CSS 
`.astroid-logo img {
    max-width: enter value px;
    max-height: enter value px;
   
}`

**Comment by MichaelMGK** [comment]
Thanks for custom CSS. Works fine
