### ISSUE TITLE
Loading Animation not ending in PHP 8,1

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#183]
Hello,
I have a really strange problem.
-Astroid 2.5.20 & Joomla 4.2.1
....
The Astroid Loading funtion is not ending in PHP 8.1. When I switch back to 7.4 its working.
Attached my 2 Json Files from the export which shows the config of PHP 7.4 and 8.1
Maybe someone find a solution. I am searching since 2 days. Even with comparing the 2 files I couldnt find the issue
Thanks, Peter
[Json.zip](https://github.com/templaza/astroid-framework/files/9479004/Json.zip)

**Comment by Chacapamac** [comment]
I @Joomlaplates,
I just try Astroid 2.5.20 and update my Joomla 4.2.0 to 4.2.1 
I’m on PHP 8.1.9

**I load the animation without problem.**

**My php extensions**
![extensions](https://user-images.githubusercontent.com/1907276/188271611-a2ab8538-4238-4bcc-8a74-18d1a8a8842a.jpg)

**My settings**
![settings](https://user-images.githubusercontent.com/1907276/188271627-0645e9b6-aa0f-418f-b931-365fb6407c0e.jpg)

Did You try re-installing Astroid 2.5.20 or try install Joomla 4.2.2?

**Comment by sonvnn** [comment]
@Joomlaplates you can send me your website link with php8.1 via sonlv@templaza.com. I will help upu check it

**Comment by Joomlaplates** [comment]
Sorry guys, now its working and the worst thing is, I dont know why!!!

**Comment by Chacapamac** [comment]
Probably some cache, somewhere. I guess...
Good Day, all Astroid  fans!
