### ISSUE TITLE
template not updating - wrong site link?

### ISSUE THREAD

**Issue by 888Jay** [templaza/astroid-framework#185]
Hi,

I started with Astroid Framework 2.5.15, and I see it has now updated to 2.5.20. However, template_one still shows as 2.5.14 (I deleted template_zero). I checked the "Update Sites" list and it shows the old joomdev update link. How do I fix this?

Thanks
![Screenshot 2022-09-03 170258](https://user-images.githubusercontent.com/45702513/188289040-d756ed9a-2d4c-4e0f-8775-0fb23549e22f.jpg)
![Screenshot 2022-09-03 170134](https://user-images.githubusercontent.com/45702513/188289047-72ae1654-e045-4d48-8a96-29297a3f2a7e.jpg)

**Comment by sonvnn** [comment]
Hello,

You can download template package here https://github.com/templaza/astroid-framework/releases/download/v2.5.20/astroid-package-v2.5.20.Framework-Template.zip

Upload to your site -> go to Update Sites -> Click rebuild. Done!

Best Regards,
Sonny

**Comment by 888Jay** [comment]
Hi Sonny,

Before I posted here I did try to reinstall the framework. I guess I didn't click rebuild.

All good now. Thanks!
