### ISSUE TITLE
Blog columns

### ISSUE THREAD

**Issue by darekmer** [templaza/astroid-framework#19]
Howto add support for blog columns (2,3,4) on Joomla 4 - Template One ?

**Comment by sonvnn** [comment]
Let's go to Menu manager > Blog Menu > Blog Layout > Columns.
![screenshot-joomla templaza com-2021 11 10-09_46_37](https://user-images.githubusercontent.com/3204103/141040489-e8412216-ba0e-472e-b58d-80034d322d46.png)

**Comment by darekmer** [comment]
This option is set, and the column is still one.
maybe it has to do with removing scss files from thread # 16?

**Comment by darekmer** [comment]
and something like this:
```
Uncaught TypeError: $(...).find(...).astroidMobileMenu is not a function
    initOffcanvasMenu https://localhost/j/media/astroid/assets/vendor/astroid/js/script.js?v=2.5.7:24
    docReady https://localhost/j/media/astroid/assets/vendor/astroid/js/script.js?v=2.5.7:237
    jQuery 2
        e
        t
script.js:24:47
```

**Comment by sonvnn** [comment]
I not sure. But it works pretty good on my site without any issue.
![screenshot-joomla templaza com-2021 11 10-12_30_46](https://user-images.githubusercontent.com/3204103/141056082-d0768fc6-6984-478e-9afe-724e75b99502.png)

**Comment by darekmer** [comment]
https://user-images.githubusercontent.com/44267306/141060808-26e3c531-7e0a-47cd-8f86-b218046b7fbe.mp4

**Comment by sonvnn** [comment]
If you send me your site url. I will help you check it. Anyway, you can check my demo at http://joomla.templaza.com/astroid/joomla/

**Comment by darekmer** [comment]
I already know...
menu setting 'Featured Articles'> no columns, 'Category Blog' are columns.
I will try to put the server outside

**Comment by Joomlaplates** [comment]
Yes I can confirm, blog settings are not working.
I get an error too when I want to setup a blog in Joomla 4. 
With Astroid 2.5.4 it was working
![article](https://user-images.githubusercontent.com/71080509/141120495-05272e18-8cb1-4af2-a870-4449253efc57.jpg)

**Comment by sonvnn** [comment]
Hello @darekmer,
![Screen Shot 2021-11-11 at 09 01 54](https://user-images.githubusercontent.com/3204103/141223889-a84f3fde-afb3-4938-9de9-1b444a31b649.png)

I found issue at astroid_template_one/html/com_content/featured/default.php line 54.
Please replace
`$columns = ASTROID_JOOMLA_VERSION > 3 ? 1 : $this->columns;`
by
`$columns = ASTROID_JOOMLA_VERSION > 3 ? $this->params->get('num_columns', 1) : $this->columns;`

It will work. I sure that.

**Comment by sonvnn** [comment]
I updated Astroid v2.5.8. You can download template package and update to your site https://github.com/templaza/astroid-framework/releases/download/v2.5.8/astroid-package-v2.5.8.Framework-Template.zip

**Comment by darekmer** [comment]
thanks, it works

**Comment by darekmer** [comment]
Hello, menu setting 'Featured Articles' article-info not visible. Can you help?
