### ISSUE TITLE
Error with PHP 8

### ISSUE THREAD

**Issue by chupidos** [templaza/astroid-framework#190]
I have been getting this error after upgrading a Joomla 4.2.2 website to PHP 8.0.23

`AH01071: Got error 'PHP message: PHP Warning: Attempt to read property "query" on null in /public_html/libraries/astroid/framework/article.php on line 52 PHP message: PHP Warning: Trying to access array offset on value of type null in /public_html/libraries/astroid/framework/article.php on line 52`

It happens quite often and it's annoying to get so many errors in Apache logs.

Do you have any solution? Thank you

**Comment by Chacapamac** [comment]
When you say “quite often”, can you precise if it happen in the administration or the frontend and where the message appear — I just update to Joomla 4.2.2 on php 8.1.10 and cant reproduce the problem.
The only remark will be that wen I try to update Joomla it ask me to update the database structure of Joomla first:

**Comment by chupidos** [comment]
I think you misunderstood me, I haven't just upgraded Joomla, it's PHP 8 that I just upgraded from PHP 7.4., with this previous version of PHP there were no errors.

**Comment by sonvnn** [comment]
Hi @chupidos 

I fixed this issue in https://github.com/templaza/astroid-framework/pull/189/commits/821569bb037d69d87e1d6e5d380be3baf1cf7bbf

Please help me download developer branch and re-test again. Please tell me if this warning is still display.

Thanks & Best Regards,
Sonny

**Comment by chupidos** [comment]
Substituting with this code in article.php:

```
      if ($itemId) {
         $menu = $mainframe->getMenu();
         $item = $menu->getItem($itemId);
         if ($item->query['option'] == 'com_content' && ($item->query['view'] == 'category' || $item->query['view'] == 'article' || $item->query['view'] == 'featured')) {
         if (isset($item->query) && is_array($item->query) && $item->query['option'] == 'com_content' && ($item->query['view'] == 'category' || $item->query['view'] == 'article' || $item->query['view'] == 'featured')) {
            $this->params = $item->getParams();
         }
      }
```

Gives error 0 syntax error, unexpected token "public"

**Comment by sonvnn** [comment]
@chupidos You're welcome. Thank you for your cooperation :)
