### ISSUE TITLE
Background Size cover is not working in IOS

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#192]
Hello, maybe we can setup another css for IOS devices because the css parameter > fixed is not working only the css parameter scroll is working on IOS
https://stackoverflow.com/questions/24154666/background-size-cover-not-working-on-ios
```
.imageDiv {
    background: url('image.jpg') center center no-repeat fixed;
    background-size: cover;
}

@supports (-webkit-touch-callout: none) {
    .imageDiv {
        background: url('image.jpg') center top no-repeat scroll;
        background-size: auto 100vh;
    }
}
```
Greatings Peter

**Comment by sonvnn** [comment]
@Joomlaplates Did you process a test on your website? Please show me the result of testing. I will add this to framework after that.

Thanks & Best Regards,
Sonny

**Comment by Joomlaplates** [comment]
Hi Sonny, 
just realize that the image parameter fixed is doing this. But finally it happens with Firefox on Windows system too.
Therefore its not a problem anymore.
![fixed](https://user-images.githubusercontent.com/71080509/191783306-bdacd3b5-0df4-4f37-88be-e8c39620c5f2.jpg)
