### ISSUE TITLE
Problem activating insert

### ISSUE THREAD

**Issue by gmath2** [templaza/astroid-framework#200]
Good morning
The Login Form insert cannot be placed in Template Astroid zero. When the insert is published (at any position), it returns:
"Oops!! Page not found.
It seems like the page that you are looking for is no longer here."
In template one it works normally.
Please help...
Thanks
gmath

**Comment by Chacapamac** [comment]
I @gmath2 , I will try to help.

**• Is this the Login Form Module from Joomla ?**

**Can you give me a bit more infos on your setup?**
• Joomla version
• Astroid Version
• Template Name & version

Good Day!

**Comment by gmath2** [comment]
good morning
Chacapamac, Thanks a lot for the reply.
Unfortunately it happens in all versions after 2.5.4 that I've tried, only Template zero.

My settings are:
Joomla version: 4.4.2
Framework Version: 2.5.20
Template name: zero
Template Version: 2.5.19
Thank you very much
gmath2

**Comment by Chacapamac** [comment]
I just test on my Test website: —> http://joom4-astro.graf-test.ca/ without problem.....
— To be sure I create a new Login Form module and add it to a position in Template zero
![frontend](https://user-images.githubusercontent.com/1907276/192860923-d4124c30-d7e6-48df-9481-ab960967374b.jpg)

**My Settings:**
With the LAST version of Joomla **4.3.3** ( you say 4.4.2(
![Astroid](https://user-images.githubusercontent.com/1907276/192861006-8554a777-fa13-42b2-b443-3082754dfc55.jpg)

**• Be sure that the Login Form Module is the original Joomla one:**
![Joomla-login](https://user-images.githubusercontent.com/1907276/192861794-dc438dc5-9737-4259-80c1-7a6f34ff2825.jpg)

**• Be sure to choose a position belonging to Template Zero in the correct layout use on frontend**
![Module-choose-template](https://user-images.githubusercontent.com/1907276/192862069-17fcdfa8-f548-4c16-910e-11b4194edadc.jpg)

**Comment by gmath2** [comment]
Chacapamac, Thank you very much for your interest and help.
The problem was solved by upgrading the templates to version 2.6.0.
gmath

**Comment by Chacapamac** [comment]
Great, happy you solve your problem.

Good Day to Astroid fans!

**Comment by gmath2** [comment]
Chacapamac, Thank you very much for your interest and help.
Good Day to Astroid fans!
gmath
