### ISSUE TITLE
Disqus comments in multilang website show on one language.

### ISSUE THREAD

**Issue by Giorgi625** [templaza/astroid-framework#201]
So I have enabled Disqus comments on two language website, but on both languages disqus shows only on one language. can you fix it?
here is instruction https://help.disqus.com/en/articles/1717203-multi-lingual-websites

**Comment by Chacapamac** [comment]
**I look at your link, did you do these 2 steps in the instruction?**
• Did you set a default language for every discussion on your site, choose a language in your Disqus Admin > Setup > [Appearance]

![Screen Shot 2023-01-02 at 3 46 48 PM](https://user-images.githubusercontent.com/1907276/210276905-dd764ef9-5efa-4b35-96c7-d9f94593f4c8.jpg)

• Did You set the JavaScript in your second language Layout > Astroid Layout Manager > Custom code?
**LANGUAGE OVERRIDE**
Using the this.language JavaScript variable, you can dynamically load the Disqus embed in different languages on a per-page basis. For example, to load the embed in Russian:

<script> 
var disqus_config = function () { 
  this.language = "ru";
}; 
</script>
