### ISSUE TITLE
Back to top button does not show up

### ISSUE THREAD

**Issue by Giorgi625** [templaza/astroid-framework#202]
https://new.apuhaku.com/en/ this is page where is enabled back to top button here is url which shows template settings. https://i.postimg.cc/VvvrzpY7/Opera-Snapshot-2022-09-29-013534-new-apuhaku-com.png
so normally it should show arrow but it does not.

**Comment by Chacapamac** [comment]
I @Giorgi625 
This is weird, your a#astroid-backtotop stay “display: none” even if you scroll down and your settings seems correct. **My guess is that your page is slightly to short** to activate it as Astroid hide the button on first view and show it when you scroll down. 
You can also add something like —> _**a#astroid-backtotop: display: inherit**_ (or block) to your custom css/scss, but the button will always show

**Comment by Giorgi625** [comment]
https://new.apuhaku.com/en/privacy.html here is privacy article which is quite long but it still does not show up.

**Comment by Giorgi625** [comment]
I set inherit here:
`#astroid-backtotop {
    display: inherit;
    line-height: 0;
    position: fixed;
    right: 20px;
    bottom: 20px;
    padding: 10px;
    z-index: 1020;
}`
now I see button but it does not work. on click it does nothing

**Comment by Chacapamac** [comment]
Yes, you right, if you inspect your long page _(your browser web inspector)_ the a#astroid-backtotop doesn’t trigger the visibility even if you go down????

**I mark it as a bug** to get help!

I remark few errors on your website that are maybe related??
![Screen Shot 2022-09-29 at 10 08 27 AM](https://user-images.githubusercontent.com/1907276/193055993-467e5875-0511-4c84-ac54-02326d664337.jpg)

**Comment by Giorgi625** [comment]
Disqus is also related to astroid, because it is enabled in Article options of Astroid. 
I will try to disable 3rd party plugins to see if something has conflict but I do not think so.

**Comment by Giorgi625** [comment]
I think its more related to what I did on my site, not to astroid because on another website also on astroid back to top button works. I was not able to solve problem so I decided to instal clean joomla and one by one add all features which I have here. and see if anything goes wrong again.

**Comment by Chacapamac** [comment]
Cool, let Us Know!

**Comment by sonvnn** [comment]
Hi @Giorgi625

May you send me your admin acc via sonlv@templaza.com?  I will help you check it.

Thanks & Best Regards,
Sonny
