### ISSUE TITLE
Astroid 2.6.0 menu and icons are reloaded with each refresh - performance not good

### ISSUE THREAD

**Issue by WM-Loose** [templaza/astroid-framework#209]
Hi Sonny, after the update from 2.5.20 to 2.6.0, the menu and icons in the toolbar are reloaded with each refresh of the website and are displayed with a time delay. This is not good. We use the templates from joomlapltes with version 1.3.9.

![1](https://user-images.githubusercontent.com/99647423/194509866-ad3556f6-2f5a-48fa-84ca-81943c9ac112.png)

Back to 2.5.20 everthing is ok.

**Comment by sonvnn** [comment]
@WM-Loose in Astroid v2.6.0 will move css to media folder. May you create a test site and give it to me? I will check it.

Thanks & Best Regards,
Sonny

**Comment by WM-Loose** [comment]
Where should I send the login data to?

**Comment by WM-Loose** [comment]
So, I found out what it is.

It is due to the locally stored and used gfonts in the Fonts folder.

Test1:
Select the Arial system font in the template options for Menu Typo and specify "customer" for all others, i.e. local font from the Fonts folder.

Result:
The menu fonts are loaded immediately and there is no reload time. All other fonts are only displayed with a time delay.

Test2:
In the template options for Menu Typo, a font from Google (not local) was selected and for all others, a "customer", i.e. local font from the Fonts folder, was specified.

Result:
The menu fonts are loaded immediately and there is no reload time. All other fonts are only displayed with a time delay.

Means that the local fonts (only those from the Fonts folder) are loaded with a time delay.
You can test it yourself

with 2.5.20
![before](https://user-images.githubusercontent.com/99647423/194573222-75e4f15e-aa78-430f-a259-1d6efdb9ac0c.png)

with 2.6.0 and loading problem
![new](https://user-images.githubusercontent.com/99647423/194573357-c9d292f0-6046-4f61-9d32-01d228cc8b9b.png)

**Comment by sonvnn** [comment]
Thank you! I will check it and response to you soon

**Comment by sonvnn** [comment]
Hi @WM-Loose 
I fixed local font in https://github.com/templaza/astroid-framework/commit/2cd14d069b0173637c699c45f4e850cf076bc52f

Please help me check it! If everything is good. I will release fixed bug version.

Best Regards,
Sonny

**Comment by sonvnn** [comment]
@WM-Loose Please help me download developer branch to test https://github.com/templaza/astroid-framework/archive/refs/heads/developer.zip

**Comment by WM-Loose** [comment]
hello sonny, that looks very good and seems to work. Much better than before. if you also deactivate the preloader, the frontend is even faster. I would say the problem is solved. I do not recommend my customers to use the preloader, as it also slows down the page a bit during construction.

**Comment by WM-Loose** [comment]
where ist now the folder "fonts". I dont now but it works.

**Comment by WM-Loose** [comment]
OK, i found it under media/templates/site/tp_power/fonts/

**Comment by WM-Loose** [comment]
Sonny, simple fix for fonts folder.

Create a possibility in the template options to upload the fonts. So the user doesn't care where you save the fonts. only upload is required. The user selects the fonts locally and with upload they are uploaded and stored in the correct folder.

Like this:
![fonts](https://user-images.githubusercontent.com/99647423/194711869-ca76869d-b6b2-4535-981a-284aa9b029bb.png)

**Comment by sonvnn** [comment]
> Sonny, simple fix for fonts folder.
> 
> Create a possibility in the template options to upload the fonts. So the user doesn't care where you save the fonts. only upload is required. The user selects the fonts locally and with upload they are uploaded and stored in the correct folder.
> 
> Like this: ![fonts](https://user-images.githubusercontent.com/99647423/194711869-ca76869d-b6b2-4535-981a-284aa9b029bb.png)

Thank you! I will consider about this ideas in the next versions.

Best Regards,
Sonny
