### ISSUE TITLE
Fonts H1 will not change / override wenn select

### ISSUE THREAD

**Issue by deltapapa01** [templaza/astroid-framework#212]
Hello Sonny,
After the update to version 2.6.0 and 2.6.0 - Developer I have a problem with loading the font in the H1 headings.
First of all: I load the uikit.min.css file via the custom CSS files. If I now select a local font in the Astroid Settings -> H1 Typography, the font is still loaded by the UIKIT.
In the heading H4 it works without any problems, here the settings are taken from Astroid.
In further experiments I found that even without UIKIT setting a custom heading H1 is unsuccessful, it is always taken over from the superordinate font.
Here are the diff from h1 and h4 with uikit:
![Screenshot 2022-10-08 090119](https://user-images.githubusercontent.com/19833064/194694539-444bdadb-3bd0-4878-9d3a-5e8781c75c32.jpg)
![Screenshot 2022-10-08 090128](https://user-images.githubusercontent.com/19833064/194694557-43e33c48-c4a1-423d-b843-b84ad1e74493.jpg)

WBR,
deltapapa

**Comment by sonvnn** [comment]
Hi @deltapapa01 

May you send me you website url? I will help you check it.

Best Regards,
Sonny

**Comment by Joomlaplates** [comment]
Hello, if you are using the org uikit.css then you always have the headline settings from the uikit.css. And these headline setings are overriding your headline settings from Astroid.
Thats why we have our own uikit plugin without some css settings.

**Comment by sonvnn** [comment]
@deltapapa01 because you are using UI kit class like .uk-h1 or .uk-heading-small

So this class will received style from UI Kit style. It is true. If you don't want it, you have to edit uikit.min.css

It is not related to Astroid, so I will close this issue.

Best regards,
Sonny
