### ISSUE TITLE
Error: ".btn-backtohome" failed to @extend ".btn-primary".

### ISSUE THREAD

**Issue by yao89** [templaza/astroid-framework#220]
Hi,

Today I got an error on the main page of my website (awkward !) : https://www.le-jardin-des-secrets.be/fr/

Error code : 
Error: ".btn-backtohome" failed to @extend ".btn-primary". The selector ".btn-primary" was not found.: libraries/astroid/framework/library/astroid/./../../../../../templates/jd_yoga_hut/scss/yoga_hut/style.scss on line 2, at column 2: ".btn-backtohome" failed to @extend ".btn-primary". The selector ".btn-primary" was not found.: libraries/astroid/framework/library/astroid/./../../../../../templates/jd_yoga_hut/scss/yoga_hut/style.scss on line 2, at column 2

I have no idea where I can search...
I tried to restore a backup old of 1 month, but I got the same message, don't know why.

Thanks in advance

**Comment by yao89** [comment]
I managed to reproduce the bug.

Switching from Astroid Framework 2.5.20 to 2.6.x breaks my whole site.

I put a backup again to make my site work, but could you look at this bug ?
I can help you to make tests without worries.

Thanks in advance

**Comment by sonvnn** [comment]
Hi @yao89,

Please send me your admin account via sonlv@templaza.com. I will help you check it.

Thanks & Best Regards,
Sonny

**Comment by yao89** [comment]
Hi,

You should normally receive an email with informations for your account.


--
Adrien Labigne

**Comment by sonvnn** [comment]
Thanks! I got your email. I will check it when I back to office in the next 12 hours.

**Comment by yao89** [comment]
Hi,

Do you have any news for me ?

Thanks

--
Adrien Labigne

**Comment by sonvnn** [comment]
> Hi, Do you have any news for me ? Thanks
> […](#)
> -- Adrien Labigne Le 11 oct. 2022, 16:20 +0200, Sonny Le ***@***.***>, a écrit :
> Thanks! I got your email. I will check it when I back to office in the next 12 hours. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

Hi @yao89,

I tried to login to your site but can not access to your administrator. But your template is old template from Joomdev. It might not compatible with Astroid latest version. I suggest you don't update Astroid Version. 
Please contact to StackIdeas.com to update Joomdev Template first.

Thanks & Best Regards,
Sonny

**Comment by Chacapamac** [comment]
@yao89 , **nice website, great job!**
— **You probably fix the problem as I don't see any error related by “btn-primary”**

I find some explanation of that particular “@extend” error here if needed —> https://stackoverflow.com/questions/26523647/shows-error-failed-to-extend-when-a-class-is-extended-in-sass
