### ISSUE TITLE
Modal login

### ISSUE THREAD

**Issue by darekmer** [templaza/astroid-framework#224]
Astroid Framework + theme "One" + Jollyany Framework style does not work modal login.
![modal-login](https://user-images.githubusercontent.com/44267306/195979683-6ea6b54e-8a89-45fb-9732-6ef5047b7fc3.jpg)

**Comment by sonvnn** [comment]
Sure! I will not work. Jollyany Framework work with TemPlaza template only. One template is not template of TemPlaza. I will not work with Jollyany framework for sure.

Best regards,
Sonny
