### ISSUE TITLE
Framework 2.6.2 cleans custom.css

### ISSUE THREAD

**Issue by fontanil** [templaza/astroid-framework#225]
Hi,

Each time I clean the Astroid cache, the media/templates/site/astroid_template_one/css/custom.css is deleted. :(
I need to let it in the temlate/astroid_template_one/css folder.

**Comment by sonvnn** [comment]
Normally, Astroid will clear complied files only. It's very strange. I will test it and response on Monday. Have a nice weekend, bro.

Best regards,
Sonny

**Comment by Chacapamac** [comment]
Yes, I just test and **only if the file is name custom.css** (in the media folder)
I put few other css files in the media/templates/site/yourtemplate/css/ with name like aos.css, editor.css and they are not deleted?
I don't think it should delete custom.css????

**Comment by fontanil** [comment]
I renamed custom.css into user.css and it's not deleted.

**Comment by Chacapamac** [comment]
Yep, that work to as any .css file seem to work except custom.css

Good Day everybody!

**Comment by sonvnn** [comment]
@fontanil @Chacapamac Hello, I fixed this issue on https://github.com/templaza/astroid-framework/commit/76fedbf3cc7ce986a607e3945cc036ca3ca832d1

Please help me download developer branch and re-check it again.

Thanks & Best Regards,
Sonny

**Comment by fontanil** [comment]
Thanks Sonny!
I tried on a test site and it works. The custom.css file is not deleted when I clean the Astroid cache!

**Comment by Chacapamac** [comment]
@sonvnn  — Work!, custom.css is not deleted when clearing cache.
Good Day!
