### ISSUE TITLE
problem with module "login form" and php8 on astroid 

### ISSUE THREAD

**Issue by otn14** [templaza/astroid-framework#227]
Hi
I have a problem when I activate the "login form" module in joomla 4 with a PHP8 environment and the astroid template.
Access to my site even becomes impossible.
I have the message "Oops!! Page not found. _ It seems like the page that you are looking for is no longer here."
When I put the PHP 7.4 environment everything is back to normal.
With the cassoipea template and php8 I have no problem
Are there people in the same situation?
Daniel

**Comment by Joomlaplates** [comment]
Hello,
which Astroid and which Template version?
Please rename the folder html/mod_login to mod_login_bak and check if the issue is gone.
Regards Peter

**Comment by otn14** [comment]
Hi Peter
Thank you for the answer
This is the Astroid Framework Version: 2.5.4 and Template Version: 2.5.4
I solved my problem.
I had not uploaded the .htaccess file.
Now it's active and everything works
Regards Daniel

**Comment by sonvnn** [comment]
> Hi Peter Thank you for the answer This is the Astroid Framework Version: 2.5.4 and Template Version: 2.5.4 I solved my problem. I had not uploaded the .htaccess file. Now it's active and everything works Regards Daniel

Hello,
Astroid 2.5.4 will not work with Joomla 4.2 and PHP8.1. Please stay with your current version if you don't want to update Astroid.

Thanks & Best Regards,
Sonny
