### ISSUE TITLE
Article title not shown in Blog view

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#23]
Astroid 2.5.8
Joomla 4.0.4
-----------
Hi Sonny,
maybe its a bug or its related to the "one" Template html override, I dont know.
The Article title will not shown in blog category view when the article title is switched off in article details options.
The article title should be shown in blog category view, even the title is hidden in article detail view.

**Article category Blog Setup**
![blog](https://user-images.githubusercontent.com/71080509/141613447-cd26876f-bbea-4c32-9880-31b3f23a5b5a.jpg)

**Article details setup**
![article](https://user-images.githubusercontent.com/71080509/141613454-25f02c56-7751-46f0-9e6d-7f02fdaf68cf.jpg)

**Comment by sonvnn** [comment]
Hello @Joomlaplates 

It's not Astroid issue. It's Joomla core issue. You can check it at 
https://github.com/joomla/joomla-cms/blob/4.0-dev/layouts/joomla/content/blog_style_default_item_title.php#L23

Best Regards,
Sonny

**Comment by BlackBrix** [comment]
I have this issue in **Joomla 3**.10.2 / Template 1.3.4 / Astroid 2.5.4,
and only with the joomlaplates "business" Template,
switching to other templates or even the default joomla Template "Protostar" everything is displayed correctly

All this was discussed very detailed in the joomlaplates.de forum,
(https://www.joomlaplates.de/forum/joomla-3-templates/56-jp-business-beitrags-settings-werden-in-der-kategorie-ansicht-angewendet.html)
so I don't understand why this is treated here as if it was a joomla 4 error (?)
