### ISSUE TITLE
Head Script is not valide when local fonts is used

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#238]
Hi Sonny,
just noticed the Head Tag not valide when local fonts selected.
See pic attached
![errors](https://user-images.githubusercontent.com/71080509/199569303-7b14b27a-9bf9-41ea-89b0-044084baaeb7.jpg)
Regards Peter

**Comment by Chacapamac** [comment]
I will test

**Comment by Joomlaplates** [comment]
Hi, you can check it here
https://dev.joomlaplates.de/
https://validator.w3.org/nu/?doc=https%3A%2F%2Fdev.joomlaplates.de%2F&checkerrorpages=yes

**Comment by Chacapamac** [comment]
Do you think it can be cause by the comments tags in the code ????
Like `<!-- head scripts -->` ???

**Comment by sonvnn** [comment]
@Joomlaplates This issue happens when your site has issue with <astroid:include type="head-scripts" />
It was not replace completely. I don't think it related to Local Font. Please check your custom css, It might contain some invalid tag.

**Comment by Solero-Artaxerxes** [comment]
Hello, 
I have this problem too. even with a clean installation of astroid and template on without custom css. the error appears as soon as I switch to local fonts.
Regards Olli

**Comment by sonvnn** [comment]
@Solero-Artaxerxes @Joomlaplates May you send me your admin account? I will help you check it.

Best Regards,
Sonny

**Comment by sonvnn** [comment]
My email is sonlv@templaza.com.

**Comment by Chacapamac** [comment]
**I re-test on my test website** —> http://joom4-astro.graf-test.ca/
_Joomla 4.2.4
Astroid Framework 2.6.2
Astroid Package 2.6.1
Astroid Plugin 2.6.2
Template One and Zero 2.6.2 ( I try both templates)_

**No problem with local fonts**

Do you have any scheme of code/files compression on from Joomla/ Astroid or third party?

https://validator.w3.org/nu/?doc=http%3A%2F%2Fjoom4-astro.graf-test.ca%2F

**Comment by Solero-Artaxerxes** [comment]
Hello,
thanks for your help with this problem.

I have installed several times cleanly without extensions and without custom css.

Joomla 4.2.4
Astroid Framework 2.6.2
Astroid Plugin 2.6.2
Template 2.6.2 One and Zero (I also tested both)

I have no code / file compression enabled in Joomla / Astroid / Third Party.
No matter what I try, as soon as I activate custom fonts this error appears.

https://validator.w3.org/nu/?showsource=yes&showoutline=yes&doc=https%3A%2F%2Fdev.bellende-baeren.de%2F

Please excuse that my english is not so good.

Best Regards, Olli

**Comment by Solero-Artaxerxes** [comment]
Hello,

I just saw that this error also occurs when I set system fonts.

Best Regards, Olli

**Comment by Solero-Artaxerxes** [comment]
Hello,
Thank you very much.
Have you tested custom fonts in all sections (Body Typography, Menu Typography, Drop Down Menu Typography, H1,H2,H3,H4,H5,H6 and Custom Typography) at the same time?

I can assign custom fonts to 9 sections step by step without errors. The error only occurs when I assign a custom font to the 10th section, i.e. when all sections have activated custom fonts. The same also happens when I activate system fonts in all sections.

I only use Open Sans Regular as a custom font in all sections.

This is very difficult for me to explain because my English is not so good. Excuse me.

Would you be so kind as to test activating custom fonts in all sections.

Best Regard, Olli

**Comment by sonvnn** [comment]
@Joomlaplates @Solero-Artaxerxes Thank you for your report bug. I found it because headScript function return null then system did not remove Astroid:include tag. I fixed it on https://github.com/templaza/astroid-framework/commit/7b1e74ee0b40b7624737893b8ce9b5ea3a2c6421

I helped @Joomlaplates update his site. You can check here https://dev.joomlaplates.de/

Thanks & Best Regards,
Sonny

**Comment by Solero-Artaxerxes** [comment]
Hello, I changed line 46 of the includer.php and it works fine on my development server now.
But it doesn't work when I work locally under Xampp (php 8.0.23 and php 8.1.10). Here I get the following error messages when starting the Astroid Framework.

Deprecated: str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in E:\xampp_8.1.10\htdocs\neu\libraries\astroid\framework\library\astroid\Component\Includer.php online 46

Warning: Cannot modify header information - headers already sent by (output started at E:\xampp_8.1.10\htdocs\neu\libraries\astroid\framework\library\astroid\Component\Includer.php:46) in E:\xampp_8. 1.10\htdocs\new\libraries\astroid\framework\library\astroid\Helper\Client.php on line 87

Best Regards, Olli

**Comment by sonvnn** [comment]
Hi @Solero-Artaxerxes 

Thank you for your feedback. I fixed this issue in https://github.com/templaza/astroid-framework/commit/d4dbfb07a4ce5dd72a09d02eb60c8b37206a9b10

Please help me download developer branch and test it on your local again. Please let me know if this issue happens again.

Best Regards,
Sonny

**Comment by Solero-Artaxerxes** [comment]
Hello Sonny,
thank you very much for your work and help.
I tested three different versions. For all tests I installed new and clean Joomla 4.2.4, Astorid Framework 2.6.2 with changed includer.php and the Astroid Template One.

The first test on my development server with php 8.1.12. I haven't encountered any problems and everything seems to be working fine.

The second test on a local development environment with Xampp and PHP 8.1.10. There was no longer an error message when starting the Astroid Framework. But when I create the fonts folder under /media/templates/site/my-template/ and upload my fonts, the Astroid Framework no longer starts. I only see the astroid (rock) but it won't load anymore. The Astroid Framework loads with an empty Fonts folder.

The third test on a local development environment with WampServer and PHP 8.1.12. There was no longer an error message when starting the Astroid Framework. But there is the same problem as soon as I create fonts folder under /media/templates/site/my-template/ and upload my fonts. The Astroid Framework no longer starts. I only see the astroid (rock) but it won't load anymore. The Astroid Framework loads with an empty Fonts folder.

For all tests I used OpenSans-Regular.ttf and RopaSans-Regular.ttf as local fonts.

Best regards,
Olli

**Comment by Solero-Artaxerxes** [comment]
Hello Sonny,

I tested something else.
If I replace openSans.ttf fonts with openSans.woff and openSans.woff2 fonts on my local development environments (Xampp and WampServer), then everything works fine on my local development environments too.
However, when I use .ttf fonts on my local development environment, the Astroid Framework does not load and I only see the Astroid (stone).

Best regards,
Olli

**Comment by Joomlaplates** [comment]
Hello,
its a known problem that local server on windows or Mac ( xampp ect pp) have problems with font files.
It depends finally on the php version which is not optimized like PHP on a Unix derivat. ( Ubuntu ect)
Greatings, Peter

**Comment by Chacapamac** [comment]
Good Infos here.
I use Mamp on Mac and never have a problem with fonts (using Woff & Woff 2 only) (I always download Google fonts to be sure)
