### ISSUE TITLE
Astroid creates a lot of tmp files in the root temp folder with local fonts

### ISSUE THREAD

**Issue by deltapapa01** [templaza/astroid-framework#239]
Hello, I made a very disturbing discovery: After I switched a Joomla 4 site to the Astroid template, I was wondering about the high disk space usage on my server interface. Within a few days there were over 10 GB with over 190,000 files in the tmp folder at root level (not the tmp folder in Joomla). The whole files look like this:
![image](https://user-images.githubusercontent.com/19833064/199961151-032088d8-aae4-4bbf-8c09-0e6c709a1a1e.png)
So I checked where all the files came from. After I found out together with the hoster that these files are generated every time the website is called up, I started troubleshooting. Cache, htaccess, JCH, page cache, http header, I really tried everything. Then I noticed that I have a Joomla 4 site that doesn't have the problem. On this site I still have installed the helix. And that was the decisive hint this morning, as soon as I deactivate Astroid on the problem pages, all these files are no longer created when the page is called up.
Now I've tried to narrow down the error further to see what exactly is creating the files. So I put back what I changed at the very end of my site, namely the google local fonts. I have set the standard fonts here. Lo and behold, this behavior suddenly stopped on all my pages that previously generated masses of tmp files.
So it is definitely due to the integration of the google fonts as local fonts. I've looked, on average, 4000 to 6000 files are created per day on my pages. On each side!
The hoster thinks that there is a problem with the session in php or joomla, and that php cannot process something properly.
As long as the problem is not solved, I can no longer use the google fontas as local fonts.
I hope there is a quick solution to the problem, now I have to clean up countless files on my server almost every day :-)

Many thanks and greetings from Germany,
delta papa

**Comment by Chacapamac** [comment]
I try to reproduce the problem on my test website —> http://joom4-astro.graf-test.ca/
Joomla 4.2.4
Astroid Framework / Template Zero 2.6.2
PHP 8.1.11 

I put 2 Google fonts ON 
Clear All Caches
Reload Pages many times

**Nothing appear in the “tmp” folder**

**• Can we access your website online**

**• You have more info on the setup**
- Joomla & php version
- http or https
- What Astroid template & version

**To Check**
— If php cannot process something properly you maybe have these errors in your server errors logs?

**To try or until its fix**
You can use the Google fonts that you choose for your website locally until you find the problem, as a bonus your website can be a bit faster

**Comment by deltapapa01** [comment]
Hello,
Thank you for your answer, the problem was found:
When calling the woff files from local fonts, these tmp files were written in bulk on the server.
I have now removed these woff files from the server (I had integrated the google fonts locally on the server, under images/astroid_template_zero/fonts) and now everything is fine again.
woff2 and ttf can be integrated with me without any problems.

Thank you and best regards
delta papa

**Comment by Chacapamac** [comment]
@deltapapa01 
I don’t think Astroid or even Joomla intent to have custom fonts files in the “images” folder

On my test website above my custom fonts are where they supposed to be, at least for Astroid:
in —> **Joomlaroot > media > templates > sites > astroid_your_template > fonts** folder

![Screen Shot 2022-11-04 at 2 51 23 PM](https://user-images.githubusercontent.com/1907276/200053984-96dfb440-e585-4bdd-9974-53ad58c1dc33.jpg)

Work perfectly in the **Astroid Typograpy manager** and no funny “tmp” files added when site is view/reload in frontend

I will test woff2 as they are even more optimized than woff

**Comment by deltapapa01** [comment]
Sure, from version 2.6.1 this is possible without any problems:
https://github.com/templaza/astroid-framework/releases/tag/v2.6.1
I have read in other forums that certain server constellations have problems with woff files, sometimes also with woff2 files. So this seems to be a server/PHP problem, there is also e.g. in Wordpress installations. The solution is always not to use these font files.
