### ISSUE TITLE
Bootstrap 5 error in custom module

### ISSUE THREAD

**Issue by darekmer** [templaza/astroid-framework#24]
Dropdown button error
```
Uncaught TypeError: i.createPopper is not a function
    _createPopper dropdown.js:258
    show dropdown.js:147
    toggle dropdown.js:124
    <anonymous> dropdown.js:487
    s event-handler.js:119
    M event-handler.js:207
    on event-handler.js:241
    <anonymous> dropdown.js:485
    <anonymous> bootstrap.min.js:6
    <anonymous> bootstrap.min.js:6
```

**Comment by Joomlaplates** [comment]
Hello, where you get the error?
In frontend editing or in frontend basic view or backend?
Friendly regards, Peter

**Comment by darekmer** [comment]
Default code [click](https://getbootstrap.com/docs/5.1/components/dropdowns/)
![dropdown](https://user-images.githubusercontent.com/44267306/141644881-629a5e04-5002-4f0a-9c60-121dd4c48d3f.png)
.  Not working. After click error.

**Comment by Joomlaplates** [comment]
Hi again, 
the BS5 bundle script is not installed. Astroid load only the bootstrap.min.js.

You can load the script file manually, just put this code into your **template/index.php** file. ( see pic attached)
  ` <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>`
![bs-bundle](https://user-images.githubusercontent.com/71080509/141649730-8b93d6d0-8708-4e25-b415-a54b99871e98.jpg)

**Comment by sonvnn** [comment]
OK, I agree. I add Bootstrap Bundle at https://github.com/templaza/astroid-framework/commit/cb6cda66d368d7d33c13467f4f9e22f1ac77edfc

I will soon release in version 2.5.9.

**Comment by darekmer** [comment]
Thanks
