### ISSUE TITLE
Again problems with Notification message close button

### ISSUE THREAD

**Issue by Giorgi625** [templaza/astroid-framework#240]
I have installed on a clean joomla latest 2.6.2 framework and template and imported settings from old  Joomla 3 website. when I get system notification it has same problem which was fixed in 2.5.19 version. X button does not close notification .

**Comment by sonvnn** [comment]
@Giorgi625 Sorry! I forgot update One & Zero with new layout. Please help me download Zero and One here and upload to your site https://astroidframe.work/download

Best Regards,
Sonny

**Comment by Chacapamac** [comment]
@sonvnn 
I Sonny, I just install over already **Template/Framework 2.6.2** with your link and I have the same problem with the system notification window.

You can try the login on my test website (**template Zero**).
http://joom4-astro.graf-test.ca/

_**Note:** don't worry about the warning, I put that on another issue (Minify JS bug)
— Also the problem with the notification window happen with or without (Minify JS)_

**Comment by sonvnn** [comment]
@Chacapamac Please help me re-install with this link https://github.com/templaza/astroid-framework/archive/refs/heads/zero-template.zip

Best Regards,
Sonny

**Comment by Chacapamac** [comment]
@sonvnn — I Just verified your last link and **Notification work perfectly**
http://joom4-astro.graf-test.ca

**Comment by sonvnn** [comment]
Thank you! I closed this issue as resolved
