### ISSUE TITLE
Since new presets no more URL to switch between styles

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#244]
Hello Sonny,,
since new presets there is no more URL to switch between styles like this
`http://xxx.com/?preset=orange-636d34f82e03c`
Thanks Peter

**Comment by sonvnn** [comment]
Hi @Joomlaplates 

Thanks for report issue. I will check and update asap

Best Regards,
Sonny

**Comment by sonvnn** [comment]
Hi @Joomlaplates 

I fixed this issue in https://github.com/templaza/astroid-framework/commit/882b70735d55f8d47b0c7e2f89fc032a01f5a802
Please help me download developer and reinstall on your wesbite.

Best Regards,
Sonny
