### ISSUE TITLE
Template ONE > script.php

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#25]
Hi Sonny,
as I see you add a script file to the template to remove the files:
```
..\scss\one\_frontend-edit.scss
..\scss\one\_variables.scss
```
But in the script you delete the file:

`scss\one\variable_overrides.scss`

![edit](https://user-images.githubusercontent.com/71080509/141647905-d4695d1b-ece4-441e-945c-3f9b16cf0b0f.jpg)

I think you try to delete the wrong file.
Its better to delete just the file **.\scss\style.scss** which is not needed anymore

**Comment by sonvnn** [comment]
Hi @Joomlaplates 

When you delete .\scss\style.scss you will lose all style from template scss folder. Astroid will load scss from Astroid core only.  So I think it's not good for others. 

Let's check this code for more information https://github.com/templaza/astroid-framework/blob/master/framework/library/astroid/Document.php#L907

In SCSS when use
`@import "frontend-edit";`
It will call both of frontend-edit.scss and _frontend-edit.scss
and SCSS will understand that is duplicated files and raise error. So I deleted one that will solve problem.
Please refer this document for more information https://www.geeksforgeeks.org/why-to-put-_-in-front-of-filename-in-scss/

Best Regards,
Sonny

**Comment by Joomlaplates** [comment]
Hi Sonny, yes youre right.
I´ve learned something again.
