### ISSUE TITLE
Joomla Mediamanager frontend - building new folder

### ISSUE THREAD

**Issue by WM-Loose** [templaza/astroid-framework#250]
Hi Sonny,
Joomla 4.2.5 and PHP 8.1 

It occurs that in the Images and Links section, if you create a new folder the popup freezes and does not go ahead, even if the folder is created. To view it, close the popup, go back and reopen the Images and Links tab.

These are the errors reported in the console:
Uncaught TypeError: Joomla.renderMessages is not a function
at Notifications.notify (media-manager.min.js?41349ab7c112a7dc4604ebd5568a311d0c57880f:1:80540)
at Notifications.success (media-manager.min.js?41349ab7c112a7dc4604ebd5568a311d0c57880f:1:80346)
at onSuccess (media-manager.min.js?41349ab7c112a7dc4604ebd5568a311d0c57880f:1:103942)
at n.onreadystatechange (core.min.js?bea7b244e267b04087cedcf531f6fe827a8e101f:1:6213)

Video Recording Screen:
https://youtu.be/n5GFW_rrQxc

We test with the templates from joomlaplates and astroid framework 2.6.2
With cassiopeia is everthing ok.

Kind regards,
Dirk
JP-Admin
Joomla-Master forum.joomla.de/

**Comment by sonvnn** [comment]
Thank you for report issue. I will check it and response you asap.

Best Regards,
Sonny

**Comment by WM-Loose** [comment]
great thanks for your support

**Comment by Chacapamac** [comment]
Just try Joomla 4.2.5 — PHP 8.1.12 — Astroid 2.6.2
In the template Zero manager I was able to create new folders with the successful message
![success](https://user-images.githubusercontent.com/1907276/204012223-c5a51cdd-a292-41ec-9622-fa0db20c5f59.jpg)
— After the folder creation, the system open the empty newly created folder, ready for uploading images
— I test uploading pictures without problems.
**I did have one error/freeze at one point?**
![error](https://user-images.githubusercontent.com/1907276/204012700-034a9cab-5fa2-4189-830e-72db28c28953.jpg)

**I also see a warning when opening the generic template manager:**
![warning1](https://user-images.githubusercontent.com/1907276/204013508-99e176dd-091b-41c1-945d-5f04544c6b03.jpg)

**and another warning when opening the popup setting window**
![warning2](https://user-images.githubusercontent.com/1907276/204013748-fe67c76b-eae7-4881-97f8-2555825eb466.jpg)

**Comment by WM-Loose** [comment]
Hi Chacapacman,
it is strange. Sometimes the directory is created in the background and other times it is not. Even if a directory is created, this is not visible to the user because the window no longer disappears. The same error can also be detected in helix ultimate. So far we haven't been able to find out more. With cassiopeia is everthing ok.

**Comment by Chacapamac** [comment]
@WM-Loose 
**When you say** 
> because the window no longer disappears
• Do You mean the popup settings window in the **Astroid template Manager**?
![Screen Shot 2022-11-25 at 6 40 35 PM](https://user-images.githubusercontent.com/1907276/204063523-bb1ebdda-da66-4f0c-b357-c7cf79021730.jpg)

• do you use an html compliant name for the folder?
• do you see any errors in the browser console?

**Comment by WM-Loose** [comment]
No, if you go to Images and links in a post and then want to insert an image. Not directly in the media manager but in the post. Only if you are using the frontend not backend.

![1](https://user-images.githubusercontent.com/99647423/204089052-398218fa-40b1-47c6-b1cc-0b072b8b957d.png)

Backend ok:
![2](https://user-images.githubusercontent.com/99647423/204089064-611d8a49-68af-4acd-b985-95de5aa6b8e1.png)

Frontend not:
![3](https://user-images.githubusercontent.com/99647423/204089075-d2a54656-f046-4021-b862-7cadd41b4f46.png)

**Comment by Chacapamac** [comment]
_I’m getting there..._

I’m logged as Super Admin
In the frontend of the website, when editing an article, I do not have access to the “**Images & Links**” available in the backend.
**Do you know how to turn it on, I was thinking to get it as an Super Admin?**

![Screen Shot 2022-11-26 at 11 22 18 AM](https://user-images.githubusercontent.com/1907276/204098583-edf5a881-8066-47c4-a001-729d6a718c47.jpg)

**Comment by WM-Loose** [comment]
youu must turn it on at backend articles working-layout an than activate Images & Links in the frontend to yes.

**Comment by Chacapamac** [comment]
Thanks @WM-Loose 

Yep something is not working properly.
The problem is not constant.

**When I went first to the frontend edit window I get these errors in the console.**
![1](https://user-images.githubusercontent.com/1907276/204110514-70f94de6-fe5d-4caf-aaef-63b3abb7f509.jpg)

When I try to choose an image in the “Images & Links” tab I get this wen I click “Select” and nothing happen.
![2](https://user-images.githubusercontent.com/1907276/204110594-078595ed-7811-4cbc-9a0d-8f91f0525c97.jpg)

Fooling around it finish by work at one point, but the problem come back sometimes
— Going to another page and coming back
— Close/save article and come back
— Logout / Login
— I think it come back 100% of the time if you clear the browser cache and Astroid/Joomla

I mark it as a bug.

**Comment by Chacapamac** [comment]
Just take a look with ALL Updates. same errors?
**PHP:** 8.1.13
**Astroid:** 2.6.3 
**Astroid Template One:** 2.6.3

**When opening a frontend article edition window** (100% reproducible)
![when-opening-image-link](https://user-images.githubusercontent.com/1907276/210176205-27ee6c93-eda0-49e4-a8d3-7dcbbc8cfabf.jpg)

After **No problem creating a folder or uploading an Image** when clicking the “**Select**” button in the **File Manager lightbox window**
But 
• **JSON error** when trying the direct “**Upload from Computer**” button
• Also the “X” cut button do absolutely nothing even if an image is present in the field
![frontend-image-link](https://user-images.githubusercontent.com/1907276/210176764-25e80948-475a-4ecb-aa1b-8599ab9f4cd4.jpg)

and when trying to **“Insert”** a selected image in the **File Manager lightbox window**
• You get this error each time you click “Insert” 100% of the time
![insert](https://user-images.githubusercontent.com/1907276/210176906-3f2e8001-e12d-4708-b903-bc735fad2790.jpg)

**Error:**
![buz](https://user-images.githubusercontent.com/1907276/210176916-6a124ab1-75a2-4824-a6f7-a745be3a45eb.jpg)

**Comment by Chacapamac** [comment]
**I Just check and Same errors ?????**

@WM-Loose You said:

> The same error can also be detected in helix ultimate but not Cassiopea

I just check and no problem or error with Cassiopea?.
@sonvnn  , so far, I cannot find the probem....

**Comment by WM-Loose** [comment]
It?s now working with Astroid 2.6.5 and J4.3.2.
I close the Thread!
