### ISSUE TITLE
Astroid 2.6.3 and Template One 2.6.3: styles are not correctly recognised

### ISSUE THREAD

**Issue by fontanil** [templaza/astroid-framework#262]
Hi,

For several monthes I'm using two styles (not child template) of Astroid One. One style as default with blue background color, no image, the other for the home only with a background picture and a transparent background color for ".astroid-layout.astroid-layout-boxed .astroid-wrapper".

Using Astroid 2.6.2 (and One 2.6.3), all work well: changing the page use the right style, picture on the home page, background color for the other pages.
If I update Astroid Framework to 2.6.3, the styles are not the right ones, all page are sometimes using the home style, sometimes the default one. If I reinstall the Framework 2.6.2, everithing is working welle again.

Is it a bug in Astroid 2.6.3, or how could I do?

Regards,
Robert

**Comment by Chacapamac** [comment]
**Maybe a problem of cache????**
— Be sure that you manually take out any compiled css in the **JoomlaRoot/templates/astroid_template_one/css** folder e.g.“compiled-a0219c0b4fffa504bb047dcdfe7aeaea.css” 
Because, when you update the template to 2.6.0+ all the compiled css are now compiled in the JoomlaRoot/media/templates/site/astroid_template_one/css folder

— Empty your Astroid and Joomla cache
— Empty your Browser cache and try again

I’m using Zero and I update few websites with multiple layout without problems.

Also, maybe recheck your Astroid Template Manager Layout Style Menu Assignment, if everything is correct in there?

**Comment by fontanil** [comment]
Sorry, no cache problem.
I have two styles, one as default, one for the home page. Each have it's own custom.css ("custom.css" as default, "custom**a**.css" for the home)
With Astroid 2.6.2, the two styles are well used.
I update to 2.6.3 and the style for the home page is used on the other pages if I clear the caches and opent the home first.
I open a page (not the home) and clear the caches (Astroid and Joomla!): the style is the good one. Then I open the home page and the style is not the one for this page.
The first custom file is not replaced by the other in the version 2.6.3

These files were placed for a while in templates/astroid_template_one/css folder. I emptied all caches and I moved the files in /media/templates/site/astroid_template_one/css, templates/astroid_template_one/css is totally empty, but no changes!

**Comment by Chacapamac** [comment]
I think that maybe the **customa.css** is not loading when place in the **media** folder

**A question, how do you assign a specific custom CSS file to both “Default” and “Home” style?**
I guess you using the Layout Style —> Template manager —> Custom CSS Files  

— Check by your browser inspector {normally the “Network” function) if **customa.css** is loaded
— What happen if you move back both custom CSS to the normal template folder
— However you are loading the specific CSS file for “Default” and “Home”, try to inverse the name of the custom CSS file to see  what happen
**customa.css** for the “**Default**” style
**custom.css** for the “**Home**” style
My guess will be that your **Home** will now work correctly, but not your **Default** pages

**Comment by Giorgi625** [comment]
I had simillar problem, Home style worked fine, but default could not load my settings and in my situation it was caused by Advanced Template Manager by regular labs. As its developer told me it is not compatible with some 3rd party template frameworks like Astroid. When I disabled that plugin template worked fine.

**Comment by fontanil** [comment]
I don't use this extension.
I remind you that I have no problem with Astroid Template One 2.6.3 and Astroid Framework 2.6.2
On a local site I tried many combinations without result. I tried to create a child template to separate the files, the problem remains the same.
It's the only website where I'm using two styles from the same Astroid template.

**Comment by sonvnn** [comment]
Hello @fontanil @Giorgi625 

May you send me your admin account and detail issue via sonlv@templaza.com? I will help you check it.

Best Regards,
Sonny

**Comment by fontanil** [comment]
Thanks Sonny but I can't send you these data because it's a production client's site and the test site is on my own local server.

**Comment by Giorgi625** [comment]
@sonvnn Sent details to your email. you can enable minify css in Home template style, to see problem.

**Comment by fontanil** [comment]
Hi,

I just tried a new test. 2 styles of Astroid One Template, one as default, one for the home page. No custom CSS files, only some custom css code in the template style of the home page.

> .astroid-framework {
    background-image:url(/images/my_picture.jpg);
}
.astroid-layout.astroid-layout-boxed .astroid-wrapper {
    background-color:transparent;
    box-shadow: none;
}
All caches were cleared, but no change, the custom css code is used on all the pages if I open first the home page, the "no custom css style" is used on all the pages if I open another page first.

**Comment by Chacapamac** [comment]
Hello @fontanil 
I just try again and it work I can insert custom code in one layout that doesn't affect the others layouts
Look at the beige background on the Header & Right Column, only in the “Home” page Layout here —> http://joom4-astro.graf-test.ca/

**You still have the same problem?**

**Comment by fontanil** [comment]
Hello,

I didn't update Astroid to 2.6.3 because I didn't find why I have the error. Perhaps will I need to uninstall Template One et recreate new styles... but the template had been extensively customised.

**Comment by Chacapamac** [comment]
You should try to upload a test, like that we can have a go at it.

Yeah I will try to create new layout and export-import the original layout to see if the problems follow in the new layout.

**Comment by fontanil** [comment]
On a local copy of the site using Astroid Framework 2.6.2, I made a backup of the two styles and user.css file. 
I uninstalled Astroid Template One, reinstalled it, imported the json file of the main style. I then duplicated this style and changed the custom css for the home page. All worked fine.
I updated the Framework to 2.6.3 and I have the same error. I really don't understand.

**Comment by sonvnn** [comment]
Hi @fontanil,

To find your issue, I need your admin account to debug. May you help me create a test site? I will check and find solution for it.

Thanks & Best Regards,
Sonny

**Comment by fontanil** [comment]
Thanks Sonny, but the site is not mine, it's heavy and I can only test it on my local server.

**Comment by fontanil** [comment]
I made a lot of tests: duplicating the template, created a child. No success, the styles are always the one of the first page I opened.

Si I tried to use Astroid template zero for the home page, imported the layout of the One for home, added the custom css code and deleted the custom.css file.
The layout works fine for home, but also for other pages: the background image is displayed and the backgroud of the center of the site remains transparent.
The home page (template zero) is using this custom.css code (no custom.css file)

> .astroid-framework {
    background-image:url(/images/FONDKENNEDY.jpg)!important;
}
.astroid-layout.astroid-layout-boxed .astroid-wrapper {
    background-color:transparent!important;
    box-shadow: none;
}
The template one (by default) is using a custom.css file with this code and other css rules:

> .astroid-framework {
    background-image:none!important;
}
Why the image of the template zero style is used with the template one style?

I remind you that the error does not occur with the Astroid Framework 2.6.2, only with 2.6.3 (and the 2.6.3 templates)
Did the Astroid cache change in 2.6.3?

**Comment by fontanil** [comment]
Last try: I removed the background image in the custom css for template zero and add it in the layout settings --> background image
No change although it's not the same template style.

**Comment by Chacapamac** [comment]
**I check again on my test site and it work without problem** —> http://joom4-astro.graf-test.ca/

**This time I did exactly what you try to achieve.**
**• Using two styles (not child template) of Astroid One.** 
— One style as default with a color background color, no image
— the other for the home only with a background picture

**Note:** 
• It work with the “Boxed” and the “Wide” Layout
• I use this custom css in the Astroid Manager 
— “Home” style —> _.astroid-framework { background-image:url(/images/Desert.jpg);}_ 
— For the “Default” style for all other pages —> _.astroid-framework { background-color: beige;}_

**For me, at this point it become extremely difficult to help you as I didn’t see any problem doing what you try to do with:**
• **Joomla**  ‎4.2.7 
• **PHP** 8.1.15
• **Astroid Framework / Template One** 2.6.3

**Without an access to a copy of your website or your website it become really hard to fix your particular problem.**

**One thing**, If something is wrong on your website its a big chance that you should have some errors generated, did you look for errors in your browser inspector or in the errors logs of the server?

**Second:**
If you send me a email to p.toulze@grafcomm.ca, I can give you access to my test website, if it can help You.

**Comment by fontanil** [comment]
Thanks Chacapamac,

I created a new site, installed Astroid 2.6.2 and the two templates, duplicated One and imported the layout for the three styles.
With Astroid 2.6.2, no problem. Then I updated to 2.6.3 and all works fine.

But on the production site and on its local copy, it works with the 2.6.2 version, not with the 2.63, and no info in the console of Firefox.
So I'm wondering how I'm going to be able to do this on the production site, as I don't have an explanation of what caused the problem.

**Comment by Chacapamac** [comment]
As I was saying, without an access to the production website or a copy, at this point we cant really find the problem.

If you give me a zip copy of your website and the database, I can test it locally. Even better, You can use the free version of Akeeba Backup and send me the restoration file. I can have a look.

https://www.akeeba.com/download.html

**Comment by Chacapamac** [comment]
I @fontanil 
Something to clarified... 

**You said**

> • The problem is simple: the specific layout is used, one for home page and one for the other pages,

**Yes, I understand, this is what I used in my test website**  —> http://joom4-astro.graf-test.ca/
You can see my 2 layout in my previous post —> https://github.com/templaza/astroid-framework/issues/262#issuecomment-1369093815

**You said:**

> not the custom CSS code. I need to clear the Astroid cache to change the custom css (in the media folder)

What do you mean by that, are you CSS to control the background are in the **Astroid Template manager** _(one different code for each layout)_ or in the **custom.css**?

**Comment by fontanil** [comment]
Hi,

There are two styles, each with its own layout and common CSS (in the layout or in a custom file) plus the transparent background and the image for the home page only.  
With Astroid 2.6.2, I can change the page from home to another or another to home and I have no problem.
With Astroid 2.6.3, the CSS of the first opened page is used for the others: after clearing the cache if I open the home, the image and the transparent background is used on the other pages; if I open another page, when I open the home page, the background has no image and the background of the site is not transparent. I need to clear the cache (or wait Cache cleaner automatic clearing) to get the right CSS for the actual page.

I sent you an email (in french) from another email address (on orange.fr).

**Comment by fontanil** [comment]
You will receive an email with credentials from a "formations64.com" address.

**Comment by Chacapamac** [comment]
@fontanil , I think I fix the problem.
**You were right, something is fishy** with the **Layout Settings** —> **Background Image**

![Screen Shot 2023-02-15 at 1 54 28 PM](https://user-images.githubusercontent.com/1907276/219126708-b7c7dd12-167c-4bef-9279-9dc5f39deab6.jpg)

**Setting the image here, seem to traverse to others layouts, sometimes, most of the times ???????**

I clear the image in the **Layout Settings** —> **Background Image**
and add this code to the **Home Page Layout** “Custom Code”
```
.astroid-framework.tp-style-25 {
    background-image:url(/images/FONDKENNEDY.jpg);
}
```
Seem to work 100% of the times....

I think @sonvnn  should look at this to find exactly the cause
You should send him some admin keys to take a deep look now that you have a test website online. If it was working in 2.6.2 it should work in 2.6.3.
I’m going to check if it happen on my test website and come back here....

**Comment by Chacapamac** [comment]
@fontanil , @sonvnn 
**It work perfectly on my 2.6.3 test Website?????**

**Comment by fontanil** [comment]
Thanks Chacapamac!
I needed to add ".tp-style-25" to the transparent background, so it's white on the other style.
The solution works well on the production site.

**Comment by Chacapamac** [comment]
Great @fontanil, well, at least it work, its definitively a bug, I will check later on your test website
**Don’t forget to send some admin keys** to @sonvnn , He is busy, but he will probably find why the background image set in a layout style appear on page with a different layout style.

**Maybe it’s only a problem of cache**, I’m not sure as my test website —> http://joom4-astro.graf-test.ca/
Work perfectly with or without cache?????

**Good Day!**

**Comment by fontanil** [comment]
Thanks @Chacapamac !

On the test site, no cache, only Astroid cache was used. On the production site, Litespeed is used with its cache plugin.
On both sites, the background image was set on the custom code, without ".tp-style-25" when the error  occured with Astroid 2.6.3, and I changed to the layout style with no change.
On the new site (only blog samples) I created where I added the same template and its options and CSS from the production site, it worked as on your test site.

**Comment by fontanil** [comment]
Thanks Sonny !

 

It works ! I tried with only custom code and only layout image (mignify CSS “on”).

 

Best regards,

Robert  

 

De : Sonny Le ***@***.***> 
Envoyé : lundi 20 février 2023 09:37
À : templaza/astroid-framework ***@***.***>
Cc : fontanil ***@***.***>; Mention ***@***.***>
Objet : Re: [templaza/astroid-framework] Astroid 2.6.3 and Template One 2.6.3: styles are not correctly recognised (Issue #262)

 

Hi @fontanil <https://github.com/fontanil> 

Thank you for your support. I check your site and found the issue. It's a bug when system minify CSS. It generate a version for 2 styles. I fixed this issue on  <https://github.com/templaza/astroid-framework/commit/9c5fc04917ba8ec1f1db2aa29887737e75fc0537> 9c5fc04

Please help me download developer branch and test on your site https://github.com/templaza/astroid-framework/archive/refs/heads/developer.zip

Thanks & Best Regards,
Sonny

**Comment by Chacapamac** [comment]
Make total sens for the Minify....
**@fontanil  — Just tell Us if we can mark the Issue as Solved?**

**Good Day to All!**

**Comment by fontanil** [comment]
Hi,

As I said, it works.
The issue can be closed.
Thanks!

**Comment by Chacapamac** [comment]
Great Day to Everybody!
