### ISSUE TITLE
Astroid/template Zero 2.6.3, ALL moduletable get strange code addition, some cause problems!

### ISSUE THREAD

**Issue by Chacapamac** [templaza/astroid-framework#271]
**Happy New Year for the Astroid Community!**

**Astroid/template Zero 2.6.3, ALL moduletable get strange code addition**
**Same for 2 different websites updated to 2.6.3**

**A live website** — Template Zero
• https://efoilsurf.ca/en/

**and my “Test Website”** — Template One
• http://new-astroid.graf-test.ca/

Both Joomla 3

—————————————————————————————
**You can see the 2.6.0 Copy  of my “Test Website” without the problem here** — Template One
• http://www.graf-test.ca/

**Example:
2.6.0**
![Screen Shot 2022-12-31 at 3 39 34 PM](https://user-images.githubusercontent.com/1907276/210155258-0c27f398-5d8d-4fa6-8862-19e8ce67c0b8.jpg)

**2.6.3
become**
![Screen Shot 2022-12-31 at 3 40 20 PM](https://user-images.githubusercontent.com/1907276/210155277-a7e789f1-62dd-44ef-9dc8-7ed355860a39.jpg)
**It also add an “event” to the “moduletable” div?**

**Comment by Chacapamac** [comment]
I don’t know if related but if you reload —> http://www.graf-test.ca/ (without the problem (2.6.0) the outside right & left limits of the layout load in place without movement or layers resizing

f you reload —> http://new-astroid.graf-test.ca/) (with the problem (2.6.3) the outside right & left limits of the layout load with a lateral shift from wider to smaller. ????????????

**Comment by sonvnn** [comment]
Hi @Chacapamac 

Happy New Year 2023!
This code when you logged in to your admin account. It display edit button to allows admin can edit module on front-end. I checked your website both Old and New. They works very well.

Best Regards,
Sonny

**Comment by Chacapamac** [comment]
Hi @sonvnn 
Thank You Sonny and Happy New Year to your family and yourself.

> This code when you logged in to your admin account. It display edit button to allows admin can edit module on front-end.

**You absolutely, right**, one of my website did have “Shared Session” on arrival. — Thanks

**In fact, I find that because I was looking for the reload and on first loading shifting layout** 

I will close that Issue and open another one with the Title “Shifting layout on load and reload in Astroid 2.6.3”
