### ISSUE TITLE
Installation of Astroid 2.6.3 does not work with Joomla 3.10.x

### ISSUE THREAD

**Issue by murugappanrm** [templaza/astroid-framework#275]
I am trying out the Astroid framework and I installed in both Joomla 4 and Jooma 3 and nothing seems to be happening. I do not see any change is Joomla at all.

What's happening?

**Comment by sonvnn** [comment]
Hi @murugappanrm 
Please try to install template package. You can download package here https://github.com/templaza/astroid-framework/releases/download/v2.6.3/astroid-package-v2.6.3.Framework-Template.zip

Thanks & Best Regards,
Sonny

**Comment by murugappanrm** [comment]
Hi @sonvnn 

Thank you for the quick response. I have just these questions that needs answering:
(1)  Youtube link for Beginners Tutorial
(2) Can i use Joomshaper's SP Page Builder with the framework/template?

Appreciate your help.

**Comment by Chacapamac** [comment]
Hi @murugappanrm 
**Welcome to the Astroid Community and Happy 2023!**

**For the You Tube Tutorial and Documentation**
You can go to the Framework website , in the “Support” Menu, you have all links to the Documentation and Support
—> https://astroidframe.work/

![Screen Shot 2023-01-10 at 12 08 16 PM](https://user-images.githubusercontent.com/1907276/211617817-14b00c01-f4b9-42c1-9886-4f31ff30ee9e.jpg)

**Comment by Chacapamac** [comment]
@murugappanrm 
**Can we close this issue?**

**Comment by murugappanrm** [comment]
@Chacapamac ,

Sorry for the delay. I was testing the framework and it works great after i downloaded the zip given by @sonvnn . Lets close this issue. Thank you so much for the help.
