### ISSUE TITLE
Astroid crashes as soon as a menu link to a Yootheme ZOO category is opened

### ISSUE THREAD

**Issue by ChrisHoefliger** [templaza/astroid-framework#277]
There will be an error message like this
ERROR 0 - Call to undefined method MenuHelper::getList() in example.org\libraries\astroid\framework\library\astroid\Component\Menu.php:585

_Call stack reads_

Call stack
--
# | Function | Location
1 | () | JROOT\libraries\astroid\framework\library\astroid\Component\Menu.php:585
2 | Astroid\Component\Menu::getMobileMenu() | JROOT\libraries\astroid\framework\frontend\mobilemenu.php:45
3 | include() | JROOT\libraries\src\Layout\FileLayout.php:128
4 | Joomla\CMS\Layout\FileLayout->render() | JROOT\libraries\astroid\framework\library\astroid\Document.php:83
5 | Astroid\Document->include() | JROOT\libraries\astroid\framework\frontend\document\body.php:51
6 | include() | JROOT\libraries\src\Layout\FileLayout.php:128
7 | Joomla\CMS\Layout\FileLayout->render() | JROOT\libraries\astroid\framework\library\astroid\Document.php:83

System info: Joomla 4.2.6. PHP 8.0.24 on localhost
Is there a solution to this?

**Comment by sparkktv** [comment]
Same issue I'm having, it actually affects all YooTheme extensions Widgetkit & Zoo. I had the same issue in the JoomDev version also and they fixed it but the fix no longer works in Joomla 4, the fix only worked in Joomla 3. It basically involved editing the AstroidFramework menu.php file and changing MenuHelper to ModMenuHelper.
