### ISSUE TITLE
Deprecated: Creation of dynamic property

### ISSUE THREAD

**Issue by darekmer** [templaza/astroid-framework#286]
Astroid 2.6.3, PHP 8.2, Joomla 4.2.7
Deprecated: Creation of dynamic property Astroid\Template::$title is deprecated in /var/www/html/test/libraries/astroid/framework/library/astroid/Template.php on line 42

**Comment by sonvnn** [comment]
Hi @darekmer 

Thanks for your report bug. I fixed this issue on https://github.com/templaza/astroid-framework/pull/261/commits/aa45f5c4e04448e884e2f5b253453945eb0a3291

Please help me download Developer branch and re-test on your site again. Please help me update the result here.

Thanks & Best Regards,
Sonny

**Comment by Joomlaplates** [comment]
Its fixed with Astroid 2.6.4
