### ISSUE TITLE
Need a hand for Translation

### ISSUE THREAD

**Issue by sonvnn** [templaza/astroid-framework#29]
Hi @Joomlaplates,

I need your help with Astroid Multi-language. As you know, Joomdev stopped maintain Astroid. And we have Astroid v2.5.8 here. But other languages still out of date. May you help me create a new transifex account and push original language to continue update it?

I will assign you to writer permission so you can update language direct to this repository.
Everyone who want to contribute to this project are welcome.

Everybody please help us check & feedback for translation packages in https://github.com/templaza/astroid-framework/tree/language
If you are interesting, please email to Joomlaplates to join translate team joomlaplates@gmail.com

Thanks & Best Regards,
Sonny

**Comment by darekmer** [comment]
hello do you need the en_gb.ini file?I translated into Polish

**Comment by sonvnn** [comment]
Hi @darekmer ,

I need someone how can manage this task (create transifex project, add language, update and manage it). I have so much task right now. So I need help from community.

Bests,
Sonny

**Comment by Joomlaplates** [comment]
> 
> 
> Hi @Joomlaplates,
> 
> I need your help with Astroid Multi-language. As you know, Joomdev stopped maintain Astroid. And we have Astroid v2.5.8 here. But other languages still out of date. May you help me create a new transifex account and push original language to continue update it?
> 
> I will assign you to writer permission so you can update language direct to this repository. Everyone who want to contribute to this project are welcome.
> 
> Thanks & Best Regards, Sonny

Hi Sonny, sure I can do it. No problem.
Should I create an account, like that
![transifex](https://user-images.githubusercontent.com/71080509/141986542-1ba1f9cb-e1f4-4955-a628-33555a977ac2.jpg)

**Comment by sonvnn** [comment]
Hi @Joomlaplates,

Thank you. I will check back and let you know, tomorrow.

Best Regards,
Sonny

**Comment by fontanil** [comment]
Hi,

Take a look to Localise we could use on a Joomla! website https://github.com/infograf768/j4localise not yet perfect but it can help and not need a commercial account on Transifex or Crowdin.
Geraint Edwards is using a similar way with translations.yoursites.net on J3, using Freestyle translator free (not compatible J4).
Personnaly, I'm using Extensions Translator to translate through Google API https://extensions.joomla.org/extension/extension-translator/ then revise the values.
If not, I can do the French translation and give it to you.

**Comment by Joomlaplates** [comment]
Hi fontanil,
I was looking to the extension and seems really good.
Ofc some native speakers are always helpful to fix the translation files.

**Comment by fontanil** [comment]
Yes, I think so too.

**Comment by fontanil** [comment]
Attention: several links remains to Joomdev or githubcom joomdev, sample social links too

**Comment by Joomlaplates** [comment]
Hello again,
ok I´ve checked both extensions. One of them i bought and just my oprinion.
Both of them are rubbish...
I think we are going to open an account with transifex and translate all files.

**Comment by darekmer** [comment]
Hi, I emailed transifex asking for the free open source plan and got a reply:

```
Hello,
Thank you for reaching out to Transifex support.

To use the open-source plan we offer, you would need to share with us the following information:

    The license you are using for your organization.
    The URL of the service/app/product you provide.
    Access to the Github/Bitbucket repository of your code (it cannot be private).

Once we have this info, our team will evaluate it and we will let you know.

Last, you can find more information about our open source projects in our documentation here.

Thank you in advance.

Kind regards,
Ryan


--
Ryan Bernstein
Customer Support Engineer | Transifex
Join Our Community!
Join user research!
```

**Comment by fontanil** [comment]
@joomlaplates 
With these "rubbish" extensions, I translated into French and corrected the whole files for Astroid and the two templates, this afternoon ;-)
Some changes may have to be made after a further review, but hardly any.

**Comment by sonvnn** [comment]
Hi,

Thank you my friend for your help. I give @Joomlaplates full control for Translation of Astroid. Please help him to find the best solution. Thank you all.

@Joomlaplates I've given you write permission for this git. So you can feel free pull/push translate file. You can create a new branch and work on it. Thank you very much.

Best Regards,
Sonny

**Comment by fontanil** [comment]
Hi,
Missing en-GB values for 
TPL_ASTROID_TYPOGRAPHY_LOGO
and
TPL_ASTROID_TYPOGRAPHY_LOGO_TAG_LINE

**Comment by Joomlaplates** [comment]
I am still not sure how I will do it??
Any help are welcome. transiflex is too complicated and Poedit I have no time to read 2 weeks and Google Api keys and so on.
Finally I did it with
https://crowdin.com
If anyone have interest to help I will give them access. Mail me then at joomlaplates@gmail.com

**Comment by Joomlaplates** [comment]
Hi Sonny, please add a new branch for me where i can upload the translations.
Thanks, Peter

**Comment by sonvnn** [comment]
Hi @Joomlaplates,

I created a new language branch for you here https://github.com/templaza/astroid-framework/tree/language
Thank you very much for your help.

Best Regards,
Sonny

**Comment by djayko** [comment]
> 
> 
> I am still not sure how I will do it?? Any help are welcome. transiflex is too complicated and Poedit I have no time to read 2 weeks and Google Api keys and so on. Finally I did it with https://crowdin.com If anyone have interest to help I will give them access. Mail me then at [joomlaplates@gmail.com](mailto:joomlaplates@gmail.com)

I'm right that you can speak german? Otherwise I could support the german translation.

**Comment by Joomlaplates** [comment]
> 
> 

> I'm right that you can speak german? Otherwise I could support the german translation.
Yes I speak german,  I would really appreciate if you would do the support for the German language.
Attached is the new **de** language file. You can have access to the https://crowdin.com with all files, if you want.
[astroid_de-DE.zip](https://github.com/templaza/astroid-framework/files/7562892/astroid_de-DE.zip)

**Comment by web54** [comment]
I can help with french translation and french documentation
Just sent you an email

**Comment by RedesMexico** [comment]
We will be delighted to support you with the Spanish en-ES translation. :)

**Comment by Joomlaplates** [comment]
> 
> 
> We would love to contribute to the Spanish "es-ES" translation. :)

Hola, youre welcome.
Download the file and check for issues. After that send me the file to mail address.
Muchas Gracias

**Comment by Joomlaplates** [comment]
> 
> 
> I can help with french translation and french documentation Just sent you an email

Hello, youre welcome.
Download the file and check for issues. After that send me the file to mail address.
Merci

**Comment by sonvnn** [comment]
> Hi, Missing en-GB values for TPL_ASTROID_TYPOGRAPHY_LOGO and TPL_ASTROID_TYPOGRAPHY_LOGO_TAG_LINE
> 
> And a question: why "en-GB.astroid.ini" instead of "en-GB.plg_system_astroid.ini" ? Usually the ini files have a prefix (com, lib, etc.)
Hi
Because Astroid is a library. Not plugin, component, etc

**Comment by djayko** [comment]
Is it ok removing the current "new" badges within language files? (I'm working on the translation.)

**Comment by fontanil** [comment]
> > Hi, Missing en-GB values for TPL_ASTROID_TYPOGRAPHY_LOGO and TPL_ASTROID_TYPOGRAPHY_LOGO_TAG_LINE
> > And a question: why "en-GB.astroid.ini" instead of "en-GB.plg_system_astroid.ini" ? Usually the ini files have a prefix (com, lib, etc.)
> 
> Hi Because Astroid is a library. Not plugin, component, etc

Thanks Sonny, but why not "lib_astroid.ini" as we have "lib_joomla.ini"?

**Comment by web54** [comment]
error in source file : 
TPL_ASTROID_FEATURE_LOAD_POSITION_DESC
If there are other module(s) published to this module position, you can select to display the content of this feature either below or after the module(s) published to this position
should be
If there are other module(s) published to this module position, you can select to display the content of this feature either before or after the module(s) published to this position

**Comment by djayko** [comment]
> error in source file : TPL_ASTROID_FEATURE_LOAD_POSITION_DESC If there are other module(s) published to this module position, you can select to display the content of this feature either below or after the module(s) published to this position should be If there are other module(s) published to this module position, you can select to display the content of this feature either before or after the module(s) published to this position

I can't find any difference between your two lines.

**Comment by fontanil** [comment]
below vs before ;)
Serge, les fichiers français sont déjà disponibles, je les ai traduits il y a quelques jours. Il y a peut-peut-être des erreurs.

**Comment by web54** [comment]
il y a pas mal d'erreur, je les avais par ailleurs déjà traduits à l'époque : https://www.web54.fr/tutoriel-astroid/installation-astroid/installation-astroid-en-francais
je reprends tout et corrige ce qui doit l'être
regarde sur crowdin si ce sont tes fichiers : https://crowdin.com/translate/astroid/1/en-fr

**Comment by fontanil** [comment]
Mes fichiers sont ici : https://github.com/templaza/astroid-framework/tree/language 
Je n'ai pas de compte Crowdin

**Comment by Chacapamac** [comment]
Je suis prêt à aider pour le Français, mais je ne suis pas sur exactement du processus avec Github?
Je peux aider aussi pour l'anglais, au besoin.

I'm ready to help with French, but I'm not sure exactly what the process is with Github?
I can also help with English if needed.
