### ISSUE TITLE
Bug: Two (Sticky) headers with simple trick

### ISSUE THREAD

**Issue by ElBe-Plaq** [templaza/astroid-framework#293]
**Info**
Affected version: `2.6.3` (probably more too)
Affected module: sticky header
Browsers tested on: `Edge 110.0.1587.50`, `Chrome 110.0.5481.104`, `Firefox 110.0`
OS tested on: `Windows 10`

**How to reproduce:**
1. Activate stick headers
2. Scroll down until there is a sticky header
3. Zoom in to at least `300%` (Edge and Chrome), `260%` (Firefox)
4. Scroll up

You will now have two headers. (1 sticky, 1 not), both are functional. If you zoom out, they will disappear.

**Additional information**
This is just a visual bug, nothing more. Also I don't know if only the site I was working on is affected.

**Comment by ElBe-Plaq** [comment]
Also the file use stick**e**y instead of sticky.

**Comment by Chacapamac** [comment]
I just test on my test website —> http://joom4-astro.graf-test.ca/
— I test on Firefox and Chrome
To be able to see the “ 2 sticky” I have to go up the page completely. 
What I see is the **Sticky header** on top of the **Normal** (non-sticky) **header** that appear at these magnifications.

![Screen Shot 2023-02-21 at 9 23 10 AM](https://user-images.githubusercontent.com/1907276/220378868-7cc64862-0217-478a-a486-769f154ea7d6.jpg)


What I find strange, Sticky or no Sticky, is that the “**Top Bar Section**” **disappear** at 150% + zoom on my Firefox and Chrome. I don’t think it should just vanish???

**Comment by ElBe-Plaq** [comment]
Yes, that's what I mean.

**Comment by sonvnn** [comment]
Hi @ElBe-Plaq @Chacapamac 

Thanks for your support! I fixed this issue on https://github.com/templaza/astroid-framework/commit/a39ee2f9899560e1b0e815ce2365e6cdcf2df1f0 

Please help me download developer branch and test it on your site https://github.com/templaza/astroid-framework/archive/refs/heads/developer.zip
Please let me know if this issue is still happen again

Thanks & Best Regards,
Sonny

**Comment by Joomlaplates** [comment]
Yes fixed in 2.6.4

**Comment by ElBe-Plaq** [comment]
Thanks! If I knew it was a JS issue, I would have been able to fix it myself.

**Comment by Chacapamac** [comment]
Yep, Working, The disappearance of the “**Topbar Section**” was set in the “Responsive Settings” of the Topbar Layout.
Seem to work OK!
