### ISSUE TITLE
New Parameters in the Color Section > Menu

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#295]
Hi Sonny,
can you add 2 new parameter to the Color Section > Menu ( See pic attached).
Its really wanted by many user and its hard to explain them how to do an override XML,

**XML Override Code**
```
   <fields name="params">
    <fieldset icon="fas fa-paint-brush" label="ASTROID_OPTIONS_COLOURS" name="astroid_colours" addfieldpath="/libraries/astroid/framework/fields" order="3">
		<field astroidgroup="main_menu" name="main_menu_active_background" type="astroidcolor" large="true" label="Link Active Background" description="Set the Main Menu Link Active Background">
		</field>
		<field astroidgroup="main_menu" name="main_menu_hover_background" type="astroidcolor" large="true" label="Link Hover Background" description="Set the Main Menu Link Hover Background">
		</field>
	</fieldset>
   </fields>
```
**SCSS Code, or you know it better**
`.nav-item-level-1.nav-item-active {background:$main_menu_active_background !important}`
![active-bg](https://user-images.githubusercontent.com/71080509/221381248-810bd9a8-245d-48de-bbac-056ffe3bfd4e.jpg)
Thanks Peter

**Comment by sonvnn** [comment]
Thanks @Joomlaplates 
I will take care about it in the next version.

**Comment by Joomlaplates** [comment]
Hi Sonny, during uopdate to dark mode feature, please dont forget this small new feature to the new Astroid version.
Thanks, Peter

**Comment by Chacapamac** [comment]
Just to see if solved?

**Comment by sonvnn** [comment]
@Joomlaplates I added this in https://github.com/templaza/astroid-framework/commit/3811288a769e119afa48bd904a57238c5912bdf0

Please help me check it.

Thanks,
Sonny

**Comment by Joomlaplates** [comment]
Hi Sonny,
yes it works many thanks.
Greatings Peter

**Comment by Chacapamac** [comment]
Yes Work perfectly!
