### ISSUE TITLE
Offcanvas, submenu will not open in Safari

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#30]
Sorry to report always new "bugs".
I dont wanne make you busy.
...
It seems the Off Canvas Menu has a problem with Mac and Safari. If you click on the "arrow" to display the submenu, it works fine with Chrome, Firefox and Edge. But With Safari, nothing happens after the click.

This can be corrected by inserting the following css code: 
`.nav-child.unstyled.dropdown-menus:not(.menu_open) {display:none;} `
Regards, Peter

**Comment by djayko** [comment]
@Joomlaplates Hi Peter,

hmm..... I read your issue by accident and tested it on my ipad mini on safari. 
I have a different behaviour:

1. No Arrow for submenu is visible (even on firefox and chrome)
2. The submenu arrow appears after a click and the main menu item is active.

Same behaviour in all browsers. 

What i did:
- i create a standard menu module with 3 item and one subitem and gave it the position offcanvas
- menu level is set from 1 to all

Maybe you can check this behaviour as well to verify the issue in more detail.

regards,
Frank

**Comment by sonvnn** [comment]
Hi Peter, 

I tested Mobile Menu and Off-canvas Menu on my iPhone - Safari. It works like a charm. I am not sure about your issue. May you help me make a video record for detail the issue.

Best Regards,
Sonny

**Comment by Joomlaplates** [comment]
Hi Sonny, with a new Ipad with actual OSX its working too.
Maybe was an issue by old version of Safari.
