### ISSUE TITLE
Mega Menu with Link on Menu heading

### ISSUE THREAD

**Issue by seoBOXX** [templaza/astroid-framework#301]
Hi there,

i try to move a pretty big vertical menu to a horizontal mega menu. The problem i face is that the Level 1 items link to an article are now menu headings and cannot be linked to an article anymore, so for me the content is lost. Is there any way to get that done without loosing the content and making the menu heading or menu seperator clickable?

Best regards,

Andreas (Andy)

**Comment by Chacapamac** [comment]
I @seoBOXX ,

If your level 1 menu item is not link to your article You have to change the Menu item “**Link Type**” from “**Separator**” or “**Menu Item Alias**”

![menu-item-separator](https://user-images.githubusercontent.com/1907276/222904205-14073609-123d-44e9-a9c4-7ffc99295610.jpg)

to the Menu item “**Link Type**” —> **“Single Article”**

![menu-item-type-article](https://user-images.githubusercontent.com/1907276/222904316-ffaa06e0-9ed1-49ba-83f4-402f90068757.jpg)

**Comment by seoBOXX** [comment]
Oh Sorry .... the former Level 1 ones are now Level 2 ones and down show the submenuitems until i change to menu heading or menu seperator ... but then the content of that item is gone ... i place a link -> https://joomla4.land-dinslaken.de/

If you go to menu Verein (Mega Menu) and the the Menu item Dinslakener Pfennig has subitems but also content on this Level 2 item ... how can i show up the subitems under the Level 2 item like shown left in the menu in Der Verein without loosing the content on the item Dinslakener Pfennig?

**Comment by Chacapamac** [comment]
@seoBOXX 
Tell me if I understand what you want to achieve.

![Screen Shot 2023-03-04 at 9 22 18 AM](https://user-images.githubusercontent.com/1907276/222908199-58f7a55f-27a5-4882-af3b-cdb42fecf7b4.jpg)

**Comment by seoBOXX** [comment]
@Chacapamac .... thats exactly what i want to achieve 👌

**Comment by Chacapamac** [comment]
@seoBOXX  
**Something like** —>  http://joom4-astro.graf-test.ca/

![Screen Shot 2023-03-05 at 10 43 02 AM](https://user-images.githubusercontent.com/1907276/222970669-f7f512d4-7a72-4265-a5eb-11e09ecc799e.jpg)

**Comment by seoBOXX** [comment]
@Chacapamac .... yes .... exactly something like this :-)

**Comment by Chacapamac** [comment]
@seoBOXX 
Ok, 
**1.** Create a menu with all your menu items and links
— (e.g. my example) do not put  “Submenu 1 &2) as a submenu of “Titre” . Put evertyng at the same level

![new-menu](https://user-images.githubusercontent.com/1907276/222987483-dcca9734-421a-4e9c-ace4-5bb1e600d3cb.jpg)

**2.** Add a menu item class for the bold “Titre” menu item. This will be use to css style your Title/link as you which.

![title-menu-item-bold](https://user-images.githubusercontent.com/1907276/222987583-b853f27f-8ffb-4678-8c7b-81459c90e274.jpg)

**3.** Create a new Module of type “**Menu**” and link your Menu to it. Give the Module a class for easy styling.

![add-menu-class](https://user-images.githubusercontent.com/1907276/222987774-11bdcc0c-da32-473b-96aa-4555227a08cb.jpg)

**4.** Load that Module in your Mega Menu

![load-module](https://user-images.githubusercontent.com/1907276/222987835-53060c11-17fa-4d85-8f24-bda5212445b6.jpg)

To make it the way it look on my example I add that CSS to the Template Style in the “Custom CSS” from Astroid Template manager
.```
font-weight-bold { font-weight: bold !important;}
.megamenu-module .astroid-nav {line-height:2.5em;}
.megamenu-module {border: 1px solid gray; margin:5px; padding:10px;}
.megamenu-module li {width: 100%;}
 
```

**Comment by seoBOXX** [comment]
Thanks so far ... that was an idea i had also but then i will have no menu structure left in the mobil menu

**Comment by Chacapamac** [comment]
I see, you right!
I’m not sure how to achieve that, I have to think about it. A menu in a Megamenu is not seen as part of the Main menu and doesn’t appear in the mobile version.

My first idea will be to repeat the menu items in the MegaMenu as parent of the First level MegaMenu and show them ONLY on mobile. 

I will try that and come back. Logically it should work.

**Comment by Chacapamac** [comment]
@seoBOXX  
I think this is what you want —> http://joom4-astro.graf-test.ca/

**Comment by seoBOXX** [comment]
@Chacapamac ... we are close to it but in fact the two submenu items habe to be a subitim od the titre item in the mobile menu ... seems that i will have to have a big mobile menu and build the mega menu from scratch with alias menu items

**Comment by Chacapamac** [comment]
I think, this will make the mobile menu complicated to use, but you know what you want to do...

> The two submenu items habe to be a subitem of the titre item

You just just do exactly that in the only mobile menu itself. —> http://joom4-astro.graf-test.ca/

**Comment by seoBOXX** [comment]
i will give that a try and it looks good how it is ... i try to get that wrking on my page ... maybe i'll come back to you ... thanks a lot so far and have a great day.

Bestr regards, stay safe and healthy,
Andreas

**Comment by Chacapamac** [comment]
**This is the main menu part now with the Megamenu and is Submenus (for mobile)**  
_• Curiously we don’t need to add an hiding class _(d-block d-lg-none)_ to the Mobile Submenus, they seem to not show on larger screen than Bootstrap MD._
That’s good because you need to be there for the SEO

![new-mainmenu](https://user-images.githubusercontent.com/1907276/223219993-d3c65062-40f4-4097-8a79-3ac34011ff03.jpg)

**Comment by seoBOXX** [comment]
@Chacapamac ... i now began to create the menu using strict aliases ... i moved all the menustructure to a new menu for mobile devices and it looks pretts good ... it will be a bit work to get all the menu items into that again but for me it works and looks good -> https://joomla4.land-dinslaken.de

**Comment by Chacapamac** [comment]
@seoBOXX  Happy to help!
**I check, looking Good!**

**Good Day to Astroid community!**

**Comment by seoBOXX** [comment]
@Chacapamac ... thanks a lot for helping me out, giving advice and prviding ideas and possible solutions!

Have a great day, stay healthy and safe and maybe we will read again here within the next weeks ;-)

Cheers,

Andreas

**Comment by Chacapamac** [comment]
@seoBOXX 
No Problem!
