### ISSUE TITLE
feature request: Button option for banners

### ISSUE THREAD

**Issue by djayko** [templaza/astroid-framework#31]
Hi,

the banner option in astroid is awesome and really useful.
I'm working with astroid for a non profit organisation and I got the question, for the best way how to setup a CTA Button on banner.

I guess it would be an idea to add this option on the menu tab as well as using the title, subtitle option.

just as field ideas:

1. LINK: for adding the URL
2. Button-Background: colorpicker - Background color of button
3. Text-Color: colorpicker - Color of Button text
4. Class: free textfield for addingting template classes to button (e.g. from boostrap like bg-primary or rounded-0...)
5. Text: Text of button

best,
Ayko

**Comment by sonvnn** [comment]
Hi @djayko,
I added this feature to git in https://github.com/templaza/astroid-framework/commit/a717d1be8f8d8480dbc8d9b5a40b325a7abda784

Please help me check it.
Thanks,
Sonny

**Comment by djayko** [comment]
@sonvnn installlation and test where successfull.
