### ISSUE TITLE
Disabling scripts or css

### ISSUE THREAD

**Issue by vtheod** [templaza/astroid-framework#310]
Hi all,

I tried to disable the fontawesome css in the frontend, but with no success. I tried with the Joomla AssetManager, I added in the template's index.php the `$wa->disableStyle('fontawesome')` but nothing happened. Is there a workaround for this?

FYI, I have disabled the fontawesome loading from the astroid plugin, but I also want to stop Joomla from loading it.

Based on this experience, I'd like to ask about/suggest the use of the joomla.asset.json in the astroid templates. Is this possible?

**Comment by Chacapamac** [comment]
I @vtheod , you are right!

Astroid plugin to load unload fontawesome seem to work well.

**It seem that Joomla now load fontawsome and so far I do not see any available easy setting to unload it?????**

**Note:** I pass a comment to Joomla here on Joomla Github —> https://github.com/joomla/joomla-cms/issues/38898
Also, remark in that post, they discuss about how to unload it., maybe that can help.

**It is loaded at** —> media/system/css/joomla-fontawesome.css?f0530-I_guess_watever_number_here-cc6

**Comment by vtheod** [comment]
Hey @Chacapamac ,

Thanks for your answer.
I tried every approach, but unfortunately nothing works (at least for astroid).
It could be stripped by using plugins like rereplacer or jquery easy, but I prefer to control the code by myself without using third party extensions.

**Comment by Chacapamac** [comment]
I think, for now, only a hack of Joomla.

**The Github post propose that solution**

Y

> ou have 2 option:
> Override 'fontawesome' to emptiness $wa->registerStyle('fontawesome', '')
> Edit joomla.asset.json and remove 'fontawesome' dependnecy for template.cassiopeia style asset, and add 'fontawesome' dependnecy to template.cassiopeia preset (And make PR, if you want).
> 
>     If it needs to be a dependency is there a method in the web asset manager to disable it
> 
> To keep track of correct dependency tree you have to override existing asset to asset with new dependencies.
> 
> [joomla-cms/libraries/src/WebAsset/WebAssetItem.php](https://github.com/joomla/joomla-cms/blob/f520c98c64efb538e70e918acffb60d07e4d6b1e/libraries/src/WebAsset/WebAssetItem.php#L23)
> 
> Line 23 in [f520c98](https://github.com/joomla/joomla-cms/commit/f520c98c64efb538e70e918acffb60d07e4d6b1e)

**Comment by vtheod** [comment]
Deleting the file is definitely not the solution ;)

**Comment by sonvnn** [comment]
@vtheod You can try delete this line in Astroid https://github.com/templaza/astroid-framework/blob/master/framework/library/astroid/Helper/Head.php#L93

I will update this in the next version.

Thanks & Best Regards,
Sonny

**Comment by vtheod** [comment]
Thank you, @sonvnn 

Is there a way to override this file?

**Comment by sonvnn** [comment]
> Thank you, @sonvnn
> 
> Is there a way to override this file?

I will integrate it to FontAwesome On/Off. So you can turn it off, but if you turn it off may be some icons of front-end editor will disappear. It will be availabled in 2.6.5.

**Comment by Chacapamac** [comment]
@vtheod Can I mark the post as solved?

**Comment by vtheod** [comment]
Sure mate!

**Comment by Chacapamac** [comment]
Good Weekend to All!
