### ISSUE TITLE
Contact Information / Social Profiles on different positions based on resolution

### ISSUE THREAD

**Issue by SirCorono** [templaza/astroid-framework#314]
Hi
In Asteroid, there is the option to add contact information and social profiles. They can be displayed for example on the top of the page (topbar-1 and topbar-2). However, these positions disappear when the resolution is reduced, e.g. on a mobile device. The contact information and the social profiles are not visible anymore.

My idea: As soon as the template switches to mobile view, I switch the contact information from topbar to the OffCanvas position. Is this possible? And if yes, how? I only found the settings for one position in the template options.

Thanks for your help.

**Comment by Joomlaplates** [comment]
Hello, please check your mobile settings for this element/section or row
https://docs.astroidframe.work/layout-settings/element-settings
![section-settings5](https://user-images.githubusercontent.com/71080509/230849617-67e0b8b7-22fc-4bdb-838f-736151ddde8e.png)

**Comment by Chacapamac** [comment]
@SirCorono 
Just to see if **Joomlaplates** answer your first question and if it answer also your second ?

> In Asteroid, there is the option to add contact information and social profiles. They can be displayed for example on the top of the page (topbar-1 and topbar-2). However, these positions disappear when the resolution is reduced, e.g. on a mobile device. The contact information and the social profiles are not visible anymore.

**Comment by SirCorono** [comment]
Sorry for the late answer, was busy with other things.
Yes, these settings are enough, thanks for your help. Learned something.
