### ISSUE TITLE
Wrong Animation if you change the animation delay

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#32]
Hi again, 
**Wrong Animation**
If you change the animation delay ( see pic)
The element is shown when it comes to viewport and then animate
https://youtu.be/nkwmfCcW5mU

**Right Animation**
The element is not shown until it comes to viewport and then animate
https://youtu.be/ScZE_QIXr9w

I hope you can understand what I mean,
regards Peter
![animation](https://user-images.githubusercontent.com/71080509/142082997-a83b2d29-8cef-4adc-8fa4-7b5c6b289b57.jpg)

**Comment by sonvnn** [comment]
I fixed this in https://github.com/templaza/astroid-framework/commit/a717d1be8f8d8480dbc8d9b5a40b325a7abda784
Let's check it.
Bests,
Sonny
