### ISSUE TITLE
Astroid very slow to boot... and in template setting.

### ISSUE THREAD

**Issue by iorbita** [templaza/astroid-framework#323]
Hi,
I love Astroid framework, but there is something that really annoys me a lot and prevents me from working properly, I don't know if I'm the only one with this problem, but I've noticed this issue for a while now, it was even before I switched to another framework and back to Astroid.

The framework is extremely slow to boot (about 25 seconds, yet I have a Mac Pro with 64 Gb...); I noticed this slowness since the last versions of the framework, if I remember well at the beginning Astroid was not so slow to boot.

Another frustrating thing is that the more I progress in template configuration, the more the interface becomes slow and therefore unusable, after a few minutes I have to quit the interface because it is impossible to continue template setting.

Could it be a problem related to the browser's cache?

Thanks,
Lorenzo

**Comment by deltapapa01** [comment]
Hi,
I can't confirm this, on all my sites the framework loads in about 5 seconds with my Intel i7 13700k. On my laptop with smaller CPU it is much slower, so it depends very much on the processing power of the client.

WBR

**Comment by iorbita** [comment]
it's strange, I don't remember Astroid being so slow... :(

**Comment by sonvnn** [comment]
@iorbita Thank you for report! I confirm this issue. Cause typography tab loading. I am working to rebuild a new typography system. I hope I can find a solution for it in 2.6.6.

Thanks & Best Regards,
Sonny

**Comment by Chacapamac** [comment]
**Astroid 2.6.4 — Joomla 4.3.0**
**Backend Administration load**
![Admin-load](https://user-images.githubusercontent.com/1907276/235221660-a8d52580-e349-4920-8a5b-67910fd6ea0e.jpg)

**Some admin bug & warning** _(maybe  problems with my test fonts????)_
![warning-admin](https://user-images.githubusercontent.com/1907276/235221910-bb842c48-9821-4950-9709-de183fdcc237.jpg)
![Admin-load-bug](https://user-images.githubusercontent.com/1907276/235221952-a554ed93-0a92-43df-9d7b-4d6888aedb6e.jpg)

**Admin Load Huggers**
![admin-load-hugger](https://user-images.githubusercontent.com/1907276/235222039-4347f0ac-6b02-44df-8065-7e5dac480070.jpg)

**Frontend**
![Frontend](https://user-images.githubusercontent.com/1907276/235222104-f455a114-f001-4f6e-a301-afaeb1574adb.jpg)

**Comment by iorbita** [comment]
Hi, 
awaiting a fix for this issue, and since the problem is related to the font tab (Google font?), is it imaginable to temporarily deactivate this option or that is just not possible? All my fonts are loaded locally, I don't use the Google font service...

Thanks again,
Lorenzo

**Comment by sonvnn** [comment]
This issue was fixed in Astroid 3

**Comment by Chacapamac** [comment]
Great!
