### ISSUE TITLE
Template One not working with Astroid 2.6.4

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#324]
Hello Sonny,
the Template One is not working with the current Astroid version 2.6.4 because of the color mode settings in the index.php of the Template One
I would insert at least a **if else option**:
```
if Astroid = astroid 2.6.4 or > astroid 2.6.4
$color_mode         =   Astroid\Framework::getTemplate()->getColorMode();
$color_mode_theme   =   $color_mode ? ' data-bs-theme="'.$color_mode.'"' : '';
```
Thanks Peter

**Comment by Buerglen** [comment]
Hallo zusammen
bei einer von vier Astroid-Installationen hatte ich auch die Meldung:
`ERROR 0 - Call to undefined method Astroid\Template::getColorMode() in /Applications/XAMPP/xamppfiles/htdocs/vier/templates/astroid_template_one/index.php:17`
mit Dank und Gruss

**Comment by sonvnn** [comment]
Hello, 

Please help me download https://github.com/templaza/astroid-framework/archive/refs/heads/one-template.zip and re-install again.

Thanks & Best Regards,
Sonny

**Comment by Joomlaplates** [comment]
Hello Sonny, yes its working now.
And the dark mode stay activated after refresh the site, becuase of the cookie you set.
Thanks, Peter

**Comment by sonvnn** [comment]
@Joomlaplates you can go to Astroid plugin to disable Color mode feature.

**Comment by Joomlaplates** [comment]
Hi Sonny,
dont worry the mode is working well and stay activated. Not like before when the mode switched back because of missing cookie.
Thanks, Peter
