### ISSUE TITLE
Full article image not showing at the right place

### ISSUE THREAD

**Issue by patrickus33** [templaza/astroid-framework#326]
HI,
Using Astroid 2.6.4 and template one.
The "full article" images chosen in the images and links tab of the article publication appear above the article title and not in the article body.

Regards
Patrick

**Comment by sonvnn** [comment]
Hello,

Let's go to Blog Menu -> Options and try to change "Postition of Article Info"
![Screen Shot 2023-05-25 at 11 51 31](https://github.com/templaza/astroid-framework/assets/3204103/9aa68c79-8675-4af4-b789-c1af4891615c)

Best Regards,
Sonny

**Comment by patrickus33** [comment]
Hi,

Sorry for the late response..

Yes, Everything is OK!

Thank you!
Regards.

Patrick Marangone
0676088910
