### ISSUE TITLE
*** URGENT***  — Update from 2.6.3 template/one/zero 2.6.4 bring frontal error?

### ISSUE THREAD

**Issue by Chacapamac** [templaza/astroid-framework#328]
**The error**————————————————————————————
![template-update-front-error](https://github.com/templaza/astroid-framework/assets/1907276/50e3ca98-77a3-48de-9648-b7e8c6a0c5a5)

**The home Page**————————————————————————————
![Screen Shot 2023-05-11 at 2 29 26 PM](https://github.com/templaza/astroid-framework/assets/1907276/e9b85843-92f7-445e-94f1-fea840ad2632)

**Comment by Chacapamac** [comment]
**More Infos:**
_
> ERROR 0 - Call to undefined method Astroid\Template::getColorMode() in /home/graftest/domains/joom4-astro.graf-test.ca/public_html/templates/astroid_template_one/index.php:17
_ 

**My Test website:** —> http://joom4-astro.graf-test.ca/
— **Joomla  ‎4.3.1**
— **PHP 8.1.18**

**Comment by sonvnn** [comment]
@Chacapamac This issue happen by ColorMode feature from Astroid 2.6.5. It is not appear in 2.6.4.
I just reverted One Template to 2.6.4. https://github.com/templaza/astroid-framework/commit/6ab28987e9cbb732b9ffecf5db4d1abf27bf544f

Please help me check it again.

Best Regards,
Sonny

**Comment by Joomlaplates** [comment]
Hello, yes its working now.
color mode feature is now in Astroid Plugin and not in template index.php anymore.
