### ISSUE TITLE
getColorMode missing

### ISSUE THREAD

**Issue by ramblerswebs** [templaza/astroid-framework#335]
I am using Joomla 3.10.11 and astroid_template_one 
Just up dated the latter to version 2.6.5 
The home screen of the site now displays "It seems like the page that you are looking for is no longer here."
Turning the error reporting on the page tab now says "Error 0: Call to undefined method Astroid/Template::getColorMode()"

see https://daftwalkers.darleyabbey.org.uk/

**Comment by ramblerswebs** [comment]
Just to clarify, The post above was just using Joomla update system.
I then looked on here and downloaded astroid-package-v2.6.5.Framework-Template and installed that
this solved the issue and web site now working again

**Comment by sonvnn** [comment]
You need update Astroid Library to 2.6.5 to fix this. 

Thanks,
Sonny
