### ISSUE TITLE
string:? undefined

### ISSUE THREAD

**Issue by biobill** [templaza/astroid-framework#34]
Hey Sonny,

I'm building a new site and I just noticed that in a column astroid produces the following code:

`<div class="astroid-column col-lg-12 col-xl-12 order-xl-? string:? string:? string:? string:? string:? string:? undefined:undefined ? ? ? ? ? ? ? order-lg-? string:? string:? string:? string:? string:? string:? undefined:undefined ? ? ? ? ? ? ? order-md-? string:? string:? string:? string:? string:? string:? undefined:undefined ? ? ? ? ? ? ? order-sm-? string:? string:? string:? string:? string:? string:? undefined:undefined ? ? ? ? ? ? ? order-? string:? string:? string:? string:? string:? string:? undefined:undefined ? ? ? ? ? ? ?" id="f-6a7euke09">`

As I have seen until now, it's happening only in a row with 1 column (col-lg12). Any idea about this?

**Comment by Joomlaplates** [comment]
Hello biobill,
please more details. 
- Astroid version
- Joomla version
- Template ?
I´ve tried with the Astroid 2.5.9 ( developer branch) and couldnt see the issue with one column, see picture
![string](https://user-images.githubusercontent.com/71080509/142491104-10c0cf75-0bfa-43d1-8f46-34415f3c104a.jpg)

**Comment by sonvnn** [comment]
Hi,
It works well on my site, too. Please detail your issue via your website url or video record.
![Screen Shot 2021-11-19 at 09 25 03](https://user-images.githubusercontent.com/3204103/142554389-3cbe23ef-7323-48ca-b079-1dcf8156dbf5.png)

**Comment by biobill** [comment]
Here are my details:

Framework Version: 2.5.9
Template One Version: 1.3.4
Joomla! Version: ‎4.0.4

I've just tested today and it is working fine. Yesterday it didn't...
Maybe a cache problem? 
If I face the same problem again I'll come back.
Thank you both for your effort!
