### ISSUE TITLE
Termination of AddThis Services Notice

### ISSUE THREAD

**Issue by salahjaafar** [templaza/astroid-framework#347]
Dear Astroid Framework GitHub Team,

We regret to inform you that the AddThis Services will no longer be available for integration within the Astroid Framework. 
Please remove any references or dependencies on AddThis Services within the Astroid Framework. 

https://www.addthis.com/

Best regards,
![Screenshot 2023-06-05 at 20-56-30 Get more likes shares and follows with smart website tools - AddThis](https://github.com/templaza/astroid-framework/assets/47123877/908786f1-ed1d-4ed7-a8c3-27ecc288c9fe)

Salah JAAFAR

**Comment by sonvnn** [comment]
It's a bad news. Thank you very much! I will remove all references related Addthis in the next Astroid Version.

Best Regards,
Sonny

**Comment by salahjaafar** [comment]
I understand that it might be disappointing news for you. However, it's important to adapt and make the necessary changes to improve the Astroid version. Removing all references related to Addthis is a decision that has been made to enhance the overall functionality and user experience.
