### ISSUE TITLE
Configuring Astroid Framework for Local Intranet Usage: Disabling External Libraries and Adding Custom Fonts

### ISSUE THREAD

**Issue by salahjaafar** [templaza/astroid-framework#350]
Dear Astroid Framework GitHub team,

I hope this message finds you well. I would like to discuss a request regarding the usage of the Astroid framework in a local intranet environment.

Currently, I am working on a Joomla project that operates within an intranet setting, and I would like to disable external libraries, such as those utilized by Google. I aim to configure the framework in a way that includes only the necessary libraries and resources for the smooth functioning of the internal site.

Additionally, I would like to have the ability to add my own custom fonts under the local project directory. This would allow me to use these specific fonts for better visual harmony with the rest of the website.

I understand that the use of external libraries can enhance performance and compatibility with online services. However, in this particular case, it is crucial to restrict access to external resources for privacy and security reasons.

I greatly appreciate the work you have done with Astroid, and I would like to inquire if it is possible to configure Astroid in a way that disables external libraries while still allowing the addition of locally stored custom fonts.

If such a configuration is feasible, could you kindly guide me through the process of achieving it? Your assistance would be immensely valuable in this endeavor.

Note: I understand that this configuration may result in limitations in terms of compatibility with certain features or online services. However, in this intranet context, it is essential to have control over the resources used by the site.

Thank you sincerely for your time and support. I eagerly await your guidance and recommendations on using Astroid in a local intranet environment, disabling external libraries, and adding my own custom fonts.

Best regards,
Salah JAAFAR

**Comment by Chacapamac** [comment]
I @salahjaafar 
You can start by the settings of the Astroid plugin.

![Screen Shot 2023-06-16 at 7 23 38 PM](https://github.com/templaza/astroid-framework/assets/1907276/7d6b2ac0-2c9c-456d-a825-fd2380d76e69)

**Comment by Chacapamac** [comment]
I’m working right now to update the typography documentation
https://astroidframe.work/
![Screen Shot 2023-06-16 at 7 31 03 PM](https://github.com/templaza/astroid-framework/assets/1907276/5b4d1570-773e-48ed-944a-715ec50f77b8)

**For Local Fonts use this:** (come back here if you have problem)
https://docs.astroidframe.work/typography/how-to-use-local-font

**Comment by salahjaafar** [comment]
"A big thank you, it's working properly."
