### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by darekmer** [templaza/astroid-framework#36]
translation strings are missing from the miscellaneous.xml file.

**Comment by sonvnn** [comment]
Hi @Joomlaplates ,

Is there a way help people follow and translate easier in crowdin.com, bro? Then contributor can follow and manager their language by themselves. It will reduce your work on tasklist.

My email sonlv@templaza.com. May you add me as a contributor? I can help translate Vietnamese.

Thanks & Best Regards,
Sonny

**Comment by Joomlaplates** [comment]
Hi Sonny, I have add you like a manager.
BTW: For all other who wnats to help with translation, please use the invitation link.
After that I will give you access.
https://crwd.in/astroid

**Comment by Joomlaplates** [comment]
I just noticed the membership we need is Bronze and costs 150$ the month.
I think we translate all of them with crowdin and after the trial is run out, I will do the tranlation manually with poEditor and Google translator.
