### ISSUE TITLE
HTML injection in getBodyClass()

### ISSUE THREAD

**Issue by emedinainnotec** [templaza/astroid-framework#360]
Many templates based on Astroid Framework use the getBodyClass() function to add classes to the body.
When using the payload ?task=">micustomhtml  or ?layout=">mycustomhtml , we can break the html structure and show our custom message.
The "<" caracter can not be injected so we can't execute any javascript or css, but we can inject our message to other websites.
This problem is caused by an incorrect input filter:
        $option = $app->input->get('option', '', 'STRING');
        $view = $app->input->get('view', '', 'STRING');
        $layout = $app->input->get('layout', 'default', 'STRING'); **// Input filter shoud be 'ALNUM' or use custom regex**
        $task = $app->input->get('task', '', 'STRING'); **// Input filter shoud be 'ALNUM' or use custom regex**
        $header = $params->get('header', TRUE);
        $headerMode = $params->get('header_mode', 'horizontal', 'STRING');
        $Itemid = $app->input->get('Itemid', '', 'INT');

**Comment by sonvnn** [comment]
@emedinainnotec Thank you for suggestion. I will fix it in the next Astroid version.

**Comment by cuserosr** [comment]
Any news on the Astriod update that solves this problem?
Thanks!

**Comment by sonvnn** [comment]
@emedinainnotec @cuserosr Thank you for remind me! I fixed this issue and It will be release in v3.0.8. You can check it here https://github.com/templaza/astroid-framework/commit/bc8f43e319889df096b070bf55d884e5d5077576
