### ISSUE TITLE
Just a question, Template update and copies of  them??

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#37]
Hi all,
just a question.
I realised when I update the template, the copies of the templates have still the old version numbers? Is this a bug ?
Sure, I know that theme copies in Joomla are just db entries, but its confusing.

BTW: Where are stored the theme settings from copied themes? In db or json file?
Ok finally I found it out. The parameters of a theme copy are stored in the Joomla db, see pic attached. And the parameter number is the json. file ( 34.json) which can be found in the template folder > template/params.
Maybe helps someone.
![db](https://user-images.githubusercontent.com/71080509/142639342-6a444a88-ceff-41f1-91e7-16c51b6db041.jpg)

Thanks, Peter

**Comment by darekmer** [comment]
json

**Comment by Joomlaplates** [comment]
Ok finally I found it out.
The parameters of a theme copy are stored in the template folder > **your template/params/template_id.json**
In my case the copy have the id 34 and therefore its the **34.json** file

![theme_id](https://user-images.githubusercontent.com/71080509/142706625-465c7e70-624f-40d1-b2e4-4d709061e070.jpg)
