### ISSUE TITLE
Read Time in articles is visible even if it is set to not show 

### ISSUE THREAD

**Issue by astroid23** [templaza/astroid-framework#372]
Hello all,

Read Time in articles is visible even if it is set to not show form astroid template one and zero settings.
Joomla 4.3.3.

Any advice, please?

**Comment by deltapapa01** [comment]
Hi,
I have never had a problem with the read time. Have you seen that there are 2 options for this? Once under "Articles Listing Options" and then under "Single Article Options".
You have to turn off both options.

**Comment by astroid23** [comment]
> Hi, I have never had a problem with the read time. Have you seen that there are 2 options for this? Once under "Articles Listing Options" and then under "Single Article Options". You have to turn off both options.
> 
> Oh, and of course clear all Joomla caches (including the page cache) and the browser cache. This is very important.

It was really easy, finally! Many thanks for your help, deltapapa01!
