### ISSUE TITLE
Multiple fnt temp files created using Body Typography settings as Custom with Astroid on Siteground

### ISSUE THREAD

**Issue by agendagroup** [templaza/astroid-framework#377]
I have found that if you set Body Typography settings set to Custom in Astroid on Siteground hosting is creates multiple files in the /tmp folder outside public_html and fills up the hosting space pretty quickly.

To fix this you have to SSH into the server and flush the /tmp folder using the command line.
There is no way to access this folder from Site tools.

The only way round it is to set Body Typography settings to default - eg, If Default selected then properties will inherit from CSS code.  

It doesn't seem to be a problem on Cpanel hosts.

It creates a lot of files called fnt00A56P etc
My account quickly rose to over 9gb in a few days for a 500mb website
7941 MB /home/ACCOUNTUSERNAME/tmp

Hopefully you can release a patch for this?

**Comment by deltapapa01** [comment]
Hi,
the solotion is here:
https://github.com/templaza/astroid-framework/issues/357#issuecomment-1643027495

woff is not supported, woff2 and ttf can be integrated with me without any problems.

**Comment by agendagroup** [comment]
ok thanks for the update

**Comment by deltapapa01** [comment]
You are welcome :-)
