### ISSUE TITLE
Unused language-string TPL_ASTROID_EXTRA_ELEMENT_SMALL_DEVICES_DESC

### ISSUE THREAD

**Issue by djayko** [templaza/astroid-framework#38]
Hello,

file: en-GB.astroid.ini
line: 546
string: TPL_ASTROID_EXTRA_ELEMENT_SMALL_DEVICES_DESC

I didn't find this string anywhere, only TPL_ASTROID_ELEMENT_EXTRA_SMALL_DEVICES_DESC exists and is already set on Line 544

best,
Frank

**Comment by sonvnn** [comment]
I removed it at https://github.com/templaza/astroid-framework/commit/1abbc65f46b1842f25a4aeee5986906e1ad5ff88

Thanks,
Sonny
