### ISSUE TITLE
Después de una migración se me queda cargando y no muestra nada

### ISSUE THREAD

**Issue by davidfinzi** [templaza/astroid-framework#385]
Hola! Tuve que migrar de servidor, instalé todo en el nuevo y cuando intento abrir el botón "Template options" me aparece esto y se queda ahí. Faltará algún archivo?
<img width="478" alt="image" src="https://github.com/templaza/astroid-framework/assets/88640280/e068dbab-0dac-46b4-a16f-44b71725da83">

**Comment by sonvnn** [comment]
We are working on Astroid 3. Please help me download and update Astroid https://github.com/templaza/astroid-framework/archive/refs/heads/v3.zip
