### ISSUE TITLE
Issue, create type of menu item, not working in J3 v2.5.9

### ISSUE THREAD

**Issue by RedesMexico** [templaza/astroid-framework#39]
Yes working in J3 v2.5.8

**Comment by RedesMexico** [comment]
Yes working in J3 v2.5.8

**Comment by sonvnn** [comment]
Hi @RedesMexico 
I fixed it at https://github.com/templaza/astroid-framework/commit/670db1fdac19417b46c522119f716a111e0e407b
Please help me download developer branch to test it.

Thanks & Best Regards,
Sonny

**Comment by RedesMexico** [comment]
Hello @Sonny
We have tested it with the 670db1f array
AND NOW IT IS RUNNING CORRECTLY. Congratulations and thank you very much for your work.
While I tell you that we continue to translate the dictionaries into Spanish, as soon as we finish we will send them to your email.

Greetings,
Networks Mexico
