### ISSUE TITLE
Hamburger item overlaps with Logo on mid-sized screens

### ISSUE THREAD

**Issue by ozwest** [templaza/astroid-framework#390]
Hello, I noticed a problem with the responsive design, mid-sized screens. Here is the website in question: [https://family-historian.com](url)

The screen seems to overlap ((see screenshot)
<img width="750" alt="Screenshot 2023-09-13 at 1 29 38 pm" src="https://github.com/templaza/astroid-framework/assets/1160390/715ac967-02f3-4107-9465-2a984b27061a">

I notice that in the smaller screens and the desktop screens the text underneath the menu lines up to the left where in this mid-sized screen it is different.
<img width="446" alt="Screenshot 2023-09-13 at 1 30 46 pm" src="https://github.com/templaza/astroid-framework/assets/1160390/707e77d9-ab77-4c1d-a9cf-418b0e8570bb">

Thank you.

**Comment by Joomlaplates** [comment]
Hello, please add the css code below to your custom.css 
https://docs.astroidframe.work/custom-code/custom-css

```
.astroid-logo img {
  max-width: 100% !important;
}
```

**Comment by ozwest** [comment]
Thank you

Kind regards,

Petra Webstein

From: Joomlaplates ***@***.***>
Date: Wednesday, 20 September 2023 at 6:22 pm
To: templaza/astroid-framework ***@***.***>
Cc: Petra Webstein ***@***.***>, Author ***@***.***>
Subject: Re: [templaza/astroid-framework] Hamburger item overlaps with Logo on mid-sized screens (Issue #390)

Hello, please add the css code below to your custom.css
https://docs.astroidframe.work/custom-code/custom-css

.astroid-logo img {

  max-width: 100% !important;

}
