### ISSUE TITLE
Header styling limitations

### ISSUE THREAD

**Issue by Giorgi625** [templaza/astroid-framework#395]
So I am trying to get header look like this https://mountis.codelayers.net
Two lines , top line modules on the sides and middle logo, line below menu. 
Luckily There is option to set this design in Astroid header settings, but if Section Layout is set to Container then this lines are not full width so I can not get this while line style full width, but if I set it to Container Fluid then it gets full width but it also throws top modules to the very end corners on both sides, as you see it here https://gmg.joomla.ge/index.php
Of course I can align them via custom css, but I think it will be cool to be able to set layout of this lines so that it will not require extra coding.
So that whole header is full width, but its parts are inside container of limited width. To be able to manipulate its background comfortably.

**Comment by Chacapamac** [comment]
I see what you want, I don’t think it is possible without using css as both left and right modules, and logo are all in the “Header” position.

For fun, I just try on the “mod-custom125” (on the right)
position: absolute;
right: 10%;
text-align: center;
padding-top: 50px;

and 
“mod-custom124”  (on the left)
position: absolute;
left: 10%;
text-align: center;
padding-top: 50px;

You will have also to lower the site-wide “p” margin-bottom: 1rem; to make it look like your example
#mod-custom125 p, #mod-custom124 p { margin-bottom: .1rem; }

**Comment by Chacapamac** [comment]
Can I close this discussion?
