### ISSUE TITLE
Astroid 3.0.0 big problem with google fonts

### ISSUE THREAD

**Issue by WM-Loose** [templaza/astroid-framework#398]
Hi Sonny,

the headings for the fonts are missing in the typography. It no longer shows whether it is system, custom or google fonts. That's not possible and is a **huge problem**, at least in Europe. Please fix it as soon as possible. We have to see what google fonts are.

**Comment by WM-Loose** [comment]
One more:
The graphical representation of the font and font size is also not always displayed under the input fields.

**Comment by WM-Loose** [comment]
bevore Astroid 2
![vorher](https://github.com/templaza/astroid-framework/assets/99647423/56f9ecf8-d803-413c-b0f7-77750f955303)

after Astroid 3
![nachher](https://github.com/templaza/astroid-framework/assets/99647423/d9ac9528-f817-4fa3-a567-ea352da2ff09)

**Comment by deltapapa01** [comment]
Hi Dirk, I know what you mean. I had already reported this somewhere here when testing, but this has gone a bit under.
You write that it is a big problem, but in the frontend everything is displayed okay, right? So purely from the implementation of the GDPR.
But I am also of your opinion that the representation in the combo box should be divided and displayed a little better.

**Comment by WM-Loose** [comment]
The fonts will not be changed after the update and will also be loaded locally as previously set. That's not what it is about. The point is that if you want to change the font, you can no longer find a heading in the template options. The division into custom fonts and google fonts is missing. If a user accidentally selects a Google font, this is not permitted by the GDPR in Europe and can have dire consequences for the website owner. Until this is resolved by Sonny, we cannot update to Astroid 3.

The visual display of the selected font is also completely missing. These 2 essential things must work, otherwise the framework is not really usable.

**Comment by sonvnn** [comment]
@WM-Loose @deltapapa01 
I fixed this issue in https://github.com/templaza/astroid-framework/pull/407/commits/232edae4e0556f7397b4ef387ad6d73cebd5c148
Please help me download v3 branch and re-test again.

The screen will look like this
![Screen Shot 2023-10-18 at 16 32 22](https://github.com/templaza/astroid-framework/assets/3204103/5cd9a392-4d4e-4377-8788-32fa008c92b9)

PS: @WM-Loose  I created a topic since September 8th, 2023 here #388 . I am happy if you can join us for testing Astroid before new version release in the future. It will help us avoid issues like that arise when the latest version is released

Thanks & Best Regards,
Sonny

**Comment by WM-Loose** [comment]
This looks very good. When can you deploy this in version 3.0.2?

**Comment by Joomlaplates** [comment]
Hi all, its working now with local fonts in Astroid 3.0.1

**Comment by deltapapa01** [comment]
Hi @sonvnn , i test v3 branch 10/18/23, but the combo box is not there:

![image](https://github.com/templaza/astroid-framework/assets/19833064/5d227b52-a38d-4119-a90e-4383458538a1)

**Comment by sonvnn** [comment]
Please clear cache browser. @deltapapa01

**Comment by sonvnn** [comment]
@deltapapa01 Please update Joomla 4.4. Then the error will disappear. This issue is available for Joomla 4.3

**Comment by WM-Loose** [comment]
Hi Sonny,
the distribution of fonts for selection is now really great. The view of the fonts under the fields is still missing in Astroid 3.0.2. Can you already say when you can show this again?

![preview](https://github.com/templaza/astroid-framework/assets/99647423/b6eb0b32-c66e-4bcb-ac58-ddf2a1c43dfd)
