### ISSUE TITLE
Pagination Buttons in mobile run out of screen

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#4]
You have to change the file
media/astroid/assets/vendor/bootstrap/scss/_pagination.scss
**Before:**
```
.pagination {
  display: flex;
  @include list-unstyled();
  @include border-radius();
}
```
**After**
```
.pagination {
  display: flex;
  @include list-unstyled();
  @include border-radius();
  flex-wrap: wrap;
}

```

**Comment by sonvnn** [comment]
Thank you. I added float-wrap at #7
Please help me update Astroid v2.5.6 and re-check your site.

Best Regards,
Sonny

**Comment by Joomlaplates** [comment]
Hi Sonny,
wow youre fast.. Even better than Joomdev.
I really appriciate this, perfect.
Many thanks, best regards Peter
