### ISSUE TITLE
Padding issue with stack eperator header

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#40]
Astroid 2.5.9 / Template One
---
All Header Settings are padding "0" and without container but there is still a padding. And this is only happend with "stacked seperator)

![stacked_11](https://user-images.githubusercontent.com/71080509/142942803-6057b534-1520-47f5-ab21-4c6cf06090a6.png)
![stacked](https://user-images.githubusercontent.com/71080509/142942812-4a3810c9-5b72-469a-81b9-7d66a271f296.png)

**Comment by sonvnn** [comment]
Yes, It's Astroid default style. It was placed in inside of Astroid Header, so you can not edit via Design Settings. But you can use template scss to override it.

**Comment by Joomlaplates** [comment]
Hi Sonny, thanks!
