### ISSUE TITLE
Astroid 3.0 left column above main content

### ISSUE THREAD

**Issue by fontanil** [templaza/astroid-framework#400]
Hi, 
I just updated Astroid and JCal Pro on a test site, and the modules set to left position are displayed above the main content. The template is Astroid One
The layout semms to be the same as it was with 2.6.5 version. What can I do? Thanks!
![Capture d’écran 2023-10-17 154808](https://github.com/templaza/astroid-framework/assets/8665970/7cf9351b-0e4d-41fe-84a7-d80a75609859)

Ifound!!! I needed to save the layout and refresh the cache and page! :)

**Comment by deltapapa01** [comment]
Hi, you mean that the layout in the frontend displays the left section above the content?
Please clear Joomla cache, Joomla page cache and Astroid cache as well as browser cache (possibly also the history, some browsers are very stubborn).
Then please try to save your current style in the Joomla backend once in the Astroid backend.

**Comment by fontanil** [comment]
Thanks for you reply.
That's I did.

I just updated another website and needed to do the same manipulations: emptying caches, saving the layout to retrieve the previous display

**Comment by deltapapa01** [comment]
@fontanil but that solved your problem?

**Comment by fontanil** [comment]
Yes!

**Comment by deltapapa01** [comment]
Glad to hear it. So it helps to clear the cache and save the style once again. I pass on so :-)
