### ISSUE TITLE
Astroid 3.0 broke all my J3 website !

### ISSUE THREAD

**Issue by yao89** [templaza/astroid-framework#401]
Hi,
Did you test your last update on Joomla 3.x version ?!

This one broke all my J3 website and will ask me lot of time to restore backups et block the update until I can migrate them to J4...

**Comment by Joomlaplates** [comment]
Hello, please more deatils! 
- PHP Version
- Joomla Version
- Template?

**Comment by sonvnn** [comment]
I fixed this issue in #403 Please help me check it.
