### ISSUE TITLE
Error: 0 Database not Set with Joomla 4.4

### ISSUE THREAD

**Issue by deltapapa01** [templaza/astroid-framework#402]
Hi,
i update my LiveSite to Joomla 4.4. with Astroid V3, PHP 8.2.8 and MySQL 8.0.32. After Update i get the follow error in frontend:

`
ERROR 0 - Database not set in Joomla\Module\RelatedItems\Site\Helper\RelatedItemsHelper in /html/petersen-webdesign/libraries/vendor/joomla/database/src/DatabaseAwareTrait.php:43

Call stack
--
# | Function | Location
1 | () | JROOT/libraries/vendor/joomla/database/src/DatabaseAwareTrait.php:43
2 | Joomla\Module\RelatedItems\Site\Helper\RelatedItemsHelper->getDatabase() | JROOT/modules/mod_related_items/src/Helper/RelatedItemsHelper.php:51
3 | Joomla\Module\RelatedItems\Site\Helper\RelatedItemsHelper->getRelatedArticles() | JROOT/modules/mod_related_items/src/Helper/RelatedItemsHelper.php:200
4 | Joomla\Module\RelatedItems\Site\Helper\RelatedItemsHelper::getList() | JROOT/libraries/astroid/framework/article.php:270
5 | AstroidFrameworkArticle->renderRelatedPosts() | JROOT/templates/astroid_template_zero/html/com_content/article/default.php:214
6 | include() | JROOT/libraries/src/MVC/View/HtmlView.php:415
7 | Joomla\CMS\MVC\View\HtmlView->loadTemplate() | JROOT/libraries/src/MVC/View/HtmlView.php:203
8 | Joomla\CMS\MVC\View\HtmlView->display() | JROOT/components/com_content/src/View/Article/HtmlView.php:244
9 | Joomla\Component\Content\Site\View\Article\HtmlView->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:660
10 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT/components/com_content/src/Controller/DisplayController.php:121
11 | Joomla\Component\Content\Site\Controller\DisplayController->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:693
12 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:143
13 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/components/com_content/src/Dispatcher/Dispatcher.php:56
14 | Joomla\Component\Content\Site\Dispatcher\Dispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
15 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/SiteApplication.php:208
16 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT/libraries/src/Application/SiteApplication.php:249
17 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:293
18 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:61
19 | require_once() | JROOT/index.php:32

`

on my tests before i have no prob, i thing we have the error in V3Beta, or?
In Moment i switch to core template, did you @sonvnn an idea?

**Comment by sonvnn** [comment]
Hi,

May you send me your admin acc via sonlv@templaza.com ? I will check and give you a quick fix for this issue.

Otherwise, you can update to Joomla 5. Astroid 3 works well with Joomla 5

**Comment by sonvnn** [comment]
I fixed it in https://github.com/templaza/astroid-framework/commit/ceb2499deeee91631252dffd1844bae6504506fc
You can download v3 branch to fix it or wait to v3.0.1.

Thanks & Best Regards
Sonny
