### ISSUE TITLE
Astroid 3 broke joomla 3 frontend 

### ISSUE THREAD

**Issue by amber7212** [templaza/astroid-framework#403]
My site is broken after migration from Astroid 2.6.6 to Astroid 3

Message in frontend:
Oops!! Page not found.
It seems like the page that you are looking for is no longer here.

Debug Message:
ERROR 0 - Class "Joomla\Module\Menu\Site\Helper\MenuHelper" not found in /home/lightor/www/libraries/astroid/framework/library/astroid/Component/Menu.php:583 

Call stack
--
# | Function | Location
1 | () | JROOT/libraries/astroid/framework/library/astroid/Component/Menu.php:583
2 | Astroid\Component\Menu::getMobileMenu() | JROOT/libraries/astroid/framework/frontend/mobilemenu.php:45
3 | include() | JROOT/libraries/src/Layout/FileLayout.php:125
4 | Joomla\CMS\Layout\FileLayout->render() | JROOT/libraries/astroid/framework/library/astroid/Document.php:84
5 | Astroid\Document->include() | JROOT/libraries/astroid/framework/frontend/document/body.php:51
6 | include() | JROOT/libraries/src/Layout/FileLayout.php:125
7 | Joomla\CMS\Layout\FileLayout->render() | JROOT/libraries/astroid/framework/library/astroid/Document.php:84
8 | Astroid\Document->include() | JROOT/templates/astroid_template_zero/index.php:33
9 | require() | JROOT/libraries/src/Document/HtmlDocument.php:678
10 | Joomla\CMS\Document\HtmlDocument->_loadTemplate() | JROOT/libraries/src/Document/HtmlDocument.php:740
11 | Joomla\CMS\Document\HtmlDocument->_fetchTemplate() | JROOT/libraries/src/Document/HtmlDocument.php:555
12 | Joomla\CMS\Document\HtmlDocument->parse() | JROOT/libraries/src/Application/CMSApplication.php:1098
13 | Joomla\CMS\Application\CMSApplication->render() | JROOT/libraries/src/Application/SiteApplication.php:778
14 | Joomla\CMS\Application\SiteApplication->render() | JROOT/libraries/src/Application/CMSApplication.php:231
15 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/index.php:49

Environment
php 8.2
Joomla 3.10

**Comment by sonvnn** [comment]
Thank you! May you send me your admin via sonlv@templaza.com? I will help you check it. 

PS: Joomla 3 is end of life. Please have plan to update to Joomla 4 asap.

**Comment by amber7212** [comment]
Hi,

Sorry , what do you want me to send you ?

**Comment by sonvnn** [comment]
Please send me your admin acc so I can help you check it. Sorry for missing message. I am on mobile

**Comment by amber7212** [comment]
I'm sorry , I cannot share my admin login and password. Though I'm not sure it is what you request..

**Comment by sonvnn** [comment]
It is okay. So please wait for update. I will try to find it on my localhost. But you still need to update to Joomla 4. That is my suggestion. Joomla 3 is unsecure right now

**Comment by sonvnn** [comment]
I fixed this issue in https://github.com/templaza/astroid-framework/commit/9f150e32739636fdb0dafaaefe5f5bbe5a5dd744
Please help me download v3 and retest again.

Thanks & Best Regards,
Sonny
