### ISSUE TITLE
Astroid 2.6.6 and 3.0.0 on joomla 4.4 - issues on internal links

### ISSUE THREAD

**Issue by amber7212** [templaza/astroid-framework#404]
Hi,

It seems that Astroid 2.6.6 and 3.0.0 on joomla 4.4 have issues with internal links management: links on the internal pages won't work as shown below
The issue does not appear with Cassiopeia (links will work)

Error message:
It seems like the page that you are looking for is no longer here.

Debug Message:
ERROR 0 - Database not set in Joomla\Module\RelatedItems\Site\Helper\RelatedItemsHelper in /home/XXX/www/libraries/vendor/joomla/database/src/DatabaseAwareTrait.php:43
             
Call stack
--
# | Function | Location
1 | () | JROOT/libraries/vendor/joomla/database/src/DatabaseAwareTrait.php:43
2 | Joomla\Module\RelatedItems\Site\Helper\RelatedItemsHelper->getDatabase() | JROOT/modules/mod_related_items/src/Helper/RelatedItemsHelper.php:51
3 | Joomla\Module\RelatedItems\Site\Helper\RelatedItemsHelper->getRelatedArticles() | JROOT/modules/mod_related_items/src/Helper/RelatedItemsHelper.php:200
4 | Joomla\Module\RelatedItems\Site\Helper\RelatedItemsHelper::getList() | JROOT/libraries/astroid/framework/article.php:270
5 | AstroidFrameworkArticle->renderRelatedPosts() | JROOT/templates/astroid_template_zero/html/com_content/article/default.php:214
6 | include() | JROOT/libraries/src/MVC/View/HtmlView.php:415
7 | Joomla\CMS\MVC\View\HtmlView->loadTemplate() | JROOT/libraries/src/MVC/View/HtmlView.php:203
8 | Joomla\CMS\MVC\View\HtmlView->display() | JROOT/components/com_content/src/View/Article/HtmlView.php:244
9 | Joomla\Component\Content\Site\View\Article\HtmlView->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:660
10 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT/components/com_content/src/Controller/DisplayController.php:121
11 | Joomla\Component\Content\Site\Controller\DisplayController->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:693
12 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:143
13 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/components/com_content/src/Dispatcher/Dispatcher.php:56
14 | Joomla\Component\Content\Site\Dispatcher\Dispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
15 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/SiteApplication.php:208
16 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT/libraries/src/Application/SiteApplication.php:249
17 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:293
18 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:61
19 | require_once() | JROOT/index.php:32

Environment
php 8.2
joomla 4.4
Astroid 2.6.6 or 3.0.0

**Comment by sonvnn** [comment]
I fixed it in #402 Please check it.

**Comment by amber7212** [comment]
Hi Sonny,

Thanks for this fix. It works !

**Comment by amber7212** [comment]
For information, this has been checked under joomla 4.4 , not under joomla 3.x
