### ISSUE TITLE
Warning : foreach() argument must be of type array|object, string given in 

### ISSUE THREAD

**Issue by RoyGlashorster** [templaza/astroid-framework#406]
**Hello, I'm just a simple Joomla/Astroid user. After updating to Joomla 4.4 I get some warnings on top of my website:**

Warning
: foreach() argument must be of type array|object, string given in
/var/www/vhosts/mysite/httpdocs/libraries/astroid/framework/library/astroid/Element/Row.php
on line
52
Warning
: foreach() argument must be of type array|object, string given in
/var/www/vhosts/mysite/httpdocs/libraries/astroid/framework/library/astroid/Element/Row.php
on line
58
Warning
: foreach() argument must be of type array|object, string given in
/var/www/vhosts/mysite/httpdocs/libraries/astroid/framework/library/astroid/Element/Row.php
on line
52
Warning
: foreach() argument must be of type array|object, string given in
/var/www/vhosts/mysite/httpdocs/libraries/astroid/framework/library/astroid/Element/Row.php
on line
99

**Can anybody help please?**

**Comment by sonvnn** [comment]
Let's try to go to template options edit layout and save again. Go to front end and show me your result.

**Comment by RoyGlashorster** [comment]
wow, amazing! how did you know 😃? saved template options and all warnings are gone. Thank you very much.

**Comment by sonvnn** [comment]
Your data is Astroid 2. So in some case you need refresh it for new system like Astroid 3. That is reason.
