### ISSUE TITLE
Custom Code Section infinity loading

### ISSUE THREAD

**Issue by Kiter1988** [templaza/astroid-framework#410]
Hello,
I updated my asteroid framework to 3.0.2 today and noticed that in the custom css section all options load endlessly, see picture. 

![grafik](https://github.com/templaza/astroid-framework/assets/23479196/21f05546-ff6a-4a57-8828-4137e3739719)

**Comment by sonvnn** [comment]
It look like you have a problem when system is trying to connect to CDN of Monaco script. Please help me refresh again and give me the result.

**Comment by Kiter1988** [comment]
Hello, 
after you wrote that it is about CDN, I took a look in my pihole. 
My pihole has blocked the domain. 
Sorry that was my own mistake. Now its works well

I have one more question, why is the editor loaded externally and not locally ?

**Comment by sonvnn** [comment]
It will reduce size of javascript file. It will help your system load faster by loading via CDN. Please check https://www.cloudflare.com/learning/cdn/what-is-a-cdn/ to understand what is CDN.
