### ISSUE TITLE
HTTP 500 Error by using php 8.1 Astroid 2.6, 3.0, 3.1 with Joomla 4.3.4 and Joomlaplates Template Medical

### ISSUE THREAD

**Issue by 2fix4u** [templaza/astroid-framework#413]
Hi there,

i was hoping that this error has been solved with the new astroid version 3.1 but no luck.
Since we've switched to php 8.1 we've got this error, only with php 7.4 the site works as expected.

Joomlaplates say several month ago, that this is an error of the native Joomla cache, but we didn't use it.

This is the StackTrace:
ValueError: 'Path cannot be empty' thrown in /... ... .../libraries/astroid/framework/library/FontLib/BinaryStream.php on line 110
Stacktrace

#0 /... ... .../libraries/astroid/framework/library/FontLib/BinaryStream.php(110): fopen()
#1 /... ... .../libraries/astroid/framework/library/FontLib/WOFF/File.php(36): FontLib\BinaryStream::getTempFile()
#2 /... ... .../libraries/astroid/framework/library/FontLib/Font.php(67): FontLib\WOFF\File->load()
#3 /... ... .../libraries/astroid/framework/library/astroid/Helper/Font.php(154): FontLib\Font::load()
#4 /... ... .../libraries/astroid/framework/library/astroid/Helper/Font.php(137): Astroid\Helper\Font::getLocalFonts()
#5 /... ... .../libraries/astroid/framework/library/astroid/Template.php(312): Astroid\Helper\Font::getUploadedFonts()
#6 /... ... .../libraries/astroid/framework/library/astroid/Helper/Font.php(275): Astroid\Template->getFonts()
#7 /... ... .../libraries/astroid/framework/library/astroid/Helper/Font.php(226): Astroid\Helper\Font::loadLocalFont()
#8 /... ... .../libraries/astroid/framework/library/astroid/Helper/Style.php(297): Astroid\Helper\Font::getFontFamily()
#9 /... ... .../libraries/astroid/framework/library/astroid/Helper/Style.php(285): Astroid\Helper\Style::getFontFamilyValue()
#10 /... ... .../libraries/astroid/framework/library/astroid/Component/Utility.php(200): Astroid\Helper\Style::renderTypography()
#11 /... ... .../libraries/astroid/framework/library/astroid/Site.php(24): Astroid\Component\Utility::typography()
#12 /... ... .../plugins/system/astroid/astroid.php(65): Astroid\Site->onAfterRender()
#13 /... ... .../libraries/src/Plugin/CMSPlugin.php(284): plgSystemAstroid->onAfterRender()
#14 /... ... .../libraries/vendor/joomla/event/src/Dispatcher.php(486): Joomla\CMS\Plugin\CMSPlugin->Joomla\CMS\Plugin\{closure}()
#15 /... ... .../libraries/src/Application/EventAware.php(111): Joomla\Event\Dispatcher->dispatch()
#16 /... ... .../libraries/src/Application/CMSApplication.php(1031): Joomla\CMS\Application\WebApplication->triggerEvent()
#17 /... ... .../libraries/src/Application/SiteApplication.php(724): Joomla\CMS\Application\CMSApplication->render()
#18 /... ... .../libraries/src/Application/CMSApplication.php(298): Joomla\CMS\Application\SiteApplication->render()
#19 /... ... .../includes/app.php(61): Joomla\CMS\Application\CMSApplication->execute()
#20 /... ... .../index.php(32): require_once('/homepages/10/d...')
#21 {main}

**Comment by Joomlaplates** [comment]
Hello, only ttf fonts are supported.
Do you have any other fonts installed?

**Comment by Chacapamac** [comment]
Woff fonts are the modern way togo. I have no problem with custom woff fonts.

**Comment by 2fix4u** [comment]
Hi,

did you mean in .../media/templates/site/tp_medical/fonts/ ?

I've had a look there and found several other font types like woff and otf.
I've deleted them and switched back to PHP 8.1. Now I'll take a look if it helps.

**Comment by Chacapamac** [comment]
woff is the best. modern and efficient way to implement fonts. Astroid NEED to be able to work with woff.
I will check and come back.

**Comment by 2fix4u** [comment]
@Chacapamac 

thank you for sorting that out.

**Comment by Chacapamac** [comment]
> @Chacapamac
> 
> thank you for sorting that out.

Did you fix your error?

**Comment by 2fix4u** [comment]
Hi @Chacapamac, for the moment everything is fine, but the problem is that the error occurs sporadically, so I've to see if it happens again. I'll come back to you and will report.

**Comment by Chacapamac** [comment]
Good Day @2fix4u
