### ISSUE TITLE
Page not found on all articles

### ISSUE THREAD

**Issue by derbli** [templaza/astroid-framework#414]
I've updated Astroi to v3.0.2 and all my articles return "page not found".

**Comment by fontanil** [comment]
Hi,

Joomla 4.3.4 or 4.4.0, Astroid Framework 3.0.1 or 3.0.2, Astroid One template 

I get an error "ERROR 0 - Call to a member function getRelatedArticles() on null" when I try to display an article.

JROOT\libraries\astroid\framework\article.php:266 

The list of articles and the blog are well displayed, only individual articles are concerned.

**Comment by fontanil** [comment]
Hi,

The site works fine now (Joomla! 5.0.0 PHP 8.2 Astroid Framework 3.0.2 Astroid One 3.0.0)
Thank to the author!

**Comment by deltapapa01** [comment]
Hi
have the same, seems like this only occurs with Joomla 4.3.4

**Comment by fontanil** [comment]
Hi,

The problem occured for me when related articles was activated in the template style and no related articles where set to the articles.

**Comment by deltapapa01** [comment]
is there error still there with J4.4 or 5.0?

**Comment by fontanil** [comment]
I just tried. I activated the "related article" settings and it seems there are no more errors.
You can test here https://bernard-lanza.par-robertg.fr

**Comment by sonvnn** [comment]
@deltapapa01 Error will display on Joomla 4.3. Please update to J4.4 or J5.0 to remove error.

**Comment by rafaelscnunes** [comment]
Thanks! It is now working...
I've followed Joomla's admin site instructions and updated all plugins, then updated Joomla to version 4.4.0.
