### ISSUE TITLE
CSS Editor in Astroid v3.0.2

### ISSUE THREAD

**Issue by jonasfhr** [templaza/astroid-framework#415]
Why is the costume CSS editor in the new v3.0.2 in a small box and I can't popup this field and couldn't enlarge the box like in the earlier versions? Now it's very difficult to code same CSS lines here.

Thanks for an solution or hint.
JR

**Comment by deltapapa01** [comment]
Hi, what did you mean with costume CSS editor? Is this a special editor? With JCE no Problems. And did you have the issue in frontend or backend?

**Comment by BlackBrix** [comment]
I Thing JR means
astroid backend -> Custom Code -> Custom CSS
see attachment
![custom css](https://github.com/templaza/astroid-framework/assets/9103352/075a2530-a74f-4180-ad3b-20043ecad43f)

**Comment by jonasfhr** [comment]
Yes, that is it like the screenshot from BlackBrix. In the older version was possible to enlarge the Custom CSS field. Why not in the current version?
The only solution is copy the CSS and create a css file and include this in the CSS files field (this is ready to enlarge). And then its possible to work with it on the template data site of the backend.
I don't understand the developers to change a running system to a worse version.

If somebody have a better idea I would be happy

**Comment by Chacapamac** [comment]
Yeah that was cool to enlarge manually, but I can see that you can easily navigate the code. Both possibility will be great.

![image](https://github.com/templaza/astroid-framework/assets/1907276/389137c5-4435-4a80-b7be-0f620c830353)

**Comment by jonasfhr** [comment]
Yes right, but the navigation is very difficult without an overview of the code:

![Bildschirmfoto 2023-10-22 um 15 28 50](https://github.com/templaza/astroid-framework/assets/148556626/2eb4ead6-a348-4b03-b0ae-488e77d2566f)

**Comment by sonvnn** [comment]
@jonasfhr @BlackBrix @Chacapamac 
I add Edit in Fullscreen in https://github.com/templaza/astroid-framework/pull/424/commits/4bc4a84c7dae797b3a708113d91ccaa5efe45056

You can download v3 Branch and test on your site. 

The screen will look like below:
![Screen Shot 2023-10-25 at 11 07 33](https://github.com/templaza/astroid-framework/assets/3204103/f85336bf-92d0-4905-8df1-241eb7ac724a)

Hope you like it ;)

**Comment by jonasfhr** [comment]
Thanks a lot!
