### ISSUE TITLE
Import/Export not presentin  Astroid 3.0.2

### ISSUE THREAD

**Issue by folmer23** [templaza/astroid-framework#417]
Hi,
I just installed Astroid 3.0.2 (latest)
But at the Bottom o
![no-export-import](https://github.com/templaza/astroid-framework/assets/120024807/090a9282-46dc-4bc4-a47a-11bd6ce6e645)
In the Menu there is **No Export/Import option**. as in 2.6.6.
We need this option badly.
(or is it placed elsewhere)
For now, we have downgraded Astroid to 2.6.6.
Look forward to here someting.
Regards,
Milian

**Comment by BlackBrix** [comment]
the functions are still there:

Import: go to "Preset Profiles" -> "Save/Import" -> "Import Preset" -> Upload a file 
(your uploaded file will become a new preset with a name of your choice)

Export: go to "Preset Profiles" ->move the mouse over the preset you want to export -> an export/download icon appears -> click on this icon and download and save your settings

**Comment by folmer23** [comment]
Thanks BlackBrix!
 For your answer and fast response!
Aha a little hidden so,
Regards,
Milian
