### ISSUE TITLE
Astroid Menu Options negative margin

### ISSUE THREAD

**Issue by biobill** [templaza/astroid-framework#42]
Hey all!

This post is about a problem with the negative margin in the #astroid-menu-options in astroid-menu-options.css
`#astroid-menu-options {
    margin-left: -180px;
}`
Just check the image below to see how it looks like.

Joomla Version: 4.0.4
Astroid Version: 2.5.10
Template (one) Version: 1.3.4

![menuoptions](https://user-images.githubusercontent.com/16140656/143268666-b00cce04-4aff-4b4f-8d6e-76e2ee7e7c8b.jpeg)

**Comment by kkaazzoo** [comment]
Hi, @biobill , I do not confirm the problem

![image](https://user-images.githubusercontent.com/19167244/143295709-e19421e9-3641-49e9-8d58-e8dd9094c1c5.png)

**Comment by biobill** [comment]
Hey @kkaazzoo!
Have you checked if there is the margin-left:-180px declaration in your css?
Also, what astroid version have you installed?

**Comment by kkaazzoo** [comment]
@biobill i checked
![2021-11-25_112355](https://user-images.githubusercontent.com/19167244/143405618-c5d0ba98-4dae-4199-bdf3-eb02e966c855.jpg)

![image](https://user-images.githubusercontent.com/19167244/143405779-5a0d738f-139a-4d40-a542-55b247574441.png)

**Comment by djayko** [comment]
hello,
I can confirm this error. In the meantime I have this error also at three installations.
It also occured on my clean installation.

At the moment, I guess that I do something within the template_zero administration which is forcing this margin.
But I can't reproduce it. First everything is ok and after setting colors, logos, typography....whatever it changed from expected behaviour to margin-left: -180px

Some thougts:
- I also see that there is the declaration from a menu.scss (SCSS!) file, but i didn't find this file anywhere
- this margin-left definition occurs /media/astroid/assets/css/astroid-menu-options.css?v=c896a1577c58118b845c7015f8e2b430 -> my guess this file will be generated via scss, right?
- menu.scss was found in 
\astroid\astroid-framework\assets\json\hash.json
and
\astroid\astroid-framework\assets\css\astroid-menu-options.css.map

- I only found the declaration of margin-left: -180px within the https://raw.githubusercontent.com/templaza/astroid-framework/master/assets/css/astroid-menu-options.css

My guess:
Maybe there it depends somehow with scss and css??? But as I said. First everything was ok and after some time it occured (like accidently.)

Maybe this information is helpful in anyway for the developers.

best,
Frank

**Comment by biobill** [comment]
@kkaazzoo may I ask, how comes you have template version 2.5.8?
Are the templates updated?

**Comment by djayko** [comment]
> @kkaazzoo may I ask, how comes you have template version 2.5.8? Are the templates updated?

Mayb this is another issue. The template version  (zero) on my site didn't change on joomla extension update of astroid. After download of template package here and upload to joomla, the version-number changed from 2.5.8 to 2.5.9 on my site.

**Comment by sonvnn** [comment]
Hi @biobill ,

Thanks for report issue. I saw you have Dashboard Admin Bar. What is extension's name? As I know Joomla 4 default has not this toolbar. It might affect to Joomla Admin style.

![143268666-b00cce04-4aff-4b4f-8d6e-76e2ee7e7c8b](https://user-images.githubusercontent.com/3204103/143412604-d8d02abb-a565-406f-b31c-24806b085b26.png)

Best Regards,
Sonny

**Comment by biobill** [comment]
> Hi @biobill ,
> 
> Thanks for report issue. I saw you have Dashboard Admin Bar. What is extension's name? As I know Joomla 4 default has not this toolbar. It might affect to Joomla Admin style.
> 
> ![143268666-b00cce04-4aff-4b4f-8d6e-76e2ee7e7c8b](https://user-images.githubusercontent.com/3204103/143412604-d8d02abb-a565-406f-b31c-24806b085b26.png)
> 
> Best Regards, Sonny

Hi @sonvnn 
It's this one [https://extensions.joomla.org/extension/phoca-top-menu/](url)
It's not a conflict with the top bar. I've already checked this.

**Comment by kkaazzoo** [comment]
> @kkaazzoo may I ask, how comes you have template version 2.5.8? Are the templates updated?

@biobill I have updated the template to the latest version, I updated the template to the latest version, I don't see a problem

![image](https://user-images.githubusercontent.com/19167244/143413241-8046a179-0f0d-4f2f-96af-2d9ca62933c7.png)

![2021-11-25_121522](https://user-images.githubusercontent.com/19167244/143413551-15c020db-c5af-443c-83aa-e9e50482e43d.jpg)

**Comment by biobill** [comment]
> > @kkaazzoo may I ask, how comes you have template version 2.5.8? Are the templates updated?
> 
> Mayb this is another issue. The template version (zero) on my site didn't change during joomla extension update of astroid. After download of template package here and upload to joomla, the version-number changed from 2.5.8 to 2.5.9 on my site.

I'm updating through Joomla update process and my template is still in 1.3.4 version.

**Comment by djayko** [comment]
> Hi @biobill ,
> 
> Thanks for report issue. I saw you have Dashboard Admin Bar. What is extension's name? As I know Joomla 4 default has not this toolbar. It might affect to Joomla Admin style.
> 
> ![143268666-b00cce04-4aff-4b4f-8d6e-76e2ee7e7c8b](https://user-images.githubusercontent.com/3204103/143412604-d8d02abb-a565-406f-b31c-24806b085b26.png)
> 
> Best Regards, Sonny

I don't use that toolbar and have the same issue.
I'll try the following now:
- clean j4 installation
- installtion of latest stable astroid framework with templates one and zero
- testing menu-settings
- export my current template-settings with astroid export function
- import my template settings with astroid import function.
- checking menu options

best,
Frank

**Comment by sonvnn** [comment]
Hi @djayko,

May you send me your admin account via sonlv@templaza.com? I will check it on your site, because it works well on my demo.

Best Regards,
Sonny

**Comment by djayko** [comment]
> Hi @djayko,
> 
> May you send me your admin account via [sonlv@templaza.com](mailto:sonlv@templaza.com)? I will check it on your site, because it works well on my demo.
> 
> Best Regards, Sonny
not necessary anymore from my side.

I installed everything as described above. And everything was fine.
After that i configured all from scratch. Everything still fine.
After this I installed my needed modules, components. and checked it after every installation
And I figured out that the Regular labs cache cleaner is the problem. I don't know exactly why, but after deactivation, everything was ok.

More specific:
![image](https://user-images.githubusercontent.com/3375044/143430136-60bb2dfd-73ab-4dd8-92bd-442c6e5b0574.png)
It happens when this plugin is active. I try to figure out more details and will report. Maybe its an issue of the cache cleaner plugin.

@kkaazzoo Do you use regular labs cache cleaner?

**Comment by djayko** [comment]
I figured out that the source code differs regarding "<div class="control-label"></div>"
Some of this labels are removed if Regular Labs Cache Plugin is active.

This missing Labels are causing the error.


the correct one:
`</joomla-tab-element><joomla-tab-element id="attrib-astroidmenu" name="&lt;span&gt;&lt;span style='background: linear-gradient(90deg, #3F2B96 0%, #A8C0FF 100%); display: inline-block; width: 10px; height: 10px; border-radius: 10px;'&gt;&lt;/span&gt; Astroid Menu Options&lt;/span&gt;"><fieldset id="fieldset-astroidmenu" class="options-form "><legend><span><span style='background: linear-gradient(90deg, #3F2B96 0%, #A8C0FF 100%); display: inline-block; width: 10px; height: 10px; border-radius: 10px;'></span> Astroid Menu Options</span></legend><div class="form-grid"><div class="control-group">
			<div class="control-label"></div>
		<div class="controls">
		<style>
   #astroid-menu-options .form-control.astroid-module-search::placeholder {
      color: #fff;
   }
</style>`

@sonvnn is astroid doing something in generating or removing labels? I guess your answer is no. ;-)

**Comment by kkaazzoo** [comment]
> @kkaazzoo Do you use regular labs cache cleaner?

@djayko  No, I do not use

**Comment by djayko** [comment]
> > @kkaazzoo Do you use regular labs cache cleaner?
> 
> @djayko No, I do not use

Any other extensions? Did you deactivate extensions or unistall it for to test, when it happens?

**Comment by kkaazzoo** [comment]
> Any other extensions? Did you deactivate extensions or unistall it for to test, when it happens?

Completely clean installation

**Comment by djayko** [comment]
> > Any other extensions? Did you deactivate extensions or unistall it for to test, when it happens?
> 
> Completely clean installation

On my fresh and clean installation, everything is ok no margin-error.
That's weird.... I've no further ideas were it comes from.

**Comment by sonvnn** [comment]
> > > @kkaazzoo may I ask, how comes you have template version 2.5.8? Are the templates updated?
> > 
> > 
> > Mayb this is another issue. The template version (zero) on my site didn't change during joomla extension update of astroid. After download of template package here and upload to joomla, the version-number changed from 2.5.8 to 2.5.9 on my site.
> 
> I'm updating through Joomla update process and my template is still in 1.3.4 version.

Hi @biobill,

Please help me try to disable some 3rd party extension and check it again. If it still happens please send me your admin account via sonlv@templaza.com.

I will help you check it.

Best Regards,
Sonny

**Comment by biobill** [comment]
Hey @sonvnn,

Sorry for the late response. I tried to disable all 3d party extensions, but with no success.
I created an admin account for you in case you want to check it. You'll find the credentials in your inbox.

Thanks in advance
Vassilis

**Comment by sonvnn** [comment]
Hi @biobill ,

Your issue is Astroid conflict with Regular Lab - Library it same with @djayko issue. 
I fixed it on https://github.com/templaza/astroid-framework/commit/9f5569bdfd477eb7fed0e8f6a0e0248c9547e1be

Please help me download developer branch and check it.

Thanks & Best Regards,
Sonny

**Comment by biobill** [comment]
Hi @sonvnn ,

Sorry for the late response. I tested the development branch locally and everything seems to work smoothly.
Thanks for your effort.

Best Regards,
Vassilis
