### ISSUE TITLE
[3.0.2] attempted to load class "Framework" from namespace "Astroid" error 

### ISSUE THREAD

**Issue by FrankReisenhofer** [templaza/astroid-framework#420]
After upgrading to Astroid 3.0.2 I get the following error on my web page www.reisenhofer.de: [1]

[1]
attempted to load class "Framework" from namespace "Astroid"
Did you forget a "use" statement for another namespace?
Exceptions 2Stack Traces 2
Symfony\Component\ErrorHandler\Error\
ClassNotFoundError
in /mnt/web217/e2/85/5210985/htdocs/MainPage/templates/tp_wedding/error.php (line 12)
 * @license https://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 or Later */defined('_JEXEC') or die;if (!defined('_ASTROID')) {   try {      Astroid\Framework::init();   } catch (\Exception $e) {      die('Please install and activate <a href="https://www.astroidframe.work/" target="_blank">Astroid Framework</a> in order to use this template.');   }}
require()

**Comment by FrankReisenhofer** [comment]
I installed the framework via upload and not via update. Doing this i got after he upload an unknown error but the page is now back to normal and the error is currently not appearing

**Comment by Joomlaplates** [comment]
Hi there, yes sometimes the automatically update produce some issues.
I always recommend to install the Astroid Update manually.
Regards Peter
