### ISSUE TITLE
Unable to exclude JS files with Astroid 3.0.2 and minify JS/CSS

### ISSUE THREAD

**Issue by 2fix4u** [templaza/astroid-framework#426]
Hi there,

for GDPR I've added this line of code in the Tracking Code area of custom code:
<script id="Cookiebot" src="https://consent.cookiebot.com/uc.js" data-cbid="ID_OF_COOKIEBOT" type="text/javascript" async></script>

And in the "exclude JS Files" area, I've tried to exclude this JS file with *uc.js and also with the full path, but no luck.
If I enable the minify JS feature, the cookiebot script didn't work.

What am I doing wrong?

Thanks for your help.

**Comment by sonvnn** [comment]
Hello,

I fixed this issue in https://github.com/templaza/astroid-framework/commit/f0c9e12bc136717b97b65c537b5270565cc4ca01

Please help me download v3-branch and test it again https://github.com/templaza/astroid-framework/archive/refs/heads/v3.zip

Thanks & Best Regards,
Sonny
