### ISSUE TITLE
change link color

### ISSUE THREAD

**Issue by SerGun78** [templaza/astroid-framework#429]
Hello. what css selector to use to change link color?
and so that when you hover the underline does not disappear?
![изображение](https://github.com/templaza/astroid-framework/assets/95705148/9d6ba2c6-7f36-4c7b-9adc-8fe2b25548b2)

**Comment by sonvnn** [comment]
The best way is use Color feature. Template Options -> Colors Tab
![Screen Shot 2023-11-02 at 12 14 04](https://github.com/templaza/astroid-framework/assets/3204103/b2d5eab6-2194-4001-b58d-7b481fac62fa)

To custom css let's use Custom Css feature
![Screen Shot 2023-11-02 at 12 16 12](https://github.com/templaza/astroid-framework/assets/3204103/b01d52a8-b957-485d-ae43-b363a1deb108)

**Comment by SerGun78** [comment]
I tried this setting, it doesn't work. since this also changes the color in the header of mail, phones, as well as in bread crumbs and the menu in the sidebar.
I don’t need this, I just need the links in the text (component) to change color and have an underline.

**Comment by SerGun78** [comment]
custome css is not that easy either. so that the styles in the header do not change, I had to write it like this:
p a {
     color: rgba(69, 191, 85);
}
p a:hover{
     text-decoration: underline;
}
