### ISSUE TITLE
500 Library path /libraries/astroid/framework/library/astroid cannot be found after update to 2.5.10

### ISSUE THREAD

**Issue by FrankReisenhofer** [templaza/astroid-framework#43]
Today I updated to Astroid 2.5.10 as an availabe update was shown in Joomla Update.

After this my page is no longer available and also I am failing to launch my webside backend.

The error in the backend is: [1].

Any idea what is causing this?

I am now installing a backup of my side :-(.

[1]
Es ist ein Fehler aufgetreten!
500 Library path /libraries/astroid/framework/library/astroid cannot be found.
 Zurück zum Kontrollzentrum

**Comment by sonvnn** [comment]
Ohhhh! I updated all of my site to 2.5.10 without any problem. I assumed that you have problem when update may be network is not stabled. Did you take a backup?

**Comment by FrankReisenhofer** [comment]
Yes...I have a backup and I am currently resetting my joomla installation

**Comment by FrankReisenhofer** [comment]
But instable network??? I did not face such an issue in the last 8 years

**Comment by sonvnn** [comment]
Please help me update again. If this issue still happen, please help me check your apache error_log and let me know. 500 is an server's issue.

**Comment by FrankReisenhofer** [comment]
The reset of my page is still ongoing. Once it is up and running again I will try again to update to 2.5.10. Will keep you informed

**Comment by sonvnn** [comment]
You're welcome :)

**Comment by FrankReisenhofer** [comment]
Very, very bad news:

As the rollback was still ongoing I tried it on a smaller page.

The same result.

The page is now also completely down.

-> Rollback triggered

**Comment by Joomlaplates** [comment]
Please try to install the Astroid via Joomla extension manager. Here is the donwload zip file
https://github.com/templaza/astroid-framework/archive/refs/heads/master.zip

**Comment by FrankReisenhofer** [comment]
After I used on both sides a backup after some hours both sides were back to normal.

As suggested I installed afterwards version 2.5.10 via the extension manager. Both sides are still working after the upgrade.

That is good news.

How do you suggest to proceed? As I am also a developer I see the problem: From your point of view you need somehow to handle the high number of possible variations on your customer sides.

On the other side the customer (in this case for example me :-)) has the following problem:

When I upgrade in time when you release a new version I have a high risk that my sides are facing issues. After my experiences from last time I thought it is sufficient to wait for some days. But I waited and then on two sides the worst case happened: The backend and the frontend was not longer available after the upgrade.
On the other side: If i wait to long (e.g. some weeks) to perform the upgrade I can guess what will happen :-): You will tell me that lot of sides were already updated successfullly and it will be my problem to show you that the issue was caused by your plugin/template.

Personally I prefer to upgrade in time to report issues as soon as possible.

But that backend + frontend are no longer accessible is the worst case I could imaging for me as a customer.

And in the last 8 years I was never facing such an issue after an upgrade of a plugin / framework used by a template.

So what are your suggestions regarding the upgrade?

Should I always wait for green light from @Joomlaplates before updating the astroid framework :-)

**Comment by FrankReisenhofer** [comment]
Maybe one idea: To avoid the worst-case scenario that neither the Backend nor the frontend is completly not working :

Would it be possible to have one Astroid Backend Plugin and one Astroid Frontend Joomla plugin?

What do you think?

**Comment by Joomlaplates** [comment]
Hello,
like I do:
1.) Make a backup with Akeeba
2.) Download the newest Version of Astroid and all old Versions maybe
3.) Now update the framework. ( Sometimes its needed to update the Template and language file too)
More instructions here
**English**
https://www.joomlaplates.com/forum/important-news-please-read/10277-how-to-update-the-template
**German**
https://www.joomlaplates.de/forum/news-updates-und-informationen/117-astroid-2-5-9-updates-changelog.html

**All Astroid Versions ( 2.5.4, 2.5.9, 2.5.10)**
https://www.joomlaplates.de/login.html

**Comment by sonvnn** [comment]
Hello @FrankReisenhofer ,

I am not sure about your issue. I updated my 25 templates from 2.5.9 to 2.5.10 without any issue (using Joomla update). I will research about it if I get more same issue from others.

Best Regards,
Sonny
