### ISSUE TITLE
Google Analytics 4

### ISSUE THREAD

**Issue by bobmcduk** [templaza/astroid-framework#431]
Hi Guys,

I've set up a website and am trying to get Google Analytics 4 to work on it.

I'm on Joomla 4.4.0, Astroid Framework Version: 3.0.2, and Astroid zero Template Version: 2.6.5.

I put the google code either in the Tracking Code box or I have tried it in the Before /head box and save it. I then clear caches, go to the front end open it up in a web browser, view page source, search for gtag and I can't find the code anywhere. On another site with the same joomla version but a different template the google analytics code works and shows up when I view page source.

Any ideas?

Kind regards

Bob McDonald

**Comment by bobmcduk** [comment]
Hi Guys,

I may have solved this myself, I found that on the website in question I had, in the Astroid Template Zero set Minify CSS JS and HTML to on by switching the off the google gtag appeared in my page source, I have attached this now to Google Analytics and will look over the next couple of days to see if the data flows.

Kind regards

Bob McDonald

**Comment by bobmcduk** [comment]
Hi Guys,

A little more investigation, it appears to be the Minify JS option that gets rid of the Google Analytics code, before minifying JS the page source looks something like this


   <link rel="preconnect" href="https://fonts.gstatic.com">
<script async src="https://www.googletagmanager.com/gtag/js?id=G-xxxxxxxxxx"></script>
<script>
    window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-xxxxxxxxxx');
</script> 

After Minifying JS this is what is left:


   <link rel="preconnect" href="https://fonts.gstatic.com">

 

Kind regards

Bob McDonald

**Comment by Chacapamac** [comment]
@bobmcduk  — Yes, even the best JS / CSS compressor can be finicky to implement.

**Did You enter the code here?**
![Screen Shot 2023-11-04 at 9 22 19 AM](https://github.com/templaza/astroid-framework/assets/1907276/8d52671d-91e4-47a1-b359-b5d77c40f363)

I think that Astroid should be able to leave that important code untouched when using its own JS/CSS compressors.

**Comment by bobmcduk** [comment]
Yes I did put the code in the Tracking Code box and yes I agree with you.

**Comment by Chacapamac** [comment]
@sonvnn can you look at that post?
I think Google tracking code should be whitelisted from Astroid CSS and JS compression.

Good Day!

**Comment by sonvnn** [comment]
Yes, I will update it in the 3.0.3

**Comment by bobmcduk** [comment]
That's great, thankyou for your help.

**Comment by sonvnn** [comment]
I update minify JS in https://github.com/templaza/astroid-framework/commit/f0c9e12bc136717b97b65c537b5270565cc4ca01

Let's check it. Thanks
