### ISSUE TITLE
Menu screen not displayed correctly

### ISSUE THREAD

**Issue by martst** [templaza/astroid-framework#437]
I'm running on Joomla 3 preparing to upgrade to 4. If I select Astroid Menu Options on a menu I see this:
![menu_problem](https://github.com/templaza/astroid-framework/assets/3466343/c30e6052-7461-4157-bc6a-955e6edb1804)
Any suggestions on how to debug if an extension is causing this problem. 
Any help appreciated

**Comment by nidzo80** [comment]
Don't use Astroid during migration. Disable it. After migration update to latest version of Astroid Framework and templates and enable it.

**Comment by Joomlaplates** [comment]
Please use for Joomla 3 the Astroid version 3.0.2
Astroid 3.0.3 is compatibe only with J4 and J5

**Comment by Chacapamac** [comment]
@martst  - Is this Solved for You?

**Comment by martst** [comment]
I was using 3.0.1 but upgrading to 3.0.2 hasn't changed anything. Thanks for the help
