### ISSUE TITLE
Templates One and Zero error 500 (button.php)

### ISSUE THREAD

**Issue by fontanil** [templaza/astroid-framework#44]
Hi,
On a site I get an error 500 with the two templates

> ERROR 500 - behavior::modal not found. in /home/www/sitesclients/**********/libraries/src/HTML/HTMLHelper.php:149 

`JROOT/templates/astroid_template_one/html/layouts/joomla/editors/buttons/button.php:29 `
`	
// Load modal popup behavior

	if ($button->get('modal')) {

		HTMLHelper::_('behavior.modal', 'a.modal-button');

	}
`

**Comment by Joomlaplates** [comment]
Hello, 
just rename the folder **editors** to **editors_bak**

And if you cant see the editor button in frontend, add this css code to your custom.css
```
/*Frontend Button*/
a.jmodedit:after{
	font-family: "Font Awesome 5 Free";
	content: "EDIT";
	color:#ff0000;
	font-size:14px;
	height:20px;
	display:inline-block !important;
}
```

**Comment by fontanil** [comment]
Thanks,

I renamed the "buttons" folder and it works.
On the error page I have no editor (a frontend page for registrants of Event Booking) so I don't know why the error 500 was here.

**Comment by sonvnn** [comment]
Thank you for report bug. I will update this issue in the next version. :)

**Comment by sonvnn** [comment]
I fixed it in the latest package. Please help me check it again.
Thanks, Sonny

**Comment by fontanil** [comment]
I updated with the Astroid "Template" pack 2.5.11 and hve no more error.
Thanks!
