### ISSUE TITLE
Animations not working in Astroid 3.0.3

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#443]
Hi Sonny,
all animations are not working anymore in Astroid 3.0.3
![animations](https://github.com/templaza/astroid-framework/assets/71080509/6e9b1129-2b9d-4e6c-91bc-491befc375c5)

**Comment by WM-Loose** [comment]
Hello Sonny, can you fix the bug at short notice? 
We really have a lot of customers who are totally disappointed and angry. 
This is no small matter and should be remedied as quickly as possible. 
I have now recommended going back to 3.0.2 for now.

**Comment by Joomlaplates** [comment]
Hi Dirk,
Sonny will fix it on Monday.
Its easy to fix, coz its just missing a file:
`\astroid-framework-master\assets\css\animate.min.css`
..
If you cant wait, copy the animates.min.css to your folder:
`media/astroid/assets/css/animate.min.css`
[animate.min.css.zip](https://github.com/templaza/astroid-framework/files/13327558/animate.min.css.zip)
Regards, Peter. Happy Sunday

**Comment by WM-Loose** [comment]
Great, thank you very much Peter and have a nice weekend!

**Comment by WM-Loose** [comment]
Unfortunately it doesn't work that way. The entire css folder is missing, including all the files necessary there. You can test it by installing 3.0.2. Then the css folder is also there. The update to 3.0.3 deletes the entire css folder.

**Comment by WM-Loose** [comment]
Sonny, please reinsert the entire folder when fixing the bug.

**Comment by sonvnn** [comment]
Yes, I will fix it on Monday. It's 21h00 on Sunday. I am at home. I think I can not do anything at the moment. My brain is going to sleep in next 15'.

**Comment by sonvnn** [comment]
@WM-Loose I am very grateful if you join us for testing new version before it is released. I wait in 2 days when all people confirm everything is fine then release new version.

Thanks & Best Regards,
Sonny

**Comment by WM-Loose** [comment]
I can't say why the folder is completely deleted. I created the folder again and then copied the file into it. 
After that everything works.

css folder before with 3.0.2 was:
![previously](https://github.com/templaza/astroid-framework/assets/99647423/908e9326-eb88-48bd-bdcb-4d11d0e86777)

css folder with 3.0.3 is now:
![after](https://github.com/templaza/astroid-framework/assets/99647423/38fe498b-227a-4256-9f0e-49164fe85e79)

**Comment by sonvnn** [comment]
I fixed this issue in https://github.com/templaza/astroid-framework/commit/ba030aac3e318626d2d64e41fe5344431a8d67a8

**Comment by WM-Loose** [comment]
Hi Sonny, thank you very much, it works great!
