### ISSUE TITLE
Only variables should be passed by reference 

### ISSUE THREAD

**Issue by chriswaterside** [templaza/astroid-framework#444]
Hi
firstly thanks for such a great template

I seem to be getting a warning notice as below
Notice
: Only variables should be passed by reference in
/home/sites/4b/1/1ecfc4337b/public_html/rec02/plugins/system/astroid/services/provider.php
on line
38

PHP 8.1.25
Joomla! 4.4.0 Stable
Astroid Framework 3.0.3
Astroid Plugin 3.0.3
astroid_template_zero 3.0.0 installed from https://github.com/templaza/astroid-framework/archive/refs/heads/zero-template.zip

**Comment by sonvnn** [comment]
Thanks for feedback! I will check and fix it on Monday

**Comment by sonvnn** [comment]
I fixed this issue in https://github.com/templaza/astroid-framework/commit/9d8c76e0c0e76d56d82477dbdcafefd5f84f8ca5 Please help me check it.

**Comment by chriswaterside** [comment]
thanks
I can confirm this works fine now - thanks a lot
