### ISSUE TITLE
problem with joomla system messages

### ISSUE THREAD

**Issue by SerGun78** [templaza/astroid-framework#446]
Why are joomla system messages not displayed in templates: informational, error messages, etc.?
although there is space for them in the template:
![изображение](https://github.com/templaza/astroid-framework/assets/95705148/18017271-ea8f-4212-9ab2-80c602e4b3ed)

in Casiopea these messages look like this:
![изображение](https://github.com/templaza/astroid-framework/assets/95705148/ba2d1c38-2457-4b2e-9b27-fb101a553aab)

**Comment by Joomlaplates** [comment]
Hi,
try following:
Copy the file attached message.php into the template folder:
`html\layouts\joomla\system\message.php`
[message.zip](https://github.com/templaza/astroid-framework/files/13341175/message.zip)

**Comment by SerGun78** [comment]
joomlaplates, thank you. The archive contains a standard file from the Joomla core, from which version?
Why do I need it?
In Cassiopeia everything appears fine for me! The only problem is with the astroid templates: one and zero.

**Comment by Joomlaplates** [comment]
Hello, you can take any system file from Joomla 4 or Joomla 5:
`..Joomla Root/layouts/joomla/system/message.php`
And yes we will add the file to the next version of the template

**Comment by sonvnn** [comment]
I fixed it in 3.0.5

**Comment by SerGun78** [comment]
Sonny, thank you. Yes, system messages appeared. But now the next problem. This file is not included in the jch optimizer plugin.
Please check what is the reason. Due to the fact that it is already minified (*.min.js) or...?!

**Comment by sonvnn** [comment]
Sorry, I don't understand your question. It is php file, it is not js file. It will not related to jch plugin.

**Comment by deltapapa01** [comment]
Hi,
btw, in j4 / j5 / j6 the jch plugin is no longer required.
On the contrary, in my tests the pages with the plugin were sometimes slower. But above all, the jch plugin causes a lot of problems. Recommendation of the Joomla developers: From j4 you should no longer use the JCH plugin!

**Comment by SerGun78** [comment]
Sonny, this is the js file:
![изображение](https://github.com/templaza/astroid-framework/assets/95705148/85a6af70-131a-4c1c-b939-33146c9988aa)
this is not a *.php file

**Comment by SerGun78** [comment]
> Recommendation of the Joomla developers: From j4 you should no longer use the JCH plugin!

Can I have a link to the proof?

**Comment by Chacapamac** [comment]
I use JCH
You have many great function to gain some speed with it. Just the ability to compress/optimize images already use by a website automatically is by itself a pretty powerful function as images is one of the BIG culprit for slow website. 

Any tools to optimized a website is tricky and demand some effort to make it work with a specific website . 

JCH is, to my knowledge the most specific and flexible tools out there to do the job and used widely by many CMS (Joomla, Wordpress, Magento and Drupal).

Who tell You that it is no longer something we should use?
