### ISSUE TITLE
Issue with Menus Badge Text — Astroid 3.0.4 - Template One 3.0.3 - Joomla 4.4.0 - PHP 8.1

### ISSUE THREAD

**Issue by Chacapamac** [templaza/astroid-framework#448]
The text is on top of the menu, logically, it should be under as it is only an addition/infos attach to the Menu Item Title. We read up to down, ( The Menu Item First, the added Badge/infos after. 

Also, in template One, the Badge text is not align to the Main Menu Item.

![Astroid-badge-text](https://github.com/templaza/astroid-framework/assets/1907276/0c4ba405-c0d6-4d41-bfb8-d682d30d99dc)

**Comment by sonvnn** [comment]
I see that there is confusion between Badge Text and Sub Title here. Please check my screenshot
![Screen Shot 2023-11-15 at 09 36 00](https://github.com/templaza/astroid-framework/assets/3204103/07204e24-2e8a-4717-a745-efaf964c198e)

Let's try to use Subtitle if you want display text under Menu Item.
![Screen Shot 2023-11-15 at 09 37 35](https://github.com/templaza/astroid-framework/assets/3204103/60989c0e-2597-4a16-b262-7a7f6efe2167)

**Comment by Chacapamac** [comment]
@sonvnn 
My bad, Solved, I see that the badge text should also need a bit of CSS to be more align and a bit closer to his corresponding Menu Item. I think Left Align or center will be more pleasant visually.

Good Day!
