### ISSUE TITLE
suggestion: favicon improvments

### ISSUE THREAD

**Issue by djayko** [templaza/astroid-framework#45]
Hello,

I checked my html code and I saw following code:
`<link href="https://mydomains.com/images/02-Logos/favicon.svg" rel="shortcut icon" type="text/css" />`

For discussion:
- optimization and adding apple touch icons and other platforms?
- adjust type from text/css to image/png or image/svg+xml ... etc.?
- more options vor setting the right favicon?
- set a practical standard for non experienced users?

related articles:
https://stackoverflow.com/questions/48956465/favicon-standard-2021-svg-ico-png-and-dimensions
https://developers.google.com/search/docs/advanced/appearance/favicon-in-search
https://dev.to/masakudamatsu/favicon-nightmare-how-to-maintain-sanity-3al7

It's a minor point, but maybe it could be improved fast and easy. Honestly, I'm not sure about the "best way".

best regards,
Frank

**Comment by sonvnn** [comment]
Thank you I added this to Version 2.5.12.

Best Regards,
Sonny

**Comment by sonvnn** [comment]
Hi @djayko ,

I updated this feature in https://github.com/templaza/astroid-framework/commit/3ad4a80a29c3077b7f8e5bce0be75b7cfa63a28b
May you help me check it on your site?

Thanks & Best Regards,
Sonny

**Comment by djayko** [comment]
Test succesful!
It's working well!

best,
Frank

**Comment by djayko** [comment]
But there is an little issue with double slashes on image path:

Its: 
`https://www.mydomaincom//images/02-Logos/favicon.svg?v=2.5.11`
instead of
`https://www.mydomain.com/images/02-Logos/favicon.svg?v=2.5.11`

![grafik](https://user-images.githubusercontent.com/3375044/145021030-e6cbbfde-97e5-43ed-a5f0-a1f418b714d8.png)
