### ISSUE TITLE
custom.css is not loading /Astroid Framework 3.0.3 / 3.0.4

### ISSUE THREAD

**Issue by Solero-Artaxerxes** [templaza/astroid-framework#450]
It seems that in Astroid 3.0.2 and 3.0.3 the custom.css from the root/media/templates/site/my_template/css/custom.css folder is not loaded. If I enter the css code in Astroid Backend, then it works. Can anyone confirm this?

I didn't test it in Astroid Framework 3.0 and 3.01.

Local installation in xampp 8.2.4

**Comment by Solero-Artaxerxes** [comment]
I just tested it in Astroid Framework 3.0. The custom.css is loaded from the root/media/templates/site/my-template/css/custom.css folder.

**Comment by Chacapamac** [comment]
@Solero-Artaxerxes 
Yes, Joomla 4.1 move the css from the root/media/templates/site/my-template/css/custom.css folder and other folders to add the new Joomla ability to create “Child Templates” 
[a](https://magazine.joomla.org/all-issues/may-2022/a-deep-dive-into-joomla-child-templates)

Astroid is one of the rare Joomla framework that permit to use that feature the Joomla way.

**This is an example:**
![Before_Joomla_4-1-templates](https://github.com/templaza/astroid-framework/assets/1907276/9e49969d-361d-4bcb-abe8-051e98fd6c7e)

**Comment by Joomlaplates** [comment]
Its right, its a bug.
If you set in Astroid Plugin > Enable Inline CSS = YES
the custom.css from folder 
`media/templates/site/your template/css/custom.css`
 is not loading.
![inline](https://github.com/templaza/astroid-framework/assets/71080509/0c7cc542-70f4-4b80-8bef-f2d6c5e4e2d9)

**Comment by sonvnn** [comment]
Fixed in https://github.com/templaza/astroid-framework/commit/32365855525cd7ff941ac127f30866544428cb65
Let's download v3-branch and retest again.
Thanks,

**Comment by Joomlaplates** [comment]
Hi Sonny,
yes its working now.
The custom.css is loading now doesnt matter if Inline CSS is "On" or "off".
And custom.css could be in template folder or media/template folder.
Both paths are working.
Thanks, youre GREAT, regards Peter
