### ISSUE TITLE
astroid does not show tags on listing of featured articles

### ISSUE THREAD

**Issue by mac-joomla** [templaza/astroid-framework#451]
astroid_template_zero – Standard with the astroid framework 3.0.4 does not show tags in the frontend under a menu for featured articles, even though the tags are activated in the general settings and in the menu item.

**Comment by sonvnn** [comment]
Because Zero template is out of date with latest Joomla version. I am working on Two template after recheck everything with Joomla 5 latest version. I will back to update Zero and One follow Two.

Thanks & Best Regards,
Sonny

**Comment by Joomlaplates** [comment]
.

> astroid_template_zero – Standard with the astroid framework 3.0.4 does not show tags in the frontend under a menu for featured articles, even though the tags are activated in the general settings and in the menu item.

Tags will be shown only in the article detail page and not in Blog or Feature Article blog.
Check with org Cassiopeia template and here is the same.

**Comment by mac-joomla** [comment]
I was double checking before writing here. Cassiopeia with Joomla 5 is showing tags in Menu Item Type "Featured Articles" and in Menu Item Type "Category Blog". In preferences you can choose in tab "Options" to show it or not to show it and this works in both cases Witt cassiopeia. Would be happy if this could work in astroid like in cassiopeia.

**Comment by Joomlaplates** [comment]
**Yes youre right,**
The Tags should shown in Blog but they are not in One Template.

**Comment by Joomlaplates** [comment]
> Because Zero template is out of date with latest Joomla version. I am working on Two template after recheck everything with Joomla 5 latest version. I will back to update Zero and One follow Two.
> 
> Thanks & Best Regards, Sonny

Hi Sonny, its a good idea, BUT I think dont confuse the users with a new Template. Most of them still using the ONE template and they dont know how to export and import to the new template. I think with a new Template you/ we will buy us work!!
Happy weekend, Peter

**Comment by mac-joomla** [comment]
> Here is a quick solution until we update the Template ONE. Copy the files attached to your Template/html/com_content folder. `html/com_content/category/blog_item.php` `html/com_content/featured/default_item.php` [com_content.zip](https://github.com/templaza/astroid-framework/files/13403282/com_content.zip) Regards, Peter

Thank you very much for your answer and help. Unfortunately it does not change anything when I use the new files. When I delete these files, then it is showing the tags but is breaking the layout.

**Comment by Joomlaplates** [comment]
Hello, the files should work.
Maybe clear your cache or disable the Joomla cache at all.
Anyway here is the demo of the template ONE
https://suspicious-galileo.85-214-95-104.plesk.page/index.php/joomla/joomla-blog-2-columns-with-tags
...
And ofc the Tags must be enabled in general settings:
Joomla System Articles > Options > Tags = Yes
![tags](https://github.com/templaza/astroid-framework/assets/71080509/4f984fc7-3e91-409a-9afd-951d543b89d8)

**Comment by sonvnn** [comment]
I updated Zero and One to v3.0.5
