### ISSUE TITLE
Save and close post - close note

### ISSUE THREAD

**Issue by WM-Loose** [templaza/astroid-framework#452]
Save and close post - Note is not closed when you click on the cross. The notice only disappears after the page is refreshed. For Cassiopeia the notice is closed.

Astroid 3.0.4 | PHP 8.2 | Template One

![1](https://github.com/templaza/astroid-framework/assets/99647423/9ac03e5d-eafc-4c9a-a40f-d467d505d023)

**Comment by Joomlaplates** [comment]
Hi Dirk, its a known bug.
https://github.com/templaza/astroid-framework/issues/446
