### ISSUE TITLE
Toolbar-Icons are not displayed (font not loaded) in the backend with Joomla 5.0.0 if "Astroid Plugin" is active

### ISSUE THREAD

**Issue by b0wtie** [templaza/astroid-framework#453]
# Issue
While using Astroid 3.0.4 and Joomla 5.0.0 I encountered a minor problem with icon-fonts not loading in the backend. This **only** occurs, while editing **menu items**.
![Bildschirmfoto 2023-11-15 um 20 37 00](https://github.com/templaza/astroid-framework/assets/3800845/c1dbb4c4-69c0-42a8-ac19-f7244a8ff8c7)

# Steps to reproduce
- Install a fresh Joomla 5.0.0
- Install Astroid 3.0.4
- Head to `Menu` - `Main Menu` and edit a menu item
- The buttons in the toolbar on top are displayed without their icons (but still work)
-----
- once you deactivate the extension "Astroid Plugin", the font is loaded again.

![Bildschirmfoto 2023-11-15 um 20 36 13](https://github.com/templaza/astroid-framework/assets/3800845/613ecdca-ce88-4d0a-a31d-1ada613aa1fa)

**Comment by sonvnn** [comment]
This issue was fixed in https://github.com/templaza/astroid-framework/commit/c264ddcb9863aed413f7666ebe90ab21e874985f#diff-8820814e2137a3c3fb9b291f36b6b516667c5334f9b63193f74f632cdd5bf332

Please help me download v3-branch and retest again.

Thanks & Best Regards,
Sonny
