### ISSUE TITLE
Pressing Enter makes Astroid UI inaccessible

### ISSUE THREAD

**Issue by MartinMajewski** [templaza/astroid-framework#454]
I am facing an issue with Astroid Framework version 3.0.3 in Joomla. When I make changes inside any modal / overlay menu and press the Enter key on my keyboard, the underlying main UI becomes unresponsive. It appears as if it lost focus and is dimmed out. It becomes interactive only once I reload the entire page, losing all modifications I made until then. I have to remember to use the UI to close the modal / overlay menus.

Is there a workaround or a fix for this?

Using Safari Version 17.1 (19616.2.9.11.7) on macOS 14.1 (23B74).

Cheers,
Martin

**Comment by sonvnn** [comment]
Thank you for report bug! I confirm this is a bug. I will soon update this in v3.0.5

**Comment by sonvnn** [comment]
I fixed this issue in https://github.com/templaza/astroid-framework/commit/03c6bcf4cbdc09d0545db55699e956a9ad7e4eb5
Please help me download v3-branch and test again.

Thanks,

**Comment by Chacapamac** [comment]
I just test v3 Dev Branch in Firefox and Chrome on Mac.

![Screen Shot 2023-11-22 at 4 20 07 PM](https://github.com/templaza/astroid-framework/assets/1907276/824035f9-4be4-4120-b301-45e570ea9746)

I cannot enter anything with the keyboard, or paste text in the fields where you can input custom ID, Classes etc....

**Comment by sonvnn** [comment]
@Chacapamac Sorry! I made a mistake. I fixed it in https://github.com/templaza/astroid-framework/commit/29cfe6f344fd1485b06042adda0abb4ef9484e2b
Please help me download and re-check again.
