### ISSUE TITLE
Astroid 3.0.4 plugin removes Joomla 4.4.0 icons in the backend when editing the menu.

### ISSUE THREAD

**Issue by WM-Loose** [templaza/astroid-framework#457]
![1](https://github.com/templaza/astroid-framework/assets/99647423/5509ad3c-8c38-4501-82dd-edcd7d8bfea4)

Test: deactivate astroid plugin, everything is normal.
Test: activate astroid plugin, icons are missing

Backend /Menu /open a menu-titel

**Comment by sonvnn** [comment]
Please check and follow this issue #453

**Comment by WM-Loose** [comment]
Thanks Sonny, have a nice weekend.
You're doing really great work!
