### ISSUE TITLE
loading unnecessary js bootstrap

### ISSUE THREAD

**Issue by SerGun78** [templaza/astroid-framework#458]
I don't have more than one js bootstarp selected in the one template:
![изображение](https://github.com/templaza/astroid-framework/assets/95705148/24709e8a-508d-4e40-becc-9151f460709f)

but two are still loaded: dom.js and carousel.js:
![изображение](https://github.com/templaza/astroid-framework/assets/95705148/4e6c3970-ac80-4319-87f7-4edec5677b4a)

Where and why?

**Comment by sonvnn** [comment]
Carousel js will auto load in Com Content to run Gallery Article.

**Comment by sonvnn** [comment]
I fixed this issue in https://github.com/templaza/astroid-framework/commit/3c072b0d7c349a04a2fa866bd08a9c9deba09457

Please help me check it.
