### ISSUE TITLE
Error Astroid Menu Options v3.0.4

### ISSUE THREAD

**Issue by vologb** [templaza/astroid-framework#461]
### Discussed in https://github.com/templaza/astroid-framework/discussions/460

<div type='discussions-op-text'>

<sup>Originally posted by **vologb** November 19, 2023</sup>
Hi,
I came across an error in v3.0.4 in the Astroid Menu Options.
The input field to specify the width of the MegaMenu is not the width input field. It is in fact the field to specify the text for the BadgeOption. When you change the BadgeText it also changes the Width input field and vice verca. I cannot change the width of the Mega Menu. Maybe you can verify and fix?
Thanks and kind regards
Volker
![Screenshot 2023-11-19 090055](https://github.com/templaza/astroid-framework/assets/151429204/6e570244-4da7-4da9-a1fc-9c17c968c8bc)

</div>

**Comment by sonvnn** [comment]
Thank you for report bug
I fixed this issue in https://github.com/templaza/astroid-framework/commit/886c5e6b40ca8263e161456554eba3c57f478bd7

Please help me check it.
Thanks & Best Regards,
Sonny

**Comment by vologb** [comment]
Hi Sonny,
it's fine now.
Thank you very much. Your are doing a great job!
Kind regards
Volker
