### ISSUE TITLE
Exo 2 font create a wrong code in css

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#462]
Hello, if you select Exo 2 font in Template options the css code is wrong, see picture
Here is the wrong code > double ´"
```
.body {
  font-family:"'Exo 2'", Arial, Helvetica, sans-serif;
}
```
It should look like that
```
.body {
  font-family:"Exo 2", Arial, Helvetica, sans-serif;
}
```
![exo](https://github.com/templaza/astroid-framework/assets/71080509/b9ab4189-ab5f-4675-8f5a-ace193296feb)

**Comment by sonvnn** [comment]
I fixed this issue in https://github.com/templaza/astroid-framework/commit/4723e0ab3be19c432ed7debc3cdc18a566ea704e
