### ISSUE TITLE
Suggestion for improvement: remove generator

### ISSUE THREAD

**Issue by salahjaafar** [templaza/astroid-framework#463]
**Dear Astroid team,**

I am a web developer who has been using your framework for several years. I am very satisfied with its performance and flexibility.

I would like to make a suggestion for improvement that I believe would be very beneficial for Astroid-based templates.

This is to add the option to change the default Joomla generator. This option would allow developers to choose the generator they want to use for their templates.

Currently, it is possible to change the default Joomla generator using a third-party plugin. However, this requires installing an additional plugin, which can be a source of problems.

Adding this option natively to Astroid would simplify template configuration and reduce the use of third-party plugins.

I propose that you be inspired by the plg_system_removegenerator plugin: [[https://github.com/SharkyKZ/plg_system_removegenerator](https://github.com/SharkyKZ/plg_system_removegenerator)] to implement this feature. This plugin is very well documented and it is easy to understand how it works.

I am convinced that this improvement would be greatly appreciated by the Astroid community.

**Sincerely,**
Salah JAAFAR

**Comment by sonvnn** [comment]
Hi Salah,

Thank you for suggestion. It's a great idea. I will add this feature in v3.0.5

Best Regards,
Sonny

**Comment by salahjaafar** [comment]
> Hi Salah,
> 
> Thank you for suggestion. It's a great idea. I will add this feature in v3.0.5
> 
> Best Regards, Sonny

Thank you for your interaction
I think this framework will have a bright future compared to existing ones,
All the support

**Comment by salahjaafar** [comment]
> I support this! I use Akeeba Admin to remove/modify the “Joomla” generator, but this is a paying extension. Akeeba Admin give this possibility for security reason. Having that in the Framework will be great!

For now you can use this free extension https://github.com/SharkyKZ/plg_system_removegenerator
but if the Astroid framework team work to add a customization field would be a great pleasure

**Comment by sonvnn** [comment]
I added this feature in https://github.com/templaza/astroid-framework/commit/4e001698349707fbc564f3497faff9224b6898af

Please help me check it.

**Comment by salahjaafar** [comment]
> I added this feature in [4e00169](https://github.com/templaza/astroid-framework/commit/4e001698349707fbc564f3497faff9224b6898af)
> 
> Please help me check it.

Congratulations, or could I download the development version to try it?

**Comment by sonvnn** [comment]
Let's try to download v3 branch and test it

**Comment by salahjaafar** [comment]
> Let's try to download v3 branch and test it

Yes it works correctly, Thanks for the effort

**Comment by Chacapamac** [comment]
I confirm, V3 Astroid Plugin can remove the “**Generator**” Head Tag. TESTED!
![Screen Shot 2023-11-22 at 3 57 49 PM](https://github.com/templaza/astroid-framework/assets/1907276/c5b35756-43e2-4a98-b8ae-a986ad763e6e)

This is a plus to be able to do it with Astroid without the need of third party components. It add a good level of security.

**A Quote!**

> < Meta Name = "Generator"
> You used the so called meta name generator tag, also known as the formatter tag, to add the name of the program you used to create your website.
> 
> Now, most people don’t want anybody to know with which tool or program they created their website and therefor they remove this tag from their site.
>
