### ISSUE TITLE
Template ONE, please delete card.php module layout, it isnt working

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#467]
Hi Sonny,
please delete the card.php module layout from
`html/mod_login/card.php`
because it isnt working anymore.
..
If you select in the Login Module the card Layout you get an error
`ERROR 0 - count(): Argument #1 ($value) must be of type Countable|array, null given in /var/www/vhosts/xxxx/html/mod_login/card.php:63 `
Thanks Peter
![card](https://github.com/templaza/astroid-framework/assets/71080509/dcf0f098-1c93-4522-9520-251fa65aca65)

**Comment by sonvnn** [comment]
I updated it https://github.com/templaza/astroid-framework/commit/41bb6d6a697416a9075345b43186079353a9d02a

**Comment by Joomlaplates** [comment]
Hi Sonny, yes its working now.
Thanks, regards Peter
