### ISSUE TITLE
ERROR 0 - Failed opening required ... astroidxhtml.php:17

### ISSUE THREAD

**Issue by nidzo80** [templaza/astroid-framework#468]
I have updated one website on localhost from Joomla 4.4.0 to Joomla 5 and I get 
`ERROR 0 - Failed opening required 'mp64\www\una\templates\astroid_template_one\html\layouts\chromes\astroidxhtml.php' (include_path='.;C:\php\pear') in C:\wamp64\www\una\templates\astroid_template_one\html\layouts\chromes\astroidxhtml.php:17`
**Framework Version: 3.0.5
Template One Version: 3.0.5**
When I rename astroidxhtml.php to astroidxhtml.phpOLD website works O.K.

![2023-11-23_114930](https://github.com/templaza/astroid-framework/assets/21330927/6a18afed-aea1-4b97-be66-c77099cba04a)

**Comment by sonvnn** [comment]
Please download astroid 3.0.5 and upload again. It's problem with child template. I reupload 3.0.5.

**Comment by nidzo80** [comment]
Hmmm... same thing. New code is there in _framework/library/astroid/Helper/Overrides.php_ 
Cache cleared, incognito window.

**Comment by Joomlaplates** [comment]
I think it has nothing todo with child theme. Its a problem with `layouts/chromes/astroidxhtml.php` module override.

**Comment by sonvnn** [comment]
@nidzo80 May you send me your admin link via sonlv@templaza.com? I will help you check it. System works well in my local

**Comment by nidzo80** [comment]
I ran more testing and uploaded website to live server and seems that problem was my WAMP settings. On live server I don't get mentioned errors. Sorry for false alarm. 😊
