### ISSUE TITLE
Astroid Section / Background Image

### ISSUE THREAD

**Issue by Solero-Artaxerxes** [templaza/astroid-framework#470]
Hello,
in an astroid section I load a background image (jpg). The image is in a folder on the local server and is selected, but it is not displayed on the website. I don't know if I'm making a mistake somewhere or if it's a bug. Would anyone be so kind as to test this out?

Joomla 5, Astroid 3.0.4 and Template one.

Please excuse my bad English, I use Google Translate

Kind Regards

**Comment by sonvnn** [comment]
May you give me a link or a video record about the issue?

**Comment by Solero-Artaxerxes** [comment]
Since I'm building the website on a local server, I can't send a link. But I took screenshots.
![1](https://github.com/templaza/astroid-framework/assets/104907519/345d8ca3-9fe6-4942-9b6b-5623f3af4287)
![2](https://github.com/templaza/astroid-framework/assets/104907519/a86ae9ec-59f4-429c-bae9-6bd3a2d79bf7)
![3](https://github.com/templaza/astroid-framework/assets/104907519/549808cb-599a-4856-bb4f-17b8d77c30b5)

**Comment by Joomlaplates** [comment]
Hello,
only an image in a section dont works
You need to insert an element or assign a joomla module with content. Otherwise the background image will not shown.
Anyway here are many videos in German language to understanbd how the Astroid is working
https://www.joomlaplates.de/joomla-tips-und-tricks/hintergrundbild.html

**Comment by Solero-Artaxerxes** [comment]
Hello, thank you for your answer. I like your videos, they have helped me many times, thank you for that. I'm sure I did it exactly like in your video, but it doesn't work for me at the moment. I've done it several times and it's always worked. Maybe I have another error somewhere that prevents this. I'd best start again from the beginning.

**Comment by Joomlaplates** [comment]
Please make sure you have also a module published in the section where the background image is placced.
