### ISSUE TITLE
Arabic language files are incorrect

### ISSUE THREAD

**Issue by salahjaafar** [templaza/astroid-framework#471]
Arabic language files are incorrect, download file points to German language
on this page https://github.com/templaza/astroid-framework/tree/language
I could participate in translating the language files from the Arabic language if it does not exist
![Screenshot 2023-11-24 at 09-37-47 templaza_astroid-framework at language](https://github.com/templaza/astroid-framework/assets/47123877/9decaf17-3b0e-43ec-8348-19451520f516)

**Comment by sonvnn** [comment]
@Joomlaplates may you help me review it? :)

**Comment by Joomlaplates** [comment]
Updated!
Thank you!

**Comment by salahjaafar** [comment]
> @Joomlaplates may you help me review it? :)

Yes of course, it's my mother tongue
