### ISSUE TITLE
Offcanvas dont not showi any content

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#472]
Hi Sonny,
Joomla 5, Astroid 3.0.5 and Template One 3.0.5.
The offcanvas doesnt show any content and there is a css code with
`visibility: hidden;`
Check yourself here, demo site
https://infallible-noether.85-214-95-104.plesk.page/
Regards Peter

**Comment by nidzo80** [comment]
I can confirm that on one of my site I upgraded to Astroid 3.0.5

**Comment by sonvnn** [comment]
Thanks, I will check it in the next morning :)

**Comment by sonvnn** [comment]
This issue because `offcanvas` class from Bootstrap 5. I added suffix for module class then now it works https://github.com/templaza/astroid-framework/commit/a1409a37613f8123405b27254e34309bc68432af

**Comment by WM-Loose** [comment]
I replaced the line, tested it and it works.
In my opinion this solved the problem.
Thanks Sonny!

**Comment by Joomlaplates** [comment]
Hi Sonny, you will fix this in next Astroid Version or we always have to select the Module Style, show below?
![Screenshot_2](https://github.com/templaza/astroid-framework/assets/71080509/e6140594-b0d2-43be-95af-9d4fcdf4e8c6)
Regards Peter

**Comment by sonvnn** [comment]
I fixed it in v3-branch. Let download and check it

**Comment by sonvnn** [comment]
@Joomlaplates I fixed this issue in https://github.com/templaza/astroid-framework/commit/a1409a37613f8123405b27254e34309bc68432af

Let's download https://github.com/templaza/astroid-framework/archive/refs/heads/v3.zip and test it. Please tell me if this issue is happen again.

**Comment by nidzo80** [comment]
It works but if you have this problem https://github.com/templaza/astroid-framework/issues/473#issuecomment-1826258242
astroidxhtml.php still needs to be copy manually in template override.

**Comment by WM-Loose** [comment]
Hi Sonny, does it have to be a class or can't you solve it any other way? If it stays the way you solved it now, all templates have to be updated. So the changed line must be corrected in all templates within the php file. It's possible, but it's a lot of work.

**Comment by Joomlaplates** [comment]
Hi Sonny,
yes V3 Branch is working without changing anything in the template
https://github.com/templaza/astroid-framework/archive/refs/heads/v3.zip

**Comment by Joomlaplates** [comment]
> Hi Sonny, does it have to be a class or can't you solve it any other way? If it stays the way you solved it now, all templates have to be updated. So the changed line must be corrected in all templates within the php file. It's possible, but it's a lot of work.
> 
> It's been dealt with. I create a script and simply exchange the changed file. The templates will then receive the adjustment automatically with the next update version.

Install the Astroid Dev branch which is the next Astroid version and test it. It should work without any changes.
https://github.com/templaza/astroid-framework/archive/refs/heads/v3.zip

**Comment by sonvnn** [comment]
@WM-Loose I am waiting @Joomlaplates Confirm and will update version in next 24h.

@nidzo80 this code works on my server. I don't know why it does not work on your server. Since v3.0.5 released, only Sergur and you report bug. But no one send me admin account for debug. May you give me your admin account? I can find a solution in few minutes.

Best regards,
Sonny

**Comment by nidzo80** [comment]
> @WM-Loose I am waiting @Joomlaplates Confirm and will update version in next 24h.
> 
> @nidzo80 this code works on my server. I don't know why it does not work on your server. Since v3.0.5 released, only Sergur and you report bug. But no one send me admin account for debug. May you give me your admin account? I can find a solution in few minutes.
> 
> Best regards, Sonny

Login details sent to email 👍🏼

**Comment by Joomlaplates** [comment]
> I fixed it in v3-branch. Let download and check it

Yes I can confirm its working.
Regards Peter

**Comment by sonvnn** [comment]
> > @WM-Loose I am waiting @Joomlaplates Confirm and will update version in next 24h.
> 
> > 
> 
> > @nidzo80 this code works on my server. I don't know why it does not work on your server. Since v3.0.5 released, only Sergur and you report bug. But no one send me admin account for debug. May you give me your admin account? I can find a solution in few minutes.
> 
> > 
> 
> > Best regards, Sonny
> 
> 
> 
> Login details sent to email 👍🏼

Thank you my friend! I will check it as soon as I back to office, tomorrow. It is time to go to bed here. Good night all :)
