### ISSUE TITLE
Logo with svg format

### ISSUE THREAD

**Issue by salahjaafar** [templaza/astroid-framework#484]
In the new version, it is necessary to allow the logo to be added in svg format

**Comment by Joomlaplates** [comment]
You have to try out!!!
I think its even not possible to add a svg logo

**Comment by salahjaafar** [comment]
Thank you, Sony, it will be another improvement option. Good luck!

**Comment by sonvnn** [comment]
@Joomlaplates @salahjaafar Astroid currently supports SVG Logos. I added it here https://github.com/templaza/astroid-framework/commit/2ee58ff196d8657a272aca5aaa1520dec1fe1a4c 
Please help me download v3-branch and test it.

Thanks & Best Regards,
Sonny

**Comment by sonvnn** [comment]
Now you can configure logo max-width and max-height, too.
![Screen Shot 2023-12-01 at 16 16 14](https://github.com/templaza/astroid-framework/assets/3204103/d8711071-2b8e-46fa-8d07-ade36206c7bd)

**Comment by Joomlaplates** [comment]
Hi Sonny,
I would set only the logo height and set the logo width always to > auto
Otherwise you get a problem with the ratio. But I never used SVG, so maybe its different here.
Regards Peter

**Comment by salahjaafar** [comment]
> @Joomlaplates @salahjaafar Astroid currently supports SVG Logos. I added it here https://github.com/templaza/astroid-framework/commit/2ee58ff196d8657a272aca5aaa1520dec1fe1a4c 
> Please help me download v3-branch and test it.
> 
> Thanks & Best Regards,
> Sonny

Well done, I'll give it a try; you're putting in a great effort.

**Comment by salahjaafar** [comment]
I tried the modified version and added a logo in SVG format, but an error occurred, blocking the site display:

ERROR 0 - Call to undefined method Joomla\Filesystem\File::getExt() in /opt/lampp/htdocs/joomla/libraries/astroid/framework/frontend/logo.php:118

I attempted to fix the error by replacing File::getExt with JFile::getExt, and it worked correctly.

**Comment by salahjaafar** [comment]
Substitute the occurrence of File::getExt on line 118 in the file logo.php with JFile::getExt. You can implement conditional statements based on the Joomla version using the constant JVERSION.

**Comment by sonvnn** [comment]
@salahjaafar JFile is deprecated in Joomla 5. If you turn off Backward Compatible Plugin in Joomla 5. All functions (JFactory, JFile, JFilter, etc) will raise error. 

Astroid now work stabled with Joomla 5 even admin turn B/C plugin off.

`Joomla\CMS\Filesystem\File` will work with both of J4 and J5. It will deprecated in J6 only. So don't worry until J6 released.

Thanks & Best Regards,
Sonny

**Comment by Joomlaplates** [comment]
> @sonvnn you can configure conditions based on the Joomla version using the JVERSION constant so that the framework works with all versions of Joomla

Yes I just wanted to ask if there is no option like:
`if else j4 or j5`

**Comment by salahjaafar** [comment]
**Description:**

This code snippet is designed to retrieve the major version of the Joomla CMS using the `Joomla\CMS\Version\Version` class. It then checks the Joomla version and prints a message based on the major version.

**Code Explanation:**

```php
use Joomla\CMS\Version;

// Get the Joomla CMS version
$joomlaVersion = Version::MAJOR_VERSION;

if (strpos($joomlaVersion, '5') !== false) {
    echo 'Joomla 5';
} elseif (strpos($joomlaVersion, '4') !== false) {
    echo 'Joomla 4';
} else {
    echo 'Unknown Joomla version';
}
```

- The `use Joomla\CMS\Version;` statement imports the `Version` class, allowing us to access Joomla's version information.

- `$joomlaVersion = Version::MAJOR_VERSION;` retrieves the major version of the Joomla CMS.

- The code then checks if the Joomla version contains '5' or '4' and prints the corresponding message. If neither condition is met, it prints 'Unknown Joomla version.'

**Usage:**

You can incorporate this code into your Joomla extension or wherever you need to determine the Joomla CMS version dynamically.

Feel free to reach out if you have any questions or suggestions!

---

**Comment by sonvnn** [comment]
@salahjaafar @Joomlaplates It's not necessary. We can not use both of them in one file like this
```
use Joomla\CMS\Filesystem\File;
use Joomla\Filesystem\File;
```
It will raise error. We can `use Joomla\CMS\Filesystem\File`  right now. It compatible with J4 and J5. And wait Joomla 4.4 update. I reported issue to Joomla in https://github.com/joomla/joomla-cms/issues/42460

**Comment by salahjaafar** [comment]
@sonvnn Well done and to be continued...

**Comment by sonvnn** [comment]
@dgrammatiko @salahjaafar @Joomlaplates Yes I know it. Actually, I don't want to mess up my code with this stupid option. I think instead of arguing which function should be used. Why don't we ask Joomla team to fix it. Please follow me on https://github.com/joomla/joomla-cms/issues/42460

**Comment by salahjaafar** [comment]
@sonvnn Alright, you're right, it's an optional feature. However, maybe if you add a textarea field to easily insert the SVG code, as seen in the template at https://github.com/C-Lodder/lightning, that could be a good idea.

**Comment by salahjaafar** [comment]
Hi everyone,

@sonvnn @dgrammatiko @Joomlaplates I wanted to share an interesting find regarding a version comparison function in Joomla. While digging into the source code of a plugin I'm currently using, I came across a noteworthy use of the `version_compare(JVERSION)` function.

This function is employed to compare the Joomla version with a specified value, and in this particular case, the comparison is made against version 4. The idea is to ensure that the plugin remains compatible with the latest Joomla versions.

If this piques your interest, the plugin in question is the "Simple Image Gallery" developed by JoomlaWorks. You can learn more about its functionality by following this link: [Simple Image Gallery](https://www.joomlaworks.net/extensions/free/simple-image-gallery).

I find the use of `version_compare` in the context of Joomla extensions to be an intriguing approach for ensuring smooth compatibility with different CMS versions. If you have other examples or similar experiences, feel free to share them.

Happy exploring, everyone!
