### ISSUE TITLE
Failed opening required 'mpp\htdocs\mysite\templates\astroid_template_zero\html\mod_menu\default.php' (include_path='D:\xampp\php\PEAR')

### ISSUE THREAD

**Issue by StephanL72** [templaza/astroid-framework#486]
Hello, 

my frontend on XAMPP doesn't run anymore sine i've updated J4.4.1 and Astroid 3.0.6 
Error message:
**Failed opening required 'mpp\htdocs\mysite\templates\astroid_template_zero\html\mod_menu\default.php' (include_path='D:\xampp\php\PEAR')**

But the file **default.php** is in the mentioned folder.
Anybody an idea?

**Comment by Chacapamac** [comment]
@StephanL72 

**On Mamp —> PHP 8.1.13**

**Template One**
— On Joomla 4.4.0, I first Update Astroid 3.0.4 to 3.0.6 — No errors after deleting all caches frontend or backend
— After update to Joomla 4.4.1 —  No errors & No errors in the console. 

After, passing to “**Templae Zero**” — No errors

**Comment by StephanL72** [comment]
Hey @Chacapamac, thank you very much! It's really strange...I've the same problem with another which was exactly the copy of a live site running on a webserver without any problems. Local on XAMP:

**Warning: include(D:\xampp\htdocs\website-name\libraries/../templates/system/fatal.php): Failed to open stream: No such file or directory in D:\xampp\htdocs\website-name\libraries\vendor\symfony\error-handler\ErrorRenderer\HtmlErrorRenderer.php on line 353

Warning: include(): Failed opening 'D:\xampp\htdocs\website-name\libraries/../templates/system/fatal.php' for inclusion (include_path='D:\xampp\php\PEAR') in D:\xampp\htdocs\website-name\libraries\vendor\symfony\error-handler\ErrorRenderer\HtmlErrorRenderer.php on line 353**

But the backend is reachable. When I logged in and click on Site Template Style (URL = localhost/website-name/administrator/index.php?option=com_templates&view=style&layout=edit&id=19) there's furthermore an error...

XAMPP ist running with PHP 8.2. Framework is Astroid 2.6.6

Any idea? Thanks a lot!!!!

**Comment by sonvnn** [comment]
@StephanL72 Please update your Astroid first. It's out of date.

**Comment by Joomlaplates** [comment]
`Failed opening required 'mpp\htdocs\mysite\templates\astroid_template_zero\html\mod_menu\default.php' (include_path='D:\xampp\php\PEAR')`
I´ve just checked this issue and it happens only on a local server and not on an online server. Maybe its a problem with the PHP pear path and Windows. Same here:
`Failed opening required xxx\html\layouts\chromes\astroidxhtml.php' (include_path='.;C:\php\pear')`

**Comment by Chacapamac** [comment]
@Joomlaplates 
**I don’t know if that can help you?** —> https://stackoverflow.com/questions/71838904/failed-opening-pear-within-trying-database-connection

It work for me on MAMP

**Comment by StephanL72** [comment]
Yes I think this is the problem. I've tested this right now in another web project:

**ERROR 0 - Failed opening required 'mpp\htdocs\my-website\templates\astroid_template_one\html\layouts\chromes\astroidxhtml.php' (include_path='D:\xampp\php\PEAR') in D:\xampp\htdocs\mywebsite\templates\astroid_template_one\html\layouts\chromes\astroidxhtml.php:17**

Joomla 5.0.1, Astroid Framework 3.0.7, Astroid Plugin 3.0.5 und Xampp v3.3.0, PHP Version 8.2.0

But how can I guarantee to have the same working version on the web server and on my local server? Do I have to update XAMPP anyway?

**Comment by Chacapamac** [comment]
@StephanL72 
Not sure if it can help!
Find this —> [Require(): Failed opening required (include_path='.;C:\xampp\php\PEAR')]
Look at the answer that help in this post.
https://stackoverflow.com/questions/35994857/require-failed-opening-required-include-path-c-xampp-php-pear

**Comment by StephanL72** [comment]
@Chacapamac thanks a lot. I've tried to change the inlude part from my php.ini as described but this causes another error and seems to be strange to me. 

The **astroidxhtml.php** is within the described folder from the template. In line 17 there's no include:

```
`<?php

/**
 * @package   Astroid Framework
 * @author    JoomDev https://www.joomdev.com
 * @copyright Copyright (C) 2009 - 2020 JoomDev.
 * @license https://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 or Later
 */

defined('_JEXEC') or die;
extract($displayData);

$moduleTag     = $params->get('module_tag', 'div');
$headerTag     = htmlspecialchars($params->get('header_tag', 'h5'), ENT_COMPAT, 'UTF-8');
$bootstrapSize = (int) $params->get('bootstrap_size', 0);
$moduleClass   = $bootstrapSize != 0 ? ' span' . $bootstrapSize : '';

// Temporarily store header class in variable
$headerClass = $params->get('header_class');
$headerClass = $headerClass ? ' class="module-title ' . htmlspecialchars($headerClass, ENT_COMPAT, 'UTF-8') . '"' : ' class="module-title"';

$content = trim($module->content);

if (!empty($content)) :
?> <<?php
    echo $moduleTag;
    ?> class="moduletable <?php
                            echo htmlspecialchars($params->get('moduleclass_sfx'), ENT_COMPAT, 'UTF-8') . $moduleClass;
                            ?>">
        <?php
        if ($module->showtitle != 0) :
        ?>
            <<?php
                echo $headerTag . $headerClass . '>' . $module->title;
                ?></<?php
                    echo $headerTag;
                    ?>> <?php
                    endif;
                        ?> <?php
                            echo $content;
                            ?> </<?php
                                    echo $moduleTag;
                                    ?>> <?php
                                    endif;
                                        ?>`
```
So where does the include starts? My error reporting:

![Screenshot 2023-12-20 153234](https://github.com/templaza/astroid-framework/assets/152803315/6db82031-851a-4af1-a5cf-f21a02a7a089)

Backend is still running. Would it help to delete all Astroid stuff and install everything new...or the long way to set up the page with a new installation (problem is then I will lose all the articles, modules, categories........

**Comment by Chacapamac** [comment]
I will try first to reinstall the newest version you can that include both templates.
Did you try with Cassiopea?

**Comment by StephanL72** [comment]
@Chacapamac What do you mean with "reinstall newest version"? Template One and Zero?

It's really strange Cassiopeia ist working and Astroid Template One too! But when I create a child template from Astroid One Template...I reveive the same error! This is really weird!

**Comment by StephanL72** [comment]
I uninstalled everything in my Joomla V5 now and reinstalled the latest version from GitHub (Astroid 3.0.7) and now I have the same error when I switch either Zero or One...

I think I try to setup a complete new Joomla. Is there a clever way to transfer all the articles, modules, catergories etc. into a new installation? When I import the old database I assume I will have the same problem...

**Comment by Chacapamac** [comment]
> It's really strange Cassiopeia ist working and Astroid Template One too! But when I create a child template from Astroid One Template...I reveive the same error

Ok, logically, it seem that the Child Template is causing the problem...

• Did you try to Duplicate the **Astroid original Template layout** and importing your problematic **Child Template layout** setting (not Using a Child Template) ?

• or trying to create another Child Template Layout and import?

**Comment by StephanL72** [comment]
Hey @Chacapamac thanks for your help - really appreciate it!
I cannot test it because neither One nor Zero is now working...

What I will try is to setup a totally new Joomla 5 with highest version of Astroid. Then normally create a child template from One or Zero and set up my site on it. As far as I know there's no other way to create a new Astroid template than by child template...or is there an alternative (better) way???

**Comment by StephanL72** [comment]
After testing and testing, setting up new joomla 5, go step by step I found the problem what causes the error:

**ERROR 0 - Failed opening required 'mpp\htdocs\mysite\templates\mytemplate\html\layouts\chromes\astroidxhtml.php' (include_path='D:\xampp\php\PEAR') in D:\xampp\htdocs\mysite\templates\mytemplate\html\layouts\chromes\astroidxhtml.php:17**

**It's the offcanvas menu**! When I publish a module / menu to the offcanvas position the front page crashes with the mentioned error. In standard the module is set to "inherit" (Vererbt in German):

![Screenshot 2023-12-21 143652](https://github.com/templaza/astroid-framework/assets/152803315/f591889e-9d1f-49b3-9f8d-0efa236c71b0)

you need to set the module style to **html5** (or something else):
![Screenshot 2023-12-21 144108](https://github.com/templaza/astroid-framework/assets/152803315/af925639-216c-44fd-8c5c-e4d1e2643136)

Then the front page is fine and the offcanvas menu will work as well!

**Comment by Chacapamac** [comment]
@sonvnn  Can you look at the previous post.
I do not test Joomla 5 yet.

**Comment by Chacapamac** [comment]
@StephanL72 
I’m looking at that documentation page and I do not have a “**Copy Template**” like the documentation show ??????
 https://docs.astroidframe.work/get-started/creating-a-basic-astroid-template

**I’m on Joomla 4.4.1, Astroid 3.0.7, maybe this is the problem?** 

**Anyway to you question:**

> As far as I know there's no other way to create a new Astroid template than by child template...or is there an alternative (better) way???

**In Joomla 4.4.1, Astroid 3.0.7, You have two way.**
1. the “**Child Template**” way. Probably the best way too always have an untouched, clean, independent original template, and a “**Child Template**” that you can messed up without fear... 😃
— This is done passing by the “**Template**” page showed in the documentation 
_As you can see on my screenshot, no “Copy Template” button there (Maybe in Joomla 5?????)_

![Screen Shot 2023-12-21 at 2 00 52 PM](https://github.com/templaza/astroid-framework/assets/1907276/ea2fbc7b-1ca4-47c2-a236-75b6abdb2db7)

2. You can also just duplicate  the original Astroid layout to a custom layout and build your website on that “Custom layout leaving the **Original Astroid layout untouched**. This is the “Old way to do in Joomla. Like that you always have an Untouched Original Layout as Master.
— This is done directly in the Astroid Layout Manager

![Screen Shot 2023-12-21 at 2 08 18 PM](https://github.com/templaza/astroid-framework/assets/1907276/1df57389-2cc9-495c-bf50-6f82e79aaffa)

**Comment by Joomlaplates** [comment]
Ok guys it has nothing todo with the template.
Some local Webservers using PHP PEAR and this path to pear.ini is not existing in Windows or is wrong
Open the php.ini file and search for this line
`include_path = ".;${US_ROOTF}/home/us_pear/PEAR"`
And comment it out. Now start your Server again and it should work.
![pear](https://github.com/templaza/astroid-framework/assets/71080509/d8b3cd76-7eef-40b5-a0e5-f616657b1f25)

Regards and Merry Christmas

**Comment by Joomlaplates** [comment]
Guys, it has nothing todo with child template or module layout html5 or anything else.
....
I copied the file **astroidxhtml.php** from 
`Joomla\libraries\astroid\framework\html\layouts\chromes`
to
`Joomla\templates\your_template\html\layouts\chromes`
..
and it works.
After Sonny changed the astroidxhtml.php and load it from astroid and not from template anymore it happend!
Dont ask me why he changed this! maybe coz of compatibility of J5...
Regards Peter

**Comment by sonvnn** [comment]
@StephanL72 I don't know why this issue happens because the System works well on my side. (On live server, localhost, Xampp, etc)

I tried to revert function loadLayout to legacy function in https://github.com/templaza/astroid-framework/commit/eed1db3499514a8bd4f002362e3d2c4e113f0f91

You can download Zero latest version here https://github.com/templaza/astroid-framework/archive/refs/heads/zero-template.zip and test on your localhost.

I think it will works.

Thanks & Best Regards,
Sonny

**Comment by sonvnn** [comment]
> Guys, it has nothing todo with child template or module layout html5 or anything else. .... I copied the file **astroidxhtml.php** from `Joomla\libraries\astroid\framework\html\layouts\chromes` to `Joomla\templates\your_template\html\layouts\chromes` .. and it works. After Sonny changed the astroidxhtml.php and load it from astroid and not from template anymore it happend! Dont ask me why he changed this! maybe coz of compatibility of J5... .. **Anyay I have this issue only on local Xampp Servers with Windows and not on my online Server** Regards Peter

@Joomlaplates Imagine when Joomla 6 is released. And the functions you are currently using are deprecated. You only need to update in one place, the Framework, instead of the 100 templates you have created. How easy and simple will the job become? I think that is main reason.

Thanks & Best Regards,
Sonny

**Comment by Joomlaplates** [comment]
@sonvnn Ohh yes youre right. Better update it only in framework and not in templates files.
Anyway, like I wrote above. It works with all online server but not on local server. I think it has something todo with PHP Pear on local server in windows!
Regards Peter

**Comment by Joomlaplates** [comment]
Just a simple question.
Is the current file in
`html/layouts/chromes/astroidxhtml.php`
now ready for J5 and J6 or you chnaged this file to deprecate function to make it work because of the issua above??

**Comment by Joomlaplates** [comment]
But the file from ONE Template you changed too and its compatible with J5 and J6
[one_template/html/layouts/chromes/astroidxhtml.php](url)
Regards Peter

**Comment by sonvnn** [comment]
Both of them will work with J5 and J6 right now. You can test it. If you find any issue please report here. I will check it.

**Comment by StephanL72** [comment]
@sonvnn 
I just wanted to add that I do not have further problems now. When I setup a new Joomla 5 I do the following steps without error
-set up new Joomla 5x
- if neccessary I import database from old site (because of the articles, categories, modules....)
-  Install Extension Astroid Framework + Template
- Delete Zero or One Template (One is enough)
- Create a copy of One or Zero template in my file system and drop all the files under **/templates/mytemplate**
- Use the menu "Überprüfen" (German) = "Check", then the new template is detected and could be installed
- Import JSON in Astroid from old template (if needed)
- transfer any missing files into media/templates/site/mytemplate (like SCSS, JSON...)

and everything is fine!! I am very happy with Astroid 3.X It's really a great tool for building great modern websites fast and robust! I've build a lot of websites in my life ;-)
A big compliment to the developer(s)!!
