### ISSUE TITLE
Problem loading astroid javascript files

### ISSUE THREAD

**Issue by vtheod** [templaza/astroid-framework#488]
Hello @sonvnn 

Today I noticed a bug in astroid since version 3.0.3 (3.0.2 works fine).
I have a site in coming soon mode and realized that the countdown was not working, as well as the background video. As I saw in the console, astroid was trying to load all javascript files from /vendor/astroid/js/ and not from /media/astroid/assets/vendor/astroid/js/.
Also, the js folder misses most scripts (only countdown.min.js exists).
I was forced to roll back to astroid 3.0.2 for the site to work.

Can you please check it?

**Comment by sonvnn** [comment]
This error happens because you override the comingsoon.php file in your zero template. I renamed it to comingsoon__.php. Then your site worked fine.
![Screen Shot 2023-12-05 at 11 13 55](https://github.com/templaza/astroid-framework/assets/3204103/4f36bdb5-a63a-4f4b-ba77-6db6e90915cb)

**Comment by vtheod** [comment]
Oh my bad, I forgot that!
Sorry for this...
