### ISSUE TITLE
error after uninstalling a package

### ISSUE THREAD

**Issue by SerGun78** [templaza/astroid-framework#49]
Hey! Found another Astroid bug.
When removing the package (Framework + template 0 + 1), an error message for the Astroid plugin appears.
You will have to delete it through the MSQL database.

**Comment by sonvnn** [comment]
I fixed it in https://github.com/templaza/astroid-framework/commit/e68cd4e1289c55f685b51ecb20a36ab8ccf04b0c

Thanks & Best Regards,
Sonny

**Comment by SerGun78** [comment]
Did not help:
![изображение](https://user-images.githubusercontent.com/95705148/145883346-80df7941-3c5f-4137-9559-f95969f0300a.png)

**Comment by sonvnn** [comment]
Hello,

You are using Master branch. You should download developer branch instead of master branch. I did not merge them yet. You can download developer branch at https://github.com/templaza/astroid-framework/archive/refs/heads/developer.zip

Best Regards,
Sonny

**Comment by SerGun78** [comment]
When you uninstall the package, the Astroid plugin still remains:
![изображение](https://user-images.githubusercontent.com/95705148/145974135-52ef4713-be30-40fc-9209-9cd60fd67283.png)

**Comment by sonvnn** [comment]
Hi @SerGun78,

I will update to uninstall plugin in the next update. 

Thanks,
Sonny
