### ISSUE TITLE
Asteroid takes over all templates

### ISSUE THREAD

**Issue by N6REJ** [templaza/astroid-framework#491]
Once you install asteroid 3.0.6 it takes over as the only template even when you've deselected it as the active template.
It doesnt' matter what the menu assignments are.

**Comment by Chacapamac** [comment]
Sorry, in my case it work, but you have to reassign the menu items. I try switch to Cassiopea as the default template without reassigning the menu, for sure, after reload, Astroid is still showing because the menu is still assign to it’s template.

**Comment by N6REJ** [comment]
looks like it was a chaching issue.  What is the difference between asteroid zero and one & the regular framework.  I see 3 downloads.

**Comment by Chacapamac** [comment]
> What is the difference between asteroid zero and one

I think it is not to much difference. I use both in projects and still not sure about the differences.
By logic using the One should bring modifications to improve Zero, not sure. I use One now.

Maybe @sonvnn  can respond better on that.
Good Day!

**Comment by sonvnn** [comment]
@Chacapamac thanks for support! 

- Astroid frameword is core library framework. It is required for all Astroid Joomla templates
- Zero and One are Joomla templates like Cassiopea. You can choose one of them to use for your website
