### ISSUE TITLE
Where are the buttons for Bootstrap and JQuery in the plugin?

### ISSUE THREAD

**Issue by WM-Loose** [templaza/astroid-framework#492]
Hi Sonny,
where can we make the settings now in Astroid 3.0.7? 
Until now, the buttons were always in the plugin.

Issue?

![1](https://github.com/templaza/astroid-framework/assets/99647423/83f30988-8707-47b7-b599-04b1e7fe81a1)

**Comment by sonvnn** [comment]
jQuery, Bootstrap will be loaded from Joomla core, only. So these functions are no longer needed.
