### ISSUE TITLE
Page does not display created article

### ISSUE THREAD

**Issue by Maury-Maia** [templaza/astroid-framework#494]
After creating an article and a menu item for "Single Article", the page that loads does not show the article, only other items inserted in the layout.
When I select the Theme Style as "Cassiopeia - Default", the page is shown with the text of the article, but with the formatting of the indicated theme.
If you select other options, the result is the same.
What can be done in this case?

**Comment by salahjaafar** [comment]
Can you send a preview and the versions of the Joomla CMS and Astroid Framework used?

**Comment by sonvnn** [comment]
@Maury-Maia may you send me your admin acc? I will help you check issue. My email is sonlv@templaza.com

Best Regards,
Sonny

**Comment by Maury-Maia** [comment]
> @Maury-Maia Can you procure the url of the page seem here on both framework? Are they different?
> 
> I ask, because the view on Astroid ( I guess the one on top) is totally different, the right column (where the Login is) is not even there?

Chacapamac,

I am generating a specific layout using Astroid. the first image is the layout of a page to present an article. The Cassiopeia page is the default.
When I noticed that the article did not appear on the page, that is, a page without the text, one of the attempts to find the problem was to change the default template from Astroid to Cassiopeia.
Today, on a localhost, I reversed the order, I created an article, a category and a menu item in Cassiopeia and installed Astroid and configured it to be the default template.
No problems occurred and the article continued to load when the page was called.
I'm starting to believe that I may have changed some configuration or deleted some element and caused the problem.
As I already mentioned, I'm a beginner and I'm learning how to configure and set up a website using Joomla and Astroid, which, by the way, proves to be extraordinary in terms of what it allows you to do.

**Comment by sonvnn** [comment]
@Maury-Maia Your layout builder does not include Component element. Single Article displays by Content Component. So you have to insert Component element to display all Content view or others component.
![Screen Shot 2023-12-09 at 14 26 49](https://github.com/templaza/astroid-framework/assets/3204103/f16fb40c-6965-498d-8e17-d0e22872ddc6)

Click add element -> Component element here
![Screen Shot 2023-12-09 at 14 29 48](https://github.com/templaza/astroid-framework/assets/3204103/350b9f62-5160-4619-b549-9d66ae5d58eb)

**Comment by Maury-Maia** [comment]
Dear Mr. Sonny,

Thank you for your attention and guidance.

  Dear Mr. Chacapamac,

I appreciate your interest and as I predicted, it was a simple rookie mistake.

Best Rgards everyone!
