### ISSUE TITLE
Vertical distance between sections

### ISSUE THREAD

**Issue by Maury-Maia** [templaza/astroid-framework#495]
Dear sirs,

How is the vertical distance between sections adjusted in the Layout?

Best Regards!

**Comment by sonvnn** [comment]
You can use padding/margin options in Section layout -> Design settings

**Comment by Maury-Maia** [comment]
Dear Mr. Sonny,

I appreciate your response.

I apologize because I was hasty and formulated my question incorrectly.

The question is, whether there is an instance above the Astroid Layout that defines parameters and is not influenced by the Astroid settings.
I have sections where even the "padding/margin" has a value of "0" or no value, there is still a space of around 20 to 30 pixs between them.
In a section, react with the configuration established in "padding/margin".

As this website was developed in Joomla 3, and I am updating and modifying it, please disregard the issue at this time.
It will be migrated to version 4, and after resolving any situations that may arise, I will check the issue again and post any questions that arise.
I'm sorry that I've taken up your time now, I thank you again and ask for your understanding.

Best Regards

**Comment by Chacapamac** [comment]
@Maury-Maia 
Did you try a “**Without**” or “**Custom**” Container?

![Screen Shot 2023-12-11 at 11 09 06 AM](https://github.com/templaza/astroid-framework/assets/1907276/9e1f2b6a-b3eb-45a9-ad6b-368c60074424)

**Comment by Chacapamac** [comment]
@Maury-Maia 
Happy to help!

> do not change the height or distance to the sections above and below.
If you want, you can play with the custom setup of the margin/padding of all the sections you want to change.

> By clearing the "Custom Class" option, section reduced the distance between sections to between 10 and 12 px.
Ok thats a bit weird, maybe @sonvnn  can have a look, probably something with the Section template?
**• What is the precise option you choose for the Section?**

I see you reopen the discussion, do you have another issue?
