### ISSUE TITLE
Logo in Sticky Header is not shown

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#5]
He there, 
the logo in sticky header ( Joomla4, Astroid 2.5.5,) is not shown. Any script set an inlne css > display:none
```
.astroid-logo .astroid-logo-sticky {
    display: none;
}
```
![sticky-header](https://user-images.githubusercontent.com/71080509/140200803-8e3fce53-69e4-4c1b-a729-39b4864defcb.jpg)
![sticky-header-logo](https://user-images.githubusercontent.com/71080509/140200811-99fea752-ba8b-4b5f-afb2-ada8f8f29988.jpg)

**Comment by sonvnn** [comment]
Hi Joomlaplates,

I fixed it at https://github.com/templaza/astroid-framework/commit/4068b007635927f9413a86b0b2e6f2c75e4c858c
I will soon release fixbug version in the next 24h.

Thank you for your support.
Best Regards,
Sonny

**Comment by Joomlaplates** [comment]
Hi Sonny,
wow youre fast.. Even better than Joomdev.
I really appriciate this, perfect.
Many thanks, best regards Peter
