### ISSUE TITLE
Change image window too small on editing article

### ISSUE THREAD

**Issue by mac-joomla** [templaza/astroid-framework#500]
Hello,

there is a problem on editing an article in frontend with astroid template active. If you are going to change any image it opens the dialog window "Change Image", but it is much too small to work with as you can see in attached screenshot.
<img width="1082" alt="Astroid-Bug-change-image" src="https://github.com/templaza/astroid-framework/assets/87974913/f5e1858b-bff5-4d9a-af29-c8431df3aadc">
Thank you and best regards

**Comment by Joomlaplates** [comment]
Hello, please more information! Joomla Version, Template and Version? Astroid?

**Comment by mac-joomla** [comment]
Oh sorry, here we are:

**Joomla! 5.0.1 Stable
PHP Version 8.2.11
Astroid Framework 3.0.7
astroid_template_zero 3.0.5
Browser Safari and Chrome on MacOS 13.6.1**

It is working fine with Cassiopeia

Thank you and best regards

**Comment by sonvnn** [comment]
@mac-joomla Thank you for report issue!
I fixed this issue in https://github.com/templaza/astroid-framework/commit/e8f35e46af5e2a7fcd79623181fde233819e4d74

Please help me download v3-branch and retest again. After upload astroid-v3, you have to clear Astroid cache to force Astroid recompile scss.

Result on my localhost below

![Screen Shot 2023-12-13 at 15 49 25](https://github.com/templaza/astroid-framework/assets/3204103/8581e869-5600-47a3-8c3d-7fedd9883c92)

Best Regards,
Sonny

**Comment by mac-joomla** [comment]
Hello @sonvnn thank you for your fast help. Window size is perfect now. Unfortunately in my case I have no icons showing  just somehow placeholders or a wrong font. You can take a look at my screenshot. Do I have to do something special to activate font awesome? I think before the update the icons has been there, but now I am not sure.
<img width="1086" alt="no-icons" src="https://github.com/templaza/astroid-framework/assets/87974913/5d93e74f-0a14-4c6f-b04a-8a30119f960f">
Thank you and best regards

**Comment by sonvnn** [comment]
Because Fontawesome does not load. Please help me check System-> plugins -> Astroid plugin -> Fontawesome -> switch between local or cdn

**Comment by mac-joomla** [comment]
Yes, there I have been. It's been configured to Local and then I switched to CDN (don't even know what that means), but unfortunately no icons to see. I am frequently clearing astroid and Joomla and browser cache.

**Comment by sonvnn** [comment]
May you send me your link and admin account via sonlv@templaza.com? I will help you check it :)

**Comment by mac-joomla** [comment]
Thank you very much, link and account is on the way to you 👍

**Comment by sonvnn** [comment]
@mac-joomla The issue happens because Zero template is out of date. I updated component.php file https://github.com/templaza/astroid-framework/commit/9bbdf95af2376964dac13790f3e6651ba641ba2a Now your site works well. Please help me check it.

**Comment by sonvnn** [comment]
@mac-joomla I will try to release a basic version of Two in the next week. Please wait for update! I will inform on Github and Astroid group https://www.facebook.com/groups/astroid/

Thanks & Best Regards,
Sonny
