### ISSUE TITLE
Sticky Header on Mobile doesn't work

### ISSUE THREAD

**Issue by strizhakovanatalya** [templaza/astroid-framework#502]
Hello.
Sticky Header on Mobile does not work in Astroid v3.0.7, but Sticky Header on Desktop and on Tablets works fine.
Also Sticky Header on Mobile, on Desktop and on Tablets works fine in Astroid v3.0.6
Please look strizh.com.ua

**Comment by Joomlaplates** [comment]
Hello, I can confirm this issue.
But the sticky header is working, only the logo is missing because of the css like that
```
.astroid-logo .astroid-logo-sticky {
  display: none;
}
```
Regards Peter

**Comment by sonvnn** [comment]
@Joomlaplates @strizhakovanatalya Opp! Sorry this is my mistake. I fixed this issue in https://github.com/templaza/astroid-framework/commit/c545910b9b49b20598a8067c6a66d42d336ebedc

Please help me confirm if it solved your issue. I will soon release fixbug version.

Best Regards,
Sonny

**Comment by Joomlaplates** [comment]
Hello Sony, I can confirm the V3 is working.
Thanks for fast response.
Regards Peter
