### ISSUE TITLE
module-title class is not available anymore

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#503]
Hello Sony, 
since you changed the html override (astroidxhtml.php) the **module-title** class is not available anymore.
Can you add the class again to
`framework/html/layouts/chromes/astroidxhtml.php`
Or is there a reason why you delete this class from **astroidxhtml.php** file?
Regards Peter

**Comment by sonvnn** [comment]
@Joomlaplates Do you mean `header-class`? It is still here.
![Screen Shot 2023-12-13 at 14 33 11](https://github.com/templaza/astroid-framework/assets/3204103/ff26ba53-9549-4e1b-96c0-cef193059e88)

https://github.com/templaza/astroid-framework/blob/master/framework/html/layouts/chromes/astroidxhtml.php#L26

![Screen Shot 2023-12-13 at 14 36 12](https://github.com/templaza/astroid-framework/assets/3204103/9f10eaf2-651f-4fe6-a917-9c0818591a8d)

Please tell me if you I mis-understand something.

Best Regards,
Sonny

**Comment by Joomlaplates** [comment]
Hello Sony, yes youre right!
But before the class was set automatically to **module-title**
`$headerClass = $headerClass ? ' class="module-title ' . htmlspecialchars($headerClass, ENT_COMPAT, 'UTF-8') . '"' : ' class="module-title"';`
Anyway, if I can add the class manually, so there is no problem.
I just wanne know why you removed the module-title class.
Regards Peter

**Comment by sonvnn** [comment]
@Joomlaplates Ahh Okay! I understand 👍 
I re-add module-title to module layout here https://github.com/templaza/astroid-framework/commit/9ad69f7b5e9f8942d4697cc3d975f9708a10cc35

Please help me test and confirm if it works. I will soon release new version :)

Best Regards,
Sonny

**Comment by sonvnn** [comment]
@Joomlaplates I just copy source file from Joomla core to replace old version, LOL. But no worry! I re-added 'module-title' again. You can download v3 and retest again. I think It should work :)

**Comment by Joomlaplates** [comment]
Hi Sony, yes it works!
Thanks, friendly regards
