### ISSUE TITLE
Error when I want to export preset profile

### ISSUE THREAD

**Issue by deltapapa01** [templaza/astroid-framework#508]
Hello,
I have noticed an error when I want to export preset profiles. I have tested it on 2 sites, Astroid Fw 3.0.7 and Zero Template 3.07: Not all data is written to the JSON file.
I tried to import a preset profile from one site to the other (also Fw and Tpl both 3.0.7), and always got the error Invalid File.
Then I had a look in the JSON file, and that's all it says. Both pages are Joomla 4.4.1.

![image](https://github.com/templaza/astroid-framework/assets/19833064/36408cf7-3bfc-4b7d-8c58-49e73e847c59)

Now I have exported a present profile test-wide from a Joomla 5.0.1 and Fw + Zero 3.0.7 and looked inside, there is much more information inside. This file is also significantly larger (904KB to 74.785KB)

![image](https://github.com/templaza/astroid-framework/assets/19833064/965dbcb3-e749-482d-a6a2-abdafe9335da)

So there seems to be something wrong with the creation of the present profile.

WBR,
deltapapa

Translated with DeepL.com (free version)

**Comment by deltapapa01** [comment]
Okay, i test somthing with my sites, i update on of the both testsites to J5.0.1, it's always the same, the present profile is only 904 kb big and only the text i posted above was in there.

**Comment by Joomlaplates** [comment]
Hello, Sony will take a look on Monday but I can say that it works on all of m sites (80).
I think there is something wrong with your rights of the folder on your server.
..
Anyway I can give you an alternate solution without export function to get the styles.
You can find all styles on your server folder and download them manuallly with FTP. All files are stored in
`Joomla Root//media/templates/site/your template/astroid/presets/ Json Files...`
MfG Peter

**Comment by deltapapa01** [comment]
Hi Peter,
thank you very much, this json file is 124Kb big, it has all information i need.
Thats work for me, i do need this on only one site to import.

WBR and i wish a good "Drittes Adventswochenende" 😊

**Comment by Joomlaplates** [comment]
Thanks, I cose this thread
Danke, schönen Sonntag
