### ISSUE TITLE
Just update from 3.0.6 to Astroid 3.0.7, all Bootstarp code not loading?

### ISSUE THREAD

**Issue by Chacapamac** [templaza/astroid-framework#509]
I just update a n Astroid Demo from Astroid 3.0.6 to 3.0.7 and nothing Bootstrap coming in the “**Network**” pane of my web inspector.
**Both on Joomla 4.4.1 ?**

![Screen Shot 2023-12-16 at 10 12 57 AM](https://github.com/templaza/astroid-framework/assets/1907276/c2c650c1-d56f-4482-88f7-f8823f716eee)

![3 0 7](https://github.com/templaza/astroid-framework/assets/1907276/0474a98e-77b9-4cfa-8112-87fd1dfd5ec4)

**Comment by sonvnn** [comment]
Please go to template options > Bootstrap Settings >> select your Bootstrap Libraries.

Thanks & Best regards,
Sonny

**Comment by Chacapamac** [comment]
Thanks @sonvnn 
— It is also normal that no Bootstrap css (like before “bootstrarp.min.css”) is loaded?
— Even Joomla seem to load nothing Bootstrap?

I’m not sure that it will be easy for casual users to use this. It take me some testing and research to just make a Bootstrap Tabs transforming to Accordion on small screen section to work without loading everything.
  
Maybe Astroid should also offer something easier for newbies to load bootstrap (Like it was in the plugin before) or ideally in the same  template options > Bootstrap Settings >> select your Bootstrap Libraries to have both a “pro” way and an user-friendly way to control Bootstrap

**Comment by Joomlaplates** [comment]
Hello,
1.) Joomla is loading the basic Bootstrap files for the layout > breakpoints, container ect
2.) If you want to use the additional Boostrap components > Accordion and so on, you can load them via Astroid
https://getbootstrap.com/docs/5.3/components/accordion/

**Comment by Chacapamac** [comment]
To make it work , I just have to put on Bootstrap “**Collapse**” & ”**Tab**”.

![Screen Shot 2023-12-17 at 5 50 45 AM](https://github.com/templaza/astroid-framework/assets/1907276/6b845d32-298d-43d1-a7d7-22b631eaf713)

**I still think that a foolproof setting should be added to be sure that Newbies can easily put Boostrap and keep the more advanced actual system**
