### ISSUE TITLE
Error: 0 Attempt to assign property "attribs" on array

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#51]
Joomla 4.0.4 / Astroid 2.5.11
Frontend Article Edit in PHP 8 brings the following error, and only in PHP 8. Cassiopeia is working.
The Module editing i working.
**Error Message**
`0 Attempt to assign property "attribs" on array`

**Line 179 \libraries\astroid\framework\library\astroid\Helper\Client.php**
`$data->attribs = $data->params;`

![frontend](https://user-images.githubusercontent.com/71080509/145704945-b7bcdd34-26e1-43dd-bd15-48f4790d57dd.jpg)

**Comment by sonvnn** [comment]
I will check on my demo and response you soon.

**Comment by woluweb** [comment]
Same here.
I went back from PHP8.0 to PHP7.4 and then Front-End Saving works again.

**Comment by sonvnn** [comment]
Hi @Joomlaplates , @woluweb 

I fixed this issue in https://github.com/templaza/astroid-framework/commit/8fed7ae4746ec203c04e0195b02ea45d92895bf8

Please help me check it again.

Thanks & Best Regards,
Sonny

**Comment by woluweb** [comment]
Txs @sonvnn
Tested successfully on 1 website
(by re-enabling PHP8.0.13 and seeing that the error msg is not there any more when editing from front-end)
