### ISSUE TITLE
Layout Issues in RTL Version of the Zero Template

### ISSUE THREAD

**Issue by salahjaafar** [templaza/astroid-framework#511]
Dear Astroid Framework Team,

I hope this message finds you well. I wanted to bring to your attention an issue I've encountered in the RTL version of the Zero template on the Astroid framework. Through testing, I've identified two significant layout problems that impact the user experience. I believe addressing these issues would greatly contribute to the overall quality improvement of the template.

1. **Incorrect Dropdown Menu Positioning:**
   When the site is configured in RTL mode, the dropdown menu appears to be improperly positioned. This creates an uncomfortable user experience, and it would be beneficial to review the menu positioning to ensure proper alignment in right-to-left written languages.

2. **Alignment Issue with ul li Bullet Icons:**
   The bullet icons in unordered lists (ul li) are currently overlapping with the text in the RTL version. It is essential to rewrite the associated CSS code to ensure proper alignment of these elements, providing a consistent visual presentation.

To help you visualize these issues, I have recorded a video of the current situation. You can view it by following this link: 

https://github.com/templaza/astroid-framework/assets/47123877/34b8c009-0eb6-4c6f-96f1-42991cd6e7d3

I encourage you to consider these issues in your future updates, and I am willing to provide additional information or collaborate with your team to address these concerns.

Thank you very much for your hard work on the Astroid framework, and I appreciate your attention to these potential issues.

Best regards,

Salah JAAFAR

**Comment by sonvnn** [comment]
Thank you for report issue! I will check and update in the next version. 

Best Regards,
Sonny

**Comment by Chacapamac** [comment]
Just following this!

**Comment by salahjaafar** [comment]
@Chacapamac @sonvnn

For RTL languages like Arabic:
- The sub-menu should appear beneath the link that the mouse hovers over, with the text on the right and RTL orientation.
- The sub-sub-menu should appear to the left, while keeping the text on the right and RTL orientation.
- Here's a video demonstrating how it works.

https://github.com/templaza/astroid-framework/assets/47123877/334f8359-e6fe-4dfb-816a-7dab3f37430b

Thank you for your efforts.

**Comment by sonvnn** [comment]
@salahjaafar I fixed this issue in https://github.com/templaza/astroid-framework/commit/1b81458677119982302db14e06e82a8436e43630

Let's download v3-branch for testing. Please tell me your result, so I can confirm this issue is solved.
Note: After re-install framework, you have to click Astroid Clear Cache to force Astroid recompile scss.

Best Regards,
Sonny

**Comment by salahjaafar** [comment]
Hello @sonvnn ,

I want to express my gratitude for your ongoing efforts. However, after reviewing the changes, it seems that the issues still persist. I'd like to share some suggestions that could help improve the situation:

    Change position: absolute; to position: relative; for .astroid-nav .nav-item-parent .nav-title > .nav-item-caret.
    Change transform: rotate(180deg); to transform: rotate(360deg); for .rtl .astroid-nav .nav-item-parent .nav-title > .nav-item-caret to ensure downward orientation while making sure the icon points to the left for the submenu.
    Ensure that the submenu is directly beneath the link of the main menu, rather than to the right.

I have also created a video showcasing these changes. You can view it here with your changes:
https://drive.google.com/file/d/1pJy0hkBplbkDCd7rjzXHrw1bCgkolp--/view?usp=sharing

 and here with my changes:
 
 https://drive.google.com/file/d/1_BELVUVxO3Yz5mA9IDft7zEy64t9PXsz/view?usp=sharing

Your feedback and corrections would be greatly appreciated. Thank you very much for your collaboration.

Best regards,
Salah JAAFAR

**Comment by Chacapamac** [comment]
I was thinking to be able to change the position of the sub-menu by changing the **Menu Heading** (first level) “**Drop Down**” alignment but changing from **Left** to **right** have no effect on the placement in my case, this is weird, it should?

**After testing, the sub-menus container is not moving until I change the “**Drop Down**” alignment to “Container” or “Full” ?**

**Comment by salahjaafar** [comment]
@Chacapamac Automating the alignment of text and directional orientations is imperative.

**Comment by sonvnn** [comment]
@salahjaafar I fixed the issue. Please help me download v3 and retest again.

**Comment by salahjaafar** [comment]
Congratulations Sonvnn, it's working correctly. Just one more simple improvement: the beginning of the submenu should be directly under the link that I hover over with the mouse. Here is an image explaining the situation:

![Capture d’écran du 2023-12-21 09-18-06](https://github.com/templaza/astroid-framework/assets/47123877/6d5325b0-fe79-4013-8f55-a501d4013c81)


Thanks once again; this encourages me to use the framework for all applications and websites that operate with RTL.

**Comment by sonvnn** [comment]
@salahjaafar Go to Astroid Mega Menu change Dropdown Alignment from Right to Left.
![Screen Shot 2023-12-21 at 16 11 09](https://github.com/templaza/astroid-framework/assets/3204103/3f518651-a6ea-47bd-a6a6-bb86b36487c8)

**Comment by salahjaafar** [comment]
@sonvnn I tried this, but it doesn't yield any results.

**Comment by Chacapamac** [comment]
Yep, as in my last post changing “**Left to Right**” and even “Center” **doesn't change the position of the dropdown container at all** on a “**Normal**” **Main Menu item** with submenus items. **(NOT A MEGA MENU)**

![Screen Shot 2023-12-21 at 1 37 51 PM](https://github.com/templaza/astroid-framework/assets/1907276/a9ae3ba8-41b4-44ae-82dd-1905d84107ba)

**Comment by salahjaafar** [comment]
Alright, I tried to solve this issue by adding the following condition to the _menu.scss file:
```scss
/* Add condition for RTL */
body.rtl .megamenu-container.nav-submenu-container.nav-item-level-1 {
  left: auto; /* Reset left value */
  right: 0px;
}
```

However, there is still an issue with the mobile display, as shown in this image:
![1](https://github.com/templaza/astroid-framework/assets/47123877/7d171b35-9758-4311-9040-7beb61f13304)


 I added the following condition to address the situation:
```scss
/* For RTL languages, override the text-align property: */
.rtl .astroid-mobilemenu-container .astroid-mobilemenu-inner .dropdown-menus .menu-indicator-back {
  text-align: right;
}
```
After modification
![2](https://github.com/templaza/astroid-framework/assets/47123877/eb94e984-d9d4-4c37-994f-b3a0d0f8c411)

**Comment by sonvnn** [comment]
@Chacapamac @salahjaafar I fixed this issue in https://github.com/templaza/astroid-framework/commit/e37e42fdc5ecb22740197a4a6a810b1ac1748cd6

Please help me check Dropdown Alignment again. My result below:
![Screen Shot 2023-12-22 at 16 09 55](https://github.com/templaza/astroid-framework/assets/3204103/217473b6-d1a5-4c80-a044-16b0e2205514)

@salahjaafar I will check mobile menu issue on the next Monday. 

Thanks,
Sonny

**Comment by salahjaafar** [comment]
Congratulations @sonvnn, it's working correctly. I am very satisfied. The **mobile menu** just needs a simple correction, and everything will be fine. Have a great day!

**Comment by sonvnn** [comment]
@Chacapamac @salahjaafar I fixed all issue related in this topic. Please help me download v3-branch and recheck again.
Note: you have to click Astroid Clear Cache to force Astroid recompile scss.

Thank you & Merry Christmas,
Sonny

**Comment by salahjaafar** [comment]
@sonvnn Yes, it works for desktop, but for mobile, there is only one simple correction remaining, as I mentioned in this comment: https://github.com/templaza/astroid-framework/issues/511#issuecomment-1866833651.

**Comment by sonvnn** [comment]
@salahjaafar Please download v3 latest, clear Astroid Cache, browser cache, etc. The result on my mobile below
![Screen Shot 2023-12-23 at 15 46 57](https://github.com/templaza/astroid-framework/assets/3204103/acba1582-ce1f-4190-8005-9c75b5e0ee56)

**Comment by salahjaafar** [comment]
The issue is present in the mobile menu; the link needs to be on the right. Here is a video showing the steps I've taken: https://drive.google.com/file/d/16vqNcIYlzYONOjxriugvsluQoiNiP2xG/view?usp=sharing.

**Comment by salahjaafar** [comment]
@sonvnn @Chacapamac 
Congratulations, it's working correctly! A big thank you; this could attract another audience for the framework.
Certainly! Feel free to close this discussion, and we'll await the release of the official version. If you have any more questions or need assistance in the future, don't hesitate to reach out.

**Comment by Chacapamac** [comment]
This is Great News that should bring more people to the framework and should be advertise on the Astroid Website to be a little bit more prominent.
 
**I like this because Joomla was really intended as an international CMS.**

**FUN FACTS**
**Joomla** is the anglicized spelling of the **Swahili** word **jumla**, meaning "**all together**" or "**as a whole**" that also has a similar meaning in at least **Amharic**, **Arabic**, **Turkic** languages and **Urdu**.

**Comment by salahjaafar** [comment]
@Chacapamac Joomla in Arabic is written as 'جملة,' which means a group or assembly of something.

**Comment by Chacapamac** [comment]
@salahjaafar 

> Joomla in Arabic is written as 'جملة,'

Cool, do you need to keep bot start and end “apostrophes” looking characters?

**Comment by salahjaafar** [comment]
> @salahjaafar 
> 
> > Joomla in Arabic is written as 'جملة,'
> 
> Cool, do you need to keep both start and end “apostrophes” looking characters?

Certainly, here is the translation:

No, she only writes like this:  جملة
