### ISSUE TITLE
Icons not loaded in backend (Astroid 3.0.7)

### ISSUE THREAD

**Issue by SirCorono** [templaza/astroid-framework#512]
Hi
I saw that in Astroid version 3.0.5, a bug related to loading icons was fixed. I've installed 3.0.7 and I still (or better new) have the problem that no icons are loaded in the backend:
![image](https://github.com/templaza/astroid-framework/assets/32664586/f2420c74-c58b-4870-9e6a-acc3f7f45995)

In addition, most of the buttons don't work, I can't for example deactivate a extension, if I press the button, nothing happens.

Could it be that there is still a problem with the icons in version 3.0.7?

Corono

**Comment by Joomlaplates** [comment]
Joomla version pls!!

**Comment by SirCorono** [comment]
Joomla version is 4.4.0. There is a 4.4.1 update available, but update button is not working anymore.

I manually deleted the cache in the main and the administrator folder (deleting the cache button in Joomla doesnt' work anymore, no change)

**Comment by sonvnn** [comment]
Please re-install Astroid Framework.

**Comment by SirCorono** [comment]
Unfortunately, that is not so easy because de-install and deactivate buttons don't work anymore. Is there a way to remove the framework properly without these buttons? Can I just delete the files on the FTP server?

**Comment by SirCorono** [comment]
Problem seems to be solves now. I found a way to disable it in the database, then I updated everything to the newest version and enabled it again. 
It seemed that it also was a problem of browser cache, after updating and re-enabling, I had to delete the browser cache.
