### ISSUE TITLE
Version nb error

### ISSUE THREAD

**Issue by patrickus33** [templaza/astroid-framework#514]
After updating to version 3.0.8 of the framework and template, there is a version identification problem.
For joomla, the template is still in 3.0.7, so there's still an update warning. 
![img1](https://github.com/templaza/astroid-framework/assets/12388965/8536b070-a7f6-469f-9650-f6ed3ee5acd1)
![img2](https://github.com/templaza/astroid-framework/assets/12388965/797b3334-d40c-4744-8da1-4b199254e9d9)
![maj](https://github.com/templaza/astroid-framework/assets/12388965/d72b8f08-8931-459c-9481-3abb8ce0fc54)
Same pbl with Joomla 4.4.1 and 5.0.1

**Comment by sonvnn** [comment]
I fixed this issue in https://github.com/templaza/astroid-framework/commit/803cbb7fcc26b461d5457eb41df215f687cbdf43

Thanks & Best Regards,
Sonny
