### ISSUE TITLE
Bootstrap 5 and Astroid 2.5.11

### ISSUE THREAD

**Issue by SerGun78** [templaza/astroid-framework#52]
Hey! Why did the Astroid 2.5.11 framework add bootstrap 5 from the Joomla core?
There used to be one bootstrap.min (or bundle) file and one request, but now every JS library is loaded?
It is necessary to include bootstrap in the Astroid plugin in the same way as fontawesome:
1.turn off
2.load locally from the server either bootstrap.min or bundle
3.download from CDN like https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js
At the same time, so that you can still choose the bootstrap version 4 or 5.

**Comment by sonvnn** [comment]
Hi,

We have some js conflict issue when load Bootstrap 5 JS on Joomla 4. I assumed Joomla has some modified in their Bootstrap library. So I choose to load Bootstrap js from Joomla core.

Thanks,

**Comment by sonvnn** [comment]
Hi Sergun78,

In Joomla 3 we still using Bootstrap from Astroid framework. But in Joomla 4 core is Bootstrap 5. If you use Bootstrap 4 some js will not work in Joomla 4. Ex front-end editor, edit button article, dropdown js, popover, etc..

PS: In Joomla 4, they just separated Bootstrap 5 JS, then if you merge or compile it will be look like Bootstrap.bundle.js. If you need compile to one js file, you can use compile js feature of Astroid.

Thanks,
Sonny

**Comment by SerGun78** [comment]
I don’t understand how the bootstrap for the backend is related to the bootstrap for the frontend ?!

**Comment by SerGun78** [comment]
I don’t understand how the bootstrap for the backend is related to the bootstrap for the frontend ?! 
I only edit the site from the backend!

**Comment by sonvnn** [comment]
Hi @SerGun78,
I am sorry but community need it. You should think for others.

**Comment by SerGun78** [comment]
then for those who proofread articles from the front-end, you need to do this: "At the same time, so that you can still choose the bootstrap version 4 or 5."
I suggested that at once.

**Comment by sonvnn** [comment]
Hi @SerGun78,
Sorry, We can not downgrade Bootstrap 5 to 4. If you love Bootstrap 4. You can downgrade your Astroid to 2.5.5 or lower.

**Comment by SerGun78** [comment]
It is possible to make the bootstrap version selection temporary as long as the js conflict persists. As you wrote: "We have some js conflict issue when load Bootstrap 5 JS on Joomla 4."

**Comment by SerGun78** [comment]
about compression and unification. When you enable these functions in the template, nothing works, all js go separately: 
![изображение](https://user-images.githubusercontent.com/95705148/145976562-0f81da90-1680-4445-abed-17a1b78b5b45.png)
![изображение](https://user-images.githubusercontent.com/95705148/145976602-2746f71f-acd2-4a6b-a121-7de192e9a9f9.png)
JCH Optimize doesn't help for this either.

**Comment by SerGun78** [comment]
J 4.0.5 was released.
Fixes made to bootstrap.
Check if it was causing a js conflict.
https://github.com/joomla/joomla-cms/pull/36178

**Comment by Chacapamac** [comment]
> Hey! Why did the Astroid 2.5.11 framework add bootstrap 5 from the Joomla core?
Personally I always prefer plugins, components, frameworks that use only  _(if possible)_ what is native to Joomla. Adding others libraries are bloating the core & recipes for bugs.

**• Using what Joomla give us get my vote.**

or even better you can add a settings that can load a custom library as your liking (to your own risk) — Leaving te choice to the user is always the better way but not necessarily the wise one...
