### ISSUE TITLE
Strange Serverpath to image folder

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#524]
I dont know if it is a Astroid problem, but the media folder from Joomla is shown correctly.
But when I want to select a logo from Astroid there is a strange serverpath, see the path on screenshot.
Joomla 5.0.1, Astroid 3.0.8, Template One
Thanks in advance
![pics1](https://github.com/templaza/astroid-framework/assets/71080509/aa0c0998-da73-4f74-9932-157ee3575f57)

**Comment by sonvnn** [comment]
@Joomlaplates The system works well in my localhost. May you send me your admin account via sonlv@templaza.com? I will check it.

Thanks & Best Regards,
Sonny

**Comment by Joomlaplates** [comment]
Hello together, I´ve found the issue. There was a another media path with backslash.
I think Astroid has a general problem when the path to media is changed by user to individual folder and its not > images
Finally deleted the backslashes and it works.
Maybe Astroid has to respect the individual media path when its not > images
![pfad](https://github.com/templaza/astroid-framework/assets/71080509/ae9c9668-90c0-4b4e-ab58-ca7dc70d916f)

**Comment by sonvnn** [comment]
Thanks! I will check and fix this issue, tomorrow

**Comment by sonvnn** [comment]
@Joomlaplates I fixed this issue in https://github.com/templaza/astroid-framework/commit/81e1e1ddadf91504ef33d5aac027b324c8a67923#diff-bfa32a49fbe93a95df7e5b078ba3c1cc1ae74d274adc72aed5a84a954f5efd37

Please help me check it.

Thanks & Best Regards,
Sonny

**Comment by Joomlaplates** [comment]
Hi Sonny, I´ve checked the V3 and its working, even with backslash after images folder.
Thanks, as always great job.
Regards Peter
