### ISSUE TITLE
logo without a link on the main (home) page

### ISSUE THREAD

**Issue by SerGun78** [templaza/astroid-framework#53]
Hey! Again, for SEO, you need to reduce the number of links to pages on itself.
It is necessary to make the logo on the main page of the site inactive (without a link) in the settings of the One + Zero templates.

Ideally, you should also make the "Home" menu item inactive or completely hide it on the main page of the site.

**Comment by SerGun78** [comment]
Ideally, you should also make the "Home" menu item inactive or completely hide it on the main page of the site.

**Comment by sonvnn** [comment]
This issue look like a custom modify from template. So you can edit in your template instead of Astroid framework.

**Comment by SerGun78** [comment]
Of course, we are talking about the logo settings in the template settings in "HEADER".
I suggest so:
![изображение](https://user-images.githubusercontent.com/95705148/145878541-aa9dd8c1-b8e5-4328-acd4-80b1c50af4e8.png)
It's easier with the HOME link on the menu. You can, of course, make a copy of the main menu, in which you can hide the display of the link to the main page in the menu and display the template style with this menu only for the main page of the site.
But this is dancing with a tambourine.
Better to add this feature to the ONE / ZERO template settings.

**Comment by sonvnn** [comment]
Thanks for your suggestion.
I added this feature on https://github.com/templaza/astroid-framework/commit/9c1245aefb727125823752a1af98ea017561f572

Please help me check it.

Best Regards,
Sonny

**Comment by SerGun78** [comment]
Sonny, hello! When you turn on the NONE mode, all three logos appear in HEADER: defaul, mobile and sticky. Maybe?!
![изображение](https://user-images.githubusercontent.com/95705148/146255355-009323b5-2105-49e4-8493-838ee11f47e7.png)
![изображение](https://user-images.githubusercontent.com/95705148/146255385-d33a6e15-5ca7-4a07-9f12-2814e3b76ece.png)

**Comment by sonvnn** [comment]
Oppp! I missed class for it. Just fixed this issue in https://github.com/templaza/astroid-framework/commit/bfc3cc5b6d5e520ba185abcdc17ad12f5a9811b6
Please help me check it again.

Best Regards,
Sonny

**Comment by SerGun78** [comment]
super! thanks!

**Comment by sonvnn** [comment]
It related to Joomla Menu. We can not do this.

Thanks,

**Comment by SerGun78** [comment]
Sonny was overjoyed early.
If NONE is selected for the logo link, then the sidebar menu layout "floats":
![изображение](https://user-images.githubusercontent.com/95705148/146361374-a91829fd-adf2-4355-a2ba-47663a28724b.png)

**Comment by sonvnn** [comment]
I test in my demo and everything works well. I am not sure, please help me clear cache and try again.

**Comment by SerGun78** [comment]
Sonny, hello! Yes, I cleared the cache, the menu became normal. Only with the alignment of the logo you need to figure it out.
With default / custom alignment of the logo in the center, with NONE - to the left. 
default/custom
![изображение](https://user-images.githubusercontent.com/95705148/146683265-b620df40-725c-4875-9266-c1a2189dbaa1.png)
NONE
![изображение](https://user-images.githubusercontent.com/95705148/146683278-6ddad7a2-3d39-4b5a-9092-0bd137a610af.png)

**Comment by SerGun78** [comment]
Sonny, hello! With the alignment of the logo, the issue has not been resolved!

**Comment by sonvnn** [comment]
Let's send me your url. I will help you check it.

**Comment by SerGun78** [comment]
http://astroid.tw1.ru/
