### ISSUE TITLE
how to prevent clicks on separator links

### ISSUE THREAD

**Issue by web54** [templaza/astroid-framework#534]
On the astroid template, when a separator-type menu link is created, the visitor can click on it and this takes them back to the home page. This should not be the correct behaviour.
clic on separator should be disabled and impossible to do

**Comment by web54** [comment]
That is not enough, I added this class , and still clickable.
I suppose you add some custom css ?

**Comment by web54** [comment]
.disabled{
   pointer-events: none;
   cursor: default;
}

**Comment by Giorgi625** [comment]
No I have not added anything else just this class to menu item which. 
I guess its Bootstrap feature.
This is what I See in console 

`.nav-link.disabled, .nav-link:disabled {
    color: var(--bs-nav-link-disabled-color);
    pointer-events: none;
    cursor: default;
}
`

**Comment by web54** [comment]
so it can be : 
.item-link-separator {
   pointer-events: none;
   cursor: default;
}

**Comment by Giorgi625** [comment]
In Screenshot I took above I added that that class to new website on J5 with latest Astroid One template so I do not get why it did not disabled link in your menu item.

**Comment by web54** [comment]
> No I have not added anything else just this class to menu item which. I guess its Bootstrap feature. This is what I See in console
> 
> .nav-link.disabled, .nav-link:disabled { color: var(--bs-nav-link-disabled-color); pointer-events: none; cursor: default; }

So that is what I found and have done, I guess bootstrap is not loaded on this site.
So I suggest to add this css in astroid files : 
.item-link-separator {
   pointer-events: none;
   cursor: default;
}

**Comment by Chacapamac** [comment]
I just test a Joomla Menu item type “**Separator**” 
Joomla 4.4.2 — PHP — 8.1.13
Astroid One 3.0.8 

• “**Separator**”  without the class “**disabled**”
— You can click on the link, and it bring you to the “Home” Page (Home Page URL)
— You have an .hover effect on the link and it bring the sub-menus
— Work Well on Mobile Menu

• “**Separator**”  with the class “**disabled**”
— You cannot click on the link (Got same Home Page URL, but disabled)
— No .hover effect on the link  and it bring the sub-menus
— Work Well on Mobile Menu

**Comment by sonvnn** [comment]
@Chacapamac @web54  I fixed this issue in https://github.com/templaza/astroid-framework/commit/c13db8cbac64ba5e449cdad4e88849d77c77fc17

Please help me download v3-branch and test it.

Thanks & Best Regards,
Sonny

**Comment by web54** [comment]
> @Chacapamac @web54 I fixed this issue in [c13db8c](https://github.com/templaza/astroid-framework/commit/c13db8cbac64ba5e449cdad4e88849d77c77fc17)
> 
> Please help me download v3-branch and test it.
> 
> Thanks & Best Regards, Sonny

Tested
So 
- no click avalaible
- submenu works well
- but still hand cursor on hover that indicate user it is a link ( and it is not )
you can see it  here : 
https://www.cigale-evasion.weblor.fr/astroid3/

**Comment by sonvnn** [comment]
@web54 I fixed issue in v3.0.9. Please help me check it again.

**Comment by web54** [comment]
that is what I have done and commented : 
it works, no link, but still a hand on hover so people can believe it is possible to click

watch it on my dev link ; https://www.cigale-evasion.weblor.fr/astroid3/
link is "test separator" for exemple

**Comment by sonvnn** [comment]
@web54 please clear Astroid cache and Browser cache. Refresh again!

**Comment by web54** [comment]
ok
that's good now, it was the cache
thanks for all
