### ISSUE TITLE
Icons in Grid WIdget not shown correct

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#537]
Hello, the Icons in Grid WIdget not shown correct
Its a part of the language file?
Regards Peter
![Screenshot_2](https://github.com/templaza/astroid-framework/assets/71080509/c05ac49a-8f3b-4b0d-afe5-ae3478758a56)

**Comment by sonvnn** [comment]
It is browser cache problem. Please help me clear cache to reload javascript file.

**Comment by Joomlaplates** [comment]
Hello Sonny,
yes youre right it was a Browser Cache problem.
In template setting press STRG + F5 and it works.
Nice weekend, regards Peter
