### ISSUE TITLE
Dead backend after uninstallation of Jollyany package

### ISSUE THREAD

**Issue by ReLater** [templaza/astroid-framework#54]
- Joomla 3.10.3
- I installed astroid-package-v2.5.11.Jollyany-Template.zip
- In `administrator/index.php?option=com_installer&view=manage` I checked the Jollyany package and clicked "Uninstall".
- Afterwards the whole Joomla backend is dead and displays 
`500 Library path /libraries/astroid/framework/library/astroid cannot be found.
/libraries/loader.php:438`

- Thrown by 
`JLoader::registerNamespace() | JROOT/plugins/system/jollyany/jollyany.php:10`

EDIT: And the jollyany package is still present in database `#__extensions`

**Comment by SerGun78** [comment]
Astroid has the same problem 
#49

**Comment by sonvnn** [comment]
Thank you. I will fix it in the next version :)

**Comment by sonvnn** [comment]
I fixed it in https://github.com/templaza/astroid-framework/commit/e68cd4e1289c55f685b51ecb20a36ab8ccf04b0c
Thanks & Best Regards,
Sonny

**Comment by Chacapamac** [comment]
**Just in case it can help.** 
This error was known by JoomDev. This is their ay to resolved it.
https://archive.joomdev.com/forum/astroid-framework/5377-error-library-path-libraries-astroid-framework-library-astroid-cannot-be-found-solucionado

> Rename the following folders via FTP.
> /libraries/astroid to libraries/astroid_old
> /plugins/system/astroid to plugins/system/astroid_old
> Backend will be available then and reinstall the framework and you should be good to go.  

and another link here —> https://docs.joomdev.com/article/things-to-remember-after-migrating-your-site-from-astroid-2-3-0-to-2-4/
