### ISSUE TITLE
Problem Update from 3.02 Call to undefined method Joomla\CMS\Factory::getContainer()

### ISSUE THREAD

**Issue by CAGIGAL-Computer** [templaza/astroid-framework#546]
When we update from out current version 3.02 to whatever higher version (3.03 to 3.09) the process finishes with an Error and after that the frontend of the site only shows Error on the upper left of the page and in the backend when we go to Templates there´s one error 0 Call to undefined method Joomla\CMS\Factory::getContainer() and a button to Return to Controlpanel.

We have PHP 8.1.27 / Joomla 3.10.12

To workaround, we must install 3.0.2 again

**Comment by deltapapa01** [comment]
Hi,
from the beginning of 3.0.3 the min Joomla Version is 4.4.x.
The best way to use Astroid for the out of date Joomla 3.x is Astroid Version 2.6.6.
The best way is update to min Joomla to 4.4 and next step to 5.0 to use Astroid Framwork 3.x

@sonvnn : Maybe this is a good point, the Technical Requirements here: https://docs.astroidframe.work/get-started/technical-requirements#requirements should point out the special versions for Joomla 3.x and Joomla 4.4 / 5.x

WBR,
deltapapa

**Comment by sonvnn** [comment]
@deltapapa01 Thank you for feedback. I updated the documentation https://docs.astroidframe.work/get-started/technical-requirements

**Comment by deltapapa01** [comment]
@sonvnn - You are welcome :-)
