### ISSUE TITLE
fontawesome is not disabled_2.5.11

### ISSUE THREAD

**Issue by SerGun78** [templaza/astroid-framework#55]
Hey! When disabled in the Astroid plugin, fontawesome is still loaded into the frontend. 
![изображение](https://user-images.githubusercontent.com/95705148/145730131-b44454e4-95ca-4b01-884b-2bd9ad6636db.png)
![изображение](https://user-images.githubusercontent.com/95705148/145730145-972b8c92-4c6b-4d32-96e8-d4a9167bd777.png)

**Comment by sonvnn** [comment]
I fixed this issue in https://github.com/templaza/astroid-framework/commit/f908ad2098380fa097ad92ed20278ee5f6a931e4
Please help me check it again.
Thanks,
Sonny
