### ISSUE TITLE
Menu item type “Separator” does not work correctly in the mobile menu

### ISSUE THREAD

**Issue by strizhakovanatalya** [templaza/astroid-framework#550]
Hello)
Menu item type “Separator” works great on the desktop version, but does not work on the mobile version.
In the mobile version, the paddings have disappeared and I can't click on a menu item to see the drop-down menu items.
Last week I wrote about my problem a href="javascript:void(0): Links are not crawlable Google PageSpeed Insights SEO #541
I uploaded v3-branch to my site and the error may be related to this, because I haven't checked how the menu works in the mobile version.
Can you check please?
![menu](https://github.com/templaza/astroid-framework/assets/49317308/21a44d13-804a-4960-8a1e-28adfbe20ee2)
![menu1](https://github.com/templaza/astroid-framework/assets/49317308/3640b05d-be9f-450a-bc11-2be58234bb12)

**Comment by sonvnn** [comment]
I fixed it in https://github.com/templaza/astroid-framework/commit/0e40084e4ae518123495c5e132b9af7c977d6a15

Please help me download v3-branch and re-upload.

Best Regards,
Sonny

**Comment by strizhakovanatalya** [comment]
Everything seems to be working great. 
Page Speed ​​likes your solution, the desktop version works well, and the mobile version works well, there are dropdown menu items.
Thank you)
![menu2](https://github.com/templaza/astroid-framework/assets/49317308/2a01911b-5c31-4799-be8e-34c1dcee6edb)
![menu3](https://github.com/templaza/astroid-framework/assets/49317308/109ae54f-f126-40a6-8e4b-087554f375bc)
![menu4](https://github.com/templaza/astroid-framework/assets/49317308/bb49f4c7-ed29-4365-9b88-39f3c16afe1a)
![menu5](https://github.com/templaza/astroid-framework/assets/49317308/7012fbd3-6ba0-4989-b3b3-74409619255a)
