### ISSUE TITLE
Errors on 404 error pages

### ISSUE THREAD

**Issue by SerGun78** [templaza/astroid-framework#553]
Hi all. The 404 error pages in the console show some errors when debugging.
![udtXXc8vzO](https://github.com/templaza/astroid-framework/assets/95705148/b6ecb129-c2d5-44af-a14a-039561b8a9a2)

J 4.4.2
Astroid 3.09
one 3.08
PHP 8.1.9

**Comment by sonvnn** [comment]
Please check your menu alias. Make sure it is valid. Try to switch to cassiopeia check if this issue still happens.

**Comment by SerGun78** [comment]
what does the menu have to do with it? I simply enter a non-existent address and an error page is displayed. Everything is correct here. But this page contains joomla errors in the console.

**Comment by sonvnn** [comment]
When you turn on debug, Joomla will show this log. Turn it off, then the log win gone.

**Comment by SerGun78** [comment]
Yes, Sonny, I know all that. But where did these errors come from on the error pages? Is this a general Joomla problem that is not template dependent?
There are no menus on the error pages at all, why did you point to a menu in your answer?!

**Comment by sonvnn** [comment]
If you think it is a problem. You should raise an issue on Joomla Cms git. I am sorry because it happens from Joomla Core not related Astroid.
