### ISSUE TITLE
Sub-menu Alignment Issue in Astroid Framework's Zero Template

### ISSUE THREAD

**Issue by salahjaafar** [templaza/astroid-framework#555]
Hello @sonvnn 
I am writing to inform you about an issue I encountered with the zero template of the Astroid framework. I confirm that the sub-menu works fine with the RTL direction, but it has caused problems for the LTR version's sub-menu. The sub-menu does not display correctly under the main menu; it appears offset.

**Comment by sonvnn** [comment]
May you send me a screenshot of issue?

**Comment by salahjaafar** [comment]
![Capture d’écran du 2024-02-07 12-45-47](https://github.com/templaza/astroid-framework/assets/47123877/16dc30ca-8e0c-472a-87e9-3acc473509b7)

**Comment by sonvnn** [comment]
Thanks! I will check it. May be a bit slowly because I am in Lunar New Year holiday at the moment.

**Comment by sonvnn** [comment]
Hello, I think you did wrong configure menu. To setup alignment for muti-language you have to follow steps below:
1. In RTL menu you must setup "Dropdown Alignment" is "Right"
![Screen Shot 2024-02-21 at 10 26 54](https://github.com/templaza/astroid-framework/assets/3204103/949c3afb-f4d3-4c54-b5aa-07dfa129c21e)

2. In LTR menu you must setup "Dropdown Alignment" is "Left"
![Screen Shot 2024-02-21 at 10 29 39](https://github.com/templaza/astroid-framework/assets/3204103/a9a3651b-3e6c-4510-a159-13b32a96fd94)

It works on my demo server and It should work on your server, too.

Thanks & Best Regards,
Sonny

**Comment by salahjaafar** [comment]
@sonvnn 
Yes, I tried it and it works correctly. Thank you for your prompt assistance.
