### ISSUE TITLE
JQuery loads twice

### ISSUE THREAD

**Issue by biobill** [templaza/astroid-framework#56]
Hi @sonvnn 
Why should astroid load the JQuery library while it's already loaded in the core?
I think you should disable JQuery as well as the jquery.noConflict.js

**Comment by SerGun78** [comment]
I completely agree.

**Comment by sonvnn** [comment]
Hello @biobill ,

There is an js issue with SP Page Builder when load jQuery from Joomla core. It appears infrequently depend of each page and I'm not sure about it. But it's SP Page Builder issue only then I added a feature allow you select whether jQuery Library assets should be loaded Joomla Core or via Astroid Framework. https://github.com/templaza/astroid-framework/commit/f125886a0f4653c68bab45f80ef6bd7fc247efbd

Please go to Astroid Plugin >> jQuery Library Loading >> Joomla Core

Thanks & Best Regards,
Sonny

**Comment by biobill** [comment]
Hi @sonvnn,
As you can see in the image below, there's no  jQuery Library Loading selector.
Regarding SP Page Builder, I managed to strip their jQuery script (version 1.12.4!!!) with the jQuery Easy plugin, but I can't disable in any way jQuery loaded by Astroid.

Many thanks,
Vassilis
![image](https://user-images.githubusercontent.com/16140656/146330347-ab88f5cc-0244-4485-bced-28056af7c4bc.png)

**Comment by sonvnn** [comment]
Hi @biobill ,

Please check your xml file https://github.com/templaza/astroid-framework/blob/developer/plugins/astroid/astroid.xml#L28

`<field name="astroid_load_jquery" type="radio" default="astroid" label="ASTROID_LOAD_JQUERY" description="ASTROID_LOAD_JQUERY_DESC" class="btn-group btn-group-yesno">
      <option value="astroid">Astroid</option>
      <option value="core">Joomla Core</option>
</field>`

Please make sure this code is available.

Best Regards,
Sonny

**Comment by biobill** [comment]
Hey @sonvnn,

There's no such code in my XML file. 

As I see, my XML file is <version>2.5.5</version> but the one you posted is <version>2.5.12</version>.
How is it possible? I have updated astroid to the latest version 2.5.11.

Thank you so much for your assistance,
Vassilis

**Comment by sonvnn** [comment]
Let's replace xml content with new content.

Thanks,
Sonny

**Comment by biobill** [comment]
Unfortunately nothing happened....

**Comment by sonvnn** [comment]
Please send me your admin account via sonlv@templaza.com.
I will help you check it.

**Comment by SerGun78** [comment]
Perhaps you need to download the framework from the developer's branch ?!

**Comment by SerGun78** [comment]
when you enable Jquery from the core of Jooma 4, three Jquery from Astroid are still uploaded to the site.
![изображение](https://user-images.githubusercontent.com/95705148/146349555-c48552d4-476b-4ae4-9daf-9b553001b968.png)

**Comment by biobill** [comment]
@sonvnn you've got email

**Comment by sonvnn** [comment]
Hello @SerGun78,

These files uses for Astroid only https://github.com/templaza/astroid-framework/blob/master/assets/vendor/jquery/jquery.noConflict.js
Don't worry about it.

Hello @biobill, Not yet.

Thanks,
Sonny

**Comment by SerGun78** [comment]
Sonny, so from the core Joomla 4 noconflict is loaded too! why duplication?

**Comment by sonvnn** [comment]
From Joomla core
`var $=jQuery.noConflict();`

It does not related to Astroid. So don't worry about it.

**Comment by sonvnn** [comment]
Hi @biobill ,

I helped you re-install Astroid and use jQuery from Joomla Core. Please help me check it again.

Thanks,
Sonny

**Comment by biobill** [comment]
Hi @sonvnn,
Now it works great! Thank you!
May I ask why the automatic updates didn't update the plugin? Is there a bug? Also, are there any updates for the templates one and zero?

Many thanks
Vassilis

**Comment by sonvnn** [comment]
Hi @biobill,
I am not sure about your issue. Normally, When I update framework, it will update all plugins related

Bests,
Sonny

**Comment by biobill** [comment]
Hi @sonvnn,
I'll check again on the next update and if it happens again I'll report it here.
Are there any updates for the templates (one and zero)?

**Comment by Chacapamac** [comment]
Just as infos:
**This is my original last Joomdev/Astroid 2.5.4 package**
![Joomdev-2 5 4](https://user-images.githubusercontent.com/1907276/147829916-b5fb0472-213c-4c17-822e-542d89424b84.jpg)
_**Note:** I’m not sure how it happen. but I realized that my Astroid Plugin was not the correct version for the Joomdev/Astroid 2.5.4 package. I did have to reinstall to get the right version?????_

**This is Templaza/Astroid 2.5.11 package**
![templaza-2 5 11](https://user-images.githubusercontent.com/1907276/147830089-eafbb646-015d-45fe-96ea-62ffaf985c46.jpg)

**Comment by Chacapamac** [comment]
**Sorry to butt in....**

@SerGun78  — I like what I see here... 
![jquery](https://user-images.githubusercontent.com/1907276/147830441-428f8702-aa00-408a-9bd1-69acc954932d.jpg)
