### ISSUE TITLE
Bug report - Submenu offset and icons rotation Framework: 3.0.10 and older version

### ISSUE THREAD

**Issue by salahjaafar** [templaza/astroid-framework#562]
Dear Astroid developers @sonvnn,
I wanted to warmly congratulate you on the release of the new version of the Astroid framework.
I would like to share some observations regarding the usage of Framework Version 3.0.10 and Template Version 3.0.10:

**Versions:**

* Framework: 3.0.10
* Template: 3.0.10

**Description of the issue:**

1. **Submenu offset:**
   - An offset is observed in the alignment of the submenu when using the LTR (left-to-right) direction.
   - I mentioned that in this section : https://github.com/templaza/astroid-framework/issues/555

2. **Submenu icons rotation on mobile:**
   - Submenu icons behave abnormally on mobile devices. They rotate 360° unexpectedly.

**Environment:**

* Browser: Firefox 122.0.1
* Operating system: Linux mint 21.2

**Screenshot:**
![Screenshot 2024-02-15 at 10-00-03 المعدات المتوفرة](https://github.com/templaza/astroid-framework/assets/47123877/77b43557-ed8a-4e23-ad65-a872266a856c)
![Screenshot 2024-02-15 at 10-00-13 المعدات المتوفرة](https://github.com/templaza/astroid-framework/assets/47123877/3fab48ec-72bf-4039-b282-5d611651714a)

**Request:**

* Please investigate this issue and provide a fix in the next version of the framework.

**Thank you for your attention.**

**Comment by sonvnn** [comment]
Thanks for feedback. 

1. Please send me your admin and I can help you check it. 
2. I will check and confirm about this issue.

Best Regards,
Sonny

**Comment by sonvnn** [comment]
I fixed this issue on https://github.com/templaza/astroid-framework/commit/288c4cc04e308e785821c636a6aebd397ce44fc2

Please help me check it.

Best Regards,
Sonny
