### ISSUE TITLE
Gradiant settings are gone after update to 3.0.10

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#563]
Hi Sonny,
happy new year of dragon!
1.) If you have already a gradiant setting in element or section, the colors are gone after update to 3.0.10
2.) Go now to the section, switch the gradiant to radial or linear and save
3.) Go back again and switch to linear/radial and save and it should be back in frontend
..
Anyway
The gradiant settings are opposite since 3.0.10
..
If you didnt use the gradiant settings at all and setup with Astroid 3.0.10 a gradiant background it works. But didnt works if you had already a gradiant and update to Astroid 3.0.10.
Regards Peter

**Comment by WM-Loose** [comment]
Linear is then exchanged. The color that was before is then below and vice versa. This only happens if the color gradient had already been set beforehand. 
![1](https://github.com/templaza/astroid-framework/assets/99647423/e9fb9635-5221-4b55-bff8-855cb6294709)

**Comment by WM-Loose** [comment]
color gradient with 3.0.9
![3 0 9](https://github.com/templaza/astroid-framework/assets/99647423/9930e333-3b7d-4ce0-b574-121d6668ffbb)

color gradient with 3.0.10
![3 0 10](https://github.com/templaza/astroid-framework/assets/99647423/3b997641-b2d2-425f-9c9d-1c2b9d46a0d4)

**Comment by sonvnn** [comment]
@Joomlaplates @WM-Loose I fixed this issue at https://github.com/templaza/astroid-framework/commit/97831530f05ba4d8024b5640de78638b4e26d493

Please help me download v3-branch and retest again.

Thanks & Best regards,
Sonny

**Comment by WM-Loose** [comment]
Hello Sonny,

I have now installed 3.0.10 in the backend and made the changes in style.php. After that the color bleeds were back again. However, I had to reverse the arrangement of the two colors in the template options. So I had to swap the left color and the right color. After that everything was ok. I can't tell you why the left and the right aren't the same anymore. But with the adjustments in style.php it now works.

The Style.php is in /joomla.../libraries/astroid/framework/library/astroid/Helper
[Style.zip](https://github.com/templaza/astroid-framework/files/14309774/Style.zip)


New style.php, look file

**Comment by sonvnn** [comment]
@WM-Loose yes, it is an mistake from Joomdev since Astroid 2. I have to correct it one. They did not add degree gradient when it has zero value and missing some attributes like start position and stop position, So please help me change your color. It will be safe in the future.

Thanks and Best regards,
Sonny

**Comment by WM-Loose** [comment]
I have now reversed the colors and everything is fine. Feel free to provide an update. Users just have to change the colors once and everything will be ok in the future.

Thank you very much for your great work.
Dirk

**Comment by Joomlaplates** [comment]
Yep its working now.
Thanks Sonny!
