### ISSUE TITLE
Background color error in dark mode when in box is used

### ISSUE THREAD

**Issue by Barcenilla00** [templaza/astroid-framework#564]
Android Framework 3.0.10 (also in 0.9)
astroid_template_two 1.0.2 (also in 0.1)

Always use the color of light mode as background color

**Comment by sonvnn** [comment]
@Barcenilla00 Did you setup background-color for dark mode?

**Comment by Barcenilla00** [comment]
> @Barcenilla00 Did you setup background-color for dark mode?

Yes
![image](https://github.com/templaza/astroid-framework/assets/22943057/b8cfccc2-0ccc-4ce0-83e8-b144e54cd95c)
![image](https://github.com/templaza/astroid-framework/assets/22943057/2b57530d-75cf-4dc4-9652-743c08c813e6)

**Comment by sonvnn** [comment]
Thanks for report issue. I fixed this issue on https://github.com/templaza/astroid-framework/commit/c3e10e0c928c0ad7cb299464e2f3db7e56705820

Please help me check it again.

Thanks & Best Regards,
Sonny
