### ISSUE TITLE
Saving changes in Astroid

### ISSUE THREAD

**Issue by Dnsftl** [templaza/astroid-framework#569]
Dear Astroid developers,

We are experiencing an issue with saving changes in Astroid 3.0.10, for example, custom.css. When you add and save custom CSS and then close Astroid, the changes appear to have been successful. 
However, upon reopening Astroid, the custom CSS code appears to have disappeared. We encounter the same issue with layout adjustments; 
a newly added section with a widget or module that is saved disappears upon reopening Astroid.

Astroid Version: 3.0.10
Jollyany Version: 3.5.21
Template Version 3.5.21

Best Regards,

Dennis

**Comment by sonvnn** [comment]
Please send me your admin acc via sonlv@templaza.com. I will help you check it.

**Comment by WM-Loose** [comment]
I can't confirm. The custom.css works without any problems. 
Did you also put the custom.css in the correct folder?
/media/templates/site/your-template/

Regards,
Dirk

**Comment by Dnsftl** [comment]
@WM-Loose 

The custom.css is in the right folder, The problem off saving remains.

Regards,

Dennis

**Comment by Dnsftl** [comment]
We tried something else and I think it's been solved, I deleted the old custom.css file  and created a new custom.css file. It looks like this has resolved the saving issue. No idea why, but it works fine now.

**Comment by sonvnn** [comment]
@Dnsftl I tried to edit Custom CSS and the system works like a charm. 

May you detail the issue?

Thanks & Best regards,
Sonny

**Comment by WM-Loose** [comment]
@Dnsftl Possibly helpful:
If you select a style from the presets and then make changes, you must save it to a new preset.
If you just click save it will be saved as default but not in connection with the preset.

**Comment by sonvnn** [comment]
@Dnsftl I fixed this issue for @Giorgi625 on https://github.com/templaza/astroid-framework/pull/565/commits/1ce13d310d09871b1aadc2c55ed52db36253a61d

May you help me try to install v3-branch and retest again?

Thanks & Best Regards,
Sonny

**Comment by Dnsftl** [comment]
> @Dnsftl I tried to edit Custom CSS and the system works like a charm.
> 
> May you detail the issue?
> 
> Thanks & Best regards, Sonny

Hi Sonny,

I made 2 videos showing the problem, hope it makes it a bit clearer what I mean by saving problems.
https://dev.nvsp.nl//images/video/Custom clear cache css.mp4
https://dev.nvsp.nl//images/video/Custom css.mp4

Regards,

Dennis

**Comment by sonvnn** [comment]
@Dnsftl Thank you! I look like server cache issue. Can you tell me the name of the cache program you are using on your server?

Best regards,
Sonny

**Comment by sonvnn** [comment]
@Dnsftl I fixed the issue on your site. It's server cache issue. I assumed that you are using Gnix cache. Please help me check it again. It should work right now.

Best Regards,
Sonny

**Comment by Dnsftl** [comment]
Hi Sonny,

So far, it works perfectly. Thank you very much for fixing the issue on my site.

I have no idea which caching system the hosting provider is using. In any case, I will ask what is used by default. As soon as I know, I will certainly pass that information on to you.

Regards,

Dennis
