### ISSUE TITLE
Article details not available in "featured" view

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#57]
Hi,
Article details not available in "featured" article blog.
Based on template one and seems to be an issue in _html/com_content/featured/default_item.php_
When I copy the content from the file:
`/html/com_content/category/blog_item.php`
to 
`html/com_content/featured/default_item.php`
its working, please check.
Thanks, Peter

**Comment by sonvnn** [comment]
Hi Peter,

Thank you I will update Astroid Zero and One file in the next version.

Best Regards,
Sonny

**Comment by sonvnn** [comment]
Hi Peter,
I did it in v2.5.13.

Thanks,
Sonny
