### ISSUE TITLE
No arrow on menu when it is a separator

### ISSUE THREAD

**Issue by Barcenilla00** [templaza/astroid-framework#570]
Android Framework 3.0.10
astroid_template_two 1.0.2

As you can see, "Guías" has a second level menu but it is a separator and no arrow appears. The last option of the menu I've captured is a category content and works well.

It also doesn't work with the option "Menu heading".

![image](https://github.com/templaza/astroid-framework/assets/22943057/66e7ec42-47b3-4a86-82d4-ea364806c6bd)

**Comment by sonvnn** [comment]
I fix this issue on https://github.com/templaza/astroid-framework/commit/85d6d35e35955f8d3ee7aebce87cd147f54e9be3

Please help me check it again.

Thanks,
Sonny
