### ISSUE TITLE
I like to contribute to your project. I’m not sure this is the right way to ask.

### ISSUE THREAD

**Issue by Chacapamac** [templaza/astroid-framework#58]
_— I’m not a Github expert  :)_
I care about **Astroid**, losing it will be a dark day for Joomla.

**BACKGROUND:** 
• working with Joomla from Joomla 1.5 — My first websites where in html/frames....
• 12 years using Rockettheme until Gantry arrive (no more Joomla friendly...). To replace it, I intensively test for 3 Years ALL the big Joomla frameworks to find the best and modern Framework available for Joomla — **Astroid was my champion, by far.**
— **You can see why on my joomla.org post here** —> https://forum.joomla.org/viewtopic.php?f=713&t=984872&hilit=astroid
• I Contribute somewhat to the Joomla 4 backend design & ergonomic
 — **You can see my record viewing (390,311 views) post** on Joomla forum here —> https://forum.joomla.org/viewtopic.php?f=803&t=970614
• Expert in UI-UX (almost 25 years experience in design and ergonomic)
• Not a big php coder but I can manage…
• Excellent knowledge of css/scss, bootstrap, flex, Joomla, Astroids & others Joomla frameworks & WYSIWYG drag & Drop Builders…..
• Bilingual (French / English (second language)
• Graphics Design / Marketing (35 years...)

**What I can probably help you with, right know:**
- Test your astroid updates
- Translation
- Help with UI-UX
- Anything, ready to go….

_**Note:** **I also tested ALL their Page Builder at the same time**, **JSN Page builder was my choice** & they sadly also close._ **You can see my Joomla.org post on my choice for this builder here** 
—> https://forum.joomla.org/viewtopic.php?f=575&t=988600

**You can see an Astroid site I’m working on** — _Not public, on my test environment here_
—> http://efoilsurf.graf-test.ca/
_**Note:** Stay on the French side, English not finished…_
**Technicals:**
- Joomla 3.10.4
- Last JoomDev Astoid package 2.5.4
- on Template Zero
- PHP 8.0.8 (on my local Mamp) Frontend/backend working perfectly
- PHP 7.4.27 (on my Live test server) Frontend/backend working perfectly — PHP 8.0 = White error page front & Back — PHP 8.1 = error (see below) only in the administration...

I also made a copy of that website to start to test your new updates here 
—> http://www.new-astroid.graf-test.ca/index.php
Exact same Technicals (for now)
I will installe your version in the following days…

Merry Christmas and thank you to save the jewel that Astroid is — You will not regret your decision.

**Comment by sonvnn** [comment]
Hi @Chacapamac ,

Thank you very much for your support. We need your hand to improve Astroid community. I send you an invitation to join to this Git. You can Pull project and create a branch to work. I will check & merge your contribution.

Let's make Joomla great again, together.

Thank you very much!.
Best Regards,
Sonny

**Comment by Chacapamac** [comment]
**No problem @sonvnn , As I was saying, I’m not a big PHP Coder, but I can surely help.**
I’m installing this afternoon your last astroid-package-v2.5.11.Framework-Template on my testing web server at —> http://www.new-astroid.graf-test.ca/index.php

This website is a clone of a website I’m working on locally with Mamp that also have a copy on the same test environment server
—> http://efoilsurf.graf-test.ca/

**On my local MAMP environment the master site is under**
Joomla 3.10.4
Last JoomDev Astoid package 2.5.4
on Template Zero
PHP 8.1

**On the testing live server environment both sites**:
Joomla 3.10.4
Last JoomDev Astoid package 2.5.4
on Template Zero
PHP 7.4.27 — I did have to downgrade my live server PHP 8.0 Kill both Front & Backend, Their 8.1 make an error only in the administration, (I’m trying to find the problem....)

Really Happy to Help, don’t hesitate to ask if you need a specific thing you want me to do.

**Comment by Chacapamac** [comment]
I close this, as it is not an issue more an introduction...
First real issue following...

**Comment by Chacapamac** [comment]
I close this, as it is not an issue more an introduction...
First real issue following...
