### ISSUE TITLE
Where are download buttons on Astroid website?

### ISSUE THREAD

**Issue by Giorgi625** [templaza/astroid-framework#581]
On Download page I remember I was able to download each template and framework separately but now I do not see download buttons there https://astroidframe.work/download

**Comment by Chacapamac** [comment]
Yeah! Its always practical to have the ability to do that

**Comment by Giorgi625** [comment]
I like to do so because Framework-Template package from github comes with all 3 templates and I do not want to install all of them when I need only Template Two, why should I use older versions?

**Comment by sonvnn** [comment]
Fixed! Thank you :)
