### ISSUE TITLE
What is the purpose of Astroid menu module?

### ISSUE THREAD

**Issue by Giorgi625** [templaza/astroid-framework#583]
Since some weeks ago I noticed that when I install template, there is also added to module list menu module with name Astroid menu. It is just joomla menu module published in position 'status'. only thing is added is that one select field about breakpoints. 
I coulkd not find any position with name status in template so can someone explain for what this module is used?
Thanks

**Comment by mac-joomla** [comment]
habe this helps: https://github.com/templaza/astroid-framework/discussions/359
