### ISSUE TITLE
duplication of meta and title in the error page code + joomla meta is visible

### ISSUE THREAD

**Issue by SerGun78** [templaza/astroid-framework#584]
Astroid 3.0.11
One 3.0.11
The title and meta UTF-8 are still duplicated in the error page code. Joomla metatag is also displayed.
![opera_VnZTVNqYOH](https://github.com/templaza/astroid-framework/assets/95705148/2a676e55-7545-4fbc-9423-4020885b49be)

**Comment by sonvnn** [comment]
Please read this article to learn more "Definition and Usage of Meta tag" 
https://www.w3schools.com/tags/tag_meta.asp

**Comment by SerGun78** [comment]
> Please read this article to learn more "Definition and Usage of Meta tag" https://www.w3schools.com/tags/tag_meta.asp

![opera_VnZTVNqYOH](https://github.com/templaza/astroid-framework/assets/95705148/9a882644-977a-4bbc-8ea4-3392f7952576)

**Comment by sonvnn** [comment]
@SerGun78 Oh sorry! That is my mistake. I fixed this on https://github.com/templaza/astroid-framework/commit/eb537141ca91a73167d28f43d8f2372ffdced1e6

Please download v3-branch and retest again.

Thanks,
Sonny

**Comment by SerGun78** [comment]
> @SerGun78 Oh sorry! That is my mistake. I fixed this on [eb53714](https://github.com/templaza/astroid-framework/commit/eb537141ca91a73167d28f43d8f2372ffdced1e6)
> 
> Please download v3-branch and retest again.
> 
> Thanks, Sonny
also "utf-8" /
