### ISSUE TITLE
Grid widget and widget editor issues

### ISSUE THREAD

**Issue by ute-sch** [templaza/astroid-framework#587]
1. Grid widget doesn't support the Read-more option. (Standard links are ok.)
![Grid-Readmore1](https://github.com/templaza/astroid-framework/assets/48823507/1e7e086b-480e-4316-a324-74a17ad32d7f)
![Grid-Readmore2](https://github.com/templaza/astroid-framework/assets/48823507/2436436b-8210-4578-b2cf-08dd65d23d4b)

2. Widget Content editor supports list format only partially
![Widget-list1](https://github.com/templaza/astroid-framework/assets/48823507/0a4b5141-f58a-418d-bff0-aabcebd14eb9)
![Widget-list2](https://github.com/templaza/astroid-framework/assets/48823507/24a7d4e9-a2de-4622-962f-5860206e1de7)

Would you like to take a look at this?
And thank you very much for your effort!

**Comment by sonvnn** [comment]
Thank you! I will check it.

**Comment by sonvnn** [comment]
@ute-sch 
I fixed editor issue at [Replace Quill editor by CKEditor. Fix issue list indent.](https://github.com/templaza/astroid-framework/commit/23f2d5d79e2bba92627a0e6bd591c7f4ae366049) and Grid readmore issue at [Fix issue buttons does not show on Grid widget](https://github.com/templaza/astroid-framework/commit/cdf2a93ba3e2674e6827a0b2f2f743c420b4d9ae)

Please help me check it.

Thanks & Best Regards,
Sonny
