### ISSUE TITLE
Translate 'Share it'

### ISSUE THREAD

**Issue by Barcenilla00** [templaza/astroid-framework#588]
Where can I translate "Share it" on article content?
Astroid Framework 3.0.11

![image](https://github.com/templaza/astroid-framework/assets/22943057/260c9b88-b081-4bf2-a067-6c906d2b543b)

Also, I think there is a problem with the link corresponding to X.

**Comment by sonvnn** [comment]
It's ASTROID_SOCIAL_SHARE_TEXT

**Comment by Barcenilla00** [comment]
Thanks!
