### ISSUE TITLE
Ready to test 2.5.11 — Is this ok on Joomla 3.10.4

### ISSUE THREAD

**Issue by Chacapamac** [templaza/astroid-framework#59]
I want to test your 2.5.11 release. Is this ok on Joomla 3.10.4 or only with Joomla 4?

— If only Joomla 4, what release should I test ?

**Comment by djayko** [comment]
Luckily, you can use it on both joomla-versions and you can use the same release.

**Comment by Chacapamac** [comment]
> Luckily, you can use it on both joomla-versions and you can use the same release.

Thank You “djayko” - I try this afternoon.

**Comment by sonvnn** [comment]
Yes, You can use it on both Joomla Versions. Thank you for your support :)

**Comment by Chacapamac** [comment]
Just test your 2.5.11 release on my testing website at —> http://new-astroid.graf-test.ca/
- Joomla 3.10.4
- multilingual + eShop & eBooking (from JoomDonation + Smart Slider 3 + Akeeba Admintools with tight/optimize htacces - Joomla cache progressive - GZIP
- PHP 7.4.27

**No errors (I’m so thrill.... You just saved the best Joomla framework**
I will take a full Yearly Membership this afternoon with Templaza....

The only weird problem (100% reproducible, but intermittent on reload or moving dow the page) was a leak of a “carbon fiber” background pattern made with an ::after pseudo element that I have on some inner pages
e.g http://new-astroid.graf-test.ca/index.php/produits-efoilsurf-takuma-eboutique
It’s a footer down the page
No problem with the original last JoomDev version????

**The code I use before and the one I use now to fix it:**
```
//The leaking code here...
//.header-footer-container::after, .carbon::after {
//	background: url(../../../images/x-construction/overlays-patterns/patterns/carbon-fiber.png) repeat;
//	content: "";
//	position: absolute;
//	background-size: 20%;
//	opacity: 0.50;
//	width: 100%;
//	height: 100%;

//	top: 0;
//	left:0;
//	}

//The actual working code here... I just play with the opacity of the png itself to have the same result...	
.header-footer-container, .carbon {
	background: url(../../../images/x-construction/overlays-patterns/patterns/carbon-fiber-50.png) repeat;
	background-size: 20%;
	}
```
![pattern-leak](https://user-images.githubusercontent.com/1907276/147592093-74fca2a3-79a9-4262-927f-7419f570ce58.jpg)

**Comment by sonvnn** [comment]
Hi @Chacapamac ,

You can add Background Image via Layout -> select a section -> Design Setting. Astroid support Background (Color, Image, Video and Gradient).

Please try it and let me know.

Best Regards,
Sonny

**Comment by Chacapamac** [comment]
Thanks @sonvnn, yes I know, In this case, I prefer to have it in custom css because I can use it on other elements, not only module positions.

**I find just weird that this happen only if I update to your 2.5.11 package from the last Joomdev version 2.5.4.**
Anyway I start to understand how to use Github a bit and **I will close this as it is more a discussion.**

**I will open a real Issue with more details to the problem.** 
Something new is introduced in the code that interfere with this pseudo element background.

**Good Day to everybody!**
