### ISSUE TITLE
Override issues

### ISSUE THREAD

**Issue by vtheod** [templaza/astroid-framework#590]
Hello @sonvnn,
I'm facing the following problem with a site's overrides.
When I update astroid templates, the default.php files in the overrides' folder are being updated (I know I can change the name for the default.php file, but it's not an option for me because of falang). 
I also know that I can use a child template, but if I do so, I face another problem. I have some overrides in html/layouts folder which are not working with the child template.
Is there any workaround for this?

**Comment by sonvnn** [comment]
May you detail this issue? It looks like Joomla core issue. About child-template you should raise a question on Joomla git. Astroid can't do anything to modify Joomla core system.

Thank you,
Sonny

**Comment by vtheod** [comment]
I thought it was an astroid issue. I'll raise a question on Joomla then.
Thank you @sonvnn
