### ISSUE TITLE
After update to 3.0.11 no white background

### ISSUE THREAD

**Issue by deltapapa01** [templaza/astroid-framework#591]
Hi @ all,

after update, a lot of my sites lost the white background:

![image](https://github.com/templaza/astroid-framework/assets/19833064/364365c1-6d8f-4ebe-879e-059f013be581)

In Boxlayout, the hole box with content has a white background. in my case, 10 sites are effected to this issue!

is there a simple solution, to put the background in the box back to white?

Linkt to one site: https://taekwondo-husum.de/

This is maybe the problem:
![image](https://github.com/templaza/astroid-framework/assets/19833064/3f06d0fb-c812-4185-a0cd-854ab5ac4780)

WBR,
deltapapa

**Comment by deltapapa01** [comment]
Okay, i don't know why, but i have to set all my sites a new color here:

![image](https://github.com/templaza/astroid-framework/assets/19833064/0dea8fc5-b537-449f-8e59-bb4f0beb3242)

That solved my prob 🤷‍♂️

**Comment by sonvnn** [comment]
Close issue that was resolved
