### ISSUE TITLE
improvement of the navigation widget

### ISSUE THREAD

**Issue by SerGun78** [templaza/astroid-framework#592]
hi all. In the navigation widget, add the ability to add classes to the link (noindex, nopopper, nofolow)

**Comment by sonvnn** [comment]
@SerGun78 I added this feature to Navigation widget here https://github.com/templaza/astroid-framework/commit/7ef746d521c49a0419aacd30e8965ecd239b1e5d

You can download v3-branch and test it.

Best Regards,
Sonny
