### ISSUE TITLE
multiple megamenu in website

### ISSUE THREAD

**Issue by babakhakimi** [templaza/astroid-framework#594]
i use mod_astroid_menu multiple time in my site and I want to change data-asteroid-trigger for each module, but the settings of the first module are executed for all modules

you use 
$('[data-megamenu]').JDMegaMenu();
in your js file

media/astroid/js/megamenu.js

but this code only work for the first menu

please change that to

      $('[data-megamenu]').each(function() {
         $(this).JDMegaMenu();
      });

**Comment by sonvnn** [comment]
Thank you! I will fix it.

**Comment by sonvnn** [comment]
@babakhakimi I updated your change in megamenu.js here https://github.com/templaza/astroid-framework/commit/c74839b9c7471375fd661c2f3b1d090652193ea6

You can download v3-branch and test it.

Thanks & Best Regards,
Sonny
