### ISSUE TITLE
login for spammers

### ISSUE THREAD

**Issue by SerGun78** [templaza/astroid-framework#596]
In the navigation widget code, all links have a title. For text messages this is not critical, but mail definitely shouldn’t have titles. Do you leave this option for spammers to parse mail from the site?

example:

`<div class="astroid-navigation small" id=n-61281d2310dc2c23083129><nav class="nav flex-column"><a id=item-61281d52fef9ac20897384 class=nav-link href=mailto:info@example.ru title=info@example.ru>`

**Comment by sonvnn** [comment]
@SerGun78 I added option enable/disable link title in Navigation Widget here https://github.com/templaza/astroid-framework/commit/6ecc61e101de107e89210c90bb5bb689c8cfaabb

You can download v3-branch and test it.

Thanks & Best Regards,
Sonny
