### ISSUE TITLE
Backward compatibility BS4.5 to BS5

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#6]
In old Bootstrap 4.5 ( Astroid 2.5.4) it was calling float-right.
Now in BS5 it calls float-end and float-start
For better backward compatibility you should add some scss code like this:
```
.float-left {float:left}
.float-right {float:right}
```

**Comment by sonvnn** [comment]
Thank you. I added float-left and float-right at #7 
Please help me update Astroid v2.5.6 and re-check your site.

Best Regards,
Sonny

**Comment by Joomlaplates** [comment]
Hi Sonny,
wow youre fast.. Even better than Joomdev.
I really appriciate this, perfect.
Many thanks, best regards Peter
