### ISSUE TITLE
2.5.11 update on Last Joomdev 2.5.4/Template zero add an underline on mostly all text links.

### ISSUE THREAD

**Issue by Chacapamac** [templaza/astroid-framework#60]
**TESTING CONDITIONS**

**• TEST WEBSITE 1**
**_Last Joomdev Astroid (2.5.4)_**
**Front Page** —> http://efoilsurf.graf-test.ca/administrator/index.php
_**Note:** Stay on the French side, English not finished…_

**Technicals:**
- Joomla 3.10.4
- Last JoomDev Astroid package 2.5.4
- on Template Zero
- PHP 7.4.27

**• TEST WEBSITE 2** 
**CLONE** of “**TEST WEBSITE 1**” with **update Templaza package 2.5.11**
**Front Page** —> http://www.new-astroid.graf-test.ca/index.php

**Technicals Same but:**
- **Update** to **Last JoomDev/Templaza** Astroid package **2.5.11**
—————————————————————————————————————————

**• PROBLEM:**
_Almost all <a href.. text link add an underline..._

![underline-ahref](https://user-images.githubusercontent.com/1907276/147689781-53a95321-0d0a-4589-9459-39e95fc3c04b.jpg)

**Problem code:**

![problem-code](https://user-images.githubusercontent.com/1907276/147689904-1125c28b-fcb1-4906-9282-339db78b7ef5.jpg)

**Main compiled Astroid scss** (zip file included) 
Line 191 
a {
  color: #0073a7;
  text-decoration: underline;
}
[compiled-6e9abea4700a1c5dd07a2ea3e4d14dae.css.zip](https://github.com/templaza/astroid-framework/files/7790054/compiled-6e9abea4700a1c5dd07a2ea3e4d14dae.css.zip)

—————————————————————————————————————
**Last JoomDev Astroid package 2.5.4 difference with Templaza package 2.5.11**
**a href > Computed Styles**
background-color: rgba(0, 0, 0, 0); —> **TEMPLAZA = Line Missing**
box-sizing: border-box;
color: rgb(0, 115, 167);
font-family: "Source Sans Pro", Verdana, sans-serif;
font-size: 16.128px;
font-weight: 400;
line-height: 24.2px;
list-style-type: circle;
outline-color: rgb(0, 115, 167);
outline-style: none;
outline-width: 0px;
text-align: left;
text-decoration-color: rgb(0, 115, 167);
text-decoration-line: none; —> **TEMPLAZA = text-decoration-line: underline;**
text-decoration-style: solid;
text-decoration-thickness: auto;
transition-delay: 0s, 0s;
transition-duration: 0.4s, 0.4s;
transition-property: color, background-color;
transition-timing-function: ease, ease;

**Comment by sonvnn** [comment]
Hi @Chacapamac,

The reason is due to the difference between Bootstrap 4 and Bootstrap 5, again. When you upgrade from Bootstrap 4 to Bootstrap 5, you will face it. You can add css to your scss to override Bootstrap 5 style.
```
a {
    text-decoration: none;
}
```
It will help you.

Best Regards,
Sonny

**Comment by Chacapamac** [comment]
Ok Cool, As you using the onboard Joomla Bootstrap (what I think is the best idea and make the framework closely related to Joomla itself compare to the otjer guys that pile up librairies over librairies) this is not a real issue. Great!

**Suggestion:**
Many designers will not go with the “underline” links look. Me the first. I think it’s an error from bootstrap to add an unnecessary underline to the links 
**I think you should add a code that reverse this in your templates:**

_I personally use in my custom.scss:_
```
///*::::::::::::::::::: TEMPLAZA ASTROID :::::::::::::::::::::::::*/
///*----- FIX Underline under many links because Templaza Astroid using the onboard Joomla Boootstrap Librairie -----*/
a:link, a:visited, a:hover, a:active { text-decoration: none; }
```

**Comment by Chacapamac** [comment]
**I close the issue at is not related to Templaza Astroid but a mistake from the Bootstrap librairie included in Joomla**
