### ISSUE TITLE
improvement of the image widget

### ISSUE THREAD

**Issue by Dnsftl** [templaza/astroid-framework#605]
@sonvnn

Is it possible to add a Link Target to the image widget, as with the navigation widget?

Regards,

Dennis

**Comment by sonvnn** [comment]
@Dnsftl Yes, I added link target option to Image Widget here https://github.com/templaza/astroid-framework/commit/6616bd2f4b8f00a0d30a5e43a93b4d7983058450

You can download v3-branch and test it.

Thanks & Best regards,
Sonny

**Comment by Dnsftl** [comment]
Works perfectly, thank!
