### ISSUE TITLE
off canvas position left not working

### ISSUE THREAD

**Issue by tim2407kes** [templaza/astroid-framework#607]
even if position "left" is activated, the icon for off canvas menu is only shown on the right (framework and template version 3.0.11)

**Comment by sonvnn** [comment]
Please check "Off-Canvas Direction". Make sure it's left
![Screen Shot 2024-03-18 at 13 15 04](https://github.com/templaza/astroid-framework/assets/3204103/d9b192b9-2808-40c4-8e30-c5cccb5b7b15)

Thanks,

**Comment by tim2407kes** [comment]
Sorry the issue still remains, no matter which direction, the icon appears on the right, not on the left.

**Comment by sonvnn** [comment]
Please send me your admin account via sonlv@templaza.com. I will help you check it.
Thanks,
Sonny
