### ISSUE TITLE
A background pattern (image) made with ::after seem to leak it’s original container element when upgrading Joomdev Astroid 2.5.4 to Templaza 2.5.11

### ISSUE THREAD

**Issue by Chacapamac** [templaza/astroid-framework#61]
**A background pattern (image) made with ::after seem to leak it’s original container element when upgrading Joomdev Astroid 2.5.4 to Templaza 2.5.11**

**A good page example is the page contact here _(On TEST WEBSITE 2 (Templaza)_**
—> http://new-astroid.graf-test.ca/index.php/contactez-efoilsurf-canada

**You can see the same page _(without problems)_ on the 2.5.4 joomdev _(TEST WEBSITE 1)_** 
—> http://efoilsurf.graf-test.ca/index.php/contactez-efoilsurf-canada

![pattern-leak-2](https://user-images.githubusercontent.com/1907276/147693858-5dbb736f-c9db-4b88-ae16-2a07db5fe884.jpg)

_**Notes:** 
**a)** The leak happens on arrival and disappear when scrolling the page, reappear or not on reload, It is not constant
**— No problems at all in the Joomdev version**

**b)** I made this pattern in custom css because I use it on different elements in the website and not only modules or template positions. Full control was needed here. I’m aware that you can do similar stuff in the Template Editor. 

**• The point is that the 2.5.11 update should not interfere with this code.**

**This is the css code used:**
```
.header-footer-container::after, .carbon::after {
	background: url(../../../images/x-construction/overlays-patterns/patterns/carbon-fiber.png) repeat;
	content: "";
	position: absolute;
	background-size: 20%;
	opacity: 0.50;
	width: 100%;
	height: 100%;
	top: 0;
	left:0;
	}
```

**TEST WEBSITE 1 - Joomdev and TEST WEBSITE 2 - Templaza Rules Compilation ARE THE SAME**
background-attachment: scroll;
background-clip: border-box;
background-color: rgba(0, 0, 0, 0);
background-image: url("http://specific-website_name-here.ca/images/x-construction/overlays-patterns/patterns/carbon-fiber.png");
background-origin: padding-box;
background-position-x: 0%;
background-position-y: 0%;
background-repeat: repeat;
background-size: 20%;
box-sizing: border-box;
color: rgb(255, 255, 255);
content: "";
font-family: "Source Sans Pro", Verdana, sans-serif;
font-size: 17.92px;
font-weight: 400;
height: 151.6px;
left: 0px;
line-height: 26.8833px;
opacity: 0.5;
position: absolute;
text-align: center;
top: 0px;
width: 1600px;

**Comment by sonvnn** [comment]
Hi @Chacapamac ,

The reason is due to the difference between Bootstrap 4 and Bootstrap 5
![bootstrap](https://user-images.githubusercontent.com/3204103/147717325-e92759b8-2c38-4e77-87e4-8547b0740160.jpg)

In Bootstrap 4: They use position: relative in column class
But Bootstrap 5: They removed it.

@Joomlaplates and I discussed about this in an issue last month. Please refer  #12  . We agreed that is template css issue. So you can use custom css to fix it. Let's try add this code below
```
.header-footer-container {
    position: relative;
}
```
before your css `.header-footer-container::after` and you will see it happen.

Thanks & Best Regards,
Sonny

**Comment by Chacapamac** [comment]
Thanks @sonvnn to take the time to look at this.
I wasn't sure if it was Astroid related.

It’s good to know that the “relative” position is remove from Bootstrap 5  (from 4 version) columns (that make the structure of Astroid layout) because it can cause problems in the updates of Joomla.

**One question,** 
in Joomla 3.10.4,  I’m looking at all “Bootstrap” files in Joomla and if I look at **media > jui > css > bootstrap.css** 
I see version —> Bootstrap v2.3.2 ????

Can you explain as I was thinking that Astroid was now getting is Bootstrap from Joomla ???

**Comment by sonvnn** [comment]
Hi @Chacapamac ,
Yes, Joomla 3 is using Bootstrap 3. But Astroid is using Bootstrap 5. 
In Joomla 3, Astroid load Bootstrap 5 from Astroid Framework Library.
In Joomla 4, Astroid load Bootstrap 5 from Joomla Core.

Thanks & Best Regards,
Sonny

**Comment by Chacapamac** [comment]
Understood & Solved - Thank you !
