### ISSUE TITLE
astroid-framework-3.0.12-error

### ISSUE THREAD

**Issue by folmer23** [templaza/astroid-framework#620]
Hi, 
astroid-framework-3.0.12 has an fatal error after installing.
**Attempt to modify property "links" on bool.**
Will you fix this.
The Astroid Administrator works  no longer. 
We have to re-installed the Joomla website with astroid-framework-3.0.11..

![astroid-framework-3 0 12-error](https://github.com/templaza/astroid-framework/assets/120024807/babeef0f-8a6c-4475-9d40-9e919526dcbf)

Regards,
Milian

**Comment by pixelhexe** [comment]
Same issue here! Joomla 4.4.3, PHP 8.0, 8.1, 8.2 tested on local and remote server. 

After installing Astroid Framework 3.0.11 and deleting Astroid Cache, issue is gone.

**Comment by sonvnn** [comment]
May you help me enable Joomla debug and give me the location of issue? It will help me easy to find solution.

**Comment by folmer23** [comment]
HI Sonvnn,
Thanks. enclosed the error report.
Hope you see the solution.
Regards, Milian
![debug-mode-on](https://github.com/templaza/astroid-framework/assets/120024807/1fc5d6bc-0d95-473d-be47-320eef080cdc)

**Comment by Chacapamac** [comment]
@folmer23 , —> “pixelhexe” said

> After installing Astroid Framework 3.0.11 and deleting Astroid Cache, issue is gone.

Is this work for You?

**Comment by WM-Loose** [comment]
I have now tested this extensively and set up a new Joomla 4.3.3 and Joomla 5.0.3 installation. Both are running PHP 8.3.3 and Maria DB. Then I first installed Astroid 3.0.11 and the Classic Template 1.3.17. Everything is wonderful. 

The update to Astroid 3.0.12 was then displayed and installed. 
Result: no errors and everything works. 
Therefore I assume that an extension or plugin in your Joomla version is the cause.

**Comment by folmer23** [comment]
Strange because 3.0.11 gives no errors with the same extensions and plugins. 
MIlian

**Comment by WM-Loose** [comment]
Can you please list all the third-party extensions and plugins that you have installed?

**Comment by folmer23** [comment]
You  mean the Admin plugins? because the front-end is working fine with astroid-framework-3.0.12.
In the Admin only: **mod_phocatopmenu_v5.0.0** (for the old horizontal Admin menu)
_I have disabled this but no improvement._

These are my adds:
**Components:**
AKEEBA Backup
RSFiles!
RSPagebuilder
JCE Editor
Weblinks
ConvertForms

**Modules:**
Minifrontpagepro
Responsive Tabs Joomla Extension
Hot Effects Rotator
Slideshow CK

But they works fine with astroid-framework-3.0.11.
_Also tried PHP 8.3.4 and PHP 8.2.17_

**Comment by WM-Loose** [comment]
test disable:
RSFiles!
RSPagebuilder

**Comment by folmer23** [comment]
No, got the same error.
Cleared astroid cache.
I realy think that it is a conflict in 3.0.12 Because  3.0.11 works fine.
Also I need my modules and components.

**Comment by WM-Loose** [comment]
More users are now reporting the same problem. 
@Chacapamac: why did you set the thread to resolved? 
Please reopen and let's have find a solution. 
We are also still troubleshooting for customers.

Thanks

**Comment by sonvnn** [comment]
The issue happens from Menu Assignment. I will release a quick fix on Monday. Solution is revert to 3.0.11

**Comment by Chacapamac** [comment]
Sorry 
> 
@Chacapamac: why did you set the thread to resolved?

**I set this as resolve because your post**

> I have now tested this extensively and set up a new Joomla 4.4.3 and Joomla 5.0.3 installation. Both are running PHP 8.3.3 and Maria DB. Then I first installed Astroid 3.0.11 and the Classic Template 1.3.17. Everything is wonderful.
> 
> The update to Astroid 3.0.12 was then displayed and installed.
> Result: no errors and everything works.
> Therefore I assume that an extension or plugin in your Joomla version is the cause.

**Comment by WM-Loose** [comment]
OK, thanks for your answer

**Comment by folmer23** [comment]
"The issue happens from Menu Assignment. I will release a quick fix on Monday. Solution is revert to 3.0.11"
Thanks Sonny Le.
Look foreward to the solution.
Regards,
Milian

**Comment by WM-Loose** [comment]
@folmer23 May you send @sonvnn  your admin account? 
He need check it on your server.
Look here: https://github.com/templaza/astroid-framework/issues/623

**Comment by folmer23** [comment]
https://sdtools.nl/rclub/administrator/
wmloose
loose!WM2024

If you are finisched please give me a sign. I shall then disable your Admin.
Thanks!
MIlian

**Comment by sonvnn** [comment]
@folmer23 This topic is public post. Don't post your private information here.

**Comment by folmer23** [comment]
Thanks sonvnn. 
Sorry for that.
Send you also the Admin to your emailaddress..
Milian

**Comment by folmer23** [comment]
On this site. Right?
Astroid 3.0.12 works here now! 
https://sdtools.nl/rclub/administrator/

What can I do to fix this on my other websites with astroid-framework-3.0.12
Or is ther an update comming soon?
Regards,
Milian

**Comment by folmer23** [comment]
https://sdtools.nl/ja50-classic-wolken/administrator/
This astroid is still not working.

**Comment by Joomlaplates** [comment]
Hello,
please disable or uninstall WEBLINKS component, its an old extension from Joomla 3!
Greatings Peter

**Comment by folmer23** [comment]
Hi Peter,
I removed WEB LINKS, but no improvement.
On another website, sonvnn resolved the error.
WEB LINKS are still there. And Astroid 3.0.12 works fine there.
For security, I disabled WEBLINKS there.
Regards, Milian

**Comment by sonvnn** [comment]
@folmer23 @Joomlaplates please help me download v3-branch and reinstall on your site. It will help you solve the issue.

Best Regards,
Sonny

**Comment by folmer23** [comment]
HI Sonny,
I see no v3-branch
![still-3_0_12](https://github.com/templaza/astroid-framework/assets/120024807/0f0d603e-2dac-4052-abaf-7f42779c5707)

![still-12-2](https://github.com/templaza/astroid-framework/assets/120024807/070e0518-a69e-4c7f-aed7-8f3f9aa02031)

Do you have a link?
Regards, Milian

**Comment by WM-Loose** [comment]
Look here:
https://github.com/templaza/astroid-framework/tree/v3

**Comment by folmer23** [comment]
Yes,
I downloaded the Astroid-Framework-developer.zip.
But the Joomla installer gives an error and Astroid is no longer availlable.
What went wrong?
![tp_classic-developer](https://github.com/templaza/astroid-framework/assets/120024807/402762a2-d0a5-4e80-acdd-e2f9022cc951)
Milian

**Comment by Joomlaplates** [comment]
Download the Astroid V3 and install it.
[Uploading astroid-framework-3.zip…]()

**Comment by folmer23** [comment]
Yes,
This one works!. I shall do some tests on other websites and let you know.
_I uploaded the last one in the list (en-GB.astroid.ini) but that has no effect...._

**Comment by folmer23** [comment]
Yes, This version works. I have tested 4 websites 'till now. 
And they are loading now the Astroid Menu structure as it should be:)
Thanks Sonny and Dirk for your efforts for all of us!
Regards, Milian

**Comment by pixelhexe** [comment]
This version also works on my site - on local and remote server. Thank you, guys!

**Comment by folmer23** [comment]
Hi,
I see that the fix (helper.php) is not yet available for download from astroidframe.work (Released 5 days ago.
)  and joomlaplates.com (28-03-2024).

Is it comming soon? Or do we have to wait ''till v3.0.13 ?
Regards,
Milian

**Comment by sonvnn** [comment]
Please wait for 3.0.13 which will be release tomorrow. Now you can download v3-branch and test it.

**Comment by folmer23** [comment]
Thanks Sonny,
Good to know.
All my Astroid websites are working fine now with the fixed Helper.php.
Thanks!
MIlian

**Comment by folmer23** [comment]
you're welcome.

**Comment by Chacapamac** [comment]
@sonvnn  Where can you donate?

**Comment by sonvnn** [comment]
@Chacapamac you can buy me a coffee on Astroid homepage or Astroid github

**Comment by Chacapamac** [comment]
**Don’t find it on Astroid Homepage???**

**Comment by sonvnn** [comment]
![image](https://github.com/templaza/astroid-framework/assets/3204103/fd422e2e-1d97-48dc-a615-8991c30ab8b9)

Go to homepage you can see it here :)

**Comment by Giorgi625** [comment]
https://github.com/templaza/astroid-framework here right above list of Astroid features.

**Comment by sonvnn** [comment]
@Giorgi625 thank you for the donate 💕

**Comment by WM-Loose** [comment]
@sonvnn sent you a a little cup of coffee ;-)

**Comment by sonvnn** [comment]
@WM-Loose thank you for the donate 😍

**Comment by minecraftthebes** [comment]
can you give me a astroid v3 unblocked link ?
