### ISSUE TITLE
Since 3.0.12 Error > Attempt to modify property "links" on false

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#623]
After update the Astroid to 3.0.12 I got an error when i want to setup the Template settings
>> Joomla 5.0.3 and PHP 8.3
`Attempt to modify property "links" on false`
![Bildschirmfoto2024-03-28um15 36 07](https://github.com/templaza/astroid-framework/assets/71080509/caf9024c-427d-4989-a5eb-bb877847446d)

Anybody know what it is?
Thanks

**Comment by sonvnn** [comment]
It's problem from Menu Assignment. I will release a quick fix on Monday. Solution is revert to 3.0.11

**Comment by sonvnn** [comment]
Hi @Joomlaplates 

May you send me your admin account? I need check it on your server.

Thanks & Best Regards,
Sonny

**Comment by Joomlaplates** [comment]
With V3 Astroid I still got the issue
![issue](https://github.com/templaza/astroid-framework/assets/71080509/08620364-e96f-424f-9312-01dc5eff4a5d)

**Comment by sonvnn** [comment]
May you send me the admin of your site? I will check it. 

Best regards,
Sonny

**Comment by Joomlaplates** [comment]
I have send you already! Now again

**Comment by RedesMexico** [comment]
I have the same error with version 3.0.12, can I help?

**Comment by sonvnn** [comment]
> I have send you already! Now again

I am sorry! I still haven't received your email yet. Can you send me again via sonlv@templaza.com?

@RedesMexico Yes, please send me your admin account via sonlv@templaza.com. I will help you check it.

**Comment by sonvnn** [comment]
@Joomlaplates @RedesMexico I added some conditions to handle exceptions of Menu Links at https://github.com/templaza/astroid-framework/commit/85f437c367f11ce528610e3475ef8623b8930002. Please help me download v3-branch and retest it.

As soon as you confirm this issue gone. I will release v3.0.13

**Comment by RedesMexico** [comment]
Ok I will test again with the new changes in 85f437c.

**Comment by RedesMexico** [comment]
Hello

The line 421 is 1 additions ? --- if ($link->level !== 0) {

**Comment by sonvnn** [comment]
@RedesMexico Just download https://github.com/templaza/astroid-framework/archive/refs/heads/v3.zip and install to your Joomla extension.

**Comment by Joomlaplates** [comment]
Hello Sonny,
yes its working now with new Astroid v3.
Thank you!! Greatings Peter
