### ISSUE TITLE
A better solution to flush the compiled CSS files when in website development (testing CSS).

### ISSUE THREAD

**Issue by Chacapamac** [templaza/astroid-framework#63]
**As a developer, I need to empty the Astroid cache often and each time I have to;** 
Step 1: enter the Astroid template manager administration> Extensions > Templates > Styles
Step 2: Click to open the “Default” (or another) Astroid layout Style 
Step 3: Click the “Template Options” button
Step 4: Wait until the Template Style admin windows are fully loaded (Astroid animation or not)
Step 5: Click the “Clear cache” button

![compiled](https://user-images.githubusercontent.com/1907276/148091491-e7ea23d2-2340-42b4-8c7e-b1f49d3ef910.jpg)

Now I bypass all that and use FTP (for live websites) or Finder Mac (local) to clear them directly, efficient but not practical.

**• JoomDev people suggest I use The Debug function????**
I try and it seems to have no effect on the CSS compiled by Astroid?
**— With Debug on:**
- compiled CSS continued to be generated
- You still need to go in Astroid template config to Clear the cache
- If you refresh (reload) the site the same compiled CSS stay in the CSS folder

**SOLUTIONS**
**a)** A “Clear Astroid Cache” button at the first level of Joomla administration (like presented here) to bypass the 3 clicks and wait to access the “Clear Cache” button in your Astroid template management. 
(I think you need an administration plugin for that?)

_Photoshop montage on what a button like that can look like._
![cache-button](https://user-images.githubusercontent.com/1907276/148091536-11669b7d-1fe7-403a-9a1a-da2dc01ed9a9.jpg)

**OR EVEN BETTER**
b) A Development button or setting in the Astroid plugin that tells the system to still generate the compiled CSS but automatically delete them and recreate a new one every time you refresh the website.
This setting exists in other frameworks.

_Photoshop montage on what a button like that can look like._
![dev-setting-astroid-plugin](https://user-images.githubusercontent.com/1907276/148091926-199fe778-761a-45e5-ad17-f55e7578fc73.jpeg)

**Comment by sonvnn** [comment]
Hi @Chacapamac,
Thank you for your suggestion. I agree with you. I will add this feature to version 2.5.13.

Best Regards,
Sonny

**Comment by Chacapamac** [comment]
**Sorry, I was wrong...**
To be sure, I just retest carefully the actual “**Debug**” button that **JoomDev give me as a solution** when developing and testing css for a website.

**This is the behaviour:**

**Debug OFF** ————————————
- When custom.scss is modified
+ Browser cache & history + All Joomla cache emptied
+ Reload website frontend

_Result:_
- **Compiled css are not removed** to reflect the change in the custom.scss
- **Need to go to the Astroid Template Manager cache button** to empty the Astroid cache (remove compiled css files)

_**Note:** I’m sure, even with Debug Off, Astroid reload it’s cache at one point? — Maybe based on the time allowed in Joomla cache refresh settings?_


**Debug ON** ————————————
- When custom.scss is modified
+ Browser cache & history + All Joomla cache emptied
+ Reload website frontend

_Result:_
- **Compiled css are removed and rebuild to reflect the change in the custom.scss**

This mean that you don’t need to add “Development” button to the Astroid plugin as the “Debug” button seem to work correctly (as JoomDev solution imply).

_**Note:**I probably didn’t empty my Browser cache/history & Joomla cache correctly when I try..._
———————————————————


Maybe the idea to have an “Empty Astroid Cache” button at the first level of Joomla (without the need to go in the Astroid template manager “Astroid Empty Cache” button or change the setting in the Astroid plugin is still a good idea — (easier for newbie)

Your welcome to close this.
Good Day

**Comment by sonvnn** [comment]
> Maybe the idea to have an “Empty Astroid Cache” button at the first level of Joomla (without the need to go in the Astroid template manager “Astroid Empty Cache” button or change the setting in the Astroid plugin is still a good idea — (easier for newbie)
Yes, this is exactly what I want to do in the next version

Thanks & Best Regards,
Sonny

**Comment by Chacapamac** [comment]
I have few other suggestions coming and I will continue to test your version.
If you need me to test something in particular or for French/English translation, don’t hesitate to ask...

Good Night (It’s 10:00 PM) in Canada!

**Comment by sonvnn** [comment]
Hi @Chacapamac,
Thank you very much. I updated Astroid 2.5.12 with new language file, please help me check it.

Hi @Joomlaplates,
Please help me update language file for multi-language. Thank you very much.

Best Regards,
Sonny

**Comment by Chacapamac** [comment]
Sorry to close this, I’m not used to Github, from now, I will let you close issues. Tell me if you prefer that?

For the languages — I’m updating to 2.5.12 and I will check French & English

**Comment by Joomlaplates** [comment]
German language is up to date for 2.5.12

**Comment by Chacapamac** [comment]
First My 2.5.11 to 2.5.12 give me this
![update](https://user-images.githubusercontent.com/1907276/148411877-d4b9bf02-b588-4b55-b72a-af7208b07b0e.jpg)
s
**Is this OK?**

**• First remark on the French versus English in the 2.5.12 version:**
English Items: 121 items
French Items: 106 items

I will fix that.

**Comment by Chacapamac** [comment]
I’m working on French language NOW!

**Comment by Joomlaplates** [comment]
Hello, mail me the language file and I will update it. You will find my mail address here:
https://github.com/templaza/astroid-framework/tree/language

**Comment by sonvnn** [comment]
> Sorry to close this, I’m not used to Github, from now, I will let you close issues. Tell me if you prefer that?
> 
> For the languages — I’m updating to 2.5.12 and I will check French & English
> 
> **Just a question**, I still have Updates Sites URL pointing to JoomDev for Template One & Zero — Can I trash?
> 
> ![update-templ-joomdec](https://user-images.githubusercontent.com/1907276/148409191-3b6d65a6-75b6-4b55-b2ea-f8fce47178b6.jpg)

Yes, your can trash it.

> Also, I remark that some links, in the template manager should start to point to Templaza as Joomdev is fading away...
> e.g. No help on Joomdev forum and you need a valid subscription.

Yes, I will find and refer user to this Github's issue in the 2.5.13. This is an independent project. So any link will just point to this github and everyone is encouraged to join as a contributor. I will keep this project open source for everyone. If anyone wants to contribute to this project is welcome. I will add their link to project description like what I did with TemPlaza and Joomlaplate.

Best Regards,
Sonny

**Comment by Chacapamac** [comment]
@Joomlaplates  - Fichier français envoyé.

**Comment by Joomlaplates** [comment]
I just attached the language file to the download area.
Thanks so much. Regards Peter

**Comment by Chacapamac** [comment]
No problem ! good night (au Québec)

Patrick Toulze
Graf • Directeur artistique — Conseiller en marketing — Canaux sociaux — SEO — Web Mobile

**Comment by Chacapamac** [comment]
@rinka88 

> 1. or didn’t produce the compiled css files at all? 
> 2. if you create a copy of the template, then also use css from the first, and not the copied one?

**Not sure I understand your point?**

**Comment by sonvnn** [comment]
Hello @Chacapamac 

I added this module to v2.5.13. But It is available on Joomla 4 only. Please help me check it.

Thanks & Best Regards,
Sonny

**Comment by Chacapamac** [comment]
I install 2.5.13 by the **normal Joomla update process** on my Joomla 3.10.5 / php 8 test site — **No problems, everything work!**
I install it also on a copy of that test website **that I will passed to Joomla 4 later to test the cache module**...
I guess its an administration module? — Do you have to turn it On?
@sonvnn 
**Is this what I should see in Joomla > Manage > Astroid ?**

![2-5-13](https://user-images.githubusercontent.com/1907276/150559155-6a5146f9-af41-48e9-bb5d-a69ff16a777f.jpg)

**Comment by sonvnn** [comment]
Helllo @Chacapamac ,

System will check if your Joomla version is 4, then module will be installed. You can check the code at https://github.com/templaza/astroid-framework/blob/master/script.php#L58

Thanks & Best Regards,
Sonny

**Comment by Chacapamac** [comment]
Thanks @sonvnn 
I’m in the process of cleaning up the website to upgrade to 4
You can see my Astroid installation above.

The Joomla 4 auto check show me this:
![infos](https://user-images.githubusercontent.com/1907276/150646648-541d4f76-da17-44d0-836b-f47c27f71356.jpg)

I guess you need to add some infos to Astroid to pass the test....

**Comment by Chacapamac** [comment]
Ok, I update correctly Astroid for Joomla 4
![complete](https://user-images.githubusercontent.com/1907276/150648635-0c6a1197-4af7-4390-adb1-868d575a246c.jpg)

**Comment by sonvnn** [comment]
Please help me re-install framework again to enable Module.

Thanks & Best Regards,
Sonny

**Comment by Chacapamac** [comment]
@sonvnn 
I’m not sure what yo are asking here Sonny ?

> Please help me re-install framework again to enable Module.

I will test Joomla 4 on Astroid in 2 days & look for testing the module....

**Comment by sonvnn** [comment]
Hi @Chacapamac ,

When you install Astroid v2.5.13 on Joomla 4, you should see this
![Screen Shot 2022-01-25 at 09 18 57](https://user-images.githubusercontent.com/3204103/150898709-be98b5f9-e8f7-4614-8c9a-f361d1c98b6c.png)

And module will appear on the top right bar.
![Screen Shot 2022-01-25 at 09 19 04](https://user-images.githubusercontent.com/3204103/150898762-be3824ec-2d3c-41c5-ab2d-875fc9b5b0fd.png)

Please help me check it again.

Thank you,
Sonny

**Comment by Chacapamac** [comment]
I understand,
I will test this in 1 or 2 days, test the fonction and come back here to tell you how it goes.

No more visits to the template/layout manager & easy for newbies.
**Great work Sonny!**

**Comment by Chacapamac** [comment]
Hi @sonvnn 
**What I did so far:**
I use that way because I want to test first if you can update a Joomla 3.10.5 with Astroid to Joomla 4. This is important for me and everybody that want to pass their existing Joomla 3 website _(with Astroid Templaza)_ to 4.

• I install a clean Joomla 3.10.5
• I install your last Astroid package and put Astroid as the main template
• I update Joomla to 4 bypassing the warning that Astroid have no infos on it’s Joomla 4 compatibility.
![Joom-3 10 5-to-4-warn](https://user-images.githubusercontent.com/1907276/151174959-d8acebcb-7b12-498a-aa73-c9e1607ec6c2.jpg)

Only bug.
**The Joomla 4 update show a white page with the top Joomla 4 admin bar with this error???**
![error-update-4](https://user-images.githubusercontent.com/1907276/151175365-42ce56d6-5c09-4903-9704-1d8c1410fa4b.jpg)
I will check what that error mean later....

After, I look for Your Cache Admin module, I didn’t see it on the top right bar and I didn’t see in the Admin Modules (disabled or Active)

**Next step, I will reinstall Astroid 2.5.13 on top to see if the module Appear and come back here.**

**Comment by Chacapamac** [comment]
I just reinstall everything and that **error: 0** have nothing to do with Astroid
I repeat the error passing directly from a clean Joomla 3.10.5 and Updating to 4.0.6 — This is a Joomla problem...

**Comment by Chacapamac** [comment]
@sonvnn 
This can be closed
