### ISSUE TITLE
Version 3.0.13 gives error 500 in Joomla

### ISSUE THREAD

**Issue by chupidos** [templaza/astroid-framework#631]
The update to version 3.0.13 gives error 500 when installing it in Joomla, leaving the website inoperative. You have to roll back to version 3.0.12 for the website to work again. Please fix it as soon as possible. Thank you

**Comment by deltapapa01** [comment]
Hi, can you add a screenshot of the error or stack? Is your backend available?

**Comment by sonvnn** [comment]
It happens on Jollyany side. I will soon update Jollyany Framework. Please wait.

**Comment by sonvnn** [comment]
@chupidos Please help me update Jollyany and Newspaper to latest version
Jollyany Version: 3.5.24
Newspaper Version 1.0.3

Please give me the result after update.

Thanks & Best Regards,
Sonny

**Comment by chupidos** [comment]
Hi Sonny, thanks for your interest.

I have the latest versions of both Astroid, Jollyany and Newspaper (see the attached image), and Joomla of course.

I have done a test on a site with little traffic. The error does not occur on the main page (home) only when you access sections and specific articles.

There is no indication of the error in the everything.php log file, nor in the Apache logs.

I think the problem is some error in the router of this version of Astroid that does not handle it according to the Joomla router. Astroid framework updates have never given me any problems.
![template-versions](https://github.com/templaza/astroid-framework/assets/17751078/daa605d6-18d2-4101-b8bd-9cf4c229f278)

**Comment by chupidos** [comment]
> It happens on Jollyany side. I will soon update Jollyany Framework. Please wait.

Thanks, I'm waiting

**Comment by sonvnn** [comment]
Newspaper latest version works well on my test server. So I need your admin account for testing. Can you send me your admin account via sonlv@templaza.com?

Best Regards, 
Sonny

**Comment by sonvnn** [comment]
Hi @chupidos 

I fixed this issue in Jollyany. You can check it here https://github.com/templaza/jollyany-framework/commit/0a18c614579392d94191716014c93f065d496a6e

I updated your Astroid and Jollyany to latest version. So you can check your site again. 
Don't hesitate contact me if you need further assistant.

Best Regards,
Sonny

**Comment by chupidos** [comment]
Thanks Sonny, it works fine on the website I gave you access to.

I now see on the rest of my websites that there are two updates: Astroid Framework and Jollyany Framework

I understand that to avoid problems I must update Jollyany Framework first, right?

**Comment by sonvnn** [comment]
Yes, I glad to see your website is well. Please let me know if you need further assistant.

**Comment by chupidos** [comment]
Hi Sonny, I inform you that I have favorably updated the rest of my sites. Thank you for your work.

**Comment by sonvnn** [comment]
Thank you! If you love it. Please help me rate/review for Newspaper on themeforest.net. 

Thank you so much!
Sonny

**Comment by chupidos** [comment]
https://themeforest.net/item/newspaper-magazine-news-portal-joomla-4-template/34972872/comments?page=1&filter=all#comment_30562937

**Comment by sonvnn** [comment]
@chupidos Can you help me rate for Newspaper at https://themeforest.net/downloads?
You can see something like this.
![Screen Shot 2024-04-08 at 10 04 34](https://github.com/templaza/astroid-framework/assets/3204103/056d9435-3f5d-4550-9547-04ff8a011dfd)

Thank you very much :)
Best Regards,
Sonny
