### ISSUE TITLE
Problem with Articles Widget

### ISSUE THREAD

**Issue by deltapapa01** [templaza/astroid-framework#633]
Hello,
I'm currently trying out the widgets a bit with 3.0.13 and Template Two.
I have noticed the following:
1) I have created 2 articles in a "News" category. These articles should only be displayed on the start page. However, if I create an additional "News" menu item (Blog Layout), the articles are displayed twice. 
Startpage, everything okay: https://p603133.mittwaldserver.info/cms/
If I now click on the "News" menu item, the articles are displayed in the widget and joomla view. However, I have deselected the News menu item in Widget Assignment : https://p603133.mittwaldserver.info/cms/news
2) It is not possible to hide the headline of the article in the Article Widget. Unfortunately, this is always linked, it is not possible to deactivate the linking (See Startpage)

WBR,
deltapapa

**Comment by sonvnn** [comment]
@deltapapa01 Thank you for report issue. May you send me your admin account? I will check it.

Thanks & Best Regards,
Sonny

**Comment by deltapapa01** [comment]
Hi Sonny,

i send account information to sonlv@templaza.com

Thanks a lot and wbr,
deltapapa

**Comment by sonvnn** [comment]
Hi @deltapapa01 

I fixed this issue on https://github.com/templaza/astroid-framework/commit/9daf3c42ad838b29350dde67950a173a416a2a7e

I updated your website. Please help me check your site again.

Best Regards,
Sonny

**Comment by deltapapa01** [comment]
Hey Sonny,

thank you very much and sorry for the late response.
I test it with with v3.0.14RC1 and it is working now.
Thank you very much, 
wbr,
deltapapa
