### ISSUE TITLE
Extra classes in Astroid Row create horizontal scroll in my browser

### ISSUE THREAD

**Issue by Giorgi625** [templaza/astroid-framework#636]
As you can see I am having a horizontal scrollbar on my website, I searched and found that after removing this class "gx-lg-4 gx-xl-5 gx-xxl-5" from one of the astroid rows horizontal scrollbar dissappears. recently I got notification on email that someone also reported about this classes but I could not find that thread. So I created new one
![noname](https://github.com/templaza/astroid-framework/assets/16633699/10ecb33b-daae-4511-8221-484948a5df13)

**Comment by sonvnn** [comment]
Go to Row settings -> Switch "Extra Large Gutter" and "Extra Extra Large Gutter" to Inherit
![Screen Shot 2024-04-08 at 09 47 07](https://github.com/templaza/astroid-framework/assets/3204103/330f7252-f83b-4465-bfb4-3e7e9361e826)
![Screen Shot 2024-04-08 at 09 44 39](https://github.com/templaza/astroid-framework/assets/3204103/bce1146a-7466-4878-a36d-a7bba83d80c7)

**Comment by Giorgi625** [comment]
Thanks it worked.
