### ISSUE TITLE
Malfunction with "Articles Anywhere" from Regular Labs

### ISSUE THREAD

**Issue by Oxaluz** [templaza/astroid-framework#645]
I have installed the current version of the “Articles Anywhere” plugin and now I get the following error message when using it in the frontend editor

```
Warning
: Constant ASTROID_TEMPLATE_NAME already defined in
C:\xampp\htdocs\sgsn_site_new\libraries\astroid\framework\library\astroid\Template.php
on line 96

0
Undefined constant "Astroid\ASTROID_MEDIA_TEMPLATE_PATH"
```

**Comment by Oxaluz** [comment]
...some additional info:

<html>
<body>
<div class="row" style="box-sizing: border-box; --bs-gutter-x: 1.5rem; --bs-gutter-y: 0; display: flex; flex-wrap: wrap; margin-top: calc(-1 * var(--bs-gutter-y)); margin-right: calc(-.5 * var(--bs-gutter-x)); margin-left: calc(-.5 * var(--bs-gutter-x)); color: rgb(33, 37, 41); font-family: Nunito, Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="col-12 text-center align-self-center" style="box-sizing: border-box; flex: 0 0 auto; width: 960px; max-width: 100%; padding-right: calc(var(--bs-gutter-x) * .5); padding-left: calc(var(--bs-gutter-x) * .5); margin-top: var(--bs-gutter-y); align-self: center !important; text-align: center !important;"><div class="py-3" style="box-sizing: border-box; padding-top: 1rem !important; padding-bottom: 1rem !important;"><h2 class="display-1" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0.7rem; font-weight: 300; line-height: 1.2; color: var(--bs-heading-color); font-size: calc(1.625rem + 4.5vw); text-transform: none; font-family: Poppins, Arial, Helvetica, sans-serif;">0</h2><p class="display-6" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; font-size: calc(1.375rem + 1.5vw); font-weight: 300; line-height: 1.2;">Undefined constant "Astroid\ASTROID_MEDIA_TEMPLATE_PATH"</p></div><a class="btn btn-backtohome btn-lg" href="https://xampp.rehlinger.me/sgsn_site_new/" role="button" style="box-sizing: border-box; color: var(--bs-btn-color); text-decoration: none; transition: color 0.15s ease-in-out 0s, background-color 0.15s ease-in-out 0s, border-color 0.15s ease-in-out 0s, box-shadow 0.15s ease-in-out 0s; cursor: pointer; --bs-btn-padding-x: 1.7rem; --bs-btn-padding-y: 0.5rem; --bs-btn-font-family: ; --bs-btn-font-size: 1.25rem; --bs-btn-font-weight: 400; --bs-btn-line-height: 1.5; --bs-btn-color: white; --bs-btn-bg: #1f52a0; --bs-btn-border-width: var(--bs-border-width); --bs-btn-border-color: #1f52a0; --bs-btn-border-radius: var(--bs-border-radius-lg); --bs-btn-hover-border-color: #194280; --bs-btn-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.15), 0 1px 1px rgba(0, 0, 0, 0.075); --bs-btn-disabled-opacity: 0.65; --bs-btn-focus-box-shadow: 0 0 0 0.25rem rgba(var(--bs-btn-focus-shadow-rgb), .5); display: inline-block; padding: var(--bs-btn-padding-y) var(--bs-btn-padding-x); font-family: var(--bs-btn-font-family); font-size: var(--bs-btn-font-size); font-weight: var(--bs-btn-font-weight); line-height: var(--bs-btn-line-height); text-align: center; vertical-align: middle; user-select: none; border: var(--bs-btn-border-width) solid var(--bs-btn-border-color); border-radius: var(--bs-btn-border-radius); background-color: var(--bs-btn-bg); --bs-btn-hover-color: white; --bs-btn-hover-bg: #1a4688; --bs-btn-focus-shadow-rgb: 65, 108, 174; --bs-btn-active-color: white; --bs-btn-active-bg: #194280; --bs-btn-active-border-color: #173e78; --bs-btn-active-shadow: inset 0 3px 5px rgba(0, 0, 0, 0.125); --bs-btn-disabled-color: white; --bs-btn-disabled-bg: #1f52a0; --bs-btn-disabled-border-color: #1f52a0;">Zur Startseite</a></div></div><div class="row bg-white" style="box-sizing: border-box; --bs-gutter-x: 1.5rem; --bs-gutter-y: 0; display: flex; flex-wrap: wrap; margin-top: calc(-1 * var(--bs-gutter-y)); margin-right: calc(-.5 * var(--bs-gutter-x)); margin-left: calc(-.5 * var(--bs-gutter-x)); --bs-bg-opacity: 1; background-color: rgba(var(--bs-white-rgb), var(--bs-bg-opacity)) !important; color: rgb(33, 37, 41); font-family: Nunito, Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="col py-3 text-center" style="box-sizing: border-box; flex: 1 0 0%; width: 960px; max-width: 100%; padding-right: calc(var(--bs-gutter-x) * .5); padding-left: calc(var(--bs-gutter-x) * .5); margin-top: var(--bs-gutter-y); padding-top: 1rem !important; padding-bottom: 1rem !important; text-align: center !important;"><code class="p-3" style="box-sizing: border-box; font-family: var(--bs-font-monospace); font-size: 0.875em; color: var(--bs-code-color); overflow-wrap: break-word; padding: 1rem !important;">ERROR 0 - Undefined constant "Astroid\ASTROID_MEDIA_TEMPLATE_PATH" in C:\xampp\htdocs\sgsn_site_new\libraries\astroid\framework\library\astroid\Document.php:1233</code></div></div><div class="row" style="box-sizing: border-box; --bs-gutter-x: 1.5rem; --bs-gutter-y: 0; display: flex; flex-wrap: wrap; margin-top: calc(-1 * var(--bs-gutter-y)); margin-right: calc(-.5 * var(--bs-gutter-x)); margin-left: calc(-.5 * var(--bs-gutter-x)); color: rgb(33, 37, 41); font-family: Nunito, Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="col mb-5 bg-white" style="box-sizing: border-box; flex: 1 0 0%; width: 960px; max-width: 100%; padding-right: calc(var(--bs-gutter-x) * .5); padding-left: calc(var(--bs-gutter-x) * .5); margin-top: var(--bs-gutter-y); margin-bottom: 3rem !important; --bs-bg-opacity: 1; background-color: rgba(var(--bs-white-rgb), var(--bs-bg-opacity)) !important;"><h2 id="caption" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0.7rem; font-weight: 600; line-height: 1.2em; color: var(--bs-heading-color); font-size: 1.6rem; text-transform: none; font-family: Poppins, Arial, Helvetica, sans-serif;">Call Stack</h2>
# | Function | Location
-- | -- | --
1 | () | JROOT\libraries\astroid\framework\library\astroid\Document.php:1233
2 | Astroid\Document->astroidCSS() | JROOT\libraries\astroid\framework\library\astroid\Helper\Head.php:88
3 | Astroid\Helper\Head::styles() | JROOT\libraries\astroid\framework\library\astroid\Site.php:40
4 | Astroid\Site->onBeforeRender() | JROOT\plugins\system\astroid\src\Extension\AstroidPlugin.php:65
5 | Joomla\Plugin\System\Astroid\Extension\AstroidPlugin->onBeforeRender() | JROOT\libraries\src\Plugin\CMSPlugin.php:289
6 | Joomla\CMS\Plugin\CMSPlugin->Joomla\CMS\Plugin\{closure}() | JROOT\libraries\vendor\joomla\event\src\Dispatcher.php:454
7 | Joomla\Event\Dispatcher->dispatch() | JROOT\plugins\system\regularlabs\src\Application.php:75
8 | RegularLabs\Plugin\System\RegularLabs\Application->render() | JROOT\plugins\system\regularlabs\src\QuickPage.php:70
9 | RegularLabs\Plugin\System\RegularLabs\QuickPage::getHtml() | JROOT\plugins\system\regularlabs\src\QuickPage.php:50
10 | RegularLabs\Plugin\System\RegularLabs\QuickPage::render() | JROOT\plugins\system\regularlabs\regularlabs.php:92
11 | PlgSystemRegularLabs->onAfterRoute() | JROOT\libraries\src\Plugin\CMSPlugin.php:289
12 | Joomla\CMS\Plugin\CMSPlugin->Joomla\CMS\Plugin\{closure}() | JROOT\libraries\vendor\joomla\event\src\Dispatcher.php:454
13 | Joomla\Event\Dispatcher->dispatch() | JROOT\libraries\vendor\joomla\application\src\AbstractApplication.php:99
14 | Joomla\Application\AbstractApplication->dispatchEvent() | JROOT\libraries\src\Application\SiteApplication.php:798
15 | Joomla\CMS\Application\SiteApplication->route() | JROOT\libraries\src\Application\SiteApplication.php:244
16 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT\libraries\src\Application\CMSApplication.php:306
17 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\includes\app.php:58
18 | require_once() | JROOT\index.php:32

</div></div>
</body>
</html>

**Comment by sonvnn** [comment]
I tried a quickfix in https://github.com/templaza/astroid-framework/commit/7b2125d17d87c96e051c9d988c83902d5e734bdc
Please help me download v3-branch and retest again. If this issue still happen please send me your admin account via sonlv@templaza.com. I will help you check it.

Best Regards,
Sonny

**Comment by Oxaluz** [comment]
It looks like it's working.
At least the error message is gone.

regards
Oxaluz

**Comment by sonvnn** [comment]
@Oxaluz Thank you! I marked this issue is resolved.
