### ISSUE TITLE
Astroid 3.0.13 after Update to J5.1 no Window open for Icons in Menuoptions

### ISSUE THREAD

**Issue by WM-Loose** [templaza/astroid-framework#652]
After updating from J5.0.3 to 5.1, the window for selecting icons in the menu options no longer opens.

Joomla 5.1
Astroid 3.0.13
PHP 8.3

In Joomla 4.4.4 ist everthing OK, only in J5.1

**Comment by WM-Loose** [comment]
Great Sonny. With your update V3 it now works wonderfully.
Do you already know when you can roll out the official update 3.0.14 to everyone?

**Comment by WM-Loose** [comment]
@sonvnn: Today I just have to praise you. I am impressed by how professionally and reliably you support the users again and again and how quickly you react. Many thanks also on behalf of our customers.

**Comment by sonvnn** [comment]
@WM-Loose Thank you very much :)
