### ISSUE TITLE
Media Manger not loading

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#66]
I always have some clients where the Astroid Media manager is hanging and could not load the images when they want to select a logo file.
The problem is always some jpg files with "üöä" or other special language characters. ( see pic attached)
Maybe you can change the PHP load media function to UTF or just give an information that the files are not supported but not hang on.
Thanks, Peter
![fehler](https://user-images.githubusercontent.com/71080509/148405073-72a8d5c0-fddb-4521-bbb5-7b7c7b8ef593.jpg)

**Comment by sonvnn** [comment]
Hi Peter,

I tried test with an image named "üöä.jpg" and system works well.
![Screen Shot 2022-01-10 at 14 58 36](https://user-images.githubusercontent.com/3204103/148733903-35a237b0-3f36-43f6-a09e-622fe6a02933.png)

May you detail issue?

Best Regards,
Sonny

**Comment by nidzo80** [comment]
> 

Do you have large amount of images? I have one site with over 2GB of images where even Joomla media manager hangs. JCE file manager works fine on the other hand.

**Comment by Chacapamac** [comment]
@nidzo80  Your php/mysql is probably entering limits set by your server.
You should have access to some settings on your CPanel, If not maybe you have a php.ini (or a similar file) that sets these limits. Ask Your hosting service they will point you to the method they use.

Depending of the PHP version some of the settings name can change but you can start with theses:

post_max_size = 750M ; Maximum size of POST data that PHP will accept. (Need to be bigger than upload) 
upload_max_filesize = 50M  ; Maximum allowed size for uploaded files
max_execution_time = 5000 ; Maximum execution time of each script, in seconds
max_input_time = -1 ; Maximum amount of time each script may spend parsing request data , in seconds. -1 is infinite
memory_limit = 1024M ; Maximum amount of memory a script may consume (32MB)
max_allowed_packet = 200M ; Not more than 900m
session.gc_maxlifetime = 1440 ; To help PHP Session in minutes — 45 minutes = 2700
max_input_vars =10000 ; Limits the number of inputs you can set when posting forms

**Comment by Joomlaplates** [comment]
> Hi Peter,
> 
> I tried test with an image named "üöä.jpg" and system works well. ![Screen Shot 2022-01-10 at 14 58 36](https://user-images.githubusercontent.com/3204103/148733903-35a237b0-3f36-43f6-a09e-622fe6a02933.png)
> 
> May you detail issue?
> 
> Best Regards, Sonny

Yes youre right, the special characters are not the problem. 
Maybe the client upload them with FTP in a wrong format, who knows!

**Comment by Chacapamac** [comment]
Take the image that doesn’t work, zipped it and upload it here, I will take a look..
