### ISSUE TITLE
Color mode switcher always visible in Sticky Header

### ISSUE THREAD

**Issue by GeoffroyVD** [templaza/astroid-framework#660]
The color mode switcher for (Light/Dark Theme) is always visible in the Sticky Header also when you define a module position of hidden or COM_MODULES_NONE. For Astroid Template Zero and Astroid Template Two

For my configuration with Astroid Template Zero it is coming twice in the Sticky Header when I define it in position topbar-2 or header-right like defined in Header section configuration.

See the different screenshots of the configurations.

![Header section config](https://github.com/templaza/astroid-framework/assets/167746810/c46e91a8-9bb5-4d24-900f-4257e9422438)
![Sticky Header with color mode enabled ](https://github.com/templaza/astroid-framework/assets/167746810/1a18d716-700a-48e4-a035-4eaafcd5eb08)
![Header with color mode enabled ](https://github.com/templaza/astroid-framework/assets/167746810/8742f2df-0dbc-4ad0-8a87-9cd502d3e68d)

**Comment by sonvnn** [comment]
Dear @GeoffroyVD 

Thanks for report issue. I fixed this at https://github.com/templaza/astroid-framework/commit/cbb319a0025eed056244de9a80759b1ed213c05f

Please help me download v3-branch and re-test again.

Best Regards,
Sonny

**Comment by GeoffroyVD** [comment]
Dear @sonvnn,

It is working like expected.
Thanks for the quick fix of it.

THX,
@GeoffroyVD
