### ISSUE TITLE
Form plugin events introduced in 2.5.12 fail

### ISSUE THREAD

**Issue by ReLater** [templaza/astroid-framework#67]
- Joomla 4.0.5.
- Astroid Framework 2.5.12.

I tried to "catch" Astroid plugin events in a custom plugin in edit view of a template style in Joomla backend.

Looking into `plg_system_astroid` I found `onAfterAstroidFormLoad($template, $form)`. But that's never used. The event is never called in framework.
See: https://github.com/templaza/astroid-framework/blob/v2.5.12/plugins/astroid/astroid.php#L100

Therefore I tried `public function onAfterAstroidTemplateFormLoad($template, $form)` because found here in `manager()` method:
https://github.com/templaza/astroid-framework/blob/v2.5.12/framework/library/astroid/Admin.php#L97

The plugin event receives the plugin but logs show some PHP warnings 

```
Warning: Attempt to read property "isAstroid" on null in plugins/system/astroid/astroid.php

Warning: Cannot modify header information - headers already sent by (output started at plugins/system/astroid/astroid.php) in libraries/astroid/framework/library/astroid/Helper/Client.php on line 86
```

Temporary solution:
Move line `$template = Framework::getTemplate();`
https://github.com/templaza/astroid-framework/blob/v2.5.12/framework/library/astroid/Admin.php#L102

up to line

https://github.com/templaza/astroid-framework/blob/v2.5.12/framework/library/astroid/Admin.php#L90

before `$template` is used the first time in `manager()`.

But that's not sufficient and more investigations necessary.

How to test/follow the whole steps:
- Delete `/astroid/presets/` directory in your Astroid template folder.
- In backend open edit view of your template style.
- Expectation: Astroid plugin removes form fields `'template_preset'` and `'presets'` from edit form. See lines 
https://github.com/templaza/astroid-framework/blob/v2.5.12/plugins/astroid/astroid.php#L103-L104
- Nothing happens. Presets area still visible (but empty).

- Rename `onAfterAstroidFormLoad($template, $form)` to `onAfterAstroidTemplateFormLoad($template, $form)` in astroid plugin.
- Activate `error_reporting`.
- Nothing happens but PHP warnings (see above).

- Move line `$template = Framework::getTemplate();` up like mentioned above.
- Now you'll get a fatal error `Call to undefined method Astroid\Helper\Form::removeField()`
- That's simply true ;-) There is no.

- Then I tried `$form->form` instead of just `$form` in plugin to access the Joomla form object which has a method `removeField()` and would theoretically do the correct thing.

```
public function onAfterAstroidTemplateFormLoad($template, $form)
{
    if ($template->isAstroid && Framework::isAdmin() && !count($template->getPresets())) {
	   $form->form->removeField('template_preset', 'params');
	   $form->form->removeField('presets', 'params');
    }
}
```

but fatal error
`Cannot access protected property Astroid\Helper\Form::$form`

As far as I see changing

`protected $form;`

to

`public $form;`

in https://github.com/templaza/astroid-framework/blob/v2.5.12/framework/library/astroid/Helper/Form.php#L19

do the expected things but I don't know if that's OK from the point of view of safety to solve the whole issue.
    
Related: https://github.com/templaza/astroid-framework/commit/31887fafb5a0c870829e5313daf85a51a34c2fb9

**Comment by ReLater** [comment]
Addition: I also tried `&$this->form` instead of $form in manager() method but came to the same results.

**Comment by sonvnn** [comment]
Hi @ReLater ,

I did it in Jollyany Framework. Please refer my code at https://github.com/templaza/jollyany/blob/master/plugins/plg_system_jollyany/jollyany.php#L1035-L1037

Actually $form is JForm. So you can use `$form->removeField()`.

Best Regards,
Sonny

**Comment by ReLater** [comment]
$form is not JForm in Astroid framework. $form->form is JForm there.

The reason why your `$form->loadOptions()` works correctly is because it's a public method of class `libraries\astroid\framework\library\astroid\Helper\Form.php` (which is $form) but it's not a method of JForm (which is $form->form).

```
public function loadOptions($dir = '')
{
	$forms = array_filter(glob($dir . '/' . '*.xml'), 'is_file');
	\JForm::addFormPath($dir);
	foreach ($forms as $fname) {
		$fname = pathinfo($fname)['filename'];
		$this->form->loadFile($fname, true);
	}
}
```

As you can see it uses `$this->form` which is the `protected` JForm. Not `$this` in class `libraries\astroid\framework\library\astroid\Helper\Form.php`.

```
public function onBeforeAstroidTemplateFormLoad(&$template, &$form) {
  if (!file_exists(JPATH_LIBRARIES . '/jollyany/framework')) {
      return false;
  }
  $form->loadOptions(JPATH_LIBRARIES . '/jollyany/framework/options');
}
```

`$template` is also empty here and throws a warning if you want to use it.

Simply test in your plugin with an Astroid template in backend:

```
public function onBeforeAstroidTemplateFormLoad($template, $form)
{
	// Doesn't putput the current $template because is null.
	echo ' $template is: <pre>' . print_r($template, true) . '</pre>';

	// Outputs fatal error because $form is not class JForm and removeField() not exists.
	$form->removeField('template_preset', 'params');
	$form->removeField('presets', 'params');
}
```

and

```
public function onBeforeAstroidTemplateFormLoad($template, $form)
{
	// Doesn't putput the current $template because is null.
	echo ' $template is: <pre>' . print_r($template, true) . '</pre>';

	// Outputs fatal error because $form->form is class JForm but here JForm is protected.
	$form->form->removeField('template_preset', 'params');
	$form->form->removeField('presets', 'params');
}
```

**Comment by sonvnn** [comment]
Hi @ReLater ,

I add getForm function at https://github.com/templaza/astroid-framework/commit/397b263242ca80784a8cd1186bcd096687f4ebfa

You can use code below:

```
$form->getForm()->removeField('presets', 'params');
$form->getForm()->removeField('template_preset', 'params');
```

I tested successful on Jollyany. You can download developer branch and test it again.

Thanks & Best Regards,
Sonny

**Comment by ReLater** [comment]
Thanks a lot! Tested successfully!

If you want to: I've created a PR for the "$template is null" thing. https://github.com/templaza/astroid-framework/pull/69/files

**Comment by sonvnn** [comment]
Thanks a lot! I reviewed and approved your pull request :)
