### ISSUE TITLE
Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated 

### ISSUE THREAD

**Issue by Pablopoland** [templaza/astroid-framework#670]
**Joomla 5.1, PHP 8.3** and a single article view in Astroid_template_zero , Template 	3.0.12 +  Astroid Framework Version 3.0.14

At the bottom of single article view I have those two messages:

- Deprecated: trim(): Passing null to parameter 1 ($string) of type string is deprecated in /public_html/libraries/vendor/joomla/registry/src/Format/Json.php on line 55
- Deprecated: trim(): Passing null to parameter 1 ($string) of type string is deprecated in /public_html/libraries/astroid/framework/frontend/blog/modules/author_info.php on line 39

**Comment by sonvnn** [comment]
I fixed this issue at https://github.com/templaza/astroid-framework/commit/abfbc8c232bdfadea584265c0547e4888de67df6 

Please help me download v3-branch and retest again.

Thanks & Best Regards,
Sonny
