### ISSUE TITLE
Do you plan to have an official page or accessible public documentation for the New Templaza Astroid?

### ISSUE THREAD

**Issue by Chacapamac** [templaza/astroid-framework#68]
I ask because I collect the existing documentation ( https://docs.joomdev.com/category/astroid-user-manual/) from Joomdev. I’m still collecting every important bit and piece I can find.
I can easily repurpose and improve the existing documentation to not infringe any copyright. When done, you can place it on your (or a new) website and I can also work on the Wiki here, on Github.

I think, if you are serious about Astroid, it will be great to start an official page and Forum section of your Templaza website or a new public website dedicated to Astroid.
I’m extremely busy until mid-February, but I will be please to help put something together.  After March, I can give you at least 1/4 or more of my day only on Astroid if needed.

Yesterday, I ask Joomdev if they let you copy their entire Youtube Playlist — **Astroid Joomla Framework Tutorials**
https://www.youtube.com/playlist?list=PLv9TlpLcSZTBBVpJqe3SdJ34A6VvicXqM
to your own or a new YouTube Channel for safekeeping.

If I don’t have any answer, I will try directly with Chetan that works at Joomdev and make most, if not all of these Videos. 

If I still don’t have an answer, after March, I can start to produce pros videos tutorials (in French & English) — We can start by highlighting the new functions you are adding to Astroid and after, starting with the most important functions that need really help by video.

**Comment by sonvnn** [comment]
Hi @Chacapamac & @Joomlaplates ,

Thank you very much, I'm glad we have contributors like you. I want to do this project as a standalone project. It will not be related to TempPlaza.com. Because I welcome all Joomler to participate in this project. So I was planning to create an official page for Astroid Framework. I bought domain astroidframe.work

Please check my Plan:

- February 2022: Official page launched
- March 2022: Video Tutorials page launched
- April 2022: Partner page (contributor websites list like Joomla Resource page)

Thank you very much!
Best Regards,
Sonny

**Comment by Joomlaplates** [comment]
Thats a really great idea to create an own domainand webspace with tutorials.
Regards Peter

**Comment by sonvnn** [comment]
When the website is ready! I will need your hand, I will assign both of you as admins for update tutorials.

Thank you,
Sonny

**Comment by Chacapamac** [comment]
Great, I continue to spread the word on joomla.org

**Comment by rinka88** [comment]
but is it possible for them (joomdev) to ask for the domain previously used for this framework

**Comment by Chacapamac** [comment]
Joomdev seem to be totally unresponsive on anything Joomla now. I posts some demands on the old (archive) forum as I have a subscription and nothing...
3 days ago, I contact them by the mail address on their new website to ask if it can be possible to transfer (copy) their Astroid YouTube video playlists documentation to another YouTube Account for safekeeping and reuse but nothing, no answer. I will try to email directly Chetan (from Joomdev) as we become somewhat friendly (on their forum as I help them with some stuff) and see. But, on my side, the door seem close...

**Comment by Joomlaplates** [comment]
Hi Sonny,
I ripped all Youtube Videos from the Astroid Joomdev Playlist.
Maybe you can include them into the new Astroid website.
https://drive.google.com/file/d/1XP18N-tJAkgDz9WKav0ycd1hYcmNzgBe/view?usp=sharing

**Comment by Chacapamac** [comment]
@Joomlaplates 
> I ripped all Youtube Videos from the Astroid Joomdev Playlist, before they are not available anymore.

**How big is the zip file and in what format the video are?**

Great, Still no news from Joomdev about using their Videos, I will send another email today and I will go directly toChetan Madaan to ask if not successful.

The only problem here is the copyright, sure it’s easy to change the front image on the videos to make it more personal to this project. I will look at the copyright laws on Youtube

**Comment by Joomlaplates** [comment]
Hello,
the file size is about 450MB ZIP file and the format is mp4.

**Comment by Chacapamac** [comment]
Just download it, seem to work, I also made a backup — I will test them all.
Cool Stuff!

**Comment by Joomlaplates** [comment]
The Joomdev documentation was made with a wordpress theme
https://demo.herothemes.com/helpguru/

**Comment by Chacapamac** [comment]
Ok, super easy to redo in simple code in Joomla. It’s the “https://docs” that make me think of some kind of systems.

**Comment by sonvnn** [comment]
Hello @Chacapamac & @Joomlaplates,

We use Vimeo in TemPlaza. I created an Vimeo Channel https://vimeo.com/channels/1767263
Please send me your email here. I will invite you to my team so you can upload video to channel.

Kind Regards,
Sonny

**Comment by Chacapamac** [comment]
Not sure Vimeo will  maximise the impact.

If you decide to go with Vimeo, I think It will be easy to duplicate the Astroid Vimeo Channel on an New Astroid YouTube channel. I can take care of that personally.

**Some big advantages of YouTube**
• Over 2 billion users log in and watch videos on YouTube every month, whereas Vimeo has just 973,000 registered users **in total**
• YouTube is absolutely free with no cap — Not Vimeo, lot of cap and restrictions
• Also Youtube is integrated with Google Analytic

**Comment by Chacapamac** [comment]
Playlists are important as you can class video by categories, really important for Tutorials. I guess we can have both. The work will be more the production. After it’s only uploading them. I think I will choose Vimeo if I was a cameraman or a video professional to show my work. But for organizing tutorials, I think YouTube is the way to go. Astroid was on YouTube originally.

**Comment by sonvnn** [comment]
Hello @Chacapamac & @Joomlaplates,

OK, Youtube has 2 votes. So, I created an Google account (astroidframework@gmail.com). I will share password to both of you. So you can use this account to publish video. Because this account is free so I can not add team member but we can use this as share account for free.

Please email me via sonlv@templaza.com. I will share password to you.

Youtube Channel https://www.youtube.com/channel/UCUHl1uU0Ofkyo-1ke-K4_xg

Kind Regards,
Sonny

**Comment by Chacapamac** [comment]
Great News as we can also use the same google account for analytics not only for the videos, but for the future website.
I send you my email in few minutes....

**Comment by sonvnn** [comment]
Hi @Chacapamac @Joomlaplates 

I upload Astroid official to astroidframe.work. Please help me check it.

Kind Regards,
Sonny

**Comment by Chacapamac** [comment]
I just see the new Astroid official website and it’s a very good start —> https://astroidframe.work/
I will come back wit suggestions.
Great work Sonny....
