### ISSUE TITLE
Frontend Article edit category/tags Remove Item issue

### ISSUE THREAD

**Issue by mac-joomla** [templaza/astroid-framework#681]
If you edit an article with astroid framework 3.0.14 and Template two 1.0.4 in frontend, it is showing the text "Remove Item" for category and tag selection where you would just expect a little x as with template zero, one or cassiopeia. You can see it in attached screenshot. Thank you! 
<img width="840" alt="Bildschirmfoto 2024-05-15 um 16 50 21" src="https://github.com/templaza/astroid-framework/assets/87974913/e8e1324d-81c5-4b98-811a-19d259180f67">

**Comment by sonvnn** [comment]
Thank you! I will improve it.

**Comment by mac-joomla** [comment]
Hello @sonvnn,
thank you for your answer, just to let you know, this issue persists with Astroid Framework 3.0.15 and astroid_template_two 1.0.5. in Joomla 5.1.0.

**Comment by mac-joomla** [comment]
Hello @sonvnn this works fine now for categories in frontend, but for tags the issue persists in Joomla 5.1.3 with Astroid Framework Version: 3.1.2-rc1 and Template Two Version: 1.0.6.

**Comment by sonvnn** [comment]
Thanks for remind me. I fixed this issue at https://github.com/templaza/astroid-framework/commit/40d76818e399fae8c652edebc7769e02f962460e

Please help me download v3-branch and Clear Astroid Cache for testing :)

**Comment by mac-joomla** [comment]
Great, this looks fine now, thank you!
