### ISSUE TITLE
Error with CB Subs Extension from JoomlaPolis

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#683]
PHP Version 8.2
Astroid Framework Version 3.0.14
-----
CB Subs is a membership extension from Joomlapolis.
When a new subscription is taken and the redirect comes from PayPal, this error message appears in the frontend:
`Incorrect string value: '\xFCr Vie...' for column 'raw_data' at row 1`
And the logfile looks like this
```
NOTICE: iconv(): Detected an illegal character in input string in /is/htdocs/wp11234580_MID85S8WTY/www/kulturbuero2023/libraries/astroid/framework/library/astroid/Helper.php on line 72
Trace:called in class cbpaidErrorHandler::_error_handler_callable(8, "iconv(): Detected an illegal character in input string", "/is/htdocs/wp11234580_MID85S8WTY/www/kulturbuero2023/libraries/astroid/framework/library/astroid/Helper.php", 72)
called in function iconv("utf-8", "us-ascii//TRANSLIT", "Center-3-top-c-3-weiß-") on line 72 in file Helper.php
called in class Astroid\Helper::slugify("Center-3-top-c-3-weiß-") on line 89 in file Helper.php
called in class Astroid\Helper::shortify("Center 3 (top-c-3, weiß)") on line 124 in file BaseElement.php
called in class Astroid\Element\BaseElement::_id() on line 51 in file BaseElement.php
```
Is this a bug or an issue of this extension??
Thanks Peter

**Comment by sonvnn** [comment]
Dear @Joomlaplates 

This issue because Paypal return an illegal character. I tried to ignore it in this commit https://github.com/templaza/astroid-framework/commit/8b2b6e0d0d1fd79ac7f99a4e605a8efd50aed527

Please help me check it again. Tell me the results.

Best regards,
Sonny

**Comment by Joomlaplates** [comment]
Hello Sonny, thanks for your anser. But its still not working...
Got already this error after paypal return
`Incorrect string value: '\xFCr Sie...' for column 'raw_data' at row 1`
Regards Peter

**Comment by sonvnn** [comment]
`Incorrect string value: '\xFCr Sie...' for column 'raw_data' at row 1`
This issue look like database issue, not Astroid issue. Please recheck your CB database and confirm about it.
