### ISSUE TITLE
Compile Error in framework\library\astroid\

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#687]
Hello, I got a compile error, when i want open the Template config, see picture attached.
Is there a missing string "$"
![ss2](https://github.com/templaza/astroid-framework/assets/71080509/1d7e6611-a63a-4a0b-9572-55e71eeb04e6)
Greatings Peter

**Comment by Joomlaplates** [comment]
Joomla - 4.4.5
PHP - 7.4.3
10.3.39-MariaDB-0ubuntu0.20.04.2-log 
..
Maybe depends on PHP 7.x ?

**Comment by sonvnn** [comment]
Yes, Please update your php to 8.x

**Comment by Joomlaplates** [comment]
Yes fixed with 7.x PHP
