### ISSUE TITLE
Alignment Icons Widget

### ISSUE THREAD

**Issue by rutgerjn** [templaza/astroid-framework#694]
I want to center the icons in the Icon Widget, but I can’t change the alignment. The icons are positioned on the left side for all options. Is this a known issue, or can I do something to solve this problem?

**Comment by sonvnn** [comment]
Switch to Design tab you can see Text Alignment option. Select "Center". It will work

**Comment by rutgerjn** [comment]
I had already tried that option, but changing it doesn’t make any difference.

**Comment by sonvnn** [comment]
I found this is a bug. I fixed this issue on https://github.com/templaza/astroid-framework/commit/bd50a3b208cadc3bb85179e9f5882de68265bd2c 

Please help me download v3-branch and test it again.

Thanks & Best Regards,
Sonny

**Comment by rutgerjn** [comment]
Sonny, thank you for the quick response! The update has resolved the issue.
