### ISSUE TITLE
add new element have bug

### ISSUE THREAD

**Issue by babakhakimi** [templaza/astroid-framework#707]
hi
i wrote a toolbar element and put files in below paths:
/media/templates/site/TEMPLATE_NAME/astroid/elements/
/templates/TEMPLATE_NAME/astroid/elements/

but element dont show  in template
I noticed a difference when I put the element files in the path below which I send the picture

Differences in values ​​are visible

The photo below shows the settings of the element when I place the element in the mentioned paths
![Screenshot 2024-06-19 at 10-58-21 ](https://github.com/templaza/astroid-framework/assets/8760124/543e081d-c424-4093-b7f7-bc6dc2c5be54)

The picture below shows the element settings when I place the element in the path of the library folder
![Screenshot 2024-06-19 at 11-14-28 ](https://github.com/templaza/astroid-framework/assets/8760124/ba3e6a96-0616-41d0-9d9a-d8f03268bf17)

When the element is placed in the library path, it can be displayed in the template settings
![Screenshot 2024-06-19 at 11-44-02 dorna_dashboard](https://github.com/templaza/astroid-framework/assets/8760124/a17935a0-4f13-4680-acfb-e645bb7caa1b)

**Comment by babakhakimi** [comment]
The photo below is when I put the element files in the mentioned paths
![Screenshot 2024-06-19 at 10-58-21 ](https://github.com/templaza/astroid-framework/assets/8760124/b4d921cf-9e59-4915-8b0d-f96d2eff3f24)


The photo below is when I put the element files in the path of the library folder
![Screenshot 2024-06-19 at 11-14-28 ](https://github.com/templaza/astroid-framework/assets/8760124/fa1cb97e-0604-47bc-bb83-10cb9949b88f)


When I place the element in the library path, the element is visible in the template
![Screenshot 2024-06-19 at 11-44-02 dorna_dashboard](https://github.com/templaza/astroid-framework/assets/8760124/fa9634c8-4df7-4945-b0c5-6c9dae82c7f1)

**Comment by babakhakimi** [comment]
![Screenshot 2024-06-19 at 10-58-21 ](https://github.com/templaza/astroid-framework/assets/8760124/543e081d-c424-4093-b7f7-bc6dc2c5be54)

The picture below shows the element settings when I place the element in the path of the library folder
![Screenshot 2024-06-19 at 11-14-28 ](https://github.com/templaza/astroid-framework/assets/8760124/ba3e6a96-0616-41d0-9d9a-d8f03268bf17)

When the element is placed in the library path, it can be displayed in the template settings
![Screenshot 2024-06-19 at 11-44-02 dorna_dashboard](https://github.com/templaza/astroid-framework/assets/8760124/a17935a0-4f13-4680-acfb-e645bb7caa1b)

**Comment by sonvnn** [comment]
Thanks for report issue. I will check and response you in the next 24h

**Comment by sonvnn** [comment]
@babakhakimi I fixed this issue on https://github.com/templaza/astroid-framework/commit/5aca217839f4e2de7f6d18a77f57f299e765e5d9

Tested and it works
![Screen Shot 2024-06-20 at 11 03 10](https://github.com/templaza/astroid-framework/assets/3204103/e6f19f1a-4c8e-4826-90d0-6786501efdaa)

To create custom Widget please follow JROOT/media/templates/site/{YOUR_ASTROID_TEMPLATE}/astroid/elements/test/test.php

Please try it by yourself and give me your feedback.

Best Regards,
Sonny

**Comment by sonvnn** [comment]
I created a tutorial about Build Widget here https://docs.astroidframe.work/developers/build-or-override-a-widget
You can check it.
