### ISSUE TITLE
bug in bootstrap utilities class

### ISSUE THREAD

**Issue by babakhakimi** [templaza/astroid-framework#711]
Hello
I noticed that in rtl languages, the classes that exist in Bootstrap are displayed incorrectly
For example, px-3 when the language of the site is ltr is as follows
.px-3 {
  padding-right: 1rem !important;
  padding-left: 1rem !important;
}
but in rtl language is
.px-3 {
  padding-left: 0 !important;
  padding-right: 1rem !important;
}

**Comment by babakhakimi** [comment]
And one more thing why when this variable exists in bootstrap 
--bs-link-hover-color
Why is this variable used?
--as-link-hover-color

And also many other variables in Bootstrap that are replaced instead of being changed

**Comment by sonvnn** [comment]
@babakhakimi I am not sure what you mean. Can you give me your link to debug?

**Comment by babakhakimi** [comment]
hi sonny @sonvnn 
Ok, I will try to explain my problem better
There is a problem in languages ​​that are written from right to left, such as Persian or Arabic
For example, when we use px-3 class
That element must have padding from the left and right sides
It is not a problem in languages ​​like English that are written from left to right because the format does not perform the conversion operation, but when we change the language of the site to one of the languages ​​I mentioned.

The px-3 class does not work properly and gets padding only on one side

in english :

.px-3 {
padding-right: 1rem !important;
padding-left: 1rem !important;
}

in persian:
.px-3 {
padding-left: 0 !important;
padding-right: 1rem !important;
}

I hope I was able to explain it well
Best Regards,
babakhakimi

**Comment by sonvnn** [comment]
@babakhakimi I am sorry for late reply. Can you send me your livesite? I will check it.

Thanks,
Sonny
