### ISSUE TITLE
Installation Errors

### ISSUE THREAD

**Issue by morrellaberdeen** [templaza/astroid-framework#713]
I have downloaded and installed the file - astroid-package-v3.0.15.Framework-Template. I am using the latest version of Joomla 5.1.1. I am using php 8.2.6.  To get it to work, I have to install  twice. On the first install, it gives the following error - 0 Undefined constant "ASTROID_JOOMLA_VERSION".  If I install again, I get the following error -  0 define() expects at least 2 arguments, 1 given.

After that second install, it works. I have installed in about 3 joomla sites and these errors have occurred on each install.

**Comment by sonvnn** [comment]
@morrellaberdeen I fixed this issue. Can you help me check it again https://github.com/templaza/astroid-framework/releases/tag/v3.1.0 ?

Thanks & Best Regards,
Sonny
