### ISSUE TITLE
I’m in discussion with Sasi Varna Kumar ex co-founder of J2 Store that leave a message on Sonny Issue Explorer post about help for Astroid. He is interested...

### ISSUE THREAD

**Issue by Chacapamac** [templaza/astroid-framework#72]
I take a chance to email him and this is is response today...

> Hi Patrick
> 
> I was the co founder of J2Store and later i stepped out and now recently running a web agency.
> Yes I m interested in this project. Lets connect and chat when you have time.
> 
> Thanks,
> Sasi varna kumar, CEO 
> Teal Orca Web Agency Pvt Ltd
> Call +91 9952661702 | Skype: sasivarnakumar
> website: https://tealorca.com

@sonvnn — Do you want me to introduce you or you want to contact him directly
His email is sasi@tealorca.com

J2 Store is a really powerful eShop on Joomla, I’m sure it can be great to have more help....

**Comment by sonvnn** [comment]
Hi @Chacapamac,

Thank you very much. We are welcome all Joomler. You can ask him join this github and spread his ideas with Astroid.

Thanks & Best regards,
Sonny

**Comment by Chacapamac** [comment]
Just receive a answer from Sasi to my last email inviting him to the project.
I quote:
> Happy to hear from you with so much interest and excitement on the above email.  
> 
> I shall join the project and I shall try to give my best.
> 
> The idea of NEW Website for Astroid sounds AWESOME. Because I too feel a new Opening / fresh start announcement is needed for the world to give them hope.
> 
> That will also motivate other such developers if something is built that is worth using, the community is there to support it.

That’s good news.  As I’m not a big deep coder, that’s the stuff, I can help with and I will continue to try to recruit good people to the project.

Also, I’m really good to find problems on websites, If you have people that have problems and you don’t have to much time, you are welcome to redirect them to me. I will take a look.

**Comment by Chacapamac** [comment]
@sonvnn 
**I have the Ok from Sasi to add him to the project**

**—> I think you need to Invite him Yourself.**

_Last email Quote:_

> Yes please do add me to the proj
> https://github.com/sasivarnakumar
> 

**User Name :**  sasivarnakumar

**_How to, if needed..._**..
https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository

**Comment by sonvnn** [comment]
Hi @Chacapamac,

Thank you very much. I invited him to this project.

Best regards,
Sonny

**Comment by Chacapamac** [comment]
Great News
