### ISSUE TITLE
Cannot save the data - save button spinning and spinning

### ISSUE THREAD

**Issue by cbal32** [templaza/astroid-framework#720]
When i click on the Save button, this is spinning around and around without saving my changes.

After i upgraded the package plus the One template to the latest 3.0.15 version.

**Comment by cbal32** [comment]
When i turn to Zero template, this seems to work as expected and save the changes.

**Comment by sonvnn** [comment]
Please send me your admin acc via sonlv@templaza.com. I will help you check it

**Comment by sonvnn** [comment]
I fixed this issue at https://github.com/templaza/astroid-framework/commit/d32460cd73a07021e1f3647eff814d9089de2826

You can check it on your website.

Best Regards,
Sonny

**Comment by cbal32** [comment]
Yes, I saw. What was the problem?

Thank u every much

Στις Τρί 9 Ιουλ 2024, 12:25 ο χρήστης Sonny Le ***@***.***>
έγραψε:
