### ISSUE TITLE
blog_item.php from Astroid 3.0.14 is wrong

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#725]
Hi Sony,
please compare the file blog_item.php from Astroid 3.0.13 with Astroid 3.0.14. There must be something different and wrong
...
**Hard to explain:**
1.) Category Blog > Introtext = ON
2.) Article Setting Introtext = OFF
With this setting it doesnt show the introtext in blog view. This happens only with Astroid 3.0.14 with the file blog_item.php from Astroid 3.0.13 its working
Greatings Peter

**Comment by Joomlaplates** [comment]
Hi again,
something is wrong only with the file in
[framework/html/com_content/category/blog_item.php](url)
Because when I select the feature blog article instead of category blog article it works.

**Comment by Joomlaplates** [comment]
Ok I found the issue.
Astroid 3.0.13 the blog view is right. But in Astroid 3.0.14 something has changed in 
`framework/html/com_content/category/blog_item.php`
Please check this asap. Thanks

**Comment by sonvnn** [comment]
@Joomlaplates I fixed this at https://github.com/templaza/astroid-framework/commit/f807a10d9a47ba67fefd9139bc55f7b2f2eb1cde
You can download v3-branch to test it.

Thanks & Best Regards,
Sonny

**Comment by Joomlaplates** [comment]
Hi Sony, yes its fixed in V3 branch.
You will update to 3.0.15 or it will be fixed in 3.1 version
Many Thanks, Peter

**Comment by sonvnn** [comment]
@Joomlaplates It will be fixed in 3.1
