### ISSUE TITLE
Provide a solution to support 3rd parties to create widgets for Astroid through plugins

### ISSUE THREAD

**Issue by sonvnn** [templaza/astroid-framework#726]
Provide a solution to support 3rd parties to create widgets for Astroid through Joomla plugins

The system will scan widgets from folders with the following priority order:

1. media/templates/site/{template}/astroid/elements
2. plugins/astroid/{plugin_name}/elements
3. libraries/astroid/framework/elements

**Comment by Chacapamac** [comment]
Great! — back from few days vacations
