### ISSUE TITLE
Some language strings missing for the typography of the Logo Text & Tag line — I Fix it (french/English) - ini files included.

### ISSUE THREAD

**Issue by Chacapamac** [templaza/astroid-framework#73]
**I TEST THE 2 INI FILES — OK**

**In Header Section of ini**
after TPL_ASTROID_BASIC_TAG_LINE_DESC....

**_Added:_**
TPL_ASTROID_TYPOGRAPHY_LOGO="Logo Text Typography"
TPL_ASTROID_TYPOGRAPHY_LOGO_TAG_LINE="Tag Line Typography"

TPL_ASTROID_TYPOGRAPHY_LOGO="Typographie du texte du logo"
TPL_ASTROID_TYPOGRAPHY_LOGO_TAG_LINE="Typographie du slogan"

**Good Night Everybody — 10PM in Quebec-Canada!**

[en-GB.astroid.ini.zip](https://github.com/templaza/astroid-framework/files/7859482/en-GB.astroid.ini.zip)
[fr-FR.astroid.ini.zip](https://github.com/templaza/astroid-framework/files/7859484/fr-FR.astroid.ini.zip)

**Comment by Joomlaplates** [comment]
Hello from Moscow,
I upload the new  french file to language section. The english file  must be upload by Sonny.
Regards, Peter

**Comment by Chacapamac** [comment]
Thanks Peter — from Moscow :)

**Comment by sonvnn** [comment]
Just updated language files in https://github.com/templaza/astroid-framework/commit/6b877f4c7fa4169907cf871ac9ec322fc0561c9e

Best Regards,
Sonny

**Comment by Chacapamac** [comment]
I close this.
