### ISSUE TITLE
Something wrong with article view picture

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#731]
In new Astroid 3.1 the single article view of the picture is bad, see pictures attached.
When i use the file
`\html\com_content\article\default.php`
from old Astroid 3.0.15 its working. Therefore something wrong with that file
![img2](https://github.com/user-attachments/assets/255c14d6-9351-45eb-8e1d-1c217ebbdc1a)

![img3](https://github.com/user-attachments/assets/d30b33b1-b304-4d0d-9118-a58289649a5c)

Greatings Peter

**Comment by sonvnn** [comment]
Can you send me the link of issue? I need to inspect html to find problem.

**Comment by Joomlaplates** [comment]
https://reverent-pare.85-214-95-104.plesk.page/index.php/9-artikel-1

**Comment by sonvnn** [comment]
@Joomlaplates Because the title and the image are in a same section. If you would like to display like your second image you have to place the title in a separate section. I created a new article layout for blog category.
![Screen Shot 2024-07-22 at 10 44 17](https://github.com/user-attachments/assets/e3cc96bc-7d81-4625-8030-c7b362fa7dbb)

And now it works like your screen.
![Screen Shot 2024-07-22 at 10 46 46](https://github.com/user-attachments/assets/f0f6ac48-e5ae-4169-9269-b83f44829f69)

You can check it here 
![Screen Shot 2024-07-22 at 10 48 18](https://github.com/user-attachments/assets/ee031219-a5ab-4154-8a2b-3fa72969a1bd)

Hope it can help!

Thanks & Best Regards,
Sonny

**Comment by Joomlaplates** [comment]
Hi Sony, of course you can fix it with an extra article layout.
But its not Joomla standard and its not like it was before.
Article title was always on top and then the introtext or fulltext and a floating image.
![2](https://github.com/user-attachments/assets/ca937772-fb6f-44ed-936b-543005bd5a95)
![1](https://github.com/user-attachments/assets/cc3e0089-7a6d-4124-9981-dcacc4d87f9a)
Thanks for your patience

**Comment by sonvnn** [comment]
You can define your layout and save as default. It will be override default layout from Astroid.

**Comment by sonvnn** [comment]
I will update to re-order Title block on top in 3.1.1. I will release quickfix in this week. Don't worry about it. Please help me check everything again. Make sure everything are running well.

Best regards,
Sonny

**Comment by Joomlaplates** [comment]
Hi, yes I know.
But thats not a solution. Imagine you have 300 clients and update to Astroid 3.1 and you have to setup a new layout only because the article layout is different to standards...
Hopefully, you understand what I mean.
Regards Peter

**Comment by sonvnn** [comment]
Yes, I understand. That is why. I will release 3.1.1 to update default layout of Astroid in this week. I will inform you to check it first before release 3.1.1. Please wait in the next 24h.

In the 3.1.0-rc6, I informed about the due date of release. I hope you can help me to check RC version carefully in the next time. It will help us avoid this situation.

Best regards,
Sonny

**Comment by Joomlaplates** [comment]
Thank you.
I´ve checked mostly everything but not this floating image in article layout, because I never used it.

**Comment by sonvnn** [comment]
@Joomlaplates I fixed this issue at https://github.com/templaza/astroid-framework/commit/39757b01df7699c5a71dbe984a686b8370b5c433

Please help me download v3-branch and test it again. When you confirm this issue is resolved. I will release 3.1.1

**Comment by Joomlaplates** [comment]
Hello Sony,
I´ve checked the new version and it works now.
Thanks for everything.
Regards Peter

**Comment by sonvnn** [comment]
@Joomlaplates It's great. I will look around one again. I will release 3.1.1 in the next 24h if everything is OK
