### ISSUE TITLE
Contact Information not on Mobiles Devices visible

### ISSUE THREAD

**Issue by alexanderfelske** [templaza/astroid-framework#732]
With the Astroid Template Two the Contact Information is only visible on Dekstop not on Mobile Devices. I tested it with multiple Devices. When I check the css in a Browser the Section ist there, the tags has been set but there ist nothing visible.

**Comment by Banuk1616** [comment]
Have you checked the responsive settings of the element? 
To do this, edit the element (it will probably be called Top-A) and then click on the “Responsive Settings” tab at the top.
![1](https://github.com/user-attachments/assets/fe137c83-f8c6-430b-94cd-eaf049d5e387)

**Comment by alexanderfelske** [comment]
Yes I checked that and they are all disabled. 
Maybe it's the same Problem or maybe not but when I rotate my Phone from vertical to horizontal the Hamburger Menu Icon disappers too.

**Comment by Banuk1616** [comment]
There are two options for responsive settings. Once in the section:

![edit_section](https://github.com/user-attachments/assets/2c79fc19-8c5d-4519-9933-5ba4f201d43b)

and once in the element: 

![edit_element](https://github.com/user-attachments/assets/bccc5ec6-c772-49c5-95d5-d5f622f08d3b)

Look for the settings in the element.
It works for me without any problems.

**Comment by alexanderfelske** [comment]
I think I figured it out. When you look in the css in a browser, you can see the section is there but if go down in the section, you will find the class "hideonxs", which should be disabled.
![Screenshot1](https://github.com/user-attachments/assets/a6894ecc-37ee-428c-9b5f-693fd73d7bca)
The class hideonxs stands on "display:none;" when you change that to "display:block;" everything is shown correctly.
![Screenshot2](https://github.com/user-attachments/assets/cc763a97-3440-4cb6-9e48-ad80fec27209)
But as I said, in the Responsive Settings is everything disabled
![Screenshot3](https://github.com/user-attachments/assets/064d8dd3-607d-4cdf-b204-a5134aa1ba11)

**Comment by alexanderfelske** [comment]
I found it, for my mistake I didn't see that there was more Responsive Settings for the Column, I only checked the Section, the row and the Element. In the Settings for the Columns was Hide on Small Devices enabled.
