### ISSUE TITLE
Image description in the post is not adopted and class is ignored

### ISSUE THREAD

**Issue by WM-Loose** [templaza/astroid-framework#736]
Hello Sonny, thank you for the new version 3.1.1. 
Unfortunately, one problem is not yet solved. Since 3.1, an image class is no longer displayed in the post if you enter text in the image description.

![1](https://github.com/user-attachments/assets/850a6473-32f7-45f3-af61-d85864c3bbd9)

![11](https://github.com/user-attachments/assets/74b9c57c-4cc4-4623-b84a-59b60aff1b2b)

![3](https://github.com/user-attachments/assets/1f32cd28-0af8-404c-8c5d-82ceed45c0db)

Example of the image class in the custom.css, which then no longer works:
`.artbild-right .img-fluid {
  max-width: 50%;
  height: auto;
  float: left;
  padding-top: 5px;
  padding-right: 1%;
}`

**Comment by sonvnn** [comment]
@WM-Loose It depends of your template. I don't know what is your template. But It's still work on Zero, One, Two. Please see the result of Two below:

### Back-end input
![Screen Shot 2024-07-26 at 10 05 37](https://github.com/user-attachments/assets/bc4b4d6a-bbc9-4673-a15e-51c54194c4f4)

### Front-end output
![Screen Shot 2024-07-26 at 10 05 09](https://github.com/user-attachments/assets/2badfa80-762c-4e97-974c-74f55c9332c4)

### View source code
![Screen Shot 2024-07-26 at 10 05 20](https://github.com/user-attachments/assets/4c648b88-24b2-47ac-8de3-a3942290529a)

**Comment by WM-Loose** [comment]
Thank you Sonny, i want talk to Peter from Joomlaplates.
