### ISSUE TITLE
Where can I download Astroid_template_one 1.3.4?

### ISSUE THREAD

**Issue by 888Jay** [templaza/astroid-framework#74]
I need to update to 1.3.4 in order to upgrade to Joomla 3.10.4.
Extensions>Manage>Update is not finding anything.

Thanks

**Comment by Chacapamac** [comment]
Install the last package from Joomdev (2.5.4) — **astroid-package-v2.5.4.Framework-Template.zip**
**Here** —> https://github.com/joomdev/Astroid-Framework/releases
(Attention: Ideally, you should always install anything big on a clone of your website first)

**Normal Joomla installation** (over any version)

It will update the framework and both template (Zero & One)

![Joomdev](https://user-images.githubusercontent.com/1907276/149547491-507f7ac6-8600-487e-9ac6-68728316d993.jpg)

**You will have that after**
![udate-joomdev](https://user-images.githubusercontent.com/1907276/149548315-c50982b5-bd62-4b8f-81d8-3d8009381523.jpg)


============================================
============================================
**I recommend to install the last package from Templaza** _(Ready for Joomla 4)_ — **astroid-package-v2.5.12.Framework-Template.zip**
**Here** —> https://github.com/templaza/astroid-framework/releases

**Normal Joomla installation** (over any version)

It will update the framework and both template (Zero & One)

![install](https://user-images.githubusercontent.com/1907276/149546439-89bdf144-97dc-4609-8dd0-727e308e63c4.jpg)

![manage](https://user-images.githubusercontent.com/1907276/149546415-d67b9f5d-a631-4114-8a65-15a8d09d4980.jpg)

**Comment by 888Jay** [comment]
That is exactly what I was looking for! Not sure why I couldn't find it. All updated now.
Thanks!!
