### ISSUE TITLE
Float image  & Image Caption not working in Category Blog view

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#740]
Joomla 5
Astroid 3.1.1
Template Two
..
In Category Blog view is no floating image and no image caption. In Blog Featured Article its working.
Maybe depends on that in Category Blog, the file: **intro_image.php** is not loading
And in the file 
`\libraries\astroid\framework\html\com_content\category\blog_item.php` 
is a "d-flex" class which must be removed to float the image.
![2](https://github.com/user-attachments/assets/ee90b45a-b8f9-49d2-94ea-4b67ac1c80a7)

**Example here**
https://reverent-pare.85-214-95-104.plesk.page/index.php/category-blog
Please check if its right.
Greatings Peter

**Comment by sonvnn** [comment]
@Joomlaplates Thanks Peter, I removed "d-flex" in the blog_item.php

For the Image Caption. It's from Joomla core. You can try to switch to "Cassiopeia" to see it no-display.

Best Regards,
Sonny
