### ISSUE TITLE
template astroid one - no version update on astroid-update

### ISSUE THREAD

**Issue by djayko** [templaza/astroid-framework#75]
Hello,

I observed second times, that the astroid templates won't be updated on astroid update automatically.
But if I use release from github it will change.

Probably it's not a real issue if there is no update on templates. But I want to ensure that upcoming updates will be possible via update manager within joomla. It would be more handy than downloading the release package from git and uploading it on my page. ;-)

best regards,
Ayko

**Comment by Chacapamac** [comment]
Yes you absolutely right @djayko, **Templates One & Zero and obviously the framework should be updated and receive update warning by the Joomla update system.**

**What I know.**
• If you want to pass from the last Joomdev version to the new Templaza/Astroid, you need to manually update the framework/templates with this package —> https://github.com/templaza/astroid-framework/releases
![packages](https://user-images.githubusercontent.com/1907276/149976024-927e3dc1-9e39-431c-9650-dee52da2c0ce.jpg)

**Make sens, to be able everything to the NEW ASTROID**
This is what I did and it update everything correctly
![templaza](https://user-images.githubusercontent.com/1907276/149976571-fd98f4a3-8eee-405b-bf6d-812639d98a6c.jpg)

**You end-up with this in the —> Joomla Admin > _Extensions > Manage > Update Sites_**

![Astroid-templaza](https://user-images.githubusercontent.com/1907276/149977499-d4b653d9-0b81-43d7-b3e5-d483c10b768c.jpg)

**The 2 Templates One & Zero point to the old Joomdev repository,** only the Framework point to Templaza.

**TASK:**
The 2 Templates “Updates Sites” infos have to be replace with the new Templaza versions, Ideally, the 2 Joomdev Templates “Updates Sites” should be remove when installing Templaza....

**Comment by djayko** [comment]
@Chacapamac I already used the framework incl. templates from here for the version 2.5.11, but now on autoupdate only the core is updated not the templates itself.

btw: I used it on joomla4.

After downloading the current release from here. I figured out that the templateDetails.xml of Zero and One have still that link to joomdev. 

I assume it will be solved with starting the website-change having a correct and working update link then.

**Comment by Chacapamac** [comment]
@djayko 
Need to be done. I add **Sonny** hashtag to the discussion.

**Comment by sonvnn** [comment]
Hi @Chacapamac ,

I will be done when Astroid official website released. I will push everything of Astroid on that.

Best Regards,
Sonny

**Comment by Chacapamac** [comment]
Hi @sonvnn 
Cool for me!

**Comment by sonvnn** [comment]
Hi @djayko

I need your words to add to Testimonial section of https://astroidframe.work/. May you give us some comment for Astroid?

Kind Regards,
Sonny

**Comment by sonvnn** [comment]
I updated server for One and Zero template in v2.5.16. Please help me update and rebuilt updateserver.

Best Regards,
Sonny

**Comment by Chacapamac** [comment]
@sonvnn 
• Joomla 4.1.2 — I first trow away the Joomdev Astroid zero/one update site 

•  I only had the Templaza Framework Update Site

• I update  from Astroid 2.5.15 (with the 2 templates zero/one) to 2.5.16

• I did have that warning —> **No checksum found on the update server.**

• Astroid Framework was updated to 2.5.16
-- Astroid plugin to 2.5.16
-- Template zero/one stay at 2.5.13
— Astroid Clear Cache to 1.0.1

• In Joomla Update Site I only had Astroid Framework update
-- After doing a rebuild again both templaza template one/zero appear in the Updates Sites

**Curiously some￼thing like that appear**
![Screen Shot 2022-04-21 at 9 57 50 AM](https://user-images.githubusercontent.com/1907276/164480039-15b5fe1c-8118-477b-aa10-fedf2d4c7d3a.jpg)

![Screen Shot 2022-04-21 at 9 57 13 AM](https://user-images.githubusercontent.com/1907276/164480296-70708507-8956-43c7-bb8c-33c258623d38.jpg)

• I reinstall over —> astroid-package-v2.5.16.Framework-Template
-- No installation error
-- Templates zero/one was updated to 2.5.16 - No override warning 
![Screen Shot 2022-04-21 at 10 33 54 AM](https://user-images.githubusercontent.com/1907276/164480959-7c5d75d9-1f9c-470b-b80d-f80deb985881.jpg)

Curiously, I still have the  (6) overrides warning???

EVERYTHING SEEM TO WORK CORRECTLY
