### ISSUE TITLE
Text alingment in Text widget does not work

### ISSUE THREAD

**Issue by Giorgi625** [templaza/astroid-framework#755]
If you check here https://tamariuni.joomla.ge/ka/ on the bottom with yellow background there is text Created by Joomla.ge so if you check console you will see it has class ql-align-right which should align it to the right but it does not. 
While in widgets editor it is aligned properly 
![image](https://github.com/user-attachments/assets/9893750d-0e1c-40a0-9eeb-21d258e631d4)

**Comment by sonvnn** [comment]
Thank you for report this issue. I will fix it in 3.1.2

**Comment by sonvnn** [comment]
@Giorgi625 I fixed this issue at https://github.com/templaza/astroid-framework/commit/82f81767c6d1b023cfffb0043945ff37addc0724
You can download v3-branch for testing.
