### ISSUE TITLE
Undefined array key "custom" in libraries/astroid/framework/library/astroid/Template.php on line 175

### ISSUE THREAD

**Issue by bayrpaul** [templaza/astroid-framework#756]
**Describe the bug**
Running latest Astroid 3.1.1 and php8.2 and my error logs is full with this error code.
PHP Warning:  Undefined array key "custom" in /home/*******/public_html/libraries/astroid/framework/library/astroid/Template.php on line 175

**System Informations (please complete the following information):**
 - Joomla Version: 4.4.6
 - PHP Version 8.2
 - Astroid Version 3.1.1

Thanks

**Comment by sonvnn** [comment]
Hi @bayrpaul 
Thank you for report the issue. I fixed it at https://github.com/templaza/astroid-framework/commit/8027bad168ea9be8ac48cac8fb28a1bf46bd4286

Please help me check it!

Best Regards,
Sonny
