### ISSUE TITLE
Article Layout Builder doesn't work in Zero and One

### ISSUE THREAD

**Issue by jsr4id** [templaza/astroid-framework#766]
**Describe the bug**
The Article Layout Builder only works with template **Two** but not with **Zero** and **One**. 

**To Reproduce**
Just follow the documentation: [https://docs.astroidframe.work/article-blog/article-layout-builder](https://docs.astroidframe.work/article-blog/article-layout-builder)

**System Informations (please complete the following information):**
 - Joomla Version: 5.1.3
 - PHP Version: 8.2.5 
 - Astroid Framework: 3.1.1 
 - Astroid Zero: 3.0.15
 - Astroid One: 3.0.15
 - Astroid Two: 1.0.6

**Additional context**
What is the difference between the three templates Zero, One and Two?

**Comment by sonvnn** [comment]
I will update One, Zero after 3.1.2 release. Thank you :)

**Comment by sonvnn** [comment]
@jsr4id I updated One and Zero to compatible with Astroid 3.1.2. You can download and check it now.
