### ISSUE TITLE
Article Layout Builder - 2 Introtext Widgets selectable

### ISSUE THREAD

**Issue by jsr4id** [templaza/astroid-framework#767]
**Describe the bug**
There are two "Introtext" widgets selectable in the builder.
![image](https://github.com/user-attachments/assets/a41517dd-0a77-4eed-8cfa-6b63dbacbc77)

Only the first one "article_introtext" works.
![image](https://github.com/user-attachments/assets/1fb85253-6bc8-4d5b-a6b6-0ec5df11ad41)

**Comment by sonvnn** [comment]
I fixed it in 3.1.2. Thanks for report it :)
