### ISSUE TITLE
Sublayout issue showing in widgets.

### ISSUE THREAD

**Issue by felixkat** [templaza/astroid-framework#768]
Using 3.1.2 RC1 plus latest commits from Github.

# Create a simple element in article builder .
.
.
![Screenshot 2024-08-24 at 20-04-04 Nights of the Turntable](https://github.com/user-attachments/assets/01c9ad03-bedf-4eb9-aa10-f052d731835b)
.
.
# Assign to the category of the article and you will see the widget.
.
.
![Screenshot 2024-08-24 at 20-05-53 Articles Edit - Nights of the Turntable - Administration](https://github.com/user-attachments/assets/df9cb206-e494-455a-9c0b-54c854cdf967)
.
.
# Do the above but instead of an element, add a sublayout.
.
.
![Screenshot 2024-08-24 at 20-06-24 Nights of the Turntable](https://github.com/user-attachments/assets/4c128f4e-3c4f-4f6b-8c01-87423226bbb5)
.
.
# The result shows no widgets available, error reporting on maximum shows the following.
.
.
![Screenshot 2024-08-24 at 20-08-09 Articles Edit - Nights of the Turntable - Administration](https://github.com/user-attachments/assets/7c47f46f-20f2-41da-98b7-ed68da063181)
.
.
Each error is for each element in the sublayout, i.e the sublayout has three elements.

If you add an element and a sublayout, only the element shows in the widgets.

NOTE:-  The sublayout does show up in the article, just the widget is the issue.

**Comment by sonvnn** [comment]
Thank you for report issue. I fixed this issue at https://github.com/templaza/astroid-framework/commit/18af49a9c40296e9f030927c6d8522bf904b988e

**Comment by felixkat** [comment]
Thanks for this @sonvnn, the errors are now gone.

But should the sublayouts show up as widgets or can we not override them here?

**Comment by sonvnn** [comment]
At the moment, we can not edit widget of sublayout here. I will find a solution for it in the next versions.

**Comment by felixkat** [comment]
Thanks @sonvnn 

Perhaps we should show a greyed out widget there, (to show it's read only), just for consistency.  i.e the widget section showing all widgets and not just the ones that are editable.

I could raise this as a feature request?
