### ISSUE TITLE
Two versions Fontawesome

### ISSUE THREAD

**Issue by SerGun78** [templaza/astroid-framework#77]
Hey! Why are two versions of a web icon font loaded?
![изображение](https://user-images.githubusercontent.com/95705148/149987505-da6c6a1f-5c20-46a0-819e-db08ee9d59e0.png)

**Comment by SerGun78** [comment]
when I disable fontawesome in the astroid plugin, then fontawesome from the kernel is still loaded into the frontend and all icons are visible. Question: why do you need a fontawesome in the astroid plugin then?
![изображение](https://user-images.githubusercontent.com/95705148/149991585-36a2d8b2-d240-4e97-b3e9-f7c6f42842ae.png)
![изображение](https://user-images.githubusercontent.com/95705148/149991813-cc59faea-46cb-45b0-a699-81e65566fe06.png)

**Comment by Chacapamac** [comment]
**I wonder were you joomla-fontawesome come from ?**

**This is my setup:**
![plugin](https://user-images.githubusercontent.com/1907276/149994245-83907e6b-a5dc-46d7-8f37-53dc7ed023a7.jpg)

**This is were my awesome font come from:*
![awesome](https://user-images.githubusercontent.com/1907276/149994654-a47ff257-f611-4b0b-a757-0b525b0293df.jpg)

media > astroid > assets > vendor > fontawesome > css > all.min.css?v=2.5.12

**Comment by SerGun78** [comment]
my astroid plugin settings
![изображение](https://user-images.githubusercontent.com/95705148/150008416-ab556ff1-be98-406b-84c7-cd1e051b044b.png)
everything about fontawesome
![изображение](https://user-images.githubusercontent.com/95705148/150008707-93f92d05-bcc2-4b79-87e8-de649b475835.png)
two css fontawesome is loaded again: 1. from cdn 2. from joomla core

**Comment by Chacapamac** [comment]
Ok this time I take the time to check a bit better 
**Google Chrome Inspector**
**Search** = awesome
**No Cache**
![astroid](https://user-images.githubusercontent.com/1907276/150022779-2578052e-5401-40be-8a79-a0f538b5ba1e.jpg)

On this site test —> http://new-astroid.graf-test.ca/

**• LOCAL**
![local](https://user-images.githubusercontent.com/1907276/150021866-10309dcc-de1c-4193-9767-82557362e3a7.jpg)

![Local-awesome](https://user-images.githubusercontent.com/1907276/150022043-34d20e4c-2396-4f31-8b69-cd53e11b48da.jpg)

**Fontawesome are showing ok in frontend**

**• CDN**
![cdn](https://user-images.githubusercontent.com/1907276/150022210-28e74772-68f2-4951-bcdb-aa2205022fb1.jpg)

![cdn-awesome](https://user-images.githubusercontent.com/1907276/150022229-da456334-61d4-47ca-b5f3-cdc716bfb9c0.jpg)

**Fontawesome are showing ok in frontend**

**• OFF**
![off](https://user-images.githubusercontent.com/1907276/150022683-97e2d134-1e0c-4fbd-8230-96ccc529b342.jpg)

![off-awesome](https://user-images.githubusercontent.com/1907276/150022706-0713f903-2242-4922-bba3-d0cf5be2e0b9.jpg)

**Fontawesome are NOT showing in frontend**

**INTERESTING TO SEE HOW FAST CDN IS !!!!!!!!!!!!!!**

**Comment by SerGun78** [comment]
here is a test site http://astroid.tw1.ru/
its characteristics
clean J 4.0.6
![изображение](https://user-images.githubusercontent.com/95705148/150192518-b02b970c-23cf-4d39-8280-8f54d9fbd1bc.png)
only astroid framework and ONE and ZERO templates are installed. nothing else installed.
current astroid plugin settings (fontawesome from cdn)
![изображение](https://user-images.githubusercontent.com/95705148/150192795-fb3434ea-425a-41e0-894c-e42c13620846.png)
and joomla-fontawesome.css is loaded again
![изображение](https://user-images.githubusercontent.com/95705148/150193045-25ab42d6-0857-4b43-a14d-a00bbac27e9c.png)

**Comment by sonvnn** [comment]
Hi @SerGun78 ,

This style was used to display icon of Joomla Core extensions. It required if you want to use some basic extensions of Joomla Core ex: Login module icon, Joomla Content icon, etc.. 

If you remove it, some icon will be disappear. 

Thanks & Best Regards,
Sonny

**Comment by SerGun78** [comment]
I still don’t understand why to load an additional fontawesome from the kernel, if it can be enabled in the astroid plugin ?!
and it loads the second joomla-fontawesome file not for expanding the core and materials, but for the settings of the device, for example, icons for the contact block and social networks
![изображение](https://user-images.githubusercontent.com/95705148/150313396-8e81b17b-beea-474a-9fba-b71633f281d1.png)
