### ISSUE TITLE
Framework 3.1.2 destroys Joomla Core feature for post pull down in the backend - stop download immediately

### ISSUE THREAD

**Issue by WM-Loose** [templaza/astroid-framework#775]
After updating from Asteroid 3.1.1 to Asteroid 3.1.2, the pulldown menu in the Joomla backend can no longer be opened:

![1](https://github.com/user-attachments/assets/bf8cb5b1-72ab-483b-a056-f555e0fb245a)

![2](https://github.com/user-attachments/assets/8c40464a-a17e-428a-87eb-d74fd1ba09bc)

Test with Joomla 4.4.7 und Joomla 5.1.3

Solution: reinstall Astroid 3.1.1 immediately.

All of our customers have the same problem. Hundreds of updates have already been made. We don't know what is quicker. Should we inform everyone that we are going back to 3.1.1 or wait until you provide an update and the error is fixed?

**Comment by sonvnn** [comment]
Oh! Thank you for report issue. I hope you can help us join to test RC version in the next versions. :)

Best Regards,
Sonny

**Comment by WM-Loose** [comment]
We always do that, sonny. But none of us noticed this error and only noticed it today by chance. But since Joomla updates were only released a few days ago, we first had to find out whether it was Joomla or other extensions that were to blame. Today we noticed that only Astroid was installed and were able to find out that way.

**Comment by sonvnn** [comment]
Thank you! I will check and release fix bug version in the short time. This problem might from Widgets tab.

**Comment by WM-Loose** [comment]
OK

 

Von: Sonny Le ***@***.***> 
Gesendet: Dienstag, 27. August 2024 09:09
An: templaza/astroid-framework ***@***.***>
Cc: Dirk ***@***.***>; Author ***@***.***>
Betreff: Re: [templaza/astroid-framework] Framework 3.1.2 destroys Joomla Core feature for post pull down in the backend - stop download immediately (Issue #775)

 

Thank you! I will check and release fix bug version in the short time. This problem might from Widgets tab.

**Comment by sonvnn** [comment]
I fixed this issue at https://github.com/templaza/astroid-framework/commit/49b82f8f8c5f344125636e7fae7f09584bc1836f

Best Regards,
Sonny

**Comment by WM-Loose** [comment]
Sorry but it still doesn't work after the changes.

**Comment by WM-Loose** [comment]
Maybe I made a mistake in the code when copying it or picked the wrong file. Can you provide an update so that the change is installed automatically? Otherwise I can't change the files manually until this afternoon and try again. I'll be out in a minute.

**Comment by sonvnn** [comment]
Please download v3-branch for testing.

**Comment by exlemor** [comment]
Hi Sonny, got my hands on Joomla 5.1.4 Stable and ran into this same issue after updating to Astroid's latest version: 3.1.2

Looking forward to a fix ;)

**Comment by exlemor** [comment]
No idea if this is related but with Astroid 3.1.2, I also got these messages on the frontend with Error Reporting set to Simple, I didn't have with 3.1.1 (after I clean cache):

Warning: Array to string conversion in /home/junniti/public_html/libraries/astroid/framework/library/vendor/scssphp/scssphp/src/Compiler.php on line 927

Warning: Array to string conversion in /home/junniti/public_html/libraries/astroid/framework/library/vendor/scssphp/scssphp/src/Compiler.php on line 927

**Comment by felixkat** [comment]
@WM-Loose @exlemor  Just download latest ZIP file and install as normal.

Go here:- https://github.com/templaza/astroid-framework/tree/v3

Then download ZIP


![Screenshot 2024-08-27 at 13-15-23 templaza_astroid-framework at v3](https://github.com/user-attachments/assets/669d93dd-d5e4-4953-8575-fe9b9dbfba23)


Tested and working.

**Comment by exlemor** [comment]
Hi @felixkat, that fixes the Save & Close dropdown menu issue BUT it does NOT solve the:

No idea if this is related but with Astroid 3.1.2, I also got these messages on the frontend with Error Reporting set to Simple, I didn't have with 3.1.1 (after I clean cache):

Warning: Array to string conversion in /home/junniti/public_html/libraries/astroid/framework/library/vendor/scssphp/scssphp/src/Compiler.php on line 927

Warning: Array to string conversion in /home/junniti/public_html/libraries/astroid/framework/library/vendor/scssphp/scssphp/src/Compiler.php on line 927

issue and please don't tell me to change Error Reporting to None from Simple as the solution - as it's not a solution but a sweeping it under the rug technique ;) (hug).

**Comment by WM-Loose** [comment]
@sonvnn The changes in the zip file helped. 
The pull down menu works again. 
Thanks

**Comment by WM-Loose** [comment]
@exlemor 
I can't confirm that. 
All of the websites we tested with Joomla 5.1.3 didn't show any errors by default.

**Comment by WM-Loose** [comment]
AND: @exlemor: There is no Joomla 5.1.4 stable version available for download. 
You have probably installed an RC version.

**Comment by patrickus33** [comment]
@sonvnn 
The V3 solve the bug for me too.

**Comment by sonvnn** [comment]
> Hi @felixkat, that fixes the Save & Close dropdown menu issue BUT it does NOT solve the:
> 
> 
> 
> No idea if this is related but with Astroid 3.1.2, I also got these messages on the frontend with Error Reporting set to Simple, I didn't have with 3.1.1 (after I clean cache):
> 
> 
> 
> Warning: Array to string conversion in /home/junniti/public_html/libraries/astroid/framework/library/vendor/scssphp/scssphp/src/Compiler.php on line 927
> 
> 
> 
> Warning: Array to string conversion in /home/junniti/public_html/libraries/astroid/framework/library/vendor/scssphp/scssphp/src/Compiler.php on line 927
> 
> 
> 
> issue and please don't tell me to change Error Reporting to None from Simple as the solution - as it's not a solution but a sweeping it under the rug technique ;) (hug).

I got this issue since Astroid 2. It is issue of scssphp library. I report it to their repository last year but no update until now. I think I need a hacking to their code in 3.1.3. I know how to fix it but I want to wait for update from scssphp's author.

**Comment by exlemor** [comment]
Hello @sonvnn - thanks for that quality explanation - hope they update fix it soon ;) (hug).

**Comment by exlemor** [comment]
> AND: @exlemor: There is no Joomla 5.1.4 stable version available for download. You have probably installed an RC version.

I understand why you might think that but I help test the latest Joomla versions and was indeed testing stable as of today.
I noticed it said on your GitHub profile that you are "interested in Joomla plugins, components and core", if you want to help improve Joomla, lots of teams could use even a bit of help ;)

**Comment by WM-Loose** [comment]
@exlemor: I am already testing the RC versions but I don't always have time. 
I am a master in the Joomla Forum Germany.
