### ISSUE TITLE
Icon after the password field is not correctly oriented 

### ISSUE THREAD

**Issue by salahjaafar** [templaza/astroid-framework#776]
**Describe the bug**
The icon in the form after the password field is not correctly oriented when the Arabic language is selected.

**To Reproduce**
Steps to reproduce the bug:
1. Go to the login page.
2. Enter a password in the corresponding field.
3. Observe the icon in the form after the password field.

**Expected behavior**
The form icon should be correctly oriented and aligned, even when the Arabic language is used.

**Screenshots**
![icon-password](https://github.com/user-attachments/assets/87dfd647-d703-4c96-92ca-603b29feab3d)

**System Information (please complete the following information):**
- Joomla Version: 5.1.3
- PHP Version: 8.2
- Astroid Version: 3.1.2
- Device: PC
- OS: Ubuntu Cinnamon 24.04
- Browser: Firefox 129.0.1 (64-bit)

**Additional context**
The issue occurs only when the interface is in Arabic.
@sonvnn

**Comment by sonvnn** [comment]
It's really an issue of Bootstrap 5. They told that they will improve it in v6. We have to wait for this :(

**Comment by sonvnn** [comment]
I fixed this issue here https://github.com/templaza/astroid-framework/commit/46267e4f37e73081aa0f4994b08a3fe130fdd310

![Screen Shot 2024-09-16 at 10 53 15](https://github.com/user-attachments/assets/bc63b1fa-74d8-44ff-897e-6f518175604e)
