### ISSUE TITLE
MinifyJS Minify and combine all JS not working

### ISSUE THREAD

**Issue by SerGun78** [templaza/astroid-framework#78]
Hey! when enabled, nothing is reduced or merged. all js-files bootstrap still go separately:
![изображение](https://user-images.githubusercontent.com/95705148/149988799-eb772fe8-7074-4520-819f-6805fd167b53.png)

**Comment by sonvnn** [comment]
You can use feature load Bootstrap from Astroid Core instead of Joomla Core. I added this feature at https://github.com/templaza/astroid-framework/commit/6c5a21b86224bfae351e0722a23fdb43dccf9794

Please help me check it.

Thank You & Kind Regards,
Sonny

**Comment by Chacapamac** [comment]
I just test this.
**• This is the uncompress Joomla Bootstrap js load**
![not-compress](https://user-images.githubusercontent.com/1907276/164487934-bcc648c5-095f-4e0a-a1f3-2cf19dfb2eb4.jpg)

**• This is the compress (by template zero) Joomla Bootstrap js load**
![compress](https://user-images.githubusercontent.com/1907276/164488031-494d3143-3711-471a-940e-4987849edf59.jpg)

**• This is the uncompress Astroid Bootstrap js load**
![Astro-Bootstrap-Not-compress](https://user-images.githubusercontent.com/1907276/164488187-76ec0206-6631-41f6-ae2d-c88c049e6c25.jpg)

**• This is the compress Astroid Bootstrap js load**
![Astro-Bootstrap-compress](https://user-images.githubusercontent.com/1907276/164488251-221b5ad0-eabc-4e22-92f5-4deb4aec58ad.jpg)
