### ISSUE TITLE
TinyMCE does not load if Minify JS process is activated

### ISSUE THREAD

**Issue by jam1974** [templaza/astroid-framework#797]
If the Minify JS process is activated, problems occur in the front end when a form field (Convert Forms, I cannot say whether the problem also exists with other components) is loaded that uses the TinyMCE.

**Comment by Chacapamac** [comment]
Any “Minify” process of JS and CSS Files by Astroid or others components need testing and user customization to work properly with all the different components, plugins and codes that build a website. You need to pinpoint the problem and build an exception.

**Comment by sonvnn** [comment]
@jam1974 Can you tell me which extension is using Tiny MCE? It would make it easier for me to check.

**Comment by jam1974** [comment]
@sonvnn I have the problem with Convert Forms.

**Comment by sonvnn** [comment]
I fixed this issue at https://github.com/templaza/astroid-framework/commit/6b81bb77c18b24c68f862e44edb4aac089588367

Please help me check it.
