### ISSUE TITLE
Footage pages navigation block truncated 

### ISSUE THREAD

**Issue by amber7212** [templaza/astroid-framework#805]
Hi Sonny

Please take into account this new bug apparently related to template zero

**Describe the bug**
The footage pages navigation block seems truncated (see picture)

**To Reproduce**
Activate template zero 3.1.0 with Astroid 3.1.3

**Expected behavior**
Pages navigation block should not be truncated

**Screenshots**
See attached

**System Informations (please complete the following information):**
 - Joomla Version: 4.4.8
 - PHP Version 8.3
 - Astroid Version 3.1.3
 - Device: PC
 - OS: Windows 10
 - Browser Firefox
- Template : Astroid zero 3.1.0

**Additional context**
None

![image](https://github.com/user-attachments/assets/2ab11e9a-af8a-4cdf-8080-d1b3519b38f6)

**Comment by sonvnn** [comment]
@amber7212 it's work on my local. Can you send me your url via sonlv@templaza.com? I will check it.
My local below:
![Screen Shot 2024-09-13 at 10 22 24](https://github.com/user-attachments/assets/10b0d417-043b-4c84-a771-ecef4d773c6b)

**Comment by amber7212** [comment]
Hi,

It seems related to Firefox : the issue does not appear with Chrome

**Comment by sonvnn** [comment]
@amber7212 It's still work on my Firefox :)
![Screen Shot 2024-09-14 at 09 06 13](https://github.com/user-attachments/assets/56e40dde-0c54-4657-afe0-848d4424233a)

**Comment by amber7212** [comment]
Hi,

it seems now fixed. I dont know how

**Comment by sonvnn** [comment]
May be cache :D
