### ISSUE TITLE
Changing the colour of the content

### ISSUE THREAD

**Issue by jam1974** [templaza/astroid-framework#807]
Changing the colour of the content in the text widget does not work. Changing the colours for the heading works perfectly.
Testing with 3.1.3. and 3.1.4RC.

**Comment by sonvnn** [comment]
@jam1974 I tested Text widget again on my localhost and it still works.
![Screen Shot 2024-09-15 at 17 44 39](https://github.com/user-attachments/assets/bee6327a-2a5d-4310-8704-30c0f9103f53)

**Comment by jam1974** [comment]
@sonvnn

![werksarzt](https://github.com/user-attachments/assets/678a03a3-f293-445a-8900-6c1c36f289f5)

**Comment by jam1974** [comment]
![werksarzt](https://github.com/user-attachments/assets/f27f85cf-bfce-42ef-88ac-3621e163dc8e)

@sonvnn

**Comment by sonvnn** [comment]
@jam1974 Can you give me your url? I can help you check in debug. It still work normally on my site.

**Comment by jam1974** [comment]
@sonvnn Okay, I have something new. If I assign the h2 property to the text, the colour does not work. The text without the h2 property works. Try this out.

**Comment by sonvnn** [comment]
I guess you are having some issues with css conflicts. You should try using chrome or firefox to debug and see if there is any css affecting your elements?

**Comment by jam1974** [comment]
@sonvnn  I don't find any conflict. The problem is that h2 is the last statement for the section and therefore overwrites the statement from the div:

<div class="astroid-content-text"><h2>Fordern Sie jetzt eine unverbindliche Beratung an und lassen Sie uns gemeinsam an der Gesundheit und Zukunft Ihres Unternehmens arbeiten!</h2></div>

.astroid-content-text {
  color: rgba(255, 255, 255, 1);
  font-size: 1.90em;
  line-height: 1.25em;
}

**Comment by jam1974** [comment]
@sonvnn I don't find any conflict. The problem is that h2 is the last statement for the section and therefore overwrites the statement from the dic.

**Comment by sonvnn** [comment]
@jam1974 It would be easier if you could provide a link so I can check it. It's hard to check a problem just by imagining it.

**Comment by jam1974** [comment]
@sonvnn  Please try the following: On your installation of the image above, give the demo text ‘Lorem ipsum’ the property h2 via the editor and then take a look at the problem with the colour.

![werksarzt2](https://github.com/user-attachments/assets/bcc9795a-37d5-4a4d-9af3-fc3820052a11)

**Comment by sonvnn** [comment]
@jam1974 Ah I found it. Because h2 style was overrided. I fixed this issue at https://github.com/templaza/astroid-framework/commit/7dfa2640576d3defdc10cae318301d027c408e00

Please help me download v3-branch and re-test it.

Thanks & Best Regards,
Sonny

**Comment by jam1974** [comment]
@sonvnn Yes error is fixed. Thanks, good work!
