### ISSUE TITLE
add on/off for "Social"

### ISSUE THREAD

**Issue by SerGun78** [templaza/astroid-framework#81]
Hello to all! It is necessary to add the ability to enable or disable social links, doing the same as "Branding" and "Contact details".
Otherwise, this module is always displayed now, even without one link to a social network.
![изображение](https://user-images.githubusercontent.com/95705148/150801602-dc88b973-7ef2-4ff1-982c-f38acfda01a9.png)
![изображение](https://user-images.githubusercontent.com/95705148/150801654-6c6b7b95-8298-4385-8bfd-2032a7336f25.png)

**Comment by sonvnn** [comment]
Hello,

I noted this for v2.5.14.

Thanks & Best Regards,
Sonny

**Comment by sonvnn** [comment]
Hello @SerGun78,

I add this feature on https://github.com/templaza/astroid-framework/commit/810aee687b2be8325ed11848f0f72142073e2aba
I will be release in v2.5.14. You can download developer branch to test it.

Kind Regards,
Sonny

**Comment by Chacapamac** [comment]
How can you download the developer branch?

**Comment by SerGun78** [comment]
https://github.com/templaza/astroid-framework/tree/developer
green button "Code", "download ZIP"

**Comment by Chacapamac** [comment]
Thank You @SerGun78

**Comment by Chacapamac** [comment]
On/Off Social work perfectly on:

Work after installing the last Dev Branch.

Joomla 3.10.5
PHP 7.4.27
Template Zero
