### ISSUE TITLE
Astroid 3.1.3 activatet Minify html creates a white page in the frontend when editing modules with large content.

### ISSUE THREAD

**Issue by WM-Loose** [templaza/astroid-framework#812]
Hi Sonny,

Problem in J4.4.8 and J5.1.4
PHP 8.3
Max Upload, Max File Size 512M

Test with UIKIT3 Modules an other Modules 

If a module is clicked on in the frontend with Edit and there is a lot of content (images) in the module, only a white page is displayed. If Minify is deactivated, the module can be opened and edited in the frontend without any problems. Here Minify seems to have a maximum limit and thus prevents it from opening.

Report errors maximum Info:
Deprecated: preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /my_joomla/libraries/astroid/framework/library/astroid/Document.php on line 485

I deactivate minify html everything works without problems.
I have recommended to our customers to deactivate minyfy for now.

**Comment by WM-Loose** [comment]
Sorry, its only in Joomla 5.1.4 and not in Joomla 4.4.8.

**Comment by sonvnn** [comment]
I test it on my local and everything is well.
