### ISSUE TITLE
After updating from 3.1.3 to 3.1.4, created presets or layouts can no longer be downloaded!

### ISSUE THREAD

**Issue by WM-Loose** [templaza/astroid-framework#815]
The function is no longer possible.

![1](https://github.com/user-attachments/assets/b3d9602d-b841-4afe-a86b-c87362a6e733)

 - Joomla Version: [e.g. Joomla 4.4.8 and 5.1.4]
 - PHP Version [8.3]
 - Astroid Version [e.g. Astroid 3.1.4]

**Comment by sonvnn** [comment]
It still work on my local. But I try to find a solution for this. May be It can work on your server. https://github.com/templaza/astroid-framework/commit/26623dc86dd3f2844d21ce458611d2af5987b12f
You can download v3-branch to test it https://github.com/templaza/astroid-framework/archive/refs/heads/v3.zip

**Comment by WM-Loose** [comment]
Yes,  https://github.com/templaza/astroid-framework/archive/refs/heads/v3.zip works Sonny.

**Comment by sonvnn** [comment]
@WM-Loose Thanks! I'll wait the next 24 hours for everyone to test before releasing the quick fix.

**Comment by WM-Loose** [comment]
IMPORTANT!
I have now tested it with J5.1.4 and it doesn't work there. 
If I use the patch with J4.4.8 I can download. 
**But the patch doesn't work with J5.1.4.**

**Comment by Joomlaplates** [comment]
Yes thats right.
New version is working but you need to clean the Browser cache before > STRG + F5
Friendly regards, Peter
