### ISSUE TITLE
Background image is not displayed

### ISSUE THREAD

**Issue by Patman29** [templaza/astroid-framework#820]
I use Astriod 3.1.5 and wanted to change a background image. However, it is no longer displayed after saving. The page background remains empty.
I also cannot select any files using the "Change Image" button, even though some are available.
![image](https://github.com/user-attachments/assets/a5f38bd9-acbc-4de6-9429-34e466b44711)

**Comment by WM-Loose** [comment]
Correct. 
The path to the media folder is missing!

**Comment by sonvnn** [comment]
> I use Astriod 3.1.5 and wanted to change a background image. However, it is no longer displayed after saving. The page background remains empty.
> 
> I also cannot select any files using the "Change Image" button, even though some are available.
> 
> ![image](https://github.com/user-attachments/assets/a5f38bd9-acbc-4de6-9429-34e466b44711)
> 
> 
> 
> 

Can you send me your admin via sonlv@templaza.com? I am at home right now. I will check it when I back to the office. I am not sure because it is still work on my site. So I need to check what is happen on your server. So I will give you solution, quickly.

Best regards,
Sonny

**Comment by WM-Loose** [comment]
Hello Sonny,
has nothing to do with the server. With 3.1.3 everything is fine. With 3.1.5 the path to the media folder is no longer correct and the images are no longer displayed in the selection field. It's the same problem for all customers.

**Comment by WM-Loose** [comment]
It only affects Joomla 4.4.8 and it works on Joomla 5.1.4

**Comment by sonvnn** [comment]
In 3.1.5 I changed url from absolute from relative to avoid some CORS error issue on some servers. I think it is problem. May be it has some diffirent between Url library of Joomla 4 and 5. Okay I will check and fix it in the next 24h

Thanks & Best regards,
Sonny

**Comment by WM-Loose** [comment]
Yes, you're right. There was a change from J4 to J5. That must be the reason. 
Thank you for your support.

**Comment by Joomlaplates** [comment]
Hello Sony, I´ve send you admin access to your mail address.
Thank you, Peter

**Comment by sonvnn** [comment]
@Joomlaplates @WM-Loose I found this issue from File::getExt library is undefined in Joomla 4. I fixed it at https://github.com/templaza/astroid-framework/pull/817/commits/e7cf6d6cc9590836923f4c20b7694445fddaa7f4 and update on your site. Now system is working. I will release 3.1.6 today. 

Thank you for report issue.

Best Regards,
Sonny

**Comment by WM-Loose** [comment]
Thank you for the quick support. The new version 3.1.6 works.

**Comment by WM-Loose** [comment]
@sonvnn: Are there users who would like to buy you a coffee but can't find the link?

**Comment by sonvnn** [comment]
@WM-Loose Thank you! It's here https://ko-fi.com/astroidframework/

**Comment by sonvnn** [comment]
Thank you very much 🍺😁
