### ISSUE TITLE
Error with tassos.gr EngageBox / not valid JSON

### ISSUE THREAD

**Issue by BirchH0lLOw** [templaza/astroid-framework#829]
**Describe the bug**
Using the Astroid framework and template and Tassos EngageBox (Pro). When trying to create NEW, I receive an error and the only available option is to start from blank.

**To Reproduce**
1. Go to Components
2. Click on EngageBox
3. Get error - SyntaxError: Unexpected token 'j', "json_decod"... is not valid JSON
  ![AstroidFmwk-EngageBox1-ErrorAlert](https://github.com/user-attachments/assets/30df6f98-3cfa-4ab3-8a63-309268b61d2a)
4. Nothing more than Blank Popup appears for EngageBox

**Expected behavior**
I expect a library of samples to quickly make a pop up box

**Screenshots**
What I'm expecting
![AstroidFmwk-EngageBox1](https://github.com/user-attachments/assets/f439f7df-848a-4364-b51f-f7908f2ecad0)
What I get
![AstroidFmwk-EngageBox1-Error](https://github.com/user-attachments/assets/2b09a0e5-ef1e-432e-a4e1-b44cc7a354bc)

**System Informations (please complete the following information):**
 - Joomla Version: 5
 - PHP Version 8.2
 - Astroid Version 3.1.6
 - Device: PC
 - OS: Win10
 - Browser Chrome

**Additional context**
This is a backup of my site and I added Astroid Framework and Template.

**Comment by sonvnn** [comment]
Hi @BirchH0lLOw 
Sorry for late reply. I am Sonny from Astroid Team. Can you send me your admin account via sonlv@templaza.com? I will help you check it.

Best Regards,
Sonny

**Comment by sonvnn** [comment]
@BirchH0lLOw 
Hello I found this issue from Tassos Framework. 
`json_decode(): Argument #1 ($json) must be of type string, array given0/home/saifhaus-14iv/htdocs/14iv.saifhaus.com/plugins/system/nrframework/nrframework.php359Array`

You can check it here 
![Screen Shot 2024-10-15 at 14 16 26](https://github.com/user-attachments/assets/5ed1e9a3-382b-4a41-ad37-7c6c9ec52b48)

I tried disabling Astroid Plugin and this error still occurs. That means this error is only related to Tassos Framework internals. This error has nothing to do with Astroid Framework.

Please help me check it again.
Best regards,
Sonny

**Comment by BirchH0lLOw** [comment]
Thank you!!
    All typos courtesy my iPhone Eric MayfieldCalifornia Licensed Professional Fiduciary #158National Certified GuardianKONSULATI INC Office: 1442 Irvine Blvd, Suite 104, Tustin, CA 92780Client Billing: {Client Name}, c/o Konsulati Inc., P.O. Box 54248, Irvine, CA 92619-4248Tel/Fax: (714) 475-2121 or (877) 456-6785 Click to Authorize Text Communications per Telephone Consumer Protection Act (TCPA) NOTICE: This e-mail (including attachments if any) is covered by the Electronic Communications Privacy Act, 18 U.S.C. §§ 2510-2521, is confidential and may contain client materials and/or work product. This e-mail is intended only for the addressee named above. If you are not the intended recipient, you are hereby notified that any retention, dissemination, distribution, or copying of this communication is strictly prohibited. Please reply to the sender that you have received this message in error, then delete it and any and all copies of it. 
  

 From: Sonny Le ***@***.***>Sent: Thursday, October 31, 2024 12:51 AMTo: templaza/astroid-framework ***@***.***>Cc: BirchH0lLOw ***@***.***>; Mention ***@***.***>Subject: Re: [templaza/astroid-framework] Error with tassos.gr EngageBox / not valid JSON (Issue #829) 
Closed #829 as completed.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
All typos courtesy my iPhone Eric MayfieldCalifornia Licensed Professional Fiduciary #158National Certified GuardianKONSULATI INC Office: 1442 Irvine Blvd, Suite 104, Tustin, CA 92780Client Billing: {Client Name}, c/o Konsulati Inc., P.O. Box 54248, Irvine, CA 92619-4248Tel/Fax: (714) 475-2121 or (877) 456-6785 Click to Authorize Text Communications per Telephone Consumer Protection Act (TCPA) NOTICE: This e-mail (including attachments if any) is covered by the Electronic Communications Privacy Act, 18 U.S.C. §§ 2510-2521, is confidential and may contain client materials and/or work product. This e-mail is intended only for the addressee named above. If you are not the intended recipient, you are hereby notified that any retention, dissemination, distribution, or copying of this communication is strictly prohibited. Please reply to the sender that you have received this message in error, then delete it and any and all copies of it.
