### ISSUE TITLE
child theme joomla 4.1

### ISSUE THREAD

**Issue by rinka88** [templaza/astroid-framework#83]
with the advent of joomla 4.1, child themes will be added. And will it be in the Astroid?

**Comment by Chacapamac** [comment]
This is interesting, the ultimate override for Joomla, Astroid should have that feature.

**Comment by Joomlaplates** [comment]
Hi together,
sorry dont understand the point of child themes. Its just another problem maker. How updates will work then if you have duplicated physically files?
And the other question is, what for? You can do everything with overrides or duplicated theme styles.
Most users are overstrained with the current functions of Astroid, dont need to confuse them even more. 
**Much more important is to do the current Astroid more stable and faster than more and more features.**
Just my 5 cent

**Comment by sonvnn** [comment]
Sure! Astroid will support all Joomla Core feature.

**Comment by Chacapamac** [comment]
Good News!
Child theme is a long feature in WordPress and it make sens. I’m sure if Joomla want to include it in its core, that it will give us more than the great actual Joomla override system. 
 For sure, any overrides done in the futur child themes or pure Joomla overrides NEED to be updated manually at a certain point to stay relevant to the codes changes to the core or the component you overrides.

**Comment by rinka88** [comment]
Has this functionality been implemented? as already close 4.2.
