### ISSUE TITLE
horizontal scroll when sppagebuilder row set on fluid

### ISSUE THREAD

**Issue by babakhakimi** [templaza/astroid-framework#839]
hi @sonvnn 

i need help

i have a problem with astroid framework and sppagebuilder
i can't say exactly which one is the problem

My problem is where when I put a row in sppagebuilder to fluid mode
A scroll will appear in the horizontal direction

I noticed that when sppagebuilder adds a row to the page normally, it gives it the sppb-row-container class.

But when it is of fluid type, it gives it the sppb-container-inner class

And the difference is that the sppb-row-container class has padding, but the sppb-container-inner class does not have this feature.

**Comment by sonvnn** [comment]
It is a problem when you configure SP Page Builder incorrectly. I don't know why the SP Page Builder guys don't figure out how to eliminate this error for users automatically. To fix this error you need to enable the "Remove Columns Gap" function which will remove all the extra column gaps in Fluid Row.
![Screen Shot 2024-10-29 at 15 20 44](https://github.com/user-attachments/assets/3882940c-edd5-4a43-b293-8064c6f00c09)

**Comment by babakhakimi** [comment]
i do that  and  set all Gutter Setting of row to inherit in template layout section and its work
thank you @sonvnn
