### ISSUE TITLE
3.1.7 RC2 error in header mode when off-canvas menu is off

### ISSUE THREAD

**Issue by jam1974** [templaza/astroid-framework#841]
I am testing the 3.1.7 RC2 and have the following error:

when I make the settings as follows:

![01Screenshot 2024-10-22 152434](https://github.com/user-attachments/assets/8e3a62f4-08d7-448f-87db-cce506c7ed6d)

![02Screenshot 2024-10-22 152539](https://github.com/user-attachments/assets/b82e8af6-5c8d-4254-bbed-395b98806228)

and then deactivate the off-canvas menu, the logo is no longer centred:

![03Screenshot 2024-10-22 152623](https://github.com/user-attachments/assets/bbfa5780-ed0b-4f4c-8b26-a4f0d1325071)

![04Screenshot 2024-10-22 152738](https://github.com/user-attachments/assets/d2cf25aa-d0e4-489b-8fa4-e30535846392)

**Comment by sonvnn** [comment]
I fixed this issue at https://github.com/templaza/astroid-framework/commit/76da7a2c7734ba80637b879273cf8c4ea6e69042 
Please help me download v3-branch and retest it.
Thanks & Best Regards,
Sonny

**Comment by jam1974** [comment]
Yes error fixed. works fine. Thank you!
