### ISSUE TITLE
Article Layout Builder: jQuery.Deferred exception: 

### ISSUE THREAD

**Issue by Dnsftl** [templaza/astroid-framework#842]
Bug
Article Layout Builder --> Template --> Jollyany | Multi-purpose - Version 3.5.28

Bug Description

he top bar above the header has disappeared. The page built with Article Layout is now blank, displaying only a blinking dot in the middle of the screen.

Uncaught TypeError: s is undefined
    injectStyle https://********.nl/cache/astroid/js/b46b80fa58da4767b1e6355d328cdffc.js?7cf332:55
    injectCss https://********.nl/cache/astroid/js/b46b80fa58da4767b1e6355d328cdffc.js?7cf332:55
    build https://********.nl/cache/astroid/js/b46b80fa58da4767b1e6355d328cdffc.js?7cf332:55
    u https://********.nl/cache/astroid/js/b46b80fa58da4767b1e6355d328cdffc.js?7cf332:55
    <anonymous> https://********.nl/test:1

b46b80fa58da4767b1e6355d328cdffc.js:55:2254
jQuery.Deferred exception: jQuery(...).imagesLoaded is not a function @https://********.nl/cache/astroid/js/b46b80fa58da4767b1e6355d328cdffc.js?7cf332:454:148
e@https://********.nl/cache/astroid/js/b46b80fa58da4767b1e6355d328cdffc.js?7cf332:17:27028
Deferred/then/l/</t<@https://********.nl/cache/astroid/js/b46b80fa58da4767b1e6355d328cdffc.js?7cf332:17:27330
 undefined b46b80fa58da4767b1e6355d328cdffc.js:17:28648

jQuery.Deferred exception: jQuery(...).imagesLoaded is not a function @https://********.nl/cache/astroid/js/b46b80fa58da4767b1e6355d328cdffc.js?7cf332:455:102
e@https://********.nl/cache/astroid/js/b46b80fa58da4767b1e6355d328cdffc.js?7cf332:17:27028
Deferred/then/l/</t<@https://********.nl/cache/astroid/js/b46b80fa58da4767b1e6355d328cdffc.js?7cf332:17:27330
 undefined b46b80fa58da4767b1e6355d328cdffc.js:17:28648

jQuery.Deferred exception: jQuery(...).imagesLoaded is not a function @https://********.nl/cache/astroid/js/b46b80fa58da4767b1e6355d328cdffc.js?7cf332:456:148
e@https://********.nl/cache/astroid/js/b46b80fa58da4767b1e6355d328cdffc.js?7cf332:17:27028
Deferred/then/l/</t<@https://********.nl/cache/astroid/js/b46b80fa58da4767b1e6355d328cdffc.js?7cf332:17:27330
 undefined b46b80fa58da4767b1e6355d328cdffc.js:17:28648

Uncaught TypeError: jQuery(...).imagesLoaded is not a function
    <anonymous> https://********.nl/cache/astroid/js/b46b80fa58da4767b1e6355d328cdffc.js?7cf332:454
    e https://********.nl/cache/astroid/js/b46b80fa58da4767b1e6355d328cdffc.js?7cf332:17
    t https://********.nl/cache/astroid/js/b46b80fa58da4767b1e6355d328cdffc.js?7cf332:17
b46b80fa58da4767b1e6355d328cdffc.js:454:148

Uncaught TypeError: jQuery(...).imagesLoaded is not a function
    <anonymous> https://********.nl/cache/astroid/js/b46b80fa58da4767b1e6355d328cdffc.js?7cf332:455
    e https://********.nl/cache/astroid/js/b46b80fa58da4767b1e6355d328cdffc.js?7cf332:17
    t https://********.nl/cache/astroid/js/b46b80fa58da4767b1e6355d328cdffc.js?7cf332:17
b46b80fa58da4767b1e6355d328cdffc.js:455:102

Uncaught TypeError: jQuery(...).imagesLoaded is not a function
    <anonymous> https://********.nl/cache/astroid/js/b46b80fa58da4767b1e6355d328cdffc.js?7cf332:456
    e https://********.nl/cache/astroid/js/b46b80fa58da4767b1e6355d328cdffc.js?7cf332:17
    t https://********.nl/cache/astroid/js/b46b80fa58da4767b1e6355d328cdffc.js?7cf332:17

Steps to Reproduce

After installing Astroid 3.1.7.RC-2, navigate to the page built with the Article Builder. The page appears nearly empty, displaying only a blinking dot. Astroid cache cleared / Joomla cache cleared after installation of Astroid 3.1.7 RC-2

Expected Behavior
Showing the article as build in Astroid

Screenshots/video

https://github.com/user-attachments/assets/c159cab3-b834-477f-be96-4614fb70a348

System Information

Joomla Version: 5.2.0
PHP Version: 8.3
Astroid Version: 3.1.7 RC-2
Device: Laptop
Operating System: Windows 11
Browsers: Chrome, Firefox, Edge

Regards,

Dennis

**Comment by sonvnn** [comment]
I tested on my local. JS minification works fine. Can you send me your admin acc via sonlv@templaza.com? I will help you check.

**Comment by Dnsftl** [comment]
Dtails send

**Comment by sonvnn** [comment]
@Dnsftl I fixed this issue at https://github.com/templaza/astroid-framework/commit/9b6dcbba555e234e824438d534934d935420acd1

I updated it on your site. Please help me check it again. 

Thanks & Best regards,
Sonny

**Comment by Dnsftl** [comment]
@sonvnn,

Thanks for updating the site, it works fine now.

Regards,

Dennis
