### ISSUE TITLE
I miss widgets in the 3.1.7 RC

### ISSUE THREAD

**Issue by jam1974** [templaza/astroid-framework#843]
They were still present in version 3.1.6. In the current RC the Hover Motion Gallery is missing, instead there is Image Carousel.

CodePen was present in version 3.1.6, but the widget is also missing in RC 3.1.7.

**Comment by sonvnn** [comment]
It moved to Pro. Let's download Pro plugin and install it.

**Comment by jam1974** [comment]
@sonvnn I am missing an invitation.

**Comment by sonvnn** [comment]
Sent! Please check your email. Thank you.

**Comment by deltapapa01** [comment]
Hi Sonny,
I have just tested 3.1.7 RC3, with and without Pro Plugin.
It would be really cool if you could see in the template manager whether you are using the Pro or the Core version.
At the moment I can only see it in the widgets, right?
Apart from that, I haven't found any other problems on 2 pages

**Comment by sonvnn** [comment]
> Hi Sonny, I have just tested 3.1.7 RC3, with and without Pro Plugin. It would be really cool if you could see in the template manager whether you are using the Pro or the Core version. At the moment I can only see it in the widgets, right? Apart from that, I haven't found any other problems on 2 pages

Thank you! I will improve UI/UX in the 3.1.8
