### ISSUE TITLE
Like to give some money to the project ?

### ISSUE THREAD

**Issue by Chacapamac** [templaza/astroid-framework#85]
@sonvnn 
I like to give some money to the project, How?
— I was going to buy the Jollyany template
— or can I give you the money instead, How ?

**Comment by sonvnn** [comment]
Hi @Chacapamac,

Thank you for your support. Your help is worth more than all the money. I will soon come back on the next Monday after Lunar Holiday. We will have many plan for Astroid and I need your help. Thank you all @Chacapamac @Joomlaplates and everyone in this project.

Happy Tiger Year from Vietnam.

Best Regards,
Sonny

**Comment by Chacapamac** [comment]
Understood
Happy Tiger Year to your family and everybody on earth, we need it.
