### ISSUE TITLE
Astroid Pro removes animation in the layouts - none of these modules are displayed anymore

### ISSUE THREAD

**Issue by WM-Loose** [templaza/astroid-framework#852]
Hi Sonny, if you activate Astroid Pro, in 3.1.7 all animations set in the layouts such as zoomleft or bounds etc. no longer work. As soon as I deactivate the Pro plugin, everything works without problems and the animations are displayed again. It is even the case that where you have inserted a module with animation, the module position is no longer displayed at all in the frontend.

**Comment by sonvnn** [comment]
@WM-Loose I fixed this issue in the last commit. Please help me re-download package and check it again. 
Thanks & Best Regards,
Sonny

**Comment by WM-Loose** [comment]
I tested and wrote everything on Astroid Pro Github.

**Comment by sonvnn** [comment]
Moved to Pro repository
