### ISSUE TITLE
Astroid menu module resets after updating Astroid

### ISSUE THREAD

**Issue by vtheod** [templaza/astroid-framework#854]
**Describe the bug**
After astroid update, the astroid menu module resets it's position from astroid header menu (or astroid header mobilemenu) to status.

**To Reproduce**
Just puplish an astroid menu module to astroid header menu or to astroid header mobilemenu positions and then update astroid to a later version.

**Expected behavior**
the module's position will be reset

**Screenshots**
Before the update:
![Before_update](https://github.com/user-attachments/assets/8af20e86-1fd2-4d1a-8df3-037365a95b80)

After the update:
![After_update](https://github.com/user-attachments/assets/240dd26e-7629-4c9e-8bbc-592996546326)

**System Informations (please complete the following information):**
 - Joomla Version: [Joomla 4 & 5]
 - PHP Version [PHP 8.1, 8.2 & 8.3]
 - Astroid Version [e.g. Astroid 3.1.0]

**Additional context**

**Comment by rinka88** [comment]
I confirm
This happens when updating a template.
When discussing 3.1.7 RC talked about this

**Comment by vtheod** [comment]
This happens when updating the framework (haven't noticed it with template updates) and it's not recent but it exists also in previous versions of astroid.

**Comment by rinka88** [comment]
> This happens when updating the framework (haven't noticed it with template updates) and it's not recent but it exists also in previous versions of astroid.

by the word template I meant framework

**Comment by sonvnn** [comment]
@rinka88 @vtheod It's my mistake. I will fix it in the next version. Please wait for the update.

**Comment by sonvnn** [comment]
@vtheod @rinka88 I fixed this issue at https://github.com/templaza/astroid-framework/commit/6f99ee765bceb6f7bd0ed332254dfefaf9898506
Please help me download v3-branch and test it.

Best Regards,
Sonny

**Comment by vtheod** [comment]
I installed it and it seems that the issue is fixed. Thanks @sonvnn 
I just noticed that after installation, the icon in the get started button doesn't display:

![Screenshot 2024-11-01 at 09-56-50 Extensions Install - Administration](https://github.com/user-attachments/assets/9e8eab84-8b17-4738-9e11-83b4013e1551)

**Comment by rinka88** [comment]
thanks for the correction
