### ISSUE TITLE
Override a Widget minor update to code

### ISSUE THREAD

**Issue by felixkat** [templaza/astroid-framework#856]
Just a minor observation.....

All the code for the widgets start with the following text

```
* You can easily override all files under /astroid/ folder.
 * Just copy the file to JROOT/templates/YOUR_ASTROID_TEMPLATE/astroid/elements/module_position/module_position.php folder to create and override
```

Where I believe the path should be.

`JROOT/media/templates/site/{YOUR_TEMPLATE_NAME}/astroid/elements`

**Comment by sonvnn** [comment]
Thank you! I will update it in the next version.
