### ISSUE TITLE
Field missing in Astroid plugin to enter Gmaps key.

### ISSUE THREAD

**Issue by felixkat** [templaza/astroid-framework#858]
Widget Google Maps looks for an API Key if selecting advanced.

`$gmap_api       =   $pluginParams->get('gmap_api', '');`

But the field is missing in the Astroid plugin.

Also errors in the console log, (even with key hard coded).

![image](https://github.com/user-attachments/assets/9ba48490-2715-4409-92d4-25f44f712748)

**Comment by sonvnn** [comment]
@felixkat Thank you for report issue. I fixed this issue at https://github.com/templaza/astroid-framework/commit/d28e5681fe1a5ad13399c06dfbbc7638668d217a

Please help me download v3-branch and test it.

**Comment by felixkat** [comment]
The new field is tested and working.

Strangely though, the advanced map only works when Minify JS is enabled.

![image](https://github.com/user-attachments/assets/6ca4e35e-e2a3-4027-96b4-384a9f66590e)

If Minify JS is disabled it only works 5% of the time 

![image](https://github.com/user-attachments/assets/34f8a316-2bc1-43f1-af14-52557b082af0)
