### ISSUE TITLE
Form builder produces "undefined" message when trying to submit a form.

### ISSUE THREAD

**Issue by felixkat** [templaza/astroid-framework#867]
### **EDIT:-**   The following diagnosis is when the form widget is launched via Article Layout Builder.

line 25 - $element - Produces expected results when launched via layout.

.
.
.

Form builder produces "undefined" message when trying to submit a form using the **Article Layout Builder.**

![image](https://github.com/user-attachments/assets/45c613c6-8e0c-439e-a146-32ed8b9979d1)

I've only had a brief look, I believe the bug lies within formbuilder/ajax.php

line 25 - $element looks to return false which prevents the if statement to process from line 26.

However, even if processed, line 31 $params, is not going to fetch the correct information.

![image](https://github.com/user-attachments/assets/fddedeb1-c5f9-4803-b1cd-07078cbbaaff)

Running latest commit, on Joomla 5.

I don't believe to be a recent issue as it's was mentioned in September

https://github.com/templaza/astroid-framework/discussions/798

**Comment by sonvnn** [comment]
Thank you I will check and response asap 👍

**Comment by sonvnn** [comment]
I fixed this issue at https://github.com/templaza/astroid-framework/commit/0a0433a5f54ef7b515bc73c645cc215f303d0134
Please help me download v3-branch and test it.
Thanks,

**Comment by felixkat** [comment]
@sonvnn All working fine, thank you.
