### ISSUE TITLE
Problem with the form widget / checkbox

### ISSUE THREAD

**Issue by jam1974** [templaza/astroid-framework#868]
When selecting a checkbox with the property Mandatory, the dispatch works even if the box is not activated.

**Comment by felixkat** [comment]
Hi,

Which Astroid version is this running?

Does this happen with all elements for Mandatory \ Field required?

Apart from the issue, does the form work correctly and send emails?   (asking the question due to a different logged issue).

**Comment by jam1974** [comment]
I am running version 3.1.7 and the form only shows the checkbox. If there is no entry in the fields for text, textarea, or email and these are also declared as mandatory fields, there is a message when sending that the fields require an entry. The form is submitted correctly.

I have just noticed that my entry is under "Success & Error Message Options" does not work either. When sending, the original text “Message sent successfully!” remains. However, I have stored my texts in the backend.
![form_checkbox](https://github.com/user-attachments/assets/85735db4-ee0a-41d1-ad41-d21f7ce513aa)

**Comment by felixkat** [comment]
Thank you for the update and video, it makes your issue clearer.

I will try and replicate your issue but I having a slight issue in getting my form working https://github.com/templaza/astroid-framework/issues/867

**Comment by jam1974** [comment]
I'm working with J5.2.1.

**Comment by jam1974** [comment]
I have tested it. The error also occurs in the following field types: Radio, Select, Range

**Comment by felixkat** [comment]
Well the good news is you have partially assisted in getting my test form working.  I took a different approach on the basis of knowing that the basic process of your form is working.

I will replicate and test your setup later.

**Comment by sonvnn** [comment]
Thank you I will check it and response asap 👍

**Comment by felixkat** [comment]
> I have just noticed that my entry is under "Success & Error Message Options" does not work either. When sending, the original text “Message sent successfully!” remains. However, I have stored my texts in the backend.

@sonvnn For this one Lines 147-148 Need to be changed to in formbuilder/ajax.php 
```

$message_success    =   $params->get('form_submit_success', Text::_('ASTROID_FORMBUILDER_SENT_SUCCESSFULLY'));
$message_failed     =   $params->get('form_submit_failed', Text::_('ASTROID_FORMBUILDER_SENT_MAIL_FAILED'));
```

**Comment by sonvnn** [comment]
> > I have just noticed that my entry is under "Success & Error Message Options" does not work either. When sending, the original text “Message sent successfully!” remains. However, I have stored my texts in the backend.
> 
> @sonvnn For this one Lines 147-148 Need to be changed to in formbuilder/ajax.php
> 
> ```
> 
> $message_success    =   $params->get('form_submit_success', Text::_('ASTROID_FORMBUILDER_SENT_SUCCESSFULLY'));
> $message_failed     =   $params->get('form_submit_failed', Text::_('ASTROID_FORMBUILDER_SENT_MAIL_FAILED'));
> ```

Thanks, you can create a pull request. I will check and merge it to the master branch :)

**Comment by felixkat** [comment]
> When selecting a checkbox with the property Mandatory, the dispatch works even if the box is not activated.

@jam1974 I can recreate this issue, a quick look suggests that there isn't any code implemented for the checkbox and radio options to make this work.

For the select, I don't think we can do much as something is always selected, ideally we need something like a "please select" which has no value, so it won't proceed unless something is selected.

I'll put a pull request in for the success and error message but you can test this yourself if you want to manually try it.  https://github.com/templaza/astroid-framework/issues/868#issuecomment-2472187419

**Comment by jam1974** [comment]
@felixkat https://github.com/templaza/astroid-framework/issues/868#issuecomment-2472187419 works. For the checkbox, I don't think it's a solution if I select “Please select”. I think about a function for the PrivacyCheckbox. Okay, maybe you need a new form type for this.

**Comment by felixkat** [comment]
> @felixkat [#868 (comment)](https://github.com/templaza/astroid-framework/issues/868#issuecomment-2472187419) works. For the checkbox, I don't think it's a solution if I select “Please select”. I think about a function for the PrivacyCheckbox. Okay, maybe you need a new form type for this.

Yes I understand, for the Privacy Checkbox it should be a checkbox or radio, I will try and look at the code later.

But in other situations that require a selection before proceeding a "Please select" would be useful otherwise it will always use the default.

**Comment by jam1974** [comment]
@felixkat I do not consider a selection for confirmation to be useful in this case. Today I tried to integrate a function that can be activated like the forwarding url or the captcha. When I activate it, I get a field in which I can enter the desired text. And if this is activated, the sending of the email is blocked in the form as long as the checkbox is not selected. but my knowledge is probably not sufficient.

**Comment by felixkat** [comment]
> I do not consider a selection for confirmation to be useful in this case

I agree, I was just thinking about other cases where this may be useful.  Ideally the function needs to work with all fields.

> Today I tried to integrate a function that can be activated like the forwarding url or the captcha. When I activate it, I get a field in which I can enter the desired text. And if this is activated, the sending of the email is blocked in the form as long as the checkbox is not selected. but my knowledge is probably not sufficient.

The check \ radio needs to be modified to prevent form submission if the boxes are not checked.  I will try and take a look later or maybe @sonvnn

**Comment by felixkat** [comment]
@jam1974 I've made the changes to check boxes and radio

You can download formbuilder.php here to test.

https://github.com/felixkat/astroid-framework/blob/e62bfce83e3954aa7fac4720b4b75236215bdd20/framework/elements/formbuilder/formbuilder.php

**Comment by felixkat** [comment]
What version or commit are you on? I think Sonny has made some changes today which may not yet be complete.

If you are on today's commit you can download the following file as well to keep everything in sync.

https://github.com/felixkat/astroid-framework/blob/e62bfce83e3954aa7fac4720b4b75236215bdd20/framework/elements/formbuilder/ajax.php

**Comment by sonvnn** [comment]
The issue from this `$element        =   Helper::getElement($unqid);` It happens when load a form in Article Layout and cause is system can not reconize the `$template`. I am working on it. Please wait for the update.

**Comment by jam1974** [comment]
@sonvnn I have integrated the form in the layout and not via the articles layout. The widget is assigned to a menu item.

**Comment by felixkat** [comment]
@jam1974 The code Sonny is working on isn't completed yet, so may break if you use the latest commit, even with layout.

If you use the two links I posted earlier it should work until Sonny has a chance to finish.  Just download the two files only, (not the whole zip file), and replace your existing ones.

**Comment by sonvnn** [comment]
@felixkat @jam1974 I fixed this issue at https://github.com/templaza/astroid-framework/commit/0a0433a5f54ef7b515bc73c645cc215f303d0134 Please help me download v3-branch and check it.

Thanks & Best Regards,
Sonny

**Comment by jam1974** [comment]
The formbuilder.php (https://github.com/felixkat/astroid-framework/blob/e62bfce83e3954aa7fac4720b4b75236215bdd20/framework/elements/formbuilder/formbuilder.php) thanks @felixkat in combination with the v3 (https://github.com/templaza/astroid-framework/commit/0a0433a5f54ef7b515bc73c645cc215f303d0134) thanks @sonvnn  fixes the problem. Email is now only sent if the checkbox is activated.

**Comment by felixkat** [comment]
Thanks for testing @jam1974.  I'll submit a fix for the checkbox, I'll let you know when it's in the main code so you can test again.
