### ISSUE TITLE
JFilters and Quickstart package trouble.

### ISSUE THREAD

**Issue by Tomisslaw** [templaza/astroid-framework#870]
Joomla 5.2.1
Astroid framework 3.1.7
Astroid Quickstart package 
BlueCoder jfilters free 1.16.4

Same  behaviors with all php 8.x.x versions.

When just the Astroid framework is installed, all works like charm. But when the quickstart package is installed, something goes wrong with jfilters extension from BlueCoder. When the jfilters plugin is installed, it works so that a new menu should be created, and the menu items should be the "jfilters Results Layout". But when this is selected, something is going wrong (see the screenshot)

Creating the menu
![image](https://github.com/user-attachments/assets/43d953a9-42d6-447c-ba67-d21c41fa20a7)

After adding the menu item.
![image](https://github.com/user-attachments/assets/b7b645d0-cf63-4706-93bf-3bb5aae62e49)

**Describe the bug**

Tom

**Comment by sonvnn** [comment]
Can you help me enable system - debug in global configuration to locate the error detail?

**Comment by Tomisslaw** [comment]
If this helps.

<h1 style="box-sizing: border-box; color: var(--heading-color); margin-top: 0px; margin-bottom: 0.5rem; font-weight: 400; line-height: 1.2; font-size: 1.65rem; font-family: Roboto, -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(240, 244, 251); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">**An error has occurred.**</h1><blockquote class="blockquote" style="box-sizing: border-box; margin: 0px 0px 1rem; font-size: 1.25rem; color: rgb(33, 37, 41); font-family: Roboto, -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(240, 244, 251); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="badge bg-secondary" style="box-sizing: border-box; --badge-padding-x: .2rem; --badge-padding-y: .3rem; --badge-font-size: .75rem; --badge-font-weight: 700; --badge-color: #fff; --badge-border-radius: .2rem; padding: var(--badge-padding-y) var(--badge-padding-x); font-size: var(--badge-font-size); font-weight: var(--badge-font-weight); color: var(--badge-color); text-align: center; white-space: nowrap; vertical-align: baseline; border-radius: var(--badge-border-radius); line-height: 1; display: inline-block; --bg-opacity: 1; background-color: var(--secondary) !important; margin-bottom: 0px;">0</span><span> </span>Class "JVersion" not found</blockquote><div style="box-sizing: border-box; color: rgb(33, 37, 41); font-family: Roboto, -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(240, 244, 251); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h2 id="caption" style="box-sizing: border-box; color: var(--heading-color); margin-top: 0px; margin-bottom: 0.5rem; font-weight: 700; line-height: 1.2; font-size: 1.5rem;">Call Stack</h2>
# | Function | Location
-- | -- | --
1 | () | JROOT/administrator/components/com_jfilters/src/Field/FiltersModalButtonField.php:132
2 | Bluecoder\Component\Jfilters\Administrator\Field\FiltersModalButtonField->getInput() | JROOT/libraries/src/Form/FormField.php:1056
3 | Joomla\CMS\Form\FormField->renderField() | JROOT/layouts/joomla/edit/fieldset.php:43
4 | include() | JROOT/libraries/src/Layout/FileLayout.php:128
5 | Joomla\CMS\Layout\FileLayout->render() | JROOT/libraries/src/Layout/LayoutHelper.php:76
6 | Joomla\CMS\Layout\LayoutHelper::render() | JROOT/layouts/joomla/edit/params.php:170
7 | include() | JROOT/libraries/src/Layout/FileLayout.php:128
8 | Joomla\CMS\Layout\FileLayout->render() | JROOT/libraries/src/Layout/LayoutHelper.php:76
9 | Joomla\CMS\Layout\LayoutHelper::render() | JROOT/administrator/components/com_menus/tmpl/item/edit.php:143
10 | include() | JROOT/libraries/src/MVC/View/HtmlView.php:416
11 | Joomla\CMS\MVC\View\HtmlView->loadTemplate() | JROOT/libraries/src/MVC/View/HtmlView.php:204
12 | Joomla\CMS\MVC\View\HtmlView->display() | JROOT/administrator/components/com_menus/src/View/Item/HtmlView.php:136
13 | Joomla\Component\Menus\Administrator\View\Item\HtmlView->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:697
14 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT/administrator/components/com_menus/src/Controller/DisplayController.php:74
15 | Joomla\Component\Menus\Administrator\Controller\DisplayController->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:730
16 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:143
17 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
18 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:150
19 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:195
20 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:306
21 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:58
22 | require_once() | JROOT/administrator/index.php:32

</div>

**Comment by Tomisslaw** [comment]
<h1 style="box-sizing: border-box; color: var(--heading-color); margin-top: 0px; margin-bottom: 0.5rem; font-weight: 400; line-height: 1.2; font-size: 1.65rem; font-family: Roboto, -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(240, 244, 251); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">**An error has occurred.**</h1><blockquote class="blockquote" style="box-sizing: border-box; margin: 0px 0px 1rem; font-size: 1.25rem; color: rgb(33, 37, 41); font-family: Roboto, -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(240, 244, 251); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="badge bg-secondary" style="box-sizing: border-box; --badge-padding-x: .2rem; --badge-padding-y: .3rem; --badge-font-size: .75rem; --badge-font-weight: 700; --badge-color: #fff; --badge-border-radius: .2rem; padding: var(--badge-padding-y) var(--badge-padding-x); font-size: var(--badge-font-size); font-weight: var(--badge-font-weight); color: var(--badge-color); text-align: center; white-space: nowrap; vertical-align: baseline; border-radius: var(--badge-border-radius); line-height: 1; display: inline-block; --bg-opacity: 1; background-color: var(--secondary) !important; margin-bottom: 0px;">0</span><span> </span>Class "JVersion" not found</blockquote><div style="box-sizing: border-box; color: rgb(33, 37, 41); font-family: Roboto, -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(240, 244, 251); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h2 id="caption" style="box-sizing: border-box; color: var(--heading-color); margin-top: 0px; margin-bottom: 0.5rem; font-weight: 700; line-height: 1.2; font-size: 1.5rem;">Call Stack</h2>
# | Function | Location
-- | -- | --
1 | () | JROOT/administrator/components/com_jfilters/src/Field/FiltersModalButtonField.php:132
2 | Bluecoder\Component\Jfilters\Administrator\Field\FiltersModalButtonField->getInput() | JROOT/libraries/src/Form/FormField.php:1056
3 | Joomla\CMS\Form\FormField->renderField() | JROOT/layouts/joomla/edit/fieldset.php:43
4 | include() | JROOT/libraries/src/Layout/FileLayout.php:128
5 | Joomla\CMS\Layout\FileLayout->render() | JROOT/libraries/src/Layout/LayoutHelper.php:76
6 | Joomla\CMS\Layout\LayoutHelper::render() | JROOT/layouts/joomla/edit/params.php:170
7 | include() | JROOT/libraries/src/Layout/FileLayout.php:128
8 | Joomla\CMS\Layout\FileLayout->render() | JROOT/libraries/src/Layout/LayoutHelper.php:76
9 | Joomla\CMS\Layout\LayoutHelper::render() | JROOT/administrator/components/com_menus/tmpl/item/edit.php:143
10 | include() | JROOT/libraries/src/MVC/View/HtmlView.php:416
11 | Joomla\CMS\MVC\View\HtmlView->loadTemplate() | JROOT/libraries/src/MVC/View/HtmlView.php:204
12 | Joomla\CMS\MVC\View\HtmlView->display() | JROOT/administrator/components/com_menus/src/View/Item/HtmlView.php:136
13 | Joomla\Component\Menus\Administrator\View\Item\HtmlView->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:697
14 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT/administrator/components/com_menus/src/Controller/DisplayController.php:74
15 | Joomla\Component\Menus\Administrator\Controller\DisplayController->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:730
16 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:143
17 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
18 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:150
19 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:195
20 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:306
21 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:58
22 | require_once() | JROOT/administrator/index.php:32

</div>

**Comment by sonvnn** [comment]
Cause is JFilter does not compatible 100% with Joomla 5. You need enable B/C plugin in the administrator to use it.

**Comment by Tomisslaw** [comment]
Thanks, I will try it on Tuesday.

**Comment by Tomisslaw** [comment]
> Cause is JFilter does not compatible 100% with Joomla 5. You need enable B/C plugin in the administrator to use it.

Thanks a lot, that solved the problem.
