### ISSUE TITLE
Next problem: Article Widget

### ISSUE THREAD

**Issue by jam1974** [templaza/astroid-framework#871]
In the image, the article widget is integrated under 1 and 2. The settings for 1 are selected so that the latest posts are displayed. 
The settings for 2 are selected so that the most popular posts are displayed. However, the latest posts are also displayed here.

![Unbenannt](https://github.com/user-attachments/assets/d7bc94e5-a559-44dc-8b89-1e492dbcd993)

**Comment by felixkat** [comment]
Try changing libraries/astroid/framework/elements/articles/articles.xml  roughly line 24

From

`<option value="**popular**">ASTROID_WIDGET_ORDERING_POPULAR</option>`

To

`<option value="**hits**">ASTROID_WIDGET_ORDERING_POPULAR</option>`

Edit and re-save widget once you've made the change.  Let me know if it works.

**Comment by jam1974** [comment]
Perfect, many thanks @felixkat

**Comment by felixkat** [comment]
Great, I'll add a commit for it.
