### ISSUE TITLE
codepen disappeared from widgets

### ISSUE THREAD

**Issue by SerGun78** [templaza/astroid-framework#874]
after updating from 3.1.6 to 3.1.7 disappeared in codepen widgets.

**Screenshots**
![изображение](https://github.com/user-attachments/assets/e039a812-dcf4-4440-897b-86bedf61b48c)

**System Informations (please complete the following information):**
 - Joomla Version: 4.4.9
 - PHP Version 8.3.8
 - Astroid Version 3.1.7
 - Device: notebook 15,6"
 - OS: Win 7
 - Browser firefox

**Comment by SerGun78** [comment]
What is the pro version, where can I download it?

**Comment by sonvnn** [comment]
You can download v3-branch and use Raw HTML widget instead of. Pro is on processing. We will release it in the end of November.
