### ISSUE TITLE
Wrong image position in blog view of template two

### ISSUE THREAD

**Issue by semideia708** [templaza/astroid-framework#875]
**Describe the bug**
The settings for positioning the images in the blog-options menu tab do not work for the 'featured articles' menu type. The images are always displayed at the top. Everything is ok for the menu type 'Category Blog'. 

**To Reproduce**
1. Go to 'menu-blog options.'
2. Click on 'image position.'
3. Select "left"

**Expected behavior**
In the frontend. Choose featured articles. All articlles will shown with the image on the left side. 

**Screenshots**
![featured view](https://github.com/user-attachments/assets/af5b52cf-d0df-46d4-8f84-934142f374f1)
![featured](https://github.com/user-attachments/assets/28a89f90-c359-4b0b-b5b5-5de89f7a32db)
![category](https://github.com/user-attachments/assets/d01ee294-30c2-42b6-9ea5-27aa51af5ffe)

**System Informations (please complete the following information):**
 - Joomla Version: [Joomla 5.2.1]
 - PHP Version [ PHP 8.2]
 - Astroid Version [Astroid 3.1.17]
 - Device: [laptop]
 - OS: [win 10]
 - Browser [firefox]

**Additional context**

**Comment by felixkat** [comment]
I can confirm this behavior.

From what I can see the code hasn't been implemented yet in 'featured', only in 'blog'

**Comment by sonvnn** [comment]
@semideia708 @felixkat I fixed this issue at https://github.com/templaza/astroid-framework/commit/d297a450f502dedba33bbf4447505371e1273847
Please download v3-branch and test it.

Thanks & Best Regards,
Sonny

**Comment by felixkat** [comment]
I can also confirmed it works.

@semideia708 Can you close this issue?
