### ISSUE TITLE
Manifest link always adds leading slash.

### ISSUE THREAD

**Issue by felixkat** [templaza/astroid-framework#876]
![Screenshot 2024-11-19 at 00-41-22 Bushey Rangers Main](https://github.com/user-attachments/assets/1af79cd7-2107-4060-867b-4aa289243355)

Whether you do a path with no leading slash or a full URL a slash is always added  `//images`

**Comment by sonvnn** [comment]
You can remove slash in the first character to fix this.

**Comment by felixkat** [comment]
Thanks @sonvnn  This is strange as I'm sure I didn't have a leading slash when I tested this.  Maybe it was a caching issue as I was doing a lot of tests with the favicon.  I will close for now.
