### ISSUE TITLE
Issue with Animations in Article Layout Builder - Astroid Pro 3.1.8 RC-1

### ISSUE THREAD

**Issue by Dnsftl** [templaza/astroid-framework#881]
Description of the Issue:
I am experiencing an issue with animations in the Article Layout Builder on a clean installation of Joomla 5.2.1 running PHP 8.3. I am using Astroid Pro 3.1.8 RC-1 in combination with the 'Two' template. The problem occurs when applying animations to Sections, Rows, and Elements.

Details:

Animations are correctly configured in the backend but do not work on the frontend.
I have tested different animation options and settings, but none are functional.
The browser inspector does not show any error messages or console logs related to this issue.
What I have tried:

Cleared and rebuilt the cache.
Tested in multiple browsers (Chrome, Firefox, Edge).
Performed a clean Joomla installation with PHP 8.3, using only Astroid Pro 3.1.8 RC-1 and the 'Two' template to rule out conflicts.

![Design Settings  Animation Settings](https://github.com/user-attachments/assets/66518c5d-9e0c-4533-9ce2-9a02b9fe24a3)
![No animation fronted_dev zlddsign nl](https://github.com/user-attachments/assets/1ee4ad90-c231-408a-abf9-a653cc97e4e1)

P.s. Stagger times are blocked even though I am using the Pro version.

Regards,

Dennis

**Comment by sonvnn** [comment]
Please download latest package from Astroid pro and make sure plugin is enabled in Plugin Manager.

**Comment by Dnsftl** [comment]
That was the solution, thank you!
