### ISSUE TITLE
Suggested improvements for Astroid in version 3.1.9

### ISSUE THREAD

**Issue by sonvnn** [templaza/astroid-framework#887]
- Create a Joomla module to load layout builder inside
- Update module element to load single module
- Improve UI/UX of Media Manager

**Comment by sonvnn** [comment]
@rinka88 I added option load single module on Module element here https://github.com/templaza/astroid-framework/commit/61c8558ceb50c2a8022770711b0f76591d5d597c

You can download v3-branch and testit.

Thanks & Best Regards,
Sonny

**Comment by rinka88** [comment]
I saw it, it's great. but it is not possible to select a module there. there is no module selection field
![IMG_20241127_142347_042](https://github.com/user-attachments/assets/e950f3f3-91bd-428f-a657-ac31bced3f83)

**Comment by sonvnn** [comment]
Maybe cache problem. Please help me clear the cache and refresh again.

Thanks,
Sonny

**Comment by rinka88** [comment]
yes, it was a cache. Cleaned it up and it worked. Hooray!!!🙂👍

**Comment by rinka88** [comment]
Now, it turns out you need to rename the widget names so that people can easily find

**Comment by sonvnn** [comment]
@rinka88 @felixkat @WM-Loose @Joomlaplates @Banuk1616 @Chacapamac I created Astroid Layout Module. Now you can load layout builder on Joomla Module. You can check it here https://github.com/templaza/astroid-framework/commit/17298103e695e816c210e3ab8f2a7493e032c8f3

Please download v3-branch and test it. Please let me know if you find any issue on it.

Best Regards,
Sonny

**Comment by Banuk1616** [comment]
Hello Sonny,
With the module, I cannot select an image via the button in the image widget. The button has no function. 

But if I use the Image Widget in the Laout Manager, the selection of an image works.

<img width="1089" alt="modul_test" src="https://github.com/user-attachments/assets/0efab2b6-677b-479a-9fa4-375f3c03092b">

**Comment by rinka88** [comment]
The color schemes are different from the template and look different.
![IMG_20241209_154036_665](https://github.com/user-attachments/assets/738aba59-f091-4556-b6cc-3d7b84a866e8)

![IMG_20241209_154036_664](https://github.com/user-attachments/assets/0e3f4626-500b-4b4c-8f17-7bf2a5274035)

![IMG_20241209_154036_035](https://github.com/user-attachments/assets/bb5e1004-8035-41c3-86e9-f41fe697af57)

and some buttons: color change doesn't work

**Comment by sonvnn** [comment]
> Hello Sonny, With the module, I cannot select an image via the button in the image widget. The button has no function.
> 
> But if I use the Image Widget in the Laout Manager, the selection of an image works.
> <img alt="modul_test" width="1089" src="https://private-user-images.githubusercontent.com/157417570/393763882-0efab2b6-677b-479a-9fa4-375f3c03092b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MDQxMTgsIm5iZiI6MTczMzgwMzgxOCwicGF0aCI6Ii8xNTc0MTc1NzAvMzkzNzYzODgyLTBlZmFiMmI2LTY3N2ItNDc5YS05ZmE0LTM3NWYzYzAzMDkyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMFQwNDEwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZTFiY2YzODZhOTQ3NDUwMmE0NzY3NWE1N2NlNmNlZTA0NDNjMGM3YTNjNDUwNzI3YTdiNGZhMTQwYTc2YmQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ev8HoRt3oaYPthFCHwOkZCCT68WTRwk9u3TLmg__iC0">
> 
> I have noticed that the selection of an image does not work with the grid widget either. The button has no function.

I fixed this issue on https://github.com/templaza/astroid-framework/commit/f67caa6a3b50340b5d82c136df3487f0ac27d68f
Please help me download v3-branch and re-test it.

Thanks,
Sonny

**Comment by sonvnn** [comment]
> The color schemes are different from the template and look different. ![IMG_20241209_154036_665](https://private-user-images.githubusercontent.com/40716604/393802790-738aba59-f091-4556-b6cc-3d7b84a866e8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MDU1NDcsIm5iZiI6MTczMzgwNTI0NywicGF0aCI6Ii80MDcxNjYwNC8zOTM4MDI3OTAtNzM4YWJhNTktZjA5MS00NTU2LWI2Y2MtM2Q3Yjg0YTg2NmU4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDA0MzQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMjFlYmU1NWNhOTkyN2IwNmRiNWY2YTgxZDViMDdkZGNjN2Q3ZTkwMmRhNjYzYTlmMDM2N2Y2ZmIxZWIwYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.b4OWvKm-GA40T6fKjcm-EYu-HJW8K1wMm6qSso1elhA)
> 
> ![IMG_20241209_154036_664](https://private-user-images.githubusercontent.com/40716604/393802803-0e3f4626-500b-4b4c-8f17-7bf2a5274035.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MDU1NDcsIm5iZiI6MTczMzgwNTI0NywicGF0aCI6Ii80MDcxNjYwNC8zOTM4MDI4MDMtMGUzZjQ2MjYtNTAwYi00YjRjLThmMTctN2JmMmE1Mjc0MDM1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDA0MzQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2NWE3Nzk2OTRiYTgwNzhiYzc1MjYxZGMyMTc1MzhkMDRiMWRkZWJmZjg3ZDMyNTkzYTQ4OTUyMDNhYTQ2MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.14HUqmwgXbir_tVgWuOmNntIwdCKV4Du9H3mbSQTmgU)
> 
> ![IMG_20241209_154036_035](https://private-user-images.githubusercontent.com/40716604/393802808-bb5e1004-8035-41c3-86e9-f41fe697af57.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MDU1NDcsIm5iZiI6MTczMzgwNTI0NywicGF0aCI6Ii80MDcxNjYwNC8zOTM4MDI4MDgtYmI1ZTEwMDQtODAzNS00MWMzLTg2ZTktZjQxZmU2OTdhZjU3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDA0MzQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViMjc2NTU1ZGY0YjA1OWY1YWRiZmQyNDVmY2Q3MzhhMzYzN2ZlY2YwYTQ1YTEyZGUzMDg3YzU5MjczYjA3NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NQcTLW4ywDlSQ5KXSUqmCJOlOGn6ExRmHj3zbKl8Vlg)
> 
> and some buttons: color change doesn't work

I fixed these issues on https://github.com/templaza/astroid-framework/commit/6f469bd1b529cf9fb31090ecf33de45ca2df57d2
Please help me download v3-branch and retest it.

Thanks,
Sonny

**Comment by Banuk1616** [comment]
Hello Sonny,
I have just tested it. If I use the image widget in the module, the image selection now works. But in the grid widget the image selection does not work yet.
<img width="1314" alt="grid_1" src="https://github.com/user-attachments/assets/fb5f8318-f307-445b-9c69-e42976fbc3c5">

**Comment by Banuk1616** [comment]
Hello Sonny,
I have just tested it. If I use the image widget in the module, the image selection now works. But in the grid widget the image selection does not work yet.
<img width="1314" alt="grid_1" src="https://github.com/user-attachments/assets/3d56d623-acb0-4549-843e-55de844b5799">

**Comment by Banuk1616** [comment]
Nachtrag:
Es funktioniert auch im Grid Widget, aber immer erst beim 2. Versuch.

**Comment by sonvnn** [comment]
Please help me clear browser cache to reload Javascript library

**Comment by Banuk1616** [comment]
I have also found one with the Image Carousel if I want to use it in the module. When I create an item and save it, I get the error: The content exceeds the allowed number of 65535 characters.
<img width="1249" alt="carousel1" src="https://github.com/user-attachments/assets/1b070b40-0734-47cf-97e7-36408ecd7b25">

**Comment by Banuk1616** [comment]
> Please help me clear browser cache to reload Javascript library

Yes, Browswer cache cleared now it works.

**Comment by WM-Loose** [comment]
It works now perfect.
