### ISSUE TITLE
FormBuilder

### ISSUE THREAD

**Issue by Tomisslaw** [templaza/astroid-framework#889]
I started with the Astroid QuickStart Package with the Astroid Core 3.1.7. There was a "Undefined" bug with the FormBuilder, I fixed it like described [here Commit 0a0433a](https://github.com/templaza/astroid-framework/commit/0a0433a5f54ef7b515bc73c645cc215f303d0134). In the meantime I updated to Astroid 3.1.8. and continued to work on the form. I made a form similar to this in the Article Layout builder. [https://demo.astroidframe.work/article-layouts/tours-example/danube-by-bike-and-boat](https://demo.astroidframe.work/article-layouts/tours-example/danube-by-bike-and-boat)

And here is the problem. When I change the Form parameters (just some values in the  in the Article "form builder widget", it do not apply this widget (i changed some fields), instead, it pick up the values from the form in the Article Layout Builder.

Let say i made in the Article Layout builder this 
![image](https://github.com/user-attachments/assets/dd3e7ca7-5e42-465f-96f0-54ebffb4de28)

And i changed it in the "Article widget" in to this

![image](https://github.com/user-attachments/assets/da43757a-c471-468b-ad3f-7ccdd126b5f5)

When I submit the form, i still get an email with the "Subject A".

Curent setup

Joomla 5.2.2
Astroid 3.1.8
php 8.3

Am I doing something wrong, or is this a bug?

**Comment by felixkat** [comment]
Yes, I can confirm this issue.  I created a form via the Article Layout Builder and sent a couple of test emails.  I then changed the email body content via the article widget and the output is still the original.

Article Builder

![image](https://github.com/user-attachments/assets/fe9be70a-bc0a-431d-8164-9d0deb07c4ed)


Widget

![image](https://github.com/user-attachments/assets/30c82768-651e-464b-a2dc-b7eb911f63d7)


Email received after changes to the widget.

From:First Name Last Name AAA
Email:xxx@xxx.com AAA
Subject:This is Subject AAA 
Message:Test Message AAAA
Sender IP: xx.xx.xx.xx

**Comment by sonvnn** [comment]
@Tomisslaw @felixkat Thank you for report the issue. I fixed this at https://github.com/templaza/astroid-framework/commit/b1f03955c9bfd931aeb26d0051c296c491650e87

Please help me download v3-branch and retest it.

Best Regards,
Sonny

**Comment by felixkat** [comment]
> @Tomisslaw @felixkat Thank you for report the issue. I fixed this at [b1f0395](https://github.com/templaza/astroid-framework/commit/b1f03955c9bfd931aeb26d0051c296c491650e87)
> 
> Please help me download v3-branch and retest it.
> 
> Best Regards, Sonny

Tested and working on my site. Will wait for @Tomisslaw to confirm.

**Comment by Tomisslaw** [comment]
I will test it tomorrow and let you know.
Thanks.

**Comment by Tomisslaw** [comment]
I confirm that the bug is fixed.
My knowledge is very limited, but id I can help in some way, let me know. I could translate the framework maybe.
Thanks.

**Comment by Tomisslaw** [comment]
Huh, this maybe cause another problem. Now, when I got an error line in the Joomla built in contact form.  It says: /home/magnaexpeditions/public_html/libraries/src/Form/FormField.php
on line
602

Here is the screenshot if it help.

![image](https://github.com/user-attachments/assets/41440a34-f9ef-4bf0-b7e0-367ba95d8fa4)

**Comment by Tomisslaw** [comment]
> Huh, this maybe cause another problem. Now I got an error line in the Joomla built in contact form. It says: /home/magnaexpeditions/public_html/libraries/src/Form/FormField.php on line 602
> 
> Here is the screenshot if it help. The link is https://magna-expeditions.com/hr/kontakt
> 
> ![image](https://private-user-images.githubusercontent.com/187876193/391240776-41440a34-f9ef-4bf0-b7e0-367ba95d8fa4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NzUxMDAsIm5iZiI6MTczMjk3NDgwMCwicGF0aCI6Ii8xODc4NzYxOTMvMzkxMjQwNzc2LTQxNDQwYTM0LWY5ZWYtNGJmMC1iN2UwLTM2N2JhOTVkOGZhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEzMFQxMzUzMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjc0OGNmNGNmM2JmYTdiOTM4MmJjOTg5ZmRhYmFiZmVhZTU0MWI3YjYxZTBkYjgwMGU5ODc5MDZlMWNjMTExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.LQqJ8Q3nOR4zvIAJvg6QzwH26KW9gBpipeXXaId-Q7s)

I am not sure any more if this is related to the Bub/Fix. I reverted back to the original state, but the error stil stays.

**Comment by Tomisslaw** [comment]
I hope this is my last message on this topic. The initial bug is solved by you. The second thing ist a bug by Joomla itself. When a Contact is linked to an user, and this and that contact is displayed on the site, the error ocur.
