### ISSUE TITLE
Jumping site after update to 3.1.8 all user must back to 3.1.7

### ISSUE THREAD

**Issue by WM-Loose** [templaza/astroid-framework#891]
Joomla 5.5.2
Astroid 3.1.8
PHP 8.3

Hello Sonny,
we had a lot of calls today from customers whose pages suddenly jumped after updating from 3.1.7 to 3.1.8 under Firefox. I made 2 videos here.

1st page with 3.1.7
https://imgur.com/a/GRxvyxf

2nd page with 1.3.8
https://imgur.com/a/fdpd4Be

We need help. It´s a very important problem for all my user.
If you want test, please take the Firefox Browser. In chrome and edge is it not present.

**Comment by felixkat** [comment]
Have you tried disabling your modules to see if there is a conflict?  I've upgraded a couple of test sites and haven't seen that behavior but I don't have any modules running like your site does.

**Comment by sonvnn** [comment]
@WM-Loose Astroid is using 3.1.8. And I can not reproduce your issue https://astroidframe.work/
Can you give me a link of your site? So I can check it more detail.

**Comment by WM-Loose** [comment]
I'm a bit confused now. I had installed 3.1.7 again after the page started jumping to 3.1.8, as you can see in the video. Then later the update to 3.1.8 was displayed in the backend. I installed it as an update via the backend this morning. After that the error went away and the page behaved completely normally. What could have happened? I can't understand it myself, but if I hadn't made the videos yesterday, people would think I was crazy. The only difference is that I didn't use the update package from Github, but this time I updated from 3.1.7 to 3.1.8 directly from the backend. You can find this page here and offline mode is temporarily deactivated. https://www.vfl-altenstadt.webrlp.de

**Comment by sonvnn** [comment]
I checked your website on firefox and it works really well. There was no interruption or lag when switching pages. I thought it might be a problem from your server that there was no good connection for a while.

However, I think there is no need to worry about it anymore. Because everything is working perfectly at this time. Thank you very much for reporting the problems of Astroid in a timely and prompt manner.

**Comment by WM-Loose** [comment]
Thanks for the test. I also think it might have been the server. The main thing is that it works now.
