### ISSUE TITLE
No scroll bar and scroll with activated Smooth Scroll possible

### ISSUE THREAD

**Issue by WM-Loose** [templaza/astroid-framework#893]
Astroid 3.1.8
Joomla 5.5.2
PHP8.3

When Smoothscroll is activated, the scrolling in the window is no longer possible.
When Smoothscroll ist deactivated everthing is ok.

Link:
https://www.sotec-kopierer.de/
Currently smoothscroll is disabled

This is how you can test it self:
Create a post and insert the following code:
[modal-code.txt](https://github.com/user-attachments/files/17948069/modal-code.txt)

Than open ist and test scroll with smoothscroll an without smoothscroll

Look a site with smoothscroll and Modal:
https://backup.sotec-kopierer.de/

**Comment by sonvnn** [comment]
@WM-Loose to solve this issue. Go to template options > Basic > Smooth Scroll -> Prevent Smooth Scroll. Add your class of element you want to prevent smooth scroll, in this case is `uk-panel-scrollable`
![Screen Shot 2024-11-29 at 09 23 02](https://github.com/user-attachments/assets/f950cecc-14fb-4d41-b177-ca81b27d06f7)
