### ISSUE TITLE
Menu split over 2 lines - MegaMenu dropdown is unselectable

### ISSUE THREAD

**Issue by C-G-White** [templaza/astroid-framework#894]
**Describe the bug**
If you have a main menu that splits over 2 lines in your header you can't select any of the dropdown menu items from the top row that have another menu item below them.  As you move the mouse pointer down towards the dropdown it closes and disappears.  The dropdowns are only selectable if they come directly below the main menu item which doesn't have a second menu item underneath. i.e. the ones on the right of the screenshot shown.

**Expected behavior**
The dropdown for the top part of the menu should cover the menu items in the second row of the menu and be selectable.

![Capture](https://github.com/user-attachments/assets/905f7fc8-e080-47c0-b220-8b71f191e79e)

Sorry but can't get a screenshot of what happens when the drop down appears.

**System Informations (please complete the following information):**
 - Joomla Version:4.4.9
 - PHP Version 8.2
 - Astroid Version 3.1.3  Astroid Template one version 3.1.0
 - Device:PC
 - OS: Windows 10
 - Browser Chrome

**Additional context**

**Comment by sonvnn** [comment]
I fixed this issue at https://github.com/templaza/astroid-framework/commit/4be7888618f939d7d0e0a3d875f37469f592ecff
Please help me download v3-branch and retest it again.

**Comment by C-G-White** [comment]
Hi Sonny,

Much as I would like to download and test I have no idea what I am
downloading and how to add it / install it.  I have been using Joomla since
Ver 2 but have never used Github before.  What should I do?

Regards,

Chris.

**Comment by C-G-White** [comment]
OK, found where to download.  Slightly confused that the downloaded version still says 3.1.8.  The dropdown menu issue has been solved and now works as expected.  Regards,  Chris.

**Comment by C-G-White** [comment]
Having tested it do I need to do anything else to complete the issue request?

**Comment by felixkat** [comment]
> OK, found where to download. Slightly confused that the downloaded version still says 3.1.8. The dropdown menu issue has been solved and now works as expected. Regards, Chris.

The version still says 3.1.8 as any bug fixes or new code will be released in 3.1.9.   The code you downloaded is after the 3.1.8 release but at a test stage before 3.1.9.  I hope that makes sense.

**Comment by felixkat** [comment]
> Having tested it do I need to do anything else to complete the issue request?

You can close with comment to say it's all working.  😃

**Comment by C-G-White** [comment]
Hi again,  Just notice that when the dropdown appears there is a large gap below the menu item and the dropdown menu.  Please see below:
![Capture](https://github.com/user-attachments/assets/c1efaa81-6479-435c-bc11-f47a2fd2ce78)

Is this adjustable or can it be set so that the dropdown is actually attached to the menu item.

Regards,

Chris.
