### ISSUE TITLE
Cannot Save Layout Items 

### ISSUE THREAD

**Issue by garyvr888** [templaza/astroid-framework#904]
Cannot save Layout Items - Like Grid or Slides 

Returns this error - Slides has not been saved. Are you sure to skip the subform?  

A simple procedure - Makes the whole template useless  

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System Informations (please complete the following information):**
 - Joomla Version: [e.g. Joomla 5]
 - PHP Version [e.g. PHP 8]
 - Astroid Version [e.g. Astroid 3.1.0]

**Additional context**

**Comment by sonvnn** [comment]
You have to "click" apply to save Subform first

![Screen Shot 2024-12-06 at 14 55 17](https://github.com/user-attachments/assets/91a02673-9bea-44d3-ba39-9c48f71bf2c4)

**Comment by garyvr888** [comment]
![image](https://github.com/user-attachments/assets/1bfddef9-6726-4f8b-9ec8-fe8042abcd15)

Clicked this - Same result

**Comment by garyvr888** [comment]
OK - I get you - Edit the slide - Apply the edit then - Save -    ( Add an Apply Button next to the save at the bottom as well ? ) 

![image](https://github.com/user-attachments/assets/be0a6b0c-4836-4d99-9c51-df31fabfa87a)

Not intuitive as you edit down - then before you save at bottom you must go back to the top to apply before you save ?  

Error message is also ambigiuous 

![image](https://github.com/user-attachments/assets/c250f33b-6478-499f-b437-2674ec046d88)

Save slide has not been saved - Yet one just clicked save - Apply slide to subform before saving would be more informative :-)

**Comment by sonvnn** [comment]
@garyvr888 Thank you for feedback about UX. I improved it on https://github.com/templaza/astroid-framework/commit/186a5d18fa6c7ac570264f62c51505ca76b9a004

You can download v3-branch here https://github.com/templaza/astroid-framework/archive/refs/heads/v3.zip and retest it again. Please help clear browser cache to reload JS libraries
