### ISSUE TITLE
Bug: Select Image Button Not Working in Listing Pro Widget in the Astroid Layout Module.

### ISSUE THREAD

**Issue by Dnsftl** [templaza/astroid-framework#908]
The "Select Image" button in the Listing Pro widget in the Astroid Layout module is unresponsive, and clicking it triggers no action, preventing  selecting or uploading an image.

**To Reproduce**

Navigate to the Astroid Layout module.
Add the Listing Pro widget.
Click on Add Item.
Attempt to use the "Select Image" button.

Actual Result:
Clicking the button does nothing, and no action occurs.
The "Select Image" button does not work. Nothing happens when the button is clicked.

**Expected behavior**
The "Select Image" button should open a dialog or interface to select and upload an image.

**Screenshots/video**
https://github.com/user-attachments/assets/e5365cb2-b877-4262-882b-f3739fa5d15d

**System Informations (please complete the following information):**
 - Joomla Version: 5.2.2
 - PHP Version: 8.3
 - Astroid Version: 3.1.8 (Pro)
 - Device: Laptop
 - OS: Windows 11
 - Browser: Firefox Developer, Chrome, Edge
**Additional context**

**Comment by sonvnn** [comment]
@Dnsftl Thanks for testing. I fixed this issue on https://github.com/templaza/astroid-framework/commit/f67caa6a3b50340b5d82c136df3487f0ac27d68f

Please help me download v3-branch and test it.

**Comment by Dnsftl** [comment]
@sonvnn 

The "Select Image" button issue in the Listing Pro Widget has been fixed.

Thanx!
