### ISSUE TITLE
Astroid Captcha does not appear at user login

### ISSUE THREAD

**Issue by WM-Loose** [templaza/astroid-framework#918]
Joomla 5.5.2
PHP 8.3
Astroid 3.1.9RC2
Astroid Captcha 1.0.0

Plugin Captcha set as default in the configuration. 
![1](https://github.com/user-attachments/assets/aad942d1-7371-4611-b4f1-30731cddb519)

User configuration also checked and the Astroid Captcha is also set there.
![2](https://github.com/user-attachments/assets/614c5cae-67b4-4e16-baa4-b9e65e8f322d)

Unfortunately, the Captcha (standard with math problem) is not displayed when the user logs in.
![3](https://github.com/user-attachments/assets/c376403c-baf9-4650-8c1d-6a6896da32ab)

**Comment by sonvnn** [comment]
Joomla Captcha only display on Register Form. It's not available on Login Form.
![Screen Shot 2024-12-16 at 09 13 21](https://github.com/user-attachments/assets/61c2a287-a0bc-4c76-abbd-5b99432e1959)

**Comment by WM-Loose** [comment]
Ok
