### ISSUE TITLE
Translations should be available at https://astroidframe.work/download

### ISSUE THREAD

**Issue by Chacapamac** [templaza/astroid-framework#93]
Translations should be available at https://astroidframe.work/download

I’m updating the french now

**Comment by sonvnn** [comment]
I added this to download page https://astroidframe.work/download
This topic should move to Discussions.

Kind Regards,
Sonny

**Comment by Chacapamac** [comment]
Great, I thing you should just give h2 title —> Translation
And a simple list of links. It will look more pro for the download page
