### ISSUE TITLE
Font Awesome shopping cart not loading

### ISSUE THREAD

**Issue by Dnsftl** [templaza/astroid-framework#935]
Describe the bug
The Font Awesome shopping cart icon is not loading in the topbar and sticky header. Despite several attempts, the icon does not appear in these areas.

To Reproduce

Go to the website.

- Navigate to the page where the topbar and sticky header are visible.
- Check for the shopping cart icon in both the topbar and sticky header.
- See the error: the shopping cart icon does not appear.

Expected behavior
The shopping cart icon should be visible in both the topbar and sticky header.

Screenshots
 
![No shoppingcast](https://github.com/user-attachments/assets/6ae33d3e-90c9-4eb9-bd8d-40b022711e6f)

System Information 

Joomla Version: 5.2.2
PHP Version: 8.3
Astroid Version: 3.19
Device: Laptop, Phone
OS: Windows 11, Android 14
Browser: Chrome, Firefox, Edge

Additional context
The issue is specifically with the Font Awesome shopping cart icon not displaying in the topbar and sticky header. Other icons from Font Awesome might be loading correctly, but the shopping cart icon is not visible.

Regards,

Dennis

**Comment by sonvnn** [comment]
Can you send me your url? I will help you check it.

**Comment by Dnsftl** [comment]
The url is: https://www.zlddsign.nl/

**Comment by sonvnn** [comment]
Your top-bar's font-family is Arial (Not Font-Awesome). That's why fontawesome icon can not be display.
![Screen Shot 2024-12-24 at 08 22 44](https://github.com/user-attachments/assets/beee20ed-7ba4-41b9-abfe-ba6f2cddc32d)
![Screen Shot 2024-12-24 at 08 22 57](https://github.com/user-attachments/assets/2370b5bb-87d9-454e-937a-3bade765243e)

**Comment by Dnsftl** [comment]
I totally overlooked that, thanks
