### ISSUE TITLE
Just completely redo the french ini file for 2.5.14

### ISSUE THREAD

**Issue by Chacapamac** [templaza/astroid-framework#94]
I just completely redo the french ini file for 2.5.14 based on the english and french file from the 2.5.14.

**I see that the french file wasn’t the one I sent before.**
— I change multiple french translation that was unclear or simply not accurate
— I replace all the lines to be identical to the english file to facilitate next translation, was a bit all over the place.
— Everything in the 2.5.14 english file are now in the french and translated correctly and comprehensibly

**You have some double entry in the english 2.5.14**
**Line 47 - 48**
47- TPL_ASTROID_CLOSE_LIVEPREVIEW="Live Preview"
48- TPL_ASTROID_CLOSE_LIVEPREVIEW="Close Live Preview"

I guess 47 should be something like —> PL_ASTROID_LIVEPREVIEW ???

**Anyway I just omit  47 in my file - I just have**
51- TPL_ASTROID_CLOSE_LIVEPREVIEW="Fermer la prévisualisation"

**Line 82 - 488**
 TPL_ASTROID_COLOR="Couleur"

I keep only one at  line 85

**Line 581-582 & 597-598**
 ASTROID_BACKGROUND_ATTCHMENT_SCROLL="Scroll"
 ASTROID_BACKGROUND_ATTCHMENT_FIXED="Fixed"

I keep one set at  line 585-586

**Rename to use — work & Tested**

[2.5.14-(PT)-fr-FR.astroid.ini.zip](https://github.com/templaza/astroid-framework/files/8050451/2.5.14-.PT.-fr-FR.astroid.ini.zip)

**Comment by Joomlaplates** [comment]
I added  your new file to the language section
