### ISSUE TITLE
Astroid Framework v2.5.14,  PHP 8.1,  Warning

### ISSUE THREAD

**Issue by beyondenvoy** [templaza/astroid-framework#95]
Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /data/www/vshitv/libraries/astroid/framework/library/astroid/Component/Utility.php on line 183

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /data/www/vshitv/libraries/astroid/framework/library/astroid/Component/Utility.php on line 183

**Comment by sonvnn** [comment]
I fixed it on https://github.com/templaza/astroid-framework/commit/7d09bce164bf2730513c4699e03aefc4bb6a852b
Please help me download Developer branch and check it again.

Kind Regards,
Sonny
