### ISSUE TITLE
Add Bootstrap Icons

### ISSUE THREAD

**Issue by SerGun78** [templaza/astroid-framework#97]
Hello everyone! It was really nice to be able to choose between fontawesome or Bootstrap Icons. You can add this setting to the Astroid plugin.
https://icons.getbootstrap.com/
Bootstrap Icons no longer inferior to fontawesome.

**Comment by sonvnn** [comment]
Hi,

Too much external Library will slow down your site. You can include extra library by Custom code tab.

Thanks & Best Regards,
Sonny

**Comment by Chacapamac** [comment]
I use Awesome personally. Anybody see an advantage to use one or the other ?
I look at this comparaison —> https://themesberg.com/blog/bootstrap/bootstrap-icons-vs-fontawesome
The only real advantage of Awesome is the choice. That is the really important and gain my vote as a designer.

Making it as a choice, meaning that you can put **only one icons library On** on one website still give the user more choice, if needed and that is good. It’s always only one library. It also will not make a big change in loading time as you cannot use both together. 

The only problem I see is that you need to include and maintain, update another library and the internal code for the developer and add some weight to the core framework. This is only for the people that want to use it locally. Why having 2 icons library include in one framework?

**Suggestion:**
Maybe that choice can be only with the choice of using the bootstrap library by CDN, easy to include, no impact at all. Nothing to maintain and more choice for the user.

**Comment by SerGun78** [comment]
Of course, I'm talking about connecting separately either one fontawesome or one bootstrap icon. so that in the astroid plugin you can choose which one font to connect from two (you can locally, but I prefer via cdn).

**Comment by biobill** [comment]
Good morning everyone.
Sorry to interrupt, but I don't think it's important to add additional icons. Anyone who needs something different (e.g. bootstrap icons) can pass it through astroid's custom code section and disable fontawesome from the plugin.

**Comment by Chacapamac** [comment]
I @biobill - 
Sure you can, but not all users are familiar with custom code. If it’s done as a choice between font awesome or Bootstrap and you keep only the cdn choice for the bootstrap icons. I think, it’s a plus that have no  real impact on the overall speed and weight of the core Astroid install and maintenance. You just add the option. 

I’m a designer by trade first and icons are important, I didn’t see the bootsrap collection but I’m sure some people will prefer the bootstrap ones over Awesome.

I doubt its a coding challenge. Not sure about that one, sometime it look easy but it is not.

**Comment by biobill** [comment]
Hi @Chacapamac 
It's very easy to add a choice for Bootstrap, but I still think it's not necessary. 
Regarding Joomla 4, even the font awesome choice should be removed from astroid since it's already included in Joomla core.

**Comment by Chacapamac** [comment]
Thanks for the infos, @biobill
“Regarding Joomla 4, even the font awesome choice should be removed from astroid since it's already included in Joomla core.”
If it’s in the core Joomla, It should be included as a the first choice of icon (with the local & CDN choice. Awesome will probably have to stay for backward compatibility

**Comment by Joomlaplates** [comment]
Hello together,
just my 5 ct. 
What I´ve learned in the last 15 years of developing Joomla and themes is: More flexibility = More complications.
Most users dont even know where the icons comes from. And the Awesome icons are integrated in Joomla core, so why we should confuse the users with another option? And these users who wants to use another icon set, they know mostly how to  include them and know how to customize.
Regards Peter

**Comment by Chacapamac** [comment]
**_Ok I was a bit confused ( I read to fast what biobill was saying..)  and I was thinking that the Bootstrap icon library was included in Joomla core, My bad!_**

> Awesome icons are integrated in Joomla core
Thats our answer right there...

As a designer, I just take a look at Bootstrap icons and I’m not to impress with their look. I find them looking thin and oldish.
I Just return to my favorite Awesome Icons and now I can see that they even have added new styles making more than 14,865 choices of icons and they simply look better and the choice of styles are simply “Awesome”.

**Now, we should try to view that logically...**
• Icons, like typography are of ultimate importance in any design, from paper to web. Having more choices is important here.

• If you want to add the ability to use easily the Bootstrap icon choice, it should be ONLY by CDN
— Now this bring the possibility that both core Joomla Awesome library and Bootstrap are loaded together. This is a problem, this is not to efficient and not the Astroid way....

**Comment by sonvnn** [comment]
Hi @Chacapamac,

The problem is Bootstrap prefix is "bi" and Font Awesome is "fa". So if you switch from Awesome to Bootstrap, some icons of Joomla and Astroid will not work, because they are "fa". You still have to use both of them Bootstrap icon and Awesome icon and it's not necessary .

Best Regards,
Sonny

**Comment by Chacapamac** [comment]
ALL THAT IS AWESOME!
